### ISSUE TITLE
Build failing due to unresolved dependencies

### ISSUE THREAD

**Issue by shoogle** [Audiveris/audiveris#10]
Build failing on Ubuntu 16.10 due to unresolved dependencies.

**`$ gradle build`**
```
targetOS=linux-x86_64
:git_build
:generateProgramId
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
  Required by:
      project :
   > Could not resolve args4j:args4j:2.33.
      > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve args4j:args4j:2.33.
      > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve args4j:args4j:2.33.
      > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
...
```
#### Full build logs:
* **`$ gradle build`** - [gradle-build.txt](https://github.com/Audiveris/audiveris/files/929771/gradle-build.txt)
* **`$ gradle build --debug`** - [gradle-build-debug.txt](https://github.com/Audiveris/audiveris/files/929791/gradle-build-debug.txt)
* **`$ gradle build --stacktrace`** - [gradle-build-stacktrace.txt](https://github.com/Audiveris/audiveris/files/929785/gradle-build-stacktrace.txt)

**`$ java -version`**
```
openjdk version "9-Ubuntu"
OpenJDK Runtime Environment (build 9-Ubuntu+0-9b134-2ubuntu1)
OpenJDK 64-Bit Server VM (build 9-Ubuntu+0-9b134-2ubuntu1, mixed mode)
```
**`$ gradle --version`**
```
------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-Ubuntu (Oracle Corporation 9-Ubuntu+0-9b134-2ubuntu1)
OS:           Linux 4.8.0-46-generic amd64
```
**`$ git --version`**
```
git version 2.9.3
```

**Comment by maximumspatium** [comment]
It looks like an issue with args4j and OpenJDK. Did you try to compile Audiveris with Oracle JDK?

**Comment by maximumspatium** [comment]
It looks like you need to properly configure your OpenJDK to use TLS encryption. Maybe smth like
`-Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2"` would help (untested)...

**Comment by shoogle** [comment]
Thanks for your help. It seems to be a problem with OpenJDK Version 9. It works with OpenJDK Version 8, or with Oracle JDK Version 8.

If anyone else has the same problem, use this command to check which versions you have installed and set the default:
```bash
sudo update-alternatives --config java
```

If you don't have version 8 installed you need to install either the OpenJDK or Oracle JDK.

#### Install OpenJDK version 8
```bash
sudo apt-get update
sudo apt-get install openjdk-8-jdk
```

#### Alternatively, install Oracle JDK version 8
```bash
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
```
