### ISSUE TITLE
make "hidden function" to define type of text easier accessable

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#101]
Actually it seems (for the user) not possible to define a text type other than lyrics and "normal" text.
But through the context menu of normal text an entry "Inter" / "SentenceInter" appears, and with it a selection box in the Inter-board, allowing to define the type of text:
lyrics, title, direction,....

It would be a good idea to make this selection directly available, in the moment when the user selects a normal text. Actually it is very hidden...

**Comment by hbitteur** [comment]
Implemented
Closing
