### ISSUE TITLE
MusicXML export misses key signature change

### ISSUE THREAD

**Issue by maximumspatium** [Audiveris/audiveris#109]
[This score](https://github.com/Audiveris/audiveris/files/1754339/BarP.-.Mack.the.Knife.2.zip) exhibits another bug in the MusicXML export - the key signature change at the end of the 2nd system won't be exported leading to the wrong key signature in the 3rd system.

The first two images below show the correct notation whereas the last image shows its invalid MusicXML output:

![keysig change](https://user-images.githubusercontent.com/6561800/37031215-3a0b731c-213e-11e8-85a7-243d23c0221e.png)
![keysig correct](https://user-images.githubusercontent.com/6561800/37031216-3a2c977c-213e-11e8-9535-db71a16cf548.png)
![keysig invalid export](https://user-images.githubusercontent.com/6561800/37031217-3a54d3c2-213e-11e8-9b50-2c56cb05bd45.png)

As usual, I was able to spot the buggy code:

https://github.com/Audiveris/audiveris/blob/7da2a9173a0d3e4a32bfa43ed8ecd53fdb5bffbb/src/main/org/audiveris/omr/score/PartwiseBuilder.java#L1388-L1402

The problem with the check below is that it considers the absence of any key as the reason to stop processing of the current measure:

```java
if (!current.measure.hasKeys()) { 
    return;
```

In the case of measure 11 at the start of the 3rd system, this is definitely wrong because we actually change from five sharps to null key signature (C key).

The solution is therefore to consider every "null key signature" at the start of a system as a **candidate key signature change** to be be verified against the previous key.

So the correct algorithm can be roughly sketched as follows:

```java
if (!current.measure.hasKeys() && !current.system.isFirstBar) {
   return;
} else {
   // assume the current measure to contain a key sig change
   // even if it has no key indication
}
```

Further, we should check why the key signature cancellation at the end of the 2nd system hasn't been recognized. The natural signs are displayed in red - an indication for unlinked symbols...

**Comment by hbitteur** [comment]
**Key cancellation**: Right now, the OMR engine does not recognize or process key cancellations, only new key signatures when they are encountered.
Cancellation is a complex recognition task, especially when natural signs appear at the beginning (sometimes at the end) of a new key sign.
Moreover, this is just a cautionary indication, the reader (including the OMR engine) should be able to process the beginning of the next system. Except that in this case with no starting key, the processing failed. :-(

**Staff header with no key**: You've correctly detected a hole in engine key processing.
I'm writing the correction right now. If this lack of key does represent a key change, what should we put into the MusicXML stream? Could we use a key element with fifths attribute set to 0? I just checked in MusicXML reference and didn't really find any concrete answer. Any advice?

**Comment by maximumspatium** [comment]
> If this lack of key does represent a key change, what should we put into the MusicXML stream?

To my knowledge, it must contain the proper key cancellation, i.e. the [cancel element.](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-cancel.htm)

**Comment by hbitteur** [comment]
I tried this MusicXML implementation:
```xml
        <key>
          <fifths>0</fifths>
        </key>
```
Finale, MuseScore, EasyABC accepted it. They even created on their own the key cancellations at end of previous system.
So this is now commited in e287da5994c7a1783bbc774ed14b952f30a54f25, if this is OK for you, please close the issue.

**Comment by hbitteur** [comment]
OK, I will output this MusicXML cancel element the day the engine is able to detect and process such cancellation sign.
For the time being, we can live without such an explicit element.

**Comment by maximumspatium** [comment]
Tested in Musescore and PriMus. Anything works fine. Thanks a lot for the quick fix!
