### ISSUE TITLE
Run CLI

### ISSUE THREAD

**Issue by Foolius** [Audiveris/audiveris#12]
gradle run works and gives me a GUI but as it is stated in the readme, the GUI is for debugging purposes. How can I run the CLI?

**Comment by maximumspatium** [comment]
You need to build the distribution archive using `gradle build` in order to be able to use the CLI. Unfortunately, it doesn't fully work due to missing resources. We will fix it soon, [see here](https://github.com/Audiveris/audiveris/issues/9).

**Comment by Foolius** [comment]
I built successfully and I know of the issues with the resources.
But still: How do I start the CLI version and not the GUI version?

**Comment by maximumspatium** [comment]
Well, the following terminal commands show how to start Audiveris CLI under Linux/Mac OS:
```
gradle clean build
cd build/distributions
unzip Audiveris.zip
bash Audiveris/bin/Audiveris -batch -help
```

**Comment by Foolius** [comment]
Thanks.
