### ISSUE TITLE
Problem to decide between "end of slur" and augmentation point

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#126]
![image](https://user-images.githubusercontent.com/33522630/37511447-233442ea-28ff-11e8-9fd7-b53f05c8953d.png)

I happens rather often that the end of a slur is interpreted as an augmentation point. The extract above shows the problem: the beginning of the slur of 1st line from measure 1 to 2 is cut off due to the notation line and is then interpreted as an aug.point.
In the third line we have a similar case, but here we really have an aug.point (which is in line with the end of the slur).
I assume that there is no "strait" way to solve this problem.

Maybe during analysis the program could keep in mind that there are these 2 possibilities and during rhythm check use the one that is more logical?

By the way: a similar way could also help to decide between quarter and half note...

**Comment by Bacchushlg** [comment]
I decided to flag this problem as a bug, because it happens rather often and it disturbs the rhythm check.
In many cases I have to do "detective like" analysis to find out, why the rhythm check fails - and finally see a hidden aug.dot and the beginning of a slur.

**Comment by hbitteur** [comment]
What I can propose is to check if a candidate augmentation dot is vertically sufficiently away from a staff line (or ledger) and thus not likely to be just an artifact resulting from staff line removal.

**Comment by Bacchushlg** [comment]
let us give it a try - may be a good way to handle this problem.

**Comment by hbitteur** [comment]
OK, done with commit b97d1d249b6f175f3f9bf0784d7fa6e937b5f77c
All candidate dots in this example are now correctly handled.
