### ISSUE TITLE
not possible to define a notehead with 2 stems manually

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#127]
sometimes 2 voices share a note head. 
During transcription this works fine, but it is not possible to connect a manually added stem to a note head. (in case the stem was not recognized). When doing so, the connection to the other stem is removed (and vice-versa).

**Comment by hbitteur** [comment]
I'm aware of this limitation. I wanted to first address the "usual" cases. I will need some specific user interaction to cope with this case.

**Comment by Bacchushlg** [comment]
problem has been solved with one of the last versions
