### ISSUE TITLE
allow to load multiple images into one book

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#129]
Actually it is not possible to create one book out of multiple single images.
Only in case of a multipage TIFF or PDF a book with several pages is created.
It would be fine to allow to add pages to an already open book in order to create one common output file for export.

**Comment by hbitteur** [comment]
I agree

**Comment by hbitteur** [comment]
Hi Baruch,

I'm thinking about features very similar to the ones provided by PDF-SAM (PDF Split And Merge) utility.
Could you have a look at their site [https://pdfsam.org/pdfsam-basic/](https://pdfsam.org/pdfsam-basic/) and tell me if you feel comfortable with these features (replacing their PDF containers by our BOOK containers, of course).

Rather than re-inventing the wheel...

**Comment by hbitteur** [comment]
Beside Split and Merge, PDF-SAM also allows Extract that might be of interest for you.
See by yourself.

**Comment by Bacchushlg** [comment]
I seldom have pdf scores as source, mostly I have paper notes. After scanning I mostly do some manual correction (esp. fine rotation and a bit contrast improvement). 
Sometimes I make TIFFs from this (could be pdf, too, of course) in order to get the score handled as one to avoid the described problem.
But there is one disadvantage: If I see that my imaging improvement was not successful, the transcription will still run for the complete score (all pages).
Therefore meanwhile I abstain from the latter (for bad score images) and do the transcription page by page.

And here, I come back to the above: a feature to "connect" all open pages to get a common export file.

**Comment by hbitteur** [comment]
So this "connect" action could be equivalent to the "merge" feature of PDF-SAM:
- Ability to select several books (and perhaps some sheets in these books)
- And merge everything as a single book

**Comment by Bacchushlg** [comment]
The important thing is to be able to merge after loading. So pages of a score can be transcribed page by page but then exported as one mxl-file

**Comment by hbitteur** [comment]
To avoid any misunderstanding, let me clarify that I'm trying to define the specifications for Audiveris split & merge features.

In this exercice, PDF-SAM is a good model, it has evolved along many years, it is well documented, etc... My intention is not to push for use of PDF-SAM, but merely to more or less "replicate" the PSF-SAM features and user interface into Audiveris software. 

This is the reason why I asked you to review these PDF-SAM features (Split, Merge, Extract) and then tell me if you would be happy with similar features within Audiveris.

We are working at specification level for the time being.

**Comment by Bacchushlg** [comment]
Ah, ok. This was my mis-understanding.
But, to be honest, this is much more than what I asked for. 
I thought of just one "simple" feature: create a common export for all opened tabs, even if they come from different image files. 

The only thing that might be necessary is to allow to re-sort the pages (tabs), either by drag-n-drop (like most browsers allow), or by a list window that allows to do the resorting (e.g. similar to what MuseScore shows in the instruments dialog on the right). This would allow to re-open (and transcribe) a single page from the already loaded list of pages (after some image improvements from an external tool)

**Comment by hbitteur** [comment]
I agree that these features may be more than what you strictly need for the specific case you described.
But rather to design something specific, I prefer to stick to a set of well-thought operations. 
Granted, implementation may take longer but, doing so, I feel more comfortable with the final suitability for the end-user.

**Comment by hbitteur** [comment]
Let's take your example, using PDF-SAM as the model
I suppose you have:
- A book B20 of 20 sheets. This book can be the result of the aggregation of smaller books, perhaps including 1-page books, etc, I don't really care.

Now, you have a problem with say sheet 10 for which you need to work on image improvement, or get a better scan, etc.
Then, once you are OK with a new version of image for sheet 10, you need to somehow replace sheet 10 in book B20 by your new version.
So, you make a Merge of the following list:
1. B20 sheets "1-9"
2. Your new image 10 
3. B20 sheets "11-"

And you get your new book.

**Comment by Bacchushlg** [comment]
Perfect.

-----Original Message-----

**Comment by hbitteur** [comment]
Commit 0b414c132487db6c8a19481b18c2eca3ae76113e provides the feature in development branch.
Handbook to be updated accordingly.

**Comment by SilverGreen93** [comment]
How do I load multiple images to be part of the same book?

**Comment by Bacchushlg** [comment]
To load images just use "Book | Split and Merge". 
A dialog will open where you can load the images to be used (load files).
Now press "Action" in order to create an omr-File.
Finally load this omr-File from "Book | open books" and continue as usual

**Comment by SilverGreen93** [comment]
> To load images just use "Book | Split and Merge". A dialog will open where you can load the images to be used (load files). Now press "Action" in order to create an omr-File. Finally load this omr-File from "Book | open books" and continue as usual

This workflow is a bit counterintuitive, but I managed to get it working. Thanks!

**Comment by hbitteur** [comment]
> This workflow is a bit counterintuitive, but I managed to get it working. Thanks!

@SilverGreen93 

Could you elaborate on the "counterintuitive" aspect?
What is not clear? What we should better explain or modify?

Thanks in advance for your help
/Hervé

**Comment by SilverGreen93** [comment]
> Could you elaborate on the "counterintuitive" aspect? What is not clear? What we should better explain or modify?

Sure!

In the first place, I would have expected that all images that I open to be part of the same book. If I open just one image, I would think of it as a separate sheet, but when I open a group, I am really loading a bunch of them to be part of the same book.
I know you would say is that if i open 2 pdf files instead, that would be 2 separate books and should not be mixed, but when opening images (png/jpg), each image is a page, so in 99% of cases, the intention is to open all images as a single book, not separate.

Even if I then try to use the Book | Split and Merge, as you suggested, I load all the images into the window, then press Action!... This prompts me to save an omr file, but, after doing that, I am left with no clue about what it just happen. Did the software open the book for me as well or not? Becasuse my intuition would say that I now should have the omr file that I just saved already opened and ready for work (the individual images are already loaded in the background). But in fact no, I need to dismiss the window and then load the newly saved omr file manually to have my proper group of files as a book, as if I only press the Transcribe book button without loading manually the omr file, I stil get single image per book, as before. One would say that the Merging feature failed, but in fact it didn't.

Hope it helps to explain where my intuition breaked.

**Comment by hbitteur** [comment]
Thanks for these valuable remarks.
I will reconsider the user interface of "Split and Merge"
Give me some time...
