### ISSUE TITLE
Student project,

### ISSUE THREAD

**Issue by vesis84** [Audiveris/audiveris#13]
Hi, I really like the idea of the project 'audiveris', while I am working at Brno University of Technology, where we have expertise both in computer vision, machine learning and computer-based speech processing (I am working on git-project kaldi). 
I was wondering, if there would be some 'work package' suitable as a final project for a master student that I would supervise (only formally, but still I'd like to be `in the information loop' :) ). The student could either work remotely or we could arrange it as an internship with some suitable funding, or a combination of both (that would be easy if you are also in academics, but it's not a big deal). What would you think about it?
With kind regards,
Karel Vesely.

**Comment by hbitteur** [comment]
@vesis84: are you looking for a possible student project within Audiveris? If so, please be more specific on which areas you are interested in and on what your concrete contribution could be. 
/Hervé

**Comment by hbitteur** [comment]
Closing this "issue", since no info has been provided as requested on May 3
