### ISSUE TITLE
chords are sometimes transposed 1 or 2 octaves when they are held to next system

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#133]
[In einem kühlen Grunde_03.zip](https://github.com/Audiveris/audiveris/files/1866224/In.einem.kuhlen.Grunde_03.zip)

Sometimes a chord that is held to the next system is transposed 1 octave (or even 1 octave plus a sixth) up. See example.
I see this after import to MuseScore - so it's not completely sure that Audiveris makes the problem.

The problem does not only appear in the case above, but generally for notes that are connected by a hold slur.

**Comment by Bacchushlg** [comment]
Curious...
I read back what I have posted - and don't get the problem. But...
... Reset transcription and re-Transcribe, then export. And the problem is back.

And now: I save the book, read back the saved book and export. Et voilà! Everything is fine.
Très curieux...

**Comment by Bacchushlg** [comment]
I have analysed the files before and after re-import.
The "octave" entry is different in these both, e.g.

>     <measure number="2" width="96">
>       <note default-x="14">
>         <pitch>
>           <step>A</step>
>           <octave>4</octave>
>         </pitch>
>         <duration>3</duration>

after re-import it is:

> 

          <octave>3</octave>

**Comment by maximumspatium** [comment]
> I save the book, read back the saved book and export. Et voilà! Everything is fine.

Looks similar to #118. Maybe it can be helpful to spot the source...

**Comment by Bacchushlg** [comment]
solved with version 5.1.0:4e19fe570
