### ISSUE TITLE
When using the Audiveris in the batch mode it gives an syntax error

### ISSUE THREAD

**Issue by FatihEbibelot** [Audiveris/audiveris#139]
Platform: Ubuntu 16.04
Steps to Reproduce;
1. Git clone development branch
2. gradle build
3- Run the command ' sh ./Audiveris -batch -export -output "/home/ubuntu/output/" -- "/home/ubuntu/input/testsheet.jpg" '

Expected Result: Start generating the mxl with LOAD,SCALE etc. steps
Actual Result: ./Audiveris: 154: ./Audiveris: Syntax error: "(" unexpected

**Comment by maximumspatium** [comment]
Hmm, where do you run the Audiveris command from? `grade build` places its output into `distributions` directory as described [here](https://github.com/Audiveris/audiveris/wiki/Installation#optional-installation).

You'd need to execute the following command chain:

```
cd [your audiveris source directory]
gradle clean build
cd build/distributions
unzip Audiveris.zip
cd Audiveris/bin
sh ./Audiveris -batch -export -output [output path] [input file]
```

I just tested it in my Mac and it works as expected...

**Comment by maximumspatium** [comment]
@FatihEbibelot Have you solved your problem?

**Comment by FatihEbibelot** [comment]
Yes I have. Thank you for the recommendation.
