### ISSUE TITLE
Audiveris.org should point to github.com or a front page for audiveris

### ISSUE THREAD

**Issue by lasconic** [Audiveris/audiveris#14]
Audiveris.org is currently redirecting to kenai.com which has been closed. It would be cool if it could redirect to a meaningful page. Maybe https://github.com/Audiveris/audiveris for now.

**Comment by hbitteur** [comment]
Thanks Nicolas, 
audiveris.org, audiveris.com & audiveris.fr now point to Audiveris organization on GitHub
(https://github.com/Audiveris)
