### ISSUE TITLE
miss-interpretation of beams as double-beams

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#145]
[Zvarniara 1.zip](https://github.com/Audiveris/audiveris/files/1901647/Zvarniara.1.zip)

In this good-quality image the beams are often interpreted as double beams, leading to a complete wrong timing.

**Comment by hbitteur** [comment]
Both examples get all their beams correctly transcribed by current version (5.1.0:37b61b05e as of this writing).
This certainly got fixed by commit 4d23ff9cf6e2787221bffbfeef43859f71872b60 (pushed on May 16) which improved beam thickness evaluation for synthetic scores.
