### ISSUE TITLE
aug.dots of chords are sometimes wrongly assigned -> left unrecognized

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#148]
[killarney.pdf](https://github.com/Audiveris/audiveris/files/1922648/killarney.pdf)

after transcription of this score many aug.dots stay unassigned. The reason is that Audiveris does the assignment in the wrong order: the 1st dot is assigned to the wrong note head, so that the 2nd one does not find a partner. This happens especially for chords where both note heads are on staff lines - so that the aug.dots are half an interline distance above the note heads. (I observed this problem for a couple of scores already).

One way to solve the problem would be to provide a special handling for these cases and do the assignment for the complete chord.
But maybe it would already help the revert the order of assignment: start with the top-most head head / aug.dot. In most cases the aug.dot (interline) is above the note head, so this should help.

**Comment by Bacchushlg** [comment]
![auld lang syne_01](https://user-images.githubusercontent.com/33522630/40900925-37878622-67ce-11e8-9b3c-6679f3dae5cc.jpg)

another example score showing the same problem several times

**Comment by hbitteur** [comment]
Commit 02c6950655054bdfe36ed35123a583a9f1e428bf uses a better ordering to process augmentation dot candidates.
All dots are OK on these 2 examples.

The only exception relates to shared heads, for which we still have no defined policy (does the dot apply to both shared heads, or to only one head and in this case which one?)

**Comment by Bacchushlg** [comment]
About the last question, I propose the following:
if a detected note head belongs to 2 stems, then a detected aug.dot belongs to both heads, too.

**Comment by hbitteur** [comment]
Yes, I will modify the OMR engine to do that: the single augmentation dot will have 2 relations, one with each of the mirrored heads.

Then, if it turns out that one of the mirrored head should not be augmented, it will be very easy for the user to manually remove that relation

**Comment by hbitteur** [comment]
Done with commit db57a1807526b98fe18e09482424fdf87cb30ae2

By default link is set with both heads in pair. User can later remove any link if so needed.
