### ISSUE TITLE
problems with assignment to voices leeding to offset in export

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#149]
[gloria_estefan--everlasting_love.zip](https://github.com/Audiveris/audiveris/files/1923142/gloria_estefan--everlasting_love.zip)

The transcription of this score makes some problems with the assignment to voices:
- page 2 measure 10 provokes an error message:
    Could not setStaff for element class org.audiveris.proxymusic.Forward
    Error visiting {Measure#10P2} in {Page#2.1}

- page 3, measures 14 and 16:
   the first note of the top voice is separated from the other notes

The 1st problem leads to an offset in the export: starting from this measure, the notes in the bass line have one measure offset to the rest.

**Comment by Bacchushlg** [comment]
I only observed this problem once - while transcribing dozens of scores, therefore -> enhancement

**Comment by Bacchushlg** [comment]
The 1st problem is solved with version 5.1.0:d13e4df9f

**Comment by Bacchushlg** [comment]
The problem (page 3) can be "solved" by deleting the note head behind the 8th rest and re-add a note head on a position a bit more to the right (middle of the stem). Then the rhythm check notices that the rest and the note belong to the same voice.

**Comment by Bacchushlg** [comment]
I just re-transcribed this score (page 3) to verify the problem.
While measure 16 is ok now, measure 14 is not output at all. I get an error message:
StackRhythm error processing MeasureStack#14 java.lang.RuntimeException: Population is empty

**Comment by Bacchushlg** [comment]
I just re-transcribed the above score.
While the described problem seems to be solved, another one appears, again in measure 14:
![image](https://user-images.githubusercontent.com/33522630/118252675-509ef700-b4a9-11eb-922e-da5a688d2564.png)

The 1st 8th note on the middle line is detected as separate voice, and I don't get it moved to the same voice (with "same voice" function). I also tried to insert a dotted quarter rest below the 8th rest - no change.

**Comment by hbitteur** [comment]
I had to fix holes in time slots algorithm.
This is now done in commit 0e98eb6285dfced194441d14b083f73b084145c2 (development branch).
Please pull development branch.

The initial problem was that first time slot contained the 8th rest (chord #4631), as you can see below:
![image](https://user-images.githubusercontent.com/22053634/119331026-2ad2d880-bc87-11eb-9fe0-a6c4ee069189.png)

To correct this mistake, you can force time separation between chords 4660 (lower staff) and 4631 (upper staff).
This gives:
![image](https://user-images.githubusercontent.com/22053634/119331978-438fbe00-bc88-11eb-8efb-ff1a928d4cdf.png)

Same correction is needed for measure 16

**Comment by hbitteur** [comment]
I think we can now close this
