### ISSUE TITLE
error when adding bar line: RubberPanel paintComponent java.lang.NullPointerException

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#150]
[Doulce mémoire 1.zip](https://github.com/Audiveris/audiveris/files/1927344/Doulce.memoire.1.zip)

I tried to add the missing bar lines in this score. It won't let me.
I get:
Cannot paint system#1
RubberPanel paintComponent java.lang.NullPointerException

**Comment by hbitteur** [comment]
I suspect that you are creating barlines from scratch, because looking at the binary view, there is no barline at all (except the left and right sides of each staff).

**Comment by hbitteur** [comment]
The TEXT step is awfully long on this example. It triggers the default time-out value.

**Comment by hbitteur** [comment]
The manual barline lacked an underlying area definition to be painted.
Bug fixed in commit f8aa1209d58f9eec660e523283006fca09e19f71

My advice: it's much more comfortable to add barlines after the MEASURES step, since you play with whole (system-high) barlines.

**Comment by Bacchushlg** [comment]
Works fine now!
Yes, the score did not contain any bars at all. This appears rather often for "old" scores.
And: it turned out that it is rather difficult to set the bars... Some notes are simply augmented by aug.points where normally 2 notes would be needed, connected by a slur.
Anyway: The result is good now!
