### ISSUE TITLE
Question: What do we need to release Audiveris 5.1?

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/audiveris#153]
I'm getting more and more pressure to start working ASAP on 6.0 developments (typically the integration of patch-classifier and full-page classifier).

Could each of us review of all pending issues (64 as of this writing) and explicitly assign the **bug** label to the ones we do want to be addressed for 5.1. The other ones will be postponed to 5.2 time frame.
5.1 should also include the related handbook (work started by @Bacchushlg)

@maximumspatium @Bacchushlg and all the others,
Thanks for your contribution

**Comment by Bacchushlg** [comment]
I have put flags to all issues added by me.
If in the list of bug issues there is something which cannot be solved with acceptable effort: for me, non of the issues is a blocker.

What I did not mention so far:
I propose to remove all entries in the menus that are not used any more or that are only meant for development. Same for the boards "pixel" and "glyph". (maybe re-enabled by some setting in the options list).

**Comment by Bacchushlg** [comment]
I have updated the documentation with the short-cut feature.

Are there any items that should be added to the documentation that you have in mind? Just tell me, and I will see want I can do...

**Comment by hbitteur** [comment]
I'm reading the documentation right now.
When you type "rose" for a color, I suppose you mean "pink" (+1 in the debate of German vs English vs French) :-)

**Comment by Bacchushlg** [comment]
https://en.m.wikipedia.org/wiki/Rose_(color)
😉

Am 23. April 2018 12:28:20 MESZ schrieb "Hervé Bitteur" <notifications@github.com>:

**Comment by hbitteur** [comment]
Yes I know of the flower named "rose", it's a French name!!! :-)
I was referring to the color, not to the flower.

**Comment by Bacchushlg** [comment]
...well, the article that is behind the link concerns just this: the color "rose" (english Wikipedia)

**Comment by hbitteur** [comment]
OK, my mistake!

**Comment by hbitteur** [comment]
Regarding the simplification oriented towards the user rather than the developer, you said:
_I propose to remove all entries in the menus that are not used any more or that are only meant for development. Same for the boards "pixel" and "glyph". (maybe re-enabled by some setting in the options list)._

For the boards, it's currently up to the user to add or remove each of them. 
- Pixel board is useful to enter a precise location 
- Glyph board is also useful to type in a precise glyph ID

But OK, perhaps we could define for each board its **initial state** using a constant modifiable by the user. Doing so, the program would provide a default initial set of boards, and the user could both add/remove each of the board interactively as well as decide on its default initial status.

For the menu items, I have no immediate idea for a clean solution. Let me think it over.

**Comment by Bacchushlg** [comment]
I came up again to this while writing the documentation...

Concerning boards, I can tell you that I only use these three boards since a couple of weeks. And I assume that other "normal" users will be more disturbed if we open the additional boards to them. I propose not to display them at all. 
Or did I not understand their usage?
(Do I need the precise location?
Do I need a glyph-id?)

Am I wrong?

Am 23. April 2018 17:13:07 MESZ schrieb "Hervé Bitteur" <notifications@github.com>:

**Comment by hbitteur** [comment]
No, you are right, they will be hidden by default

**Comment by JalonSolov** [comment]
[rose vs pink](https://www.quora.com/What-are-the-differences-between-the-colors-rose-pink-fuschia-and-magenta)...  😃

**Comment by hbitteur** [comment]
Every switch will ultimately be implemented as a persistent constant (this is the low-level means used for persisting any constant, and accessible directly by the user through the "Tools | Options" menu).

At higher level, we can consider several entries:
1.   Global switches on the program itself: Binarization, OCR languages, plugins, DnD, plus all "advanced" switches not yet implemented. Accessible via a new "Tools | Preferences" pull-down menu. 
2.   Switches for the Book at hand, Binarization, OCR languages, accessible via "Book | (set) Parameters" pull-down menu.
3.   Switches for the Sheet at hand, accessible via a new "Sheet | Parameters" pull-down menu. Same parameters as book parameters, but limited to the sheet at hand.

My question: I am not sure of the interest of having separate pull-down menus for book and sheet. Perhaps a popup menu would be more convenient, opening a dialog with 2 tabs, one for the containing book, and one for the sheet at hand.
Such popup menu could also be used to manually specify data such as part name (when clicked from within a part), this kind of things.

So, I can propose:
- One pull-down menu (Tools | Preferences) for all general things.
- One popup menu for book/sheet related switches and information (I'd remove the current "Book | Set parameters" pull-down menu)

Please tell me what you think before I implement this.

**Comment by hbitteur** [comment]
The "Tools | Options" could be renamed as "Tools | Constants" which would be a better fit. If so, we should then rename the CLI  "-option key=value" as something like "-constant key=value". This would also better calll attention on the low-level aspect of this tool.

Then we keep the new "Tools | Preferences" (or name it Tools | Options)

What do you think?

**Comment by Bacchushlg** [comment]
About the 3 proposed high levels: let us reduce to 2. It is - from my point of view - not necessary to provide different settings for each sheet and will make the handling more complicated. Normally we can expect that the pages are of same scan-quality.

What do you mean with "part name"?

Did you have a look at #110 ? I had proposed a couple of settings to improve recognition by suppressing certain elements resp. reduce amount of voices/verses.

I agree to what you propose in the last 4 lines.

about
>  The "Tools | Options" could be renamed as "Tools | Constants" which would be a better fit <
I would prefer to remain with "options". I know that from the point of programming, we have constants, but no "normal" user will understand this. Options is more "common-known" from other programs.

**Comment by hbitteur** [comment]
Basically, we are heading to 2 levels: 
- One (pull-down menu) for global switches (advanced options, default plugin, default DnD step) and default values (binarization params, OCR languages, your added options about lyrics, voices, small heads, etc)
- Another one (popup menu), in the context of a given book/sheet only about the values (not the switches). This will be a 3-tab dialog (default/book/sheet) with the sheet tab pre-selected according to the sheet at hand. Transitively, a default value applies to book unless a book value is specified, and it applies to sheet unless a sheet value is specified. This mechanism is already in place in the old ScoreParameters class. It is  not complex and the user can easily decide on the scope of his modification since he has the 3 tabs available.

So the user only has to specify where something specific is needed: if default binarization parameters are OK for him, he has nothing to do. Otherwise he can specify a binarization param at book level and this will apply to all sheets of the book, except the sheet(s) for which he does specify a local value.

Handling of small heads, handling of voices, are other examples where we can expect to sometimes need different settings in some sheets.

**Comment by hbitteur** [comment]
Update:
The pull-down menu will contain only the global switches (advanced options, default plugin, default DnD step).
The default values will appear only via the popup 3-tab dialog.

**Comment by Bacchushlg** [comment]
Ah, now I see. Yes, good idea.
This means, the user - normally - does not need to provide any setting per sheet unless he really needs to do so.

**Comment by hbitteur** [comment]
Advanced features, to be hidden for end-user by default:
- Book menu
   - Set parameters (removed)
   - Sample Book Symbols
   - View Book Repository
   - Save Book Repository
   - Annotate Book Symbols
- Sheet menu
   - Display Scale plots
   - Display Stem plots
   - Display Staves plots
   - Display NoStaff
   - Display line Glyphs
   - Sample sheet Symbols
   - Annotate sheet Symbols
- View menu
   - Show score Marks
   - Show staff Lines
   - Show staff Peaks
   - Show stick Lines
   - Show letter Boxes
   - Show Attachments
   - Show Sentences
   - Display boards window
   - Display log window
   - Display errors window
- Tools menu
   - Browse Global Repository
   - Save Global Repository
   - Browse a local Repository
   - Train Classifier
- Debug menu (totally removed)

This should make a change!

**Comment by Bacchushlg** [comment]
thumb up!

**Comment by hbitteur** [comment]
Switches for advanced topics are now available in menu "Tools | Advanced Topics" as of commit 4b4ce58a3d60c4410e12ba0b34dd2af2b8070d23

I still need to address the various values handled by the 3-tab popup menu

@maximumspatium Yes, good idea, I will use a temporary branch for this

**Comment by maximumspatium** [comment]
> So the user only has to specify where something specific is needed: if default binarization parameters are OK for him, he has nothing to do. Otherwise he can specify a binarization param at book level and this will apply to all sheets of the book, except the sheet(s) for which he does specify a local value.

Adaptive binarization is a tricky thing. The most users will leave these params untouched because there is no way for them to understand their meaning. In other words, they are just kinda magic numbers, (barely) grokable by advanced users or even programmers.

We either need to explain what happens when the user changes these coefficients or provide a GUI element that visualize the changes like it was done in Capella Scan:

`moving the slide to the left will make the score objects to appear "fat"; moving it the right will make them "thin".` 

Moreover, a possibility to reset the value to the _**factory settings**_ is required, too. Just for the case if anything goes wrong...

**Comment by Bacchushlg** [comment]
From my personal experience concerning these parameters, I can tell you that I tried to improve recognition twice - with no success. I always use a imaging program (XnView normally - Gimp for serious cases) for improvement. The later especially for bad scans (copies of copies of...) with a lot of noise on it.
The advantage of this pre-treatment with such tools is that I see the result of the settings.

So, what I finally want to say: I assume that this settings are not very useful for the user. We should provide a just a very simple setting similar to Capella, e.g. 3-way selection: "thin / normal / fat".

**Comment by maximumspatium** [comment]
> From my personal experience concerning these parameters, I can tell you that I tried to improve recognition twice - with no success.

Well, the purpose of the adaptive binarization filter is to determine foreground/background threshold in images with non-uniform illumination (shadows). It doesn't help to correct other forms of image distortion (skew, speckle, salt&pepper noise etc). In this case, a good image processing software is indispensable...

**Comment by hbitteur** [comment]
The two adaptive binarization coefficients are available with default values. They are meant to cope with illumination differences between an image region and another, but they work equally well for standard well-illuminated images.
This is the reason why this adaptive binarization is always applied by default now.

Any user can play with the adaptive parameters, just to see if the result seems better at end of BINARIZATION step. If not, it's easy to fall-back to the factory values (as with any other Audiveris constant) and to relaunch the BINARIZATION step.

I don't know immediately how to provide a fat/standard/slim approach, so I will leave these parameters as they are.

**Comment by hbitteur** [comment]
Score parameters have been redesigned , see commit fa887f5e574adaee7f9df87a98574277c3771f5b
It is accessible via the `Book | Set parameters` menu and opens a dialog with several tabs:
1. A first one for default global values
2. A second one for book values
3. Other ones for sheet values (if book has several sheets)

The parameters cover: binarization, OCR languages, and 10 processing switches (articulations, chordNames, lyrics, lyrics above staff, fingerins, etc...)
There is an inheritance chain: sheet to book to global to source. So the user can always revert any modification, even up until the source value.

I will need to write a specific section in user documentation to present these features. But you can already discover them by yourselves.
