### ISSUE TITLE
beams are sometimes not detected

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#154]
Since a couple of days (maybe a week) I often have scans where many beams are not detected.
Here is an extreme case where non of the beams have been detected, although the scan is of good quality.

[Zogen einst fünf wilde Schwäne.zip](https://github.com/Audiveris/audiveris/files/1947737/Zogen.einst.funf.wilde.Schwane.zip)

**Comment by hbitteur** [comment]
Yet another .omr without the BINARY part. There must be a bug in saving .omr files perhaps under some wierd conditions. How did you create this .omr file?

Could you send  me the initial image (or another .omr file)?

**Comment by Bacchushlg** [comment]
[Zogen einst fünf wilde Schwäne.pdf](https://github.com/Audiveris/audiveris/files/2030955/Zogen.einst.funf.wilde.Schwane.pdf)

In both cases the source was a PDF-file. Maybe this is the reason for the problem?

**Comment by Bacchushlg** [comment]
another example for this problem can be found in #201 (Desktop.zip)

**Comment by Bacchushlg** [comment]
I have checked this problem after #201 has been solved - and I find out that the changed option value minBeamFraction is rather critical:
For this score I must set the value DOWN to 0.2 and get a "good" result. Except for: in measures 1 and 5 now the transcription detected double beams (16th) (only visible when clicking on the beam).

It seems that the beam detection is really delicate...

**Comment by hbitteur** [comment]
Perhaps we need a different strategy to pick up the typical beam height.
I will check on both #154 and #201

**Comment by hbitteur** [comment]
@Bacchushlg 
In your example, there is almost no beam. So, any detection based on run histogram peaks (which is the current strategy) is very likely to fail.

I will add a quorum test, just to exclude the histogram strategy if the relative part of "probable beam vertical runs" is too low.
And in this case, we'll resort to simply extrapolate typical beam height from interline value. This is not perfect, but certainly better than an erratic histogram.

Also, I plan to add the ability for the user to interactively review and modify the output of the SCALE step (which includes this beam scale), just to have a fallback solution.

**Comment by hbitteur** [comment]
Beam retrieval improved, using quorum and better extrapolation. 
See commit 44e9e82b6c0fa9a05050f139a777291ded9d38fc

Still pending: development of user dialog to modify scale data.

**Comment by Bacchushlg** [comment]
I have tested a couple of "critical" score with this version: all of them are perfect transcribed concerning the beams now!

**Comment by hbitteur** [comment]
Finally, with commit bf2fb1d0afe320881a9e8699bcb2237324893629, the user can interactively modify any sheet scaling parameter, before or after the SCALE step.
Feature is in menu "Sheet | set Sheet Parameters..."
