### ISSUE TITLE
How to make it understand different OCR language in batch mode?

### ISSUE THREAD

**Issue by adie** [Audiveris/audiveris#158]
Hello, I use Audiveris in batch mode, and I have a music sheet photo with Russian title. I have installed `tesseract-ocr-rus` but it cannot recognize it.
It worked when I added `+rus` to https://github.com/Audiveris/audiveris/blob/master/src/main/org/audiveris/omr/text/Language.java#L169 and recompiled. But I wonder is there any way to do it without modification/recompilation in batch mode?
I tried both `master` and `development` branches.

**Comment by hbitteur** [comment]
@adie 
Language(s) specification is an application constant, and as such it can be modified either in interactive or in batch mode. You don't have to modify the code and recompile Audiveris for this.

**Interactive**: Use `Tools | Options` menu, and in the search field, type "language" (without the quotes). You should get quickly to the constant `org.audiveris.omr.text.Language.defaultSpecification`, then simply modify the value by adding "+rus" to the current string value.

**Batch**: use -option org.audiveris.omr.text.Language.defaultSpecification=fra+eng+deu+rus

Mind the fact that interactive modification is persistent, while batch modification is not. 
You should also have the ability to modify this in the `Book | Set parameters` menu, but I'm right now redesigning this feature. Give me a couple of days.

And also, you have to make sure that the russian data for Tesseract has been properly downloaded and installed. But I think you already did that.

**Comment by maximumspatium** [comment]
@adie Was Hervé's answer helpful? Can we close this issue?

**Comment by adie** [comment]
@hbitteur thanks for the hint about `-option`, it worked fine. I use Audiveris only in batch mode, and didn't know that I can override a constant like this.

**Comment by yuriymosk** [comment]
@adie 
Hello.
Please tell, how to add additional language? (rus).
(Подскажите, пож., как подключить русский пакет для распознавания).
Thnx.

**Comment by maximumspatium** [comment]
Audiveris relies on [Tesseract OCR](https://github.com/tesseract-ocr/tesseract) for text recognition so your question actually belongs there. Installation of Tesseract languages is platform-specific and therefore a bit clumsy.

What OS are you running on?

Below a couple of examples:

Linux-Ubuntu: `sudo apt-get install tesseract-ocr-rus`
MacOS: `sudo port install tesseract-rus`
Windows: download russian language data [here](https://github.com/tesseract-ocr/langdata/tree/master/rus), place it into a directory of your choice and set the TESSDATA_PREFIX environment variable to the parent of the destination directory. The default path is `C:/Program Files` on 64bit Windows or `C:/Program Files (x86)` on 32bit Windows (these directory names can be localized in your system so be careful)...

Please ensure that the (mandatory) english language data is installed as well...

**Comment by hbitteur** [comment]
@maximumspatium 
Reading  your message, I realized that there is a need to clarify the handbook on how to support an additional language.

Two actions are needed:
* Have the proper language data downloaded and installed (clearly said in the handbook)
* Add the extension name in the languages specification string (not clearly said, appears only within the Score Parameters dialog, and with no mention of the application constant)

I will take care of this.

**Comment by yuriymosk** [comment]
@maximumspatium @hbitteur 
Hello
I downloaded russian language data to "c:\Program Files\Audiveris\TESSDATA". 
Set the TESSDATA_PREFIX environment variable.
```
>echo %TESSDATA_PREFIX%
c:\Program Files\Audiveris\TESSDATA
```
Added `+rus` option.
And I get error:  "Could not initialize Tesseract with lang deu+eng+fra+rus"

What's wrong?

**Comment by hbitteur** [comment]
Could you post the whole log?
Does it run OK with a language specification of just "deu+eng+fra" (that is without rus)?

**Comment by yuriymosk** [comment]
Done!
It works.
Thnx.

**Comment by hbitteur** [comment]
- Do you have the "eng" language installed (it is mandatory for Tesseract)
- Could you post the full path to your .traineddata files

**Comment by yuriymosk** [comment]
Well, I guess I have "eng" language installed (by default). 
Before coping "rus.traineddata" (v. 3.04) file I search for "tesseract-ocr" and found it here - "c:\Program Files (x86)\tesseract-ocr\" with "tessdata" subdirecroty inside. Then I copied "rus.traineddata" to "c:\Program Files (x86)\tesseract-ocr\tessdata\".
That's all. And it works!
TESSDATA_PREFIX I deleted (If I need, I can set it again)
```
>echo %TESSDATA_PREFIX%
%TESSDATA_PREFIX%
```

**Comment by hbitteur** [comment]
You said:
>echo %TESSDATA_PREFIX%
%TESSDATA_PREFIX%
That's wrong

Are you in a terminal window (cmd.exe):
>echo %TESSDATA_PREFIX%
c:\Program Files (x86)\tesseract-ocr\

or a cygwin window:
$ echo $TESSDATA_PREFIX
c:\Program Files (x86)\tesseract-ocr\

**Comment by yuriymosk** [comment]
```
echo %TESSDATA_PREFIX%
%TESSDATA_PREFIX%
```
This means that there is no variable  TESSDATA_PREFIX at all.
You can try "echo %ANYVAR%" and you get
```
>echo %ANYVAR%
%ANYVAR%
```

**Comment by hbitteur** [comment]
Ah yes, my mistake.
So Tesseract works without TESSDATA_PREFIX ???

**Comment by yuriymosk** [comment]
Audiveris works, yes.

**Comment by yuriymosk** [comment]
How to get news about new version of Audiveris?

**Comment by maximumspatium** [comment]
> How to get news about new version of Audiveris?

By visiting our homepage from time to time maybe? Alternatively, you can pull the latest changes from `development` branch and build Audiveris from source. This way you'll always get the bleeding edge software.
