### ISSUE TITLE
Error in performing [RHYTHMS, PAGE]

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#160]
[Morgenlied.zip](https://github.com/Audiveris/audiveris/files/2000634/Morgenlied.zip)

I don't get the transcription completely running due to the following error:

[Morgenlied] Error in performing [RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException

(version 5.1.0:caef27098)

**Comment by hbitteur** [comment]
Fixed in commit 9fd5ba1031b65d34a5f392df297b0a96f09a0afe
Bug was due to very slanted bars at end of system 3, resulting in a "partial" courtesy stack with a measure for staff 5 but no measure for staff 6. Hence the NPE.
Now, such "partial" courtesy stacks are simply discarded.

**Comment by Bacchushlg** [comment]
works fine now! 
Thank you for the fix!
