### ISSUE TITLE
export mixes systems together

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#166]
[The Girl from Ipanema (2-1).zip](https://github.com/Audiveris/audiveris/files/2022529/The.Girl.from.Ipanema.2-1.zip)

When exporting this score, I get a double size system with part of the 2nd system (measure 4ff) in the lower part.
The rest of the system appears in the following measures.

**Comment by hbitteur** [comment]
This was due to a wrong strategy in connecting parts.
Fixed by commit 5b623fa0b38e3e6032b0d08bcf0f1d48891a3a13

**Comment by Bacchushlg** [comment]
Perfect!
Solved with version 5.1.0:751f97d80
