### ISSUE TITLE
Rhythm analysis ignores existing bar line

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#167]
[Ich weiss es wird einmal ein Wunder geschehn 2.zip](https://github.com/Audiveris/audiveris/files/2041695/Ich.weiss.es.wird.einmal.ein.Wunder.geschehn.2.zip)

In measure 13 there is a bar line, but it is ignored in rhythm analysis. I tried to delete and re-insert, but I cannot delete it.

**Comment by hbitteur** [comment]
Several bugs, fixed by commits e9b8537e0b621c76ab10a9df5e5aa44546476ace and commit 00101959378e3249e55b021f8481479fb3a37adf
The first one relates to better handling of vertical connectors between barlines.
The second one is a bug fix about retrieving parts in a system.
