### ISSUE TITLE
problem with rhythm check for 2 voices with notes of common tick but large offset in score

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#172]
![enya a day without rain2](https://user-images.githubusercontent.com/33522630/40976784-73619406-68cf-11e8-9ab2-a33ce34a6bf9.jpg)

From time to time I get problems with some scores where 2 voices in a staff are not correctly synchronised because note heads of a common tick have a certain offset due to certain circumstances (e.g. common tone but different length).
In this score we can see this in measure 12, where the 8th note of the bottom voice is arranged after the augmented quarter of the top voice, although it is meant to be at the same time slot.
Maybe we need a more flexible algorithm to decide, when notes share the same time slot. In this case there is a great offset due to the aug.dot of the top voice's note.

**Comment by hbitteur** [comment]
Which chords belong to the same time slot?

Vertical alignment is generally a good hint.
But when chords of the same staff are located rather far apart abscissawise, there is no vertical alignment to say the least.

If chords overlap vertically and stems are oriented in the same direction, we can generally infer that these chords don't share the same time slot.

If chords overlap vertically but stems are oriented in opposite directions, we can infer that these chords share the same time slot if the abscissa gap is really small.
But the meaning of "really small" is vague, especially if we want to cope with crowded scores, with tiny horizontal gaps.
Plus here, we have a dot right in the middle of the gap!!! So, the algorithm should take the dot space into account...
It's like an endless fight.

For the interested reader, this is handled in buildRelationships() method within SlotsBuilder class, and especially in the areAdjacent(ch1, ch2) method which decides whether the 2 provided chords should share the same time slot.
Happy reading! Contributions are welcome.

**Comment by hbitteur** [comment]
As a temporary workaround for the example at hand, you can increase the constant maxAdjacencyXGap (in SlotsBuilder class). It is currently set to 0.3 (times score interline).

**Comment by hbitteur** [comment]
Done with commit 176b2fca6ad0eac3d4458ad1bfc39ebb52632880 which takes the potential augmentation dots into account when measuring the horizontal gap between candidate "adjacent" chords.
