### ISSUE TITLE
Audiveris cannot export triplets correctly

### ISSUE THREAD

**Issue by FatihEbibelot** [Audiveris/audiveris#174]
I scanned a pdf file that has multiple triplets and analyzed it with Audiveris. In Audiveris logs and GUI there seem to be very few problems but when I exported the book as mxl, I realized that there are missing triplets. What can be the cause of this problem?

Here is everything necessary to reproduce the problem;
 - PDF -
[test_triplets.pdf](https://github.com/Audiveris/audiveris/files/2091263/test_triplets.pdf)
 - Log Image -
<img width="1263" alt="audiveris_log" src="https://user-images.githubusercontent.com/31078763/41250513-00062dfe-6d6c-11e8-82e0-0d1244d5822a.png">
 - Audiveris GUI first part -
<img width="1333" alt="first_scene" src="https://user-images.githubusercontent.com/31078763/41250519-0529ed20-6d6c-11e8-9f33-62dfb7f9c72d.png">
 - Audiveris GUI second part -
<img width="1333" alt="second_scene" src="https://user-images.githubusercontent.com/31078763/41250520-0544403a-6d6c-11e8-85f8-3a491fd5feb6.png">
 - MXL file -
[test_triplet.mxl.zip](https://github.com/Audiveris/audiveris/files/2091266/test_triplet.mxl.zip)
 - Finale view of MXL -
<img width="597" alt="finaleview" src="https://user-images.githubusercontent.com/31078763/41250628-5507c5ce-6d6c-11e8-985f-7922e4cb566a.png">

**Comment by Bacchushlg** [comment]
![clipboard 1](https://user-images.githubusercontent.com/33522630/41395519-48bb08fa-6fae-11e8-98e1-331d23c39f42.jpg)

Audiveris expects that triplets are marked with a "3". In this score only in the first measure a 3 marks the triplets (and here the number is so bad within the staff lines that it is not detected).
You can add the triplet mark manually by drag-n-drop over the concerning 3 notes (see image).
But: There are triplets with irregual rhythm (measure 3, 7, 9,...) which cannot be handled by Audiveris (I never saw such notation before...)
Despite of the measures with irregular triplets I could correctly analyse the score:
[test_triplets.zip](https://github.com/Audiveris/audiveris/files/2101104/test_triplets.zip)

**Comment by hbitteur** [comment]
For now Audiveris requires that triplets be explicitly marked.
There is no such thing like "implicit" forwarding of triplets in a measure to the following ones.

So, I'm closing the issue as such.
