### ISSUE TITLE
f-clef is interpreted as whole note although the basic classifier recognizes it

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#180]
![sur le fil_01](https://user-images.githubusercontent.com/33522630/41968536-0a7e8ea2-7a05-11e8-9422-a4522c4bf135.jpg)

The f-clefs inside the score are all interpreted as whole note. When putting a lasso around, the basic classifier gives a value around 98% for f-clef-small.

And: after adding the f-clef manually, it is not exported in the MXL-file. More precise: I don't see it in MuseScore (may also be a problem of this program, I cannot verify)

**Comment by hbitteur** [comment]
In Audiveris 5.x, note heads are recognized by template matching (in step HEADS), while most of other symbols are recognized later (in step SYMBOLS) by means of a glyph classifier.

In your particular case, somme inner part of small clef gave a rather good result in template matching for a whole head. Template matching basically checks, for a given properly sized shape, the ratio of expected black pixels that are indeed  black and the ratio of expected white pixels that are indeed white.

This is a bit more complex than that, but this explains why a whole head was "recognized" here.
![image](https://user-images.githubusercontent.com/22053634/42726140-0eb7b82a-8790-11e8-889d-e7de88a577c1.png)

Whenever you manually select a glyph, it is automatically submitted to the glyph classifier (and not to the template matching algorithm), and the top 5 results are displayed.

**Comment by Bacchushlg** [comment]
![sur le fil_02](https://user-images.githubusercontent.com/33522630/44000669-97496512-9e24-11e8-86a1-a48f7032ebbb.jpg)

Look at page 2 of this score - none of the small f-clefs is detected.
Maybe a different detection order could help to solve the problem?
...but on the other hand, I also have problems with detection of clefs where there are none (e.g. in the top score, where some of the fingering digits are detected as clefs).

**Comment by Bacchushlg** [comment]
what would interest me: could there not be a different solution.
I assume that the glyph of the f-clef is marked as "resolved" in a certain way, so that the algorithm does no more look for a symbol in the symbols step.
Maybe there could be provided a sort of "maybe resolved"-flag that allows to search for a symbol and overwrite the first detected interpretation...

**Comment by Bacchushlg** [comment]
problem is no more present in version 145bc93.
