### ISSUE TITLE
Cheat sheet for key bindings

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/audiveris#183]
There are a few key bindings in Audiveris.
There are also some 2-key sequences to manually select a specific shape, for example the sequence 'h'+'b' triggers family "Heads" then shape "Black".

Truth is that often I can't remember the sequences. We need a way to give user a quick access to some kind of cheat sheet.
Perhaps an additional item in Help menu?

**Comment by Bacchushlg** [comment]
Very good idea!
what about a display in the "Shape"-board, directly below the icons? Would be the best place in my opinion

**Comment by hbitteur** [comment]
Done in commit 69f92d138db1f2fa2dcaaa5a3d7baa6ca56f51eb available in development branch

**Comment by hbitteur** [comment]
Closing.
