### ISSUE TITLE
Transcription stops in step "Links" with unclear reason 

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#185]
![allegrettango 1](https://user-images.githubusercontent.com/33522630/42363005-17567818-80f6-11e8-93d7-bd54ee1d4c51.jpg)

The transcription of this score stops with no clear reason with the following errors:

> [Allegrettango 1] No clef found in {Staff id=3 left:147 right:1974} before java.awt.Point[x=1793,y=751]
> [Allegrettango 1] Error in performing [LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.IllegalStateException: No clef found in {Staff id=3 left:147 right:1974} before java.awt.Point[x=1793,y=751]
> [Allegrettango 1] End of sheet step PAGE
> 
The coordinate goes to a normal note head that seems to be of good quality.
I had transcribed the score some time ago with no problem...

**Comment by Bacchushlg** [comment]
![autumn leaves 1](https://user-images.githubusercontent.com/33522630/42363951-c4c56010-80f9-11e8-865c-6394d39faa68.jpg)

same problem with this score.

**Comment by Bacchushlg** [comment]
I just checked out the version 5.1.0:ad92ab927 (10 days old). This one works fine.

**Comment by hbitteur** [comment]
Bug fix in commit d326eb0ff16908e6386e2ee7fc358c93f0ac2d5a 
It was due to an uncomplete assignment of a small flag, with no underlying glyph and thus no bounds, leading to NPE when sorting inters in LINKS step.
I worked on Allegrettango, could you please check on Autumn leaves (because it takes ages to download anything, sorry)

**Comment by hbitteur** [comment]
The bug was already there 10 days ago.
Perhaps, you had disabled the handling of small_flag/small_flag_slash?
