### ISSUE TITLE
Error with imageio spi

### ISSUE THREAD

**Issue by ioan2** [Audiveris/audiveris#19]
Hi,
I have just build audiveris from the git clone. But when I try to run it I get an error at the end for which I cannot find a solution. I use
   export TESSDATA_PREFIX=/usr/share/tesseract-ocr/tessdata
to make tesseract find its data and run audiveris with
  gradle run -Dorg.gradle.java.home=/usr/local/jdk1.8.0_92

The error I get with SchbAvMaSample.pdf is at the end
  [SchbAvMaSample] stem(3 max:4)
Classifier data loaded from default file:///home/jhe/incoming/audiveris/res/deep-classifier.zip
  [SchbAvMaSample] BeamDistance{count:40 mean:14.11 stdDev:0.30}
  **[SchbAvMaSample] Error in TEXTS java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageReaderSpiBase**

I cannot at all open the .png examples, if I try I get a similar error on the console
SEVERE: org.audiveris.omr.sheet.ui.BookActions$LoadImageTask@12d0aea7 failed: java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO

Could somebody point me to my error ?
Thanks in advance
regards
Johannes

**Comment by ioan2** [comment]
Hi again,
I think I've found the solution (at least for the development branch). I added
       [group: 'com.twelvemonkeys.imageio', name: 'imageio-core', version: '3.3.1']
to 
      dependencies {     compile(...) ...
and
      dependencies {     run(...) ...
in build.gradle

(since I have not yet used gradle (only maven) my local repo did not have those packages)

Best
Johannes

**Comment by maximumspatium** [comment]
Are running from the `development` branch or from the `master` branch?

**Comment by maximumspatium** [comment]
Hello Johannes,

which operating system are you running on?

Vectorized PDF files, like SchbAvMaSample.pdf, require FreeType to be available in your $PATH. Please double check it's installed.

For troubleshooting PNG import, please change to the development branch and recompile Audiveris with the following commands:
```
git checkout development
gradle clean run
```
What happens then?

**Comment by ioan2** [comment]
Hi
I'm running Ubuntu 14.04
Which FreeType (jar ?) do you mean? 
With the changes to build.gradle it seems to work (both the stable and the dev branches. I tested the examples (and some IMSLP stuff) and they all work (btw. thanks !)

**Comment by maximumspatium** [comment]
> Which FreeType (jar ?) do you mean?

I mean the [Freetype](https://www.freetype.org) library which is an integral part of every Linux-based OS (but not Windows). Audiveris delegates PDF rendering to [jPod renderer library](https://sourceforge.net/projects/jpodrenderer/) that uses Freetype to render PDFs containing embedded musical and textual fonts.

Freetype is the so-called **native dependency** - that implies that this library is **platform-dependent** and must be therefore installed or compiled for each platform/CPU separately.

I may want to install Freetype in your Ubuntu as follows:

`sudo apt-get install libfreetype6`

If that doesn't work try the following:

`sudo apt-get install libfreetype6-dev`

**Comment by ioan2** [comment]
Oh yes, this one is of course installed. 
The problem was only the 
[SchbAvMaSample] Error in TEXTS java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageReaderSpiBase
Error, but with the modification in the gradle file (see above) it is OK. I'm now wondering how to improve the recoginition rate for some lousy scans (from IMSLP)...

**Comment by maximumspatium** [comment]
This weird error indicates that you're experiencing issues with Audiveris dependencies. Audiveris doesn't normally require imageio-core from com.twelvemonkeys.imageio. It uses [jai-imageio-core](https://github.com/jai-imageio/jai-imageio-core) to handle non-PDF files.

Are you running Oracle's JDK or OpenJDK? What does `java -version` say?

Would you kindly try to delete Maven and Gradle caches and then rebuild Audiveris from the `development` branch?

**Comment by ioan2** [comment]
Hi again,
I did as you said.
My standard java is OpenJDK 7u131. But I run gradle using
gradle run -Dorg.gradle.java.home=/usr/local/jdk1.8.0_92 (which is in Oracle JDK)
After it dowloaded all things needed, GUI started. This are the last lines in the terminal
`:run`
`Property logback.configurationFile not defined.`
`Using /home/jhe/incoming/audiveris-dev/config/logback.xml`
`INFO  []                WellKnowns 496  | Not running from jar.`
`INFO  []                       CLI 253  | CLI args: []`
`INFO  []                      Main 338  | Environment:`
`- Audiveris:    5.0.0:04e0239`
`- OS:           Linux 3.13.0-119-generic`
`- Architecture: amd64`
`- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)`
`- OCR Engine:   Tesseract OCR, version 3.04.01`
`INFO  []             AliasPatterns 121  | Alias patterns: [(IMSLP[0-9]*)-.*]`
`INFO  []               Nd4jBackend 194  | Loaded [CpuBackend] backend`
`INFO  []           NativeOpsHolder 38   | Number of threads used for NativeOps: 4`
`INFO  []        AbstractClassifier 323  | Classifier data loaded from default file:///home/jhe/incoming/audiveris-dev/res/basic-classifier.zip`
`> Building > :run`


I chose `data/examples/SchbAvMaSample.pdf` as a test, but again I get

`[SchbAvMaSample] BeamDistance{count:40 mean:14.11 stdDev:0.30}`
**`[SchbAvMaSample] Error in TEXTS java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageWriterSpiBase`
`[SchbAvMaSample] Cause java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageWriterSpiBase`**
`[SchbAvMaSample] StepException detected in [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, RHYTHMS, LINKS, PAGE]`

**Comment by hbitteur** [comment]
What is the current stats of this issue?

**Comment by maximumspatium** [comment]
I'm going to close this issue due to a long period of inactivity. Feel free to reopen it if the problem still persists.
