### ISSUE TITLE
Does Audiveris support staccato in the musicXML output? if yes how?

### ISSUE THREAD

**Issue by melfk** [Audiveris/audiveris#191]
Hello all,

I have used a PDF file to convert to musicXML. it's super simple, but I don't see any <articulations> or <staccato> in the generated musicXML. Looks like Audiveris detected the staccato on the UI, but didn't put them in the generated musicXML file. 

**1- does Audiveris support staccato in the musicXML? yes or no?
2- if supports, then how come we can't  we see it in the musicXML file? what element specifies it?
3- do we need to set a specific flag for the musicXML export to include <articulations> and <staccato> ** 

Thanks a lot for your help and answer. both PDF and musicXML files are attached.
[Ten Little Indian.pdf](https://github.com/Audiveris/audiveris/files/2190670/Ten.Little.Indian.pdf)

[Ten Little Indian.mxl.zip](https://github.com/Audiveris/audiveris/files/2190674/Ten.Little.Indian.mxl.zip)

**Comment by Bacchushlg** [comment]
I just tested with your score and I get the same problem.
It seems that for some reason, the export of the accents does not work any more  - it did so in the past.
The accents are properly recognized and also appear in the PDF output file.

**Comment by melfk** [comment]
Thanks Bacchushlg, Could it be fixed? Could you point out to the code part for accent export so maybe we can fix it and send it for contribution?

Are staccto articulations supported the audiveris musicXML export?

**Comment by Bacchushlg** [comment]
I finally must admit that I'm not completely sure if the export to xml worked for the staccato symbols - maybe I just saw them inside Audiveris during transcription.
Unfortunately I am not part of the programming team - I just do some testing. So you need to wait for somebody more competent to get an answer to your question.

**Comment by maximumspatium** [comment]
> It seems that for some reason, the export of the accents does not work any more - it did so in the past.

If it worked in the past, we can quickly find the commit causing the failure with `git bisect`. How far in the past did it work?

**Comment by hbitteur** [comment]
Commit c691588626e9b0a832ed049e2e33252cd5424830 fixes the MusicXML export for articulations (this includes staccato), ornaments and arpeggiato.
