### ISSUE TITLE
a black note is not detected in a very simple note sheet in a high quality photo. a bug or a config error? 

### ISSUE THREAD

**Issue by melfk** [Audiveris/audiveris#192]
Hi
I am using a simple note sheet photo that has a high quality, but looks like Audiveris cannot detect the measure 6 notes in the base cleff properly. 

I thought, maybe the black head is small or too close to the measure line?

1) is it a bug or a configuration error?
2) Is there a size for black note head detection that can be adjusted in the template? 

Appreciate your help
Melody

Below is the photo used. you will see the note error in measure 6. I know the accent and staccato problem has been fixed so those are not a concern here only the correct black note detection.

![img_0773](https://user-images.githubusercontent.com/31078432/42728265-afce21f6-876b-11e8-9af2-75c8fa7a9e42.jpg)

**Comment by maximumspatium** [comment]
This issue looks similar to #112.

> is it a bug or a configuration error?

Neither. I suspect that the template matching technique is striking back again. It has been proved to be sensitive to small pixel variations. The images below depict a chord from your score as shown in the template tab (`enabled via Tools | Options | displayTemplates = True`).

First, good note head:

![blkhead_good](https://user-images.githubusercontent.com/6561800/43457265-99d8a0d4-94c6-11e8-986d-0ed36302e6ab.png)

And now, the bad (unrecognized) note head:

![blkhead_bad](https://user-images.githubusercontent.com/6561800/43457296-b29e5e56-94c6-11e8-953f-0767a436855f.png)

As we can see in the last picture, the best grade I could get for this head/template pair is 0.565 while the good head above got a much better grade of 0.71. It's easy to see that the template used for the recognition (actually taken from MusicalSymbols font) differs in its shape from the note head in the score of interest - the note heads in your score exhibit a different rotation and size compared to the note heads in the template font.

> Is there a size for black note head detection that can be adjusted in the template?

IIRC, the size for the template is adjusted automatically based on the interline value (that is, number of white pixels between staff lines) and some analysis of black head spots.

**Comment by hbitteur** [comment]
@melfk Sorry for such a late answer.

It turns out that template matching is not involved in this issue.
It is due to a preliminary check between head candidate and validated barline or bar connector.

Look at your example: this head is rather close to the barline on its left, it was indeed found too close by the preliminary check, and the template matching was not even evaluated...

I made it work by lowering the horizontal margin: you can immediately pull the latest version and it will work on your concrete example.

But I noticed the code is fragile and might not work correctly with slanted scores. Some additional work is still needed.

**Comment by maximumspatium** [comment]
@hbitteur Thank you for your investigation. I was already wondering why it doesn't work as expected. Manual playing with template matching shows good grades. I therefore suspected that any other part of code is responsible for rejecting the missing notes.

**Comment by hbitteur** [comment]
Finally, it was much easier than expected.
Code is now correctly improved with commit bb979f68a7291e1d4d492c8fb92d32f504fa1b02
