### ISSUE TITLE
Building Audiveris on Windows

### ISSUE THREAD

**Issue by joewolf93** [Audiveris/audiveris#193]
Hi!

I installed Git, jdk-10.0.2 and  Tesseract on a Windows 10 machine.
When I try to build it using ./gradlew clean install,  it throws an exception
How can I solve this problem?

$ ./gradlew clean build
targetOS=windows-x86_64
:clean
:git_build
:generateProgramId
:compileJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.ExceptionInInitializerError

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
4 actionable tasks: 4 executed

**Comment by hbitteur** [comment]
Current Audiveris requires JDK8, if you are trying to build with JDK10, this may be a reason for failure.

**Comment by maximumspatium** [comment]
> I installed Git, jdk-10.0.2

JDK 10 isn't supported yet. We're waiting for JDK 11 (the next long-term JDK release) which is expected end of September 2018.

**Comment by joewolf93** [comment]
thanks very much! I'm downgrading to JDK 8 then.

**Comment by joewolf93** [comment]
BUILD SUCCESSFUL in 8m 49s

Thanks for the quick solution
