### ISSUE TITLE
missing staff-end-line lead to detection of whole notes

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#196]
![after you ve gone_01](https://user-images.githubusercontent.com/33522630/44000636-169f8b3a-9e24-11e8-9707-e1be2137d8bd.jpg)

In this score scan the staff end lines are missing. This leads to a detection of whole notes on each line-end

**Comment by hbitteur** [comment]
OK, this is fixed by commit 6782fa7c85056cb176923ad37913e7cc56ad9169
which uses a safety horizontal margin to make sure template is **fully applied within** image limits.
