### ISSUE TITLE
Improving Windows Installer

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/audiveris#203]
Baruch,
Following your Wiki section, I have been playing with building the Windows installer, here are a few results and suggestions.

1/ We should suggest to start from a **clean Audiveris build**, since the build/distributions/Audiveris folder may still contain outdated versions of Audiveris.tar and Audiveris.zip files. This could be commands like "gradlew.bat clean build" for Windows command prompt and "./gradlew clean build" for Windows cygwin terminal.

2/ I downloaded the HM NIS EDIT software as you suggested and opened the Installer.nsi file from it. I edited the default profile, adding a VERSION symbol with 5.1.0 value, then launched NSIS | Compile script.
I got the error message: "Before compile the script please select the NSIS compiler".
Where is that beast? Browsing the documentation I read about **MakeNSIS.exe** being the compiler, but I had no such file. I browsed the Internet, downloaded nsis-3.03-setup.exe from https://sourceforge.net/projects/nsis/ and installed this NSIS compiler.

3/ I was then able, from the NSIS editor window, to actually launch the script compilation. It stopped quickly with error on line 14 (!include "**FileAssociation.nsh**"). I remembered our discussion, then went on Internet to download this file and stored it in /dev folder, next to Installer.nsi script. This time, the script compilation resulted in a Setup_Audiveris.exe file in the /dev folder.

4/ I ran the installer, which showed a first window about Audiveris 5.1 (so what about 5.1.0 I had specified via the **VERSION symbol**???) and went OK. I was then able to launch Audiveris from the Windows launch menu. Also a double-click on a .omr file in file explorer opened the file with Audiveris. Wonderful!

5/ I then unintalled Audiveris from Windows launch menu, asking to remove any configuration data. I tried again a double-click on a .omr file, and Windows prompted me for confirmation of command: **"c:\Program Files (x86)\Audiveris\bin\Audiveris.bat" "%1"**. This was pointing to deleted files. My understanding is that the uninstallation had uninstalled Audiveris software but not the .omr file association.

Recap on suggestions:

- Clean & build (see above)
- NSIS compiler in the prerequisites (see above)
- Clarify how to specify the software version (I tried PRODUCT_VERSION instead of VERSION, but this failed because it was already defined)
- Add FileAssociation.nsh to installer material
- Perhaps provide user prompt for file association?
- Remove file association during the uninstall.
- Define a new folder in /dev, perhaps **/dev/windows-installer**, which would gather Installer.nsi plus FileAssociation.nsh, plus perhaps other related stuff to come (see below).
- Perhaps one day, we'll do something similar for Linux (such as what Raphael just did for Arch Linux), so let's separate the installers right now.
- Could we somehow automate the update of Installer.nsi file, because it contains hard-coded versions of a bunch of .jar files. Could we somehow get these informations automatically from the gradle build file?
- I don't like the idea of storing temporary data (such as Setup_Audiveris.exe" file) in the /dev folder. The /dev folder should contain only "source" data, versioned by GitHub, and the resulting data should be located somewhere below the /build folder.

OK, that's a long list, but the topic is worth it.
Thanks,
/Hervé

**Comment by Bacchushlg** [comment]
I have moved the installer to "installer-windows" subdirectory.
The installer now works with wildcards, so the version of the files does not interest any more (and also any new file will automatically be added).
The setup output now goes to the build directory.
The version text is corrected
The file association for omr-files is removed on uninstall

And I added some advices to the Wiki text - did I get everything?

**Comment by Bacchushlg** [comment]
everything done except for removing the association completely. Seems that the INC file does not work correctly at this point...

**Comment by Bacchushlg** [comment]
found a solution for removing the association completely.

**Comment by Bacchushlg** [comment]
what is the exact error message that you get?

**Comment by webfischi** [comment]
build.gradle line 234
"Cannot find NSIS compiler!"
because I hadn't installed one.

**Comment by hbitteur** [comment]
I guess it's "Cannot find NSIS compiler!"
A stupid bug I'm just working on.
Sorry for that
/Hervé

**Comment by hbitteur** [comment]
Bug is now fixed with commit cdaa061c8f1997a57eb024c407888eb6a7daa4ad
Sorry for this (I'm still learning Gradle...)
