### ISSUE TITLE
Task :compileJava FAILED

### ISSUE THREAD

**Issue by juelan** [Audiveris/audiveris#207]
my attempt to build audiveris fails with essentially the following:
:compileJava (Thread[Task worker for ':',5,main]) started.

> Task :compileJava FAILED
file or directory '/usr/local/src/audiveris/src/main/java', not found
file or directory '/usr/local/src/audiveris/src/main/java', not found
Task ':compileJava' is not up-to-date because:
  Task has failed previously.
All input files are considered out-of-date for incremental task ':compileJava'.
file or directory '/usr/local/src/audiveris/src/main/java', not found
Compiling with JDK Java compiler API.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:compileJava (Thread[Task worker for ':',5,main]) completed. Took 1.544 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.ExceptionInInitializerError

Complete debugging info is in the attached file.
Any help is appreciated.

[audiveris.txt](https://github.com/Audiveris/audiveris/files/2569606/audiveris.txt)

Thanks!

**Comment by maximumspatium** [comment]
OpenJDK 10 and Tesseract 4.x aren't yet supported. To overcome the latter, please downgrade to Tesseract 3.4.

To solve the former, there are currently two options:

- downgrade to OpenJDK 8, then build from `development` branch
- upgrade to JDK11, then switch to `jdk11` branch and build from there

**Comment by juelan** [comment]
thanks a lot for your help!
According to this post I do have openjdk11 already:
https://dzone.com/articles/installing-openjdk-11-on-ubuntu-1804-for-real
Can you confirm this, even when java -version says openjdk version "10.0.2" 2018-07-17?

I downloaded the audiveris-java11 branch and tried to build again. result is:
$ ./gradlew --info build
Initialized native services in: /home/xxxxxxx/.gradle/native
The client will now receive all logging from the daemon (pid: 26164). The daemon log file: /home/xxxxxxx/.gradle/daemon/4.10.2/daemon-26164.out.log
Starting 2nd build in daemon [uptime: 14.324 secs, performance: 99%]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '/usr/local/src/audiveris-java11/settings.gradle'.
Projects loaded. Root project using build file '/usr/local/src/audiveris-java11/build.gradle'.
Included projects: [root project 'Audiveris']

> Configure project :
Evaluating root project 'Audiveris' using build file '/usr/local/src/audiveris-java11/build.gradle'.
targetOS=linux-x86_64
file or directory '/usr/local/src/audiveris-java11/private', not found
All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':git_build', task ':generateProgramId', task ':compileJava', task ':processResources', task ':classes', task ':jar', task ':startScripts', task ':distTar', task ':distZip', task ':assemble', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':test', task ':check', task ':build']
:git_build (Thread[Task worker for ':',5,main]) started.

> Task :git_build FAILED
Task ':git_build' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'git''. Working directory: /usr/local/src/audiveris-java11 Command: git rev-parse --short HEAD
Successfully started process 'command 'git''
fatal: not a git repository (or any of the parent directories): .git
:git_build (Thread[Task worker for ':',5,main]) completed. Took 0.029 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':git_build'.
> Process 'command 'git'' finished with non-zero exit value 128

My git version is 2.17.1

**Comment by maximumspatium** [comment]
> Can you confirm this, even when java -version says openjdk version "10.0.2" 2018-07-17?

Run `update-alternatives --config java` and select JDK11. Then relaunch the terminal and try again.

> I downloaded the audiveris-java11 branch and tried to build again.

Please don't download source code from Github. The build won't work. Audiveris build script queries Git for the latest revision. This script will fail because the downloaded folder doesn't actually contain a valid Git repository+metadata.

You'll need to clone the source code instead using `git clone` from your terminal. It will take a while. Switch to jdk11 branch with `git checkout java11`. You can finally build it.

Below a summary of the terminal commands:

```
git clone https://github.com/Audiveris/audiveris.git [optional destination folder]
cd audiveris
git checkout java11
./gradlew clean run
```
[Our README](https://github.com/Audiveris/audiveris#building-and-running) describes all these steps in great detail. Please take a minute and re-read it.

**Comment by juelan** [comment]
thanks again for the quick reply!
OK, I ran update-alternatives and got
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      manual mode
i.e. JDK11 is selected. Should I switch to "manual mode"? I left it at "auto mode" for now.
I also needed to set an environment variable to get the tesseract plugin loaded:
$ TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/ ./gradlew run
Finally the graphic interface started and didn't initially display error messages!
However, when I tried to open a music score PDF file I got:
WARN  [Halvorsen Clar. II#1]                 SheetStub 764  | Error in performing [LOAD, BINARY] java.util.concurrent.ExecutionException: de.intarsys.pdf.content.CSError: Image can't be rendered (null)
in case of a scanned score.
In the case of a machine generated score (by MuseScore) the image was displayed in audiveris, though.
I then "transcribe"d the score which resulted in the following error message:
WARN  [Ouvertuere_fuer_Orchester_op._posth._170,_D591#1]            TesseractOrder 171  | Could not initialize Tesseract with lang deu+eng+fra 
[Ouvertuere_fuer_Orchester_op._posth._170,_D591#1] Error in performing [TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException
(I did install those languages together with tesseract, though.)
When I tried ti re-import the generated .mxl file, I got the message:
"is not a valid MusicXML file" and "Fatal error: line 36 column 14 Element part-list is missing child element."
The contained XML file looked pretty empty:
[Ouvertuere_fuer_Orchester_op._posth._170,_D591.xml.txt](https://github.com/Audiveris/audiveris/files/2572852/Ouvertuere_fuer_Orchester_op._posth._170._D591.xml.txt)
Anyway, the whole purpose is of course to OCR scanned scores, and in that case even the image wasn't loaded at all.
Should I try to export a page of the score to png format or the like?

**Comment by maximumspatium** [comment]
> However, when I tried to open a music score PDF file I got:
WARN [Halvorsen Clar. II#1] SheetStub 764 | Error in performing [LOAD, BINARY] java.util.concurrent.ExecutionException: de.intarsys.pdf.content.CSError: Image can't be rendered (null)
in case of a scanned score.

Can you share the PDF?

**Comment by juelan** [comment]
[Halvorsen Clar. II.pdf](https://github.com/Audiveris/audiveris/files/2575610/Halvorsen.Clar.II.pdf)
here it is. The resolution seems to be quite low, though.

**Comment by maximumspatium** [comment]
> here it is. The resolution seems to be quite low, though.

The resolution isn't a problem with this PDF, but rather the encoding of the embedded raster image. It looks like we hit one of many PDF corner cases. The story is as follow: audiveris delegates PDF processing to jPodRenderer library which isn't able to render document content for some reason. My bet is that your PDF uses an obscure encoding that is currently unimplemented in jPodRenderer. It's the first time we see such an error after switching to jPodRenderer since 2015.

What to do? Well, the quickest solution is to convert your PDF to multi-page TIFF using another PDF library. Ghostscript is mature enough so you can give it a try.

Sorry for the inconvenience. There is not much our team can do. I'll open an issue in JPodRenderer forum. They may provide a solution. Don't put in too much hope though.

BTW, what utility has produced this PDF?

**Comment by juelan** [comment]
I'm not sure; it was sent to me by an orchestra member. Maybe a stand-alone copier or something like that? I hope to get the music on paper so I can scan it myself. I will post the outcome here.
But nevertheless, the other file I mentionend (generated by musescore) and also all other PDFs I tried as a test could be opened indeed, "transcribe" resulted in that error message about tesseract languages and the produced mxl file couldn't be opened by musescore for further editing. Here is another example:
[preludio-bach.pdf](https://github.com/Audiveris/audiveris/files/2575981/preludio-bach.pdf)
[preludio-bach.xml.txt](https://github.com/Audiveris/audiveris/files/2575984/preludio-bach.xml.txt)
Again there doesn't seem to be much content in the xml file.
Btw, thank you very much for the great support!

**Comment by maximumspatium** [comment]
> Here is another example: preludio-bach.pdf

No problem. Audiveris recognizes the first two pages almost perfectly. Although the last page contains errors, the overall recognition is good.

> "transcribe" resulted in that error message about tesseract languages

As I already said, Tesseract 4.x isn't supported by audiveris. It looks like you're trying to feed Tesseract 3.4 with v4.0 language files. That won't work because Tesseract 4 uses a completely different model.

You need v3 language files. You could try built-in packages first:

```
sudo apt-get install tesseract-ocr-swe
sudo apt-get install tesseract-ocr-eng
...
``` 

This should install specified language files into the location audiveris expects them. On Debian/Ubuntu it's `/usr/share/tesseract-ocr`

Alternatively, you can download them manually to a directory of your choice and set TESSDATA_PREFIX to point to its PARENT directory. TESSDATA_PREFIX need to be set permanently.

**Comment by juelan** [comment]
It finally worked! Your help is very much appriciated!
For others, here is what I did:
- removed tesseract 4 language files: sudo apt remove tesseract-ocr-deu tesseract-ocr-fra (tesseract 4 remained installed)

- downloaded the 3.04.01 source code from https://github.com/tesseract-ocr/tesseract/releases/tag/3.04.01 to /usr/local/src/tesseract-3.04.01

- installed dependencies  sudo apt-get install libleptonica-dev
 sudo apt-get install g++ autoconf automake libtool pkg-config libpng-dev libjpeg8-dev libtiff5-dev zlib1g-dev

- built and installed tesseract 3.04.01:
./autogen.sh
./configure
 make
 sudo make install

- downloaded language Data Files for Version 3.04/3.05 from https://github.com/tesseract-ocr/tesseract/wiki/Data-Files to /usr/local/share/tessdata/

at this point I couldn't run audiveris as you explained before with again this error message: "Task :git_build FAILED"

Thus I did again:
git clone https://github.com/Audiveris/audiveris.git audiveris-java11
cd audiveris-java11
git checkout java11

So finally I could run audiveris:
TESSDATA_PREFIX=/usr/local/share/ ./gradlew --info clean run

Btw. is this the correct way of starting the program (i.e. by using gradlew)?

**Comment by juelan** [comment]
After a week of testing Audiveris, here is my feedback:
For machine generated scores the recognition is indeed very good, at least the music part thereof. For the text/lyrics parts it doesn't work that well. I suppose it's much more difficult as this isn't as standardized as the score.
For scanned music (glitches like dots and slanted scores) the recognition is quite bad or not working at all, as far as I see.
See e.g. these 3 pages: 
![halvorsenclarii-i-1](https://user-images.githubusercontent.com/44943516/48777187-39189600-ecd2-11e8-8c9e-7569ac84ea6a.png)
![halvorsenclarii-i-2](https://user-images.githubusercontent.com/44943516/48777188-39b12c80-ecd2-11e8-8575-2801b4805941.png)
![halvorsenclarii-i-3](https://user-images.githubusercontent.com/44943516/48777189-39b12c80-ecd2-11e8-8980-85187e4f5b5c.png) (bad recognition)
or this page: 
![halvorsenclarii_7](https://user-images.githubusercontent.com/44943516/48777210-4a61a280-ecd2-11e8-8c87-6b993202a1ca.png) (not working)
Please consider this as a feedback, not as a request!
Thank you very much for your help and effort!

**Comment by maximumspatium** [comment]
> For machine generated scores the recognition is indeed very good, at least the music part thereof. For the text/lyrics parts it doesn't work that well. I suppose it's much more difficult as this isn't as standardized as the score.

No, this is a well-known Tesseract problem, been already discussed several times. Please refer to these posts for further description:
https://github.com/Audiveris/audiveris/issues/44#issuecomment-358401602
https://github.com/Audiveris/audiveris/issues/44#issuecomment-359288734
https://github.com/Audiveris/audiveris/issues/44#issuecomment-359354701

> For scanned music (glitches like dots and slanted scores) the recognition is quite bad or not working at all, as far as I see.

Your precise Halvorsen-example is a low-resolution, handwritten score audiveris hasn't been designed for. The results may therefore vary from okay to bad. We're currently focusing on recognizing of printed scores so you're encouraged to test audiveris on a scan of a printed score. I'm sure you'll obtain satisfying results then...

**Comment by jajavava** [comment]
I had rather similar issue when ./gradlew run. Got the following error.
I'm very new to this.
my tesseract is 3.0.3
I am running Debian Jessie.
=========
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-8-openjdk-i386 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
3 actionable tasks: 3 
================

**Comment by maximumspatium** [comment]
JDK installed? Try
`sudo apt install openjdk-8-jdk`

**Comment by hekkup** [comment]
Is this still an issue? I have been able to build&run Audiveris with OpenJDK 8, 11, and 13 (each from Ubuntu 19.04 stock packages), and Oracle Java 13 (DEB package from Oracle).

There was only a small hiccup with Java 13 but it was easy to fix: needed to change FileSystems.newFileSystem(path, null) to FileSystems.newFileSystem(path) in Book.java and ZipFileSystem.java. Check the build error messages to see the actual line numbers.

You may have to set the JAVA_HOME environment variable correctly. With the current Oracle JDK 13 at Ubuntu it's /usr/lib/jvm/jdk-13.0.1.

**Comment by hbitteur** [comment]
No more activity
Closing the issue
