### ISSUE TITLE
Reducing CPU load

### ISSUE THREAD

**Issue by their** [Audiveris/audiveris#21]
Building on Fedora Linux. Is there a way to reduce the number of CPU cores to only one throughout the gradle build process? So far the only method tried is ```gradle build --max-workers 1``` but at some point this utilizes all CPU cores. Only utilizing one CPU core is preferable. The build process is long and CPU temperature is an issue.

**Comment by hbitteur** [comment]
Sorry, I don't know of any way to do this.
Question: how long does it take to build Audiveris on your machine? On my 6-year old laptop, it takes exactly 1 mn for a clean build, the CPU doesn't have time to warm up.

**Comment by their** [comment]
Ah, okay. That is interesting. The build is stalling during running tests and never completing. The longest it has run or is maybe twenty minutes. At that point it either crashes with memory limit exceeded or I close it because the CPU usage is too demanding. Usually the CPU temp. would not be an issue but right now I am avoiding re-pasting the CPU due to travel 👍 . Maybe there are some prerequisites to install prior to building to speed up the build process?

**Comment by hbitteur** [comment]
I just ran all 187 tests. 4 failed (in TestCompound and TestEntity classes) with the same com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException generally due to an illegal annotation in JAXB.
Sorry, I have no time to further investigate this (now useless) test case. Please ignore it.

**Comment by hbitteur** [comment]
OK, I finally found a more precise error message.
The test is now fixed (available on release-5.0 branch)

**Comment by their** [comment]
Okay. So it makes it further along. But it is still taking a long time on a five-year-old laptop. It is sitting here: ```> Building 81% > :test > 94 tests completed```. Is there any way to skip the test as part of building?

**Comment by jlpoolen** [comment]
For what it's worth, here are my statistics and recollection.

I have a Dell Inspiron N7010 which I bought in the Fall of 2010.

Processor: 2.4GHz Intel Pentium Core I3
  Chipset: Mobile Intel HM57 Express
  Memory: 6GB DDR3-1333
  Hard drive: 500GB 5400rpm

I had tried using the Subversion pull, it failed (I was on a train through the Oregon Alps where wifi was intermittent).  Then I read that GIT needs to be active.  I tried with a git pull at home with a good Internet connection and I recall it took about 2-5 minutes to build.  I just monitored the console and it looked like there were hundreds of files being downloaded.  I do not remember hearing the processor fan ramp up.

**Comment by hbitteur** [comment]
My statistics did not include any downloads, because they usually are done once only.
I think I remember there was about 128 binaries to download, transitively.

**Comment by hbitteur** [comment]
@their 
A quick googling gave me:
gradle build -x test

**Comment by their** [comment]
@hbitteur Ah okay. Thanks 👍

**Comment by their** [comment]
Yes, it builds very quickly now.
