### ISSUE TITLE
Same Beam Heads not reading on different page

### ISSUE THREAD

**Issue by WilloZA** [Audiveris/audiveris#212]
Beam heads that are exactly the same are not being read correctly on 2 separate pages:

![image](https://user-images.githubusercontent.com/26063400/49288416-55be8600-f4a9-11e8-83a3-a230d0189bd8.png)

Whereas on the very next page it will not pickup:

![image](https://user-images.githubusercontent.com/26063400/49288428-5ce59400-f4a9-11e8-8601-d2f0ca2bb3a5.png)

Any help or advice would be greatly appreciated, thanks

**Comment by WilloZA** [comment]
Thank you for your response. I do apologize for not adding enough information.

I will send you the full pdf document:

[Purpose.pdf](https://github.com/Audiveris/audiveris/files/2636216/Purpose.pdf)

**Comment by WilloZA** [comment]
Thank you for your response. I tried to search within options for beamRangeRatio, unfortunately it cannot be found. Are you perhaps talking about another option?

 
![image](https://user-images.githubusercontent.com/26063400/49365985-d58a6180-f6f0-11e8-94dd-77fb21d88e31.png)

**Comment by hbitteur** [comment]
I'm positive. "beamRangeRatio" is the right name.
But yesterday I detected and fixed a regression in the Options dialog, that may prevent you for correct search.
Could you pull again, checkout the release-5.1 branch, and rebuild?
Sorry for that.

**Comment by WilloZA** [comment]
Thank you the problem is now resolved.
