### ISSUE TITLE
some notes are missing in the exported file

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#213]
some notes in this file are missing in the exported file (at least don't appear after import in MuseScore) although they are properly recognized.
It concerns the last system, first and 2nd measure.
[Was Du mir erzählt hast (1).zip](https://github.com/Audiveris/audiveris/files/2636052/Was.Du.mir.erzahlt.hast.1.zip)

**Comment by Filius-Patris** [comment]
Happened to me too.

Also the lyrics is very wrongly aligned at this point.
Just in MuseScore however.

**Comment by Bacchushlg** [comment]
problem is no more present with actual version c5a505aff
