### ISSUE TITLE
detection of Ties as Slurs in case of Accidentals

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#219]
in case that accidentals appear before notes that span over to the next measure (with a tie), these accidentals are not applied to the tied note. Therefore the note gets a wrong note pitch and the tie is replaced by a slur (logical, because the pitch is no more identical).
See this score as example (1st system)

![wiseguys mad world-3](https://user-images.githubusercontent.com/33522630/49643143-3d082000-fa15-11e8-8b17-654350f25124.jpg)

**Comment by hbitteur** [comment]
Tie detection should now be correct in commit 78926ccf5b99b149ca9bd927087e634377c9aeee with or without accidentals.
Could you try on some other examples?

**Comment by Bacchushlg** [comment]
perfect. I checked with a couple of scores - even some complex ones. All of them were now correctly analysed with ties at the correct places and correct pitch
