### ISSUE TITLE
Support for 4 hands piano sheet

### ISSUE THREAD

**Issue by Maarethyu** [Audiveris/audiveris#220]
Some four hands piano sheets have a page/page layout, where left page is for left player and right page is for right player.
The two pages are meant to be played at the same time.

We need a way to tell Audiveris that every 2 pages needs to be played at the same time.

**Comment by hbitteur** [comment]
@Maarethyu 

1. Could you provide an input file (certainly pdf or tiff format) that we could use as a concrete example?
2. How such page-based layout would be formalized in the MusicXML output? Here again, a concrete MusicXML output might help.
3. We need a way for the user to tell Audiveris that the input at hand is a 4-hand piano specific layout.
4. How should we assign a given page to its proper player? A (perhaps simplistic) approach could rely on page number: an even number for left player and an odd number for right player (or vice versa???).

**Comment by Maarethyu** [comment]
1. Here is an example: [[Free-scores.com]_rachmaninoff-sergei-the-island-the-dead-111715.pdf](https://github.com/Audiveris/audiveris/files/2752324/Free-scores.com._rachmaninoff-sergei-the-island-the-dead-111715.pdf)

2. I have not digged into MusicXML yet, so I would guess the best way to express this 2 page format would be 4 piano staves like this: ![screenshot_1](https://user-images.githubusercontent.com/11776438/51076518-affe5980-1699-11e9-97e5-1839870a00ab.png)

3. That's up to you, it doesn't really matter to the end user.

4. The odd/even approach will probably work everytime as long as you allow to choose wich one of odd or even is the left or right page

**Comment by maximumspatium** [comment]
To my knowledge, there is no way to express such layout in MusicXML 3.0. Moreover, changing music layout is beyond the scope of Audiveris.
I think the easiest approach is to extend Audiveris export function to spill sheets into MusicXML in a custom-defined way by means of an additional dialog. In this precise case it would look like that: odd sheets -> left piano, even sheets -> right piano.
Then both piano parts can be merged into one score using a dedicated score editor (if wanted to).

**Comment by hbitteur** [comment]
In standard notation, music flows from one system to the next, and from one page to the next.
Here, we are talking about changing this principle, so it is not only a question on exporting to MusicXML.

By introducing odd/even pages, we require the OMR engine to "jump" over each other page. For example  orphan slurs at the end of a page will need to be connected to orphan slurs at the beginning of the "next" page, and of course "next" here has a very special meaning, not +1 but +2. A very specific feature.

Instead, I would suggest that you have a look at issue #232 your request is a bit different but you could use a similar workaround. With PDFSAM utility, you could easily gather every other page into a "primo" PDF and the others into a "secundo" PDF. Then ask Audiveris to transcribe each PDF into MusicXML and finally "merge" the two instruments with help of a music editor like MuseScore, Finale, etc...
