### ISSUE TITLE
start on Windows 10 is impossible

### ISSUE THREAD

**Issue by LeTraviator** [Audiveris/audiveris#225]
Hello!

It is impossible, to start Audiveris. Only a very short time a window comes up. If I start as an administrator the same occures.

Audiveris_Setup-5.1.0-windows-x86_64.exe ( Dec 13, 2018)
I have Win 10 (64), Java see:
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

Installation was no problem. I changed path to "c:\Program Files\Sound\Audiveris\". Could that make problems?

What can I do?

Thank you for all help and excuse please my bad English.

Best greetings and all the best to the New Year

LeTraviator

**Comment by hbitteur** [comment]
@LeTraviator 

1/ First check for Audiveris log file(s).
You should find them in %APPDATA%\AudiverisLtd\audiveris\log folder
where %APPDATA% translates as something like C:\Users\YOUR-NAME\AppData\Roaming
There, you should find files named like: 20190103T184806.log
Please post such .log file if you can find one.

2/ If there is no .log file, then there might be a problem with the .bat file that is used to launch Audiveris.
What you should try is to open a terminal window (cmd.exe), navigate to where you installed Audiveris, and manually launch the audiveris.bat file from the terminal window.
Then pay attention to the error messages that you may get (and post them as well)

**Comment by LeTraviator** [comment]
Hello!

1:
I'm sorry, but I couldn't find %APPDATA%\AudiverisLtd\audiveris\log folder

2:
I got the error message
ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files 
(x86)\Java\jre1.8.0_131

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Where can I correct the JAVA_HOME variable, please? 
c:\Program Files\Java\jre1.8.0_192\     does exist

Thanks for your help!

LeTraviator

**Comment by LeTraviator** [comment]
Hi!
I managed to correct the variable. Now Audiveris starts! Great. But I get new messages:

Audiveris version 5.1.0

LogUtil. Property logback.configurationFile not defined, skipped.
LogUtil. No C:\Users\home\AppData\Roaming\AudiverisLtd\audiveris\config\logback.xml, skipped.
LogUtil. Configuration found jar:file:/C:/Program%20Files/Sound/Audiveris/lib/audiveris.jar!/res/logback.xml
LogUtil. Logging to C:\Users\home\AppData\Roaming\AudiverisLtd\audiveris\log\20190104T184749.log

No C:\Users\home\AppData\Roaming\AudiverisLtd\audiveris\config\plugins.xml file found
Classifier loaded XML norms.
Classifier data loaded from default uri jar:file:/C:/Program%20Files/Sound/Audiveris/lib/audiveris.jar!/res/basic-classifier.zip

Are this a serious problems?

Could you help please again?

LeTraviator

**Comment by maximumspatium** [comment]
Closed because everything seems to work as expected.

**Comment by Mairani** [comment]
Same issue. here are the log files
20190611T170601
20190611T170601
20190611T171147
20190611T171224

**Comment by maximumspatium** [comment]
@Mairani I can't see any attached files, only names...

**Comment by Mairani** [comment]
These were to Log files found in the APPData  just cet cmd, the runs and see the lone of code by goes right off.  Can't capture. in Prog. x86 I just have the short cut,  and uninst.  In BIn I have a windows batch, icon, and a small 7KB audivereis file, and in Lib thereare 42 executables. In tesseract-ocr there are 20 file but no .exe files.  Maybe you can see the issue.  Java is up to date and as Windows 10. Thx

**Comment by Mairani** [comment]
Thank you so much

Please explain what you need and I will do my best.  I just provided you with the log names.  So, it is logging . Here are screen shots od the files. Let me know which files you need. What I do not see is an executable?

[cid:image001.jpg@01D520ED.6151DAB0]

[cid:image002.jpg@01D520ED.6151DAB0]

[cid:image003.jpg@01D520ED.6151DAB0]

[cid:image004.jpg@01D520ED.6151DAB0]

Jerry & Jan Mairani
Jan: janm@mairani.com<mailto:janm@surewest.net>
916-775-4487
Jerry: jerry@mairani.com<mailto:jerry@mairani.com>
916-384-6777

**Comment by maximumspatium** [comment]
> Please explain what you need and I will do my best.

Open the Windows terminal and run the following command:

`java -version`

What does it say?

**Comment by Mairani** [comment]
I ran the “Run Command” for java -version and the cmd window appeared briefly (just flashed) and the closed.
?

Jerry & Jan Mairani
Jan: janm@mairani.com<mailto:janm@surewest.net>
916-775-4487
Jerry: jerry@mairani.com<mailto:jerry@mairani.com>
916-384-6777

**Comment by Mairani** [comment]
Got it

Jerry & Jan Mairani
Jan: janm@mairani.com<mailto:janm@surewest.net>
916-775-4487
Jerry: jerry@mairani.com<mailto:jerry@mairani.com>
916-384-6777

**Comment by Mairani** [comment]
Sorry. I should have told what the issue is. I cannot run Audiveris.  Pretty much does what I just did with java-version but I see a script run and then it closes.

Jerry & Jan Mairani
Jan: janm@mairani.com<mailto:janm@surewest.net>
916-775-4487
Jerry: jerry@mairani.com<mailto:jerry@mairani.com>
916-384-6777

**Comment by maximumspatium** [comment]
> I ran the “Run Command” for java -version and the cmd window appeared briefly (just flashed) and the closed.

Don't use "Run Command". Open a separate terminal window instead. The quickest way to do that is to type "term" into the Windows [search box](https://support.microsoft.com/en-us/help/4028221/windows-10-locating-the-search-box-in-windows-10). It should immediately find the command prompt. Select it and hit "Enter". A new (usually black) window will appear.
[This](https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/) blog article explains several ways to open the command prompt under Windows. Just pick up one that works for you.

Then type in

`java -version`

followed by enter and post the result here. Thanks.

**Comment by Mairani** [comment]
Here it is:

[cid:image002.jpg@01D52111.61A6F530]

Thx

Jerry & Jan Mairani
Jan: janm@mairani.com<mailto:janm@surewest.net>
916-775-4487
Jerry: jerry@mairani.com<mailto:jerry@mairani.com>
916-384-6777

**Comment by maximumspatium** [comment]
> Here it is:

Sorry, I cannot see any picture. Github seems to remove attachments within email messages. You'd need to upload your picture directly via Github web interface or copy the content of your command prompt and paste it here as plain text. Thanks...

**Comment by Mairani** [comment]
Here is the text

Microsoft Windows [Version 10.0.17134.829]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\quali>java-version
'java-version' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\quali>java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode)

C:\Users\quali>

Jerry & Jan Mairani
Jan: janm@mairani.com<mailto:janm@surewest.net>
916-775-4487
Jerry: jerry@mairani.com<mailto:jerry@mairani.com>
916-384-6777

**Comment by maximumspatium** [comment]
>java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode)

It looks like you're running 32bit Java. Is your CPU also 32bit or 64bit? If you have "C:\Program Files (x86)" folder in your Windows folder then you're on 64bit CPU and should run 64bit Java...

Did you try to run Audiveris directly from the command prompt? If not, it's worth trying. In your command prompt, run the following commands:

```
cd [path to audiveris directory]
Audiveris.bat
```

For further explanation see [this](https://github.com/Audiveris/audiveris/wiki/Launching#launching-audiveris) wiki page.

What do you see there?

**Comment by Mairani** [comment]
This is a 64bit machine. Just on the way to the dump. Will try all you suggestions later today. Thanks so much.



Sent from my Samsung Galaxy , an AT&T LTE smartphone


-------- Original message --------

**Comment by Mairani** [comment]
Uninstalled 32bit java and then installed 64bit.  Issue resolved.  Thank you very much.

Jerry & Jan Mairani
Jan: janm@mairani.com<mailto:janm@surewest.net>
916-775-4487
Jerry: jerry@mairani.com<mailto:jerry@mairani.com>
916-384-6777

**Comment by maximumspatium** [comment]
> Uninstalled 32bit java and then installed 64bit.  Issue resolved.  Thank you very much.

You're welcome!

**Comment by royleith** [comment]
I know I'm late to the party, but,

Running the batch file via Command Prompt gives me

```
c:\Program Files (x86)\Audiveris\bin>audiveris.bat
INFO  []                      Main 338  | Environment:
- Audiveris:    5.1.0:9fa751d43
- OS:           Windows 10 10.0
- Architecture: amd64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 206  | CLI args: []
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:128)
        at org.audiveris.omr.sheet.BookManager.getInstance(BookManager.java:313)
        at org.audiveris.omr.Main.main(Main.java:140)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 4 more
```

Running from the start button briefly gives what appears to be a prompt window with the same text.

**Comment by hbitteur** [comment]
JAXBException is part of the Java items that were part of Java 8, but optional on Java 9 and later. This is the root cause for the failure you encountered.

Now, you have two possibilities:

- Audiveris latest official release is 5.1 which **requires** Java 8, not Java 9 or other higher Java version. If you just use the Windows installer or if you pull and build from "master" branch, you get this 5.1 version. This is because "master" branch gets updated only when a new Audiveris version is officially released.

- You can use Java 11, if you pull and build from the "development" branch (which gives 5.2-alpha, not yet officially released). I'd advise you to do so.

**Comment by royleith** [comment]
Hi Hervé,

Thank you for such a prompt and helpful response. I will polish up my 
maker skills and give the Developer branch a go.

Regards
Roy Leith

------ Original Message ------

**Comment by EchoRoblox** [comment]
This thread is closed, I know, but Command Prompt gives me this when I tried to run the .bat file.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnilept in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
        at org.bytedeco.javacpp.Loader.load(Loader.java:613)
        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
        at org.bytedeco.javacpp.lept.<clinit>(lept.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bytedeco.javacpp.Loader.load(Loader.java:585)
        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
        at org.bytedeco.javacpp.tesseract$TessBaseAPI.<clinit>(tesseract.java:3648)
        at org.audiveris.omr.text.tesseract.TesseractOCR.identify(TesseractOCR.java:152)
        at org.audiveris.omr.Main.showEnvironment(Main.java:348)
        at org.audiveris.omr.Main.main(Main.java:122)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.UnsatisfiedLinkError: no liblept in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
        at org.bytedeco.javacpp.Loader.load(Loader.java:604)
        ... 11 more
```

I installed 64-bit Java and my PC is 64-bit. When I tried to do java -version, it gives me this:
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) Client VM (build 25.261-b12, mixed mode, sharing)

How do I solve it? Thank you.
