### ISSUE TITLE
Malware detection: Audiveris_Setup-5.1.0-windows-x86_64.exe

### ISSUE THREAD

**Issue by amai2012** [Audiveris/audiveris#226]
https://github.com/Audiveris/audiveris/releases/download/5.1.0/Audiveris_Setup-5.1.0-windows-x86_64.exe gets detected as malicious by various virus scanners.
e.g. https://www.virustotal.com/#/file/de10be0ed3320406fe0c114b53b0630c7b53c8163c8945f80fbf0dd3bd26b3e1/community

**Comment by hbitteur** [comment]
The question is: Does it really contain a virus or is this a false positive?

**Comment by amai2012** [comment]
My report just covers the findings, I cannot add more information :-(

In case of false positives one should probably try to report those. For the two AV engines from virustotal I did not find an upload facility at the vendor homepages.

**Comment by amai2012** [comment]
https://virusscan.jotti.org/de-DE/filescanjob/406mndp2ie shows no problem, and trying again on virustotal shows only engine complaining today...

**Comment by maximumspatium** [comment]
1 of 67 looks with 99% confidence like false positive. Don't worry about that. Windows does much more harmful stuff behind your back (just think of it continuously "calling home"), so I think it itself qualifies as malware to say the least.

If you don't trust our installer, feel free to build Audiveris from source. This way you can make sure you won't install a malware this time 😉

**Comment by maximumspatium** [comment]
It looks like there is no further objections/complains. The issue will be closed.
