### ISSUE TITLE
Multiple staccato dots attached to the same note/chord

### ISSUE THREAD

**Issue by maximumspatium** [Audiveris/audiveris#230]
The following score

[albjugend5.pdf](https://github.com/Audiveris/audiveris/files/2775811/albjugend5.pdf)

reveals several cases of multiple staccato dots assigned to the same note/chord:

![multiplestaccato1](https://user-images.githubusercontent.com/6561800/51430413-7094b780-1c1b-11e9-8b2f-ea0a83b7a00f.png)
![multiplestaccato2](https://user-images.githubusercontent.com/6561800/51430425-991cb180-1c1b-11e9-948e-55523ebdebab.png)

Because that makes no musical sense, Audiveris should check for multiple articulations of the same type assigned to the same note/chord and reject them.

**Comment by hbitteur** [comment]
This case is now avoided by the fact that ChordArticulationRelation which formalizes the link between a chord and an articulation (tenuto, accent, staccato, staccatissimo or marcato) is declared as both singleSource and singleTarget.

So, this issue is now closed.
