### ISSUE TITLE
Text overlaps with other musical symbols

### ISSUE THREAD

**Issue by maximumspatium** [Audiveris/audiveris#231]
As the title say, the score [albjugend5.pdf](https://github.com/Audiveris/audiveris/files/2775819/albjugend5.pdf) reveals the case where some text and musical symbols are overlapping:

![textmusicoverlap](https://user-images.githubusercontent.com/6561800/51430511-a38b7b00-1c1c-11e9-86bf-f330366ec02b.png)

Such cases are difficult to locate and should be checked during recognition (perhaps by examining the bounding boxes)...

**Comment by hbitteur** [comment]
The engine has run step TEXTS resulting in the Langsamer word.
Then the step CURVES has "detected" a small curve.

We could trust the OCR and "remove" the underlying glyph of Langsamer before launching the CURVES step.
The point is: when can we trust OCR? Here, I think the word is long enough. But for very short words, we cannot know.

**Comment by hbitteur** [comment]
Done with commit 5c9d2b8e198c69e0ba668a04a1be32f3b0f6aed8
which uses each word grade to decide on its removal.
