### ISSUE TITLE
some minor handling features

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#235]
some minor features would be nice to have:
- allow breaking the actual transcription process (esp. for multipage scores)
- after opening a multipage image (pdf or tif), the blue transcribe button stays inactive. The user must switch to a 2nd page in order to make it active.
- provide a function to clear the output windows

**Comment by hbitteur** [comment]
> * allow breaking the actual transcription process (esp. for multipage scores)

I think this can be addressed by the `Book | Select sheets` menu item, allowing to focus on some sheets only before getting to others.

If you mean "launching a full-nook transcription" and suddenly realize that this is too much, well there is no safe way to "interrupt" the processing.

**Comment by hbitteur** [comment]
> * after opening a multipage image (pdf or tif), the blue transcribe button stays inactive. The user must switch to a 2nd page in order to make it active.

This is  no longer true: the blue transcribe button is immediately enabled.

**Comment by hbitteur** [comment]
> * provide a function to clear the output windows

What do you mean by "output window"?

If you mean to clear the log window at the bottom of Audiveris screen, this feature is already available under the pulldown `Debug` menu, provided you activate proper DEBUG switch in the `Tools | Advanced topics`.

If you think this feature should be available for everyone and not only a debugger just tell me.
The risk is to click on the Scissor-like button (which is bound to this feature). This clears the log windows immediately, without prompting for confirmation.
We still have the .log file though, so we don't delete every information.
Tell me if a confirmation should be implemented.

**Comment by Bacchushlg** [comment]
Oh, I did not see this possibilty (activate debug menu).
But why not allow everybody to clear the window?
I often have multipage scores, and with the time the log windows gets very long. 
And on the other hand: even when clearing the log window by accident: nothing is really lost - only the logs.

So, about the latter question: yes, put this command to a "public" menu part (or right-click into the log window - which is the most intuitive way in my opinion)

**Comment by hbitteur** [comment]
> (or right-click into the log window - which is the most intuitive way in my opinion)

Very good idea, thanks!

**Comment by hbitteur** [comment]
> What about the first query of my list: breaking the transcription process? Actually the only way to stop it is to shut down the program.

OK, I'll investigate a more user-friendly alternative.

**Comment by hbitteur** [comment]
All features are OK now, I'll close this issue
