### ISSUE TITLE
beam with interleaved rests disturbs rhythm check

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#236]
[Willy the Weeper.zip](https://github.com/Audiveris/audiveris/files/2782110/Willy.the.Weeper.zip)

This score has beams with interleaved rests (measures 3 and 4). Rhythm check fails for these measures.
Solution actually is to replace the beam with flags...

**Comment by Bacchushlg** [comment]
can be solved by removing the beam and set flags instead. Therefore: flag as enhancement.

**Comment by hbitteur** [comment]
OMR engine coming version will be more robust about rests interleaved within beamed chords.
And if needed, the end-user will be able to manually "force" the inclusion of rest into the beam chords sequence.
So, you shouldn't have to replace beams by flags any more.

**Comment by hbitteur** [comment]
This was fixed long ago, see release 5.2.5
Closing the issue
