### ISSUE TITLE
Articulation Sforzato is often detected as dim gabel

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#237]
the score in #236 shows another problem:
the Sforzato articulations are often detected as dim gabel.
Idea for separation: give a minimum length for gabels (e.g. 1/4 of a measure width). Shorter gabels are the interpreted as articulation.

**Comment by hbitteur** [comment]
Fixed by commit 5fe8c12886488bd1eda82ea3fb2ae0e454a36360
Closing the issue
