### ISSUE TITLE
wrong numeration for voltas 

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#239]
voltas are almost each time wrongly numerated: the volta counter is always set to "99"
see e.g. #238 as example.

**Comment by hbitteur** [comment]
The specific 99 value is used to indicate "unknown" when the ending number could not be retrieved.
Then the user will have to edit the number manually via some external music editor.

It's just a trick to generate a valid MusicXML file, while calling the user attention on some missing value for the ending sign.

**Comment by Bacchushlg** [comment]
Although I generally support the idea, better to set completely unvalid values than wrong ones, I suggest to set guessed values in these cases.
I most cases, there are 2 voltas following in 2 or 3 measures. At least in such a case, volta 1 and 2 could be properly assigned with their guessed values.

**Comment by hbitteur** [comment]
With Audiveris 5.3, voltas now get default numbers (1, 2) when not recognized, instead of the old "99" placeholder.
Closing the issue.
