### ISSUE TITLE
Audiveris DTD - change to local DTD

### ISSUE THREAD

**Issue by chrismeo** [Audiveris/audiveris#244]
Hi there,
audiveris adds the dtd source to the musicxml files, but to pass the files to other programms, you need to work with a localcopy of the DTD.
Is there a way to change that?
If I change the files manually, it works fine.I replaced the url of the dtd in the DOCTYPE line, by a local path on my pc.

But, when I start changing the DOCTYPE line with the java parser, I can't get rid of the errors.
I want to do something like this:

       DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();		
        try
        {
        	DocumentBuilder db = dbf.newDocumentBuilder();
  	
        	db.setEntityResolver(new EntityResolver()
        	{
				@Override
				public InputSource resolveEntity(String arg0, String arg1) throws SAXException, IOException
				{ 
					InputStream is = getClass().getResourceAsStream("file:///C:/Users/name/Desktop/musicxml-3.1/schema/partwise.dtd");
					
					return new InputSource(is);
				}
        		
        	});

			Document doc= db.parse(inputFile);

I get a NullpointerException, the parser can't find the dtd file. Do you happen to have any solution for that? Thanks so much in advance!

**Comment by maximumspatium** [comment]
First of all, Audiveris generates MusicXML 3.0 files. V3.1 isn't supported yet. You'd need to pass over the right schema for a start. Then there is a couple of name collisions in MusicXML 3.0 that need some special handling. I don't remember all the details but Hervé could provide some explanation.

This stuff is pretty low-level and has been already solved. The whole story thus boils down to the question: why bother playing with that ol' DTD schema at all?

FYI, Audiveris uses [Proxymusic library](https://github.com/Audiveris/proxymusic) for marshaling/marshalling of MusicXML files. Proxymusic handles all required low-level parsing and validation using XSD schema automatically. You don't ever need to get your hands dirty. Just include it in your Java project and you'll be able to access all musical information using convenient Java classes...

**Comment by chrismeo** [comment]
Thanks  a lot. I will try and do that.
