### ISSUE TITLE
transcription stops in step "symbols" with unclear reason

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#245]
[Lila_Tilla.zip](https://github.com/Audiveris/audiveris/files/2812316/Lila_Tilla.zip)

This score seems to be of good quality - but transcription stops at step symbols

I exported the original PDF to Tiff (300 dpi) - this works !?!

**Comment by maximumspatium** [comment]
In my machine, it's the TEXTS step that causes troubles. It takes too much time and will be aborted by the internal timer. It looks like there is a deadlock somewhere in the Tesseract engine. I fails even after increasing the timeout to 180 secs.

After restarting the TEXTS step the recognition finally succeeded. There are some textual errors but the overall result is good.

Another problem with this score is that the refrain has been printed on indented staves. That causes Audiveris to think that there are actually two independent movements on the same page and will produce two separate files during MusicXML export.

Here we hit the case where the assumption "indented staves -> new movement" doesn't hold...

**Comment by Bacchushlg** [comment]
interesting...
I re-transcribed the score - with the same result that you got.

And then I re-worked in the same way that I had done before: after transcription had stopped, I had re-assigned the lyrics manually (lasso around the 4 lines, delete inters, assign as lyrics).
After this I tried to continue transcription - and again got the problem at step "symbols".

**Comment by maximumspatium** [comment]
> After this I tried to continue transcription - and again got the problem at step "symbols".

Does the console display any error?

**Comment by Bacchushlg** [comment]
I just tried this score with the actual version (commit 9b5cb49):
Here the assignment of the verses 3 and 4 is not perfect.
Maybe just a fine-tuning?

**Comment by hbitteur** [comment]
Yep!
The heuristic I use to assign an inter (here a word for example) between two systems is the vertical distance to system. This is the reason why some verses go to the upper one and the the others to the lower one.

I need to find out something smarter.
Perhaps an incremental approach, not measuring the vertical distance to system, but to the closest item (such as lyrics line) that has already be assigned to the system.

**Comment by hbitteur** [comment]
A side remark: The good news is that TEXTS step now takes just 8 seconds on this score, with the recent fix.

**Comment by hbitteur** [comment]
Fixed today with commit d52e4385e4cccbd30bdb8d62d557a29900a76ad2 in development branch.
The modifications are compatible with the other case #343 but let's keep an eye on this because the heuristics used may need some additional tuning.

Don't hesitate to signal wrong behaviors.

**Comment by Bacchushlg** [comment]
Fixed with commit d52e438
