### ISSUE TITLE
some forms of flags are badly recognized

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#246]
There are a couple of scores where the form of flags is a bit different from what is in the trained patterns.
Maybe it is helpful to add some of these patterns to improve recognition.

Examples:
[THE BLUE MOON.zip](https://github.com/Audiveris/audiveris/files/2818200/THE.BLUE.MOON.zip)
[Opus One.zip](https://github.com/Audiveris/audiveris/files/2818205/Opus.One.zip)

**Comment by Bacchushlg** [comment]
I tried these scores with the new classifiers (commit f2b6506).
Unfortunately the first one does not profit from it.
The second one does, but during transcription I get an error:

[Opus One] Scores built: 1
[Opus One#1] Error in performing [RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException

**Comment by hbitteur** [comment]
In 'Opus One' flags are correctly recognized.

in 'THE BLUE MOON', flags have been assigned manually and the global repository augmented by the samples from that score.
All flags are now correctly recognized.

Closing the issue.
