### ISSUE TITLE
User Interface classes in the project

### ISSUE THREAD

**Issue by rdbergen** [Audiveris/audiveris#247]
Hello,
I am trying to add something to the user interface. In which classes should I search?
Thanks

**Comment by rdbergen** [comment]
Thanks so much. I will start working straight away.

Another thing I haven’t quite figured out: 
I read that there is away to assign my ausiveris git Folder as a development branch.
Does it mean, I can work on it, push it and it still doesn’t interrupt anyone’s work? 

Thanks again, Ruwen Bergen

Von: Hervé Bitteur
Gesendet: Dienstag, 5. Februar 2019 15:26
An: Audiveris/audiveris
Cc: rdbergen; Mention
Betreff: Re: [Audiveris/audiveris] User Interface classes in the project(#247)

@rdbergen
Pull-down menus are governed by:
• res/system-actions.xml file for all users
• <your-audiveris-folder>/config/user-actions.xml file for user-supplied features. By default, this file does not exist.
If you want to add user items only for you, use the latter, otherwise use the former.
Syntax is rather simple, it allows the unmarshalling of instances of ActionDescriptor class (see explanations in this class).
Among other things, an ActionDescriptor refers to a class name and a method name. The class name is often BookActions or GuiActions or ViewParameters. It's there that you can host your action code, although this is not mandatory.
And the related properties (menu item text, tool tip, icon, accelerator) are in the sibling resources/class.properties file (for example ./resources/BookActions.properties)
For popup menus, things are more hard-coded right now. See SheetPopupMenu class and derived EditorMenu class.
Don't hesitate to ask, should you need additional information.

**Comment by hbitteur** [comment]
At Audiveris, we try to follow a git workflow as described in this [wiki section](https://github.com/Audiveris/audiveris/wiki/Git-Workflow).

Basically, nobody ever works directly on the master branch.

In your case, you should work on a dedicated feature branch created off of the development branch for your specific feature. When you are done with the feature, you merge your specific branch into development.

This is typically what is explained in the [feature example](https://github.com/Audiveris/audiveris/wiki/Git-Workflow#feature).
