### ISSUE TITLE
What are RunTables?

### ISSUE THREAD

**Issue by rdbergen** [Audiveris/audiveris#248]
Hi,
I have a question concerning `RunTables`.
Does a `RunTable `contain a binary information for every pixel?
As in `sheet.Picture`: the `BINARY `table contains flags for white/black or foreground/background and the `HEAD_SPOTS` table has flags for "yes, here is a head"/"nothing to see".
I know that they are run length encoded. But for the general application I only have this guess.
Thanks, Ruwen Bergen

**Comment by hbitteur** [comment]
A RunTable is a table of runs, encoded in RLE, an efficient way to record a binary image.
But it just records the pixel value (foreground or background), nothing more.

Within Audiveris, it is used for example to record the binarized image which is the source for many subsequent processings.

It is used also to record the head spots, conveyed from the BEAMS step to the HEADS step. The purpose is to use a side effect of the detection of black spots made during the BEAMS step, to record those spots that are likely to contain black noteheads.

Also a separate RunTable instance is used for each and every glyph registered.

And perhaps others uses as well.

**Comment by maximumspatium** [comment]
RLE stands for [run-length encoding](https://en.wikipedia.org/wiki/Run-length_encoding).
