### ISSUE TITLE
Batch export to mxl

### ISSUE THREAD

**Issue by larrabee** [Audiveris/audiveris#250]
Hello.
I'm a developer from Musescore editor team.
We are use [Audiveris-eg](https://github.com/Audiveris/audiveris-eg.git) for PDF recognition. We want to upgrade to the new version of Audiveris, but the new version does not have a convenient option for batch export.
It can export with these options:
```
Audiveris -batch -export -option org.audiveris.omr.sheet.BookManager.useOpus=true -output /tmp/score22131323213-output /tmp/score22131323213.pdf
```
but this is not convenient, because the name of the output file (`/tmp/score22131323213-output/score22131323213/score22131323213.mxl`) based on the name of output dir and the name of score.
It will be great if you add the option to export only one file (mxl). 
Something like that:
```
Audiveris -batch -export -option org.audiveris.omr.sheet.BookManager.useOpus=true -output-mxl /tmp/score22131323213-output.mxl /tmp/score22131323213.pdf
```
to export only mxl to the specified mxl file.
Can you add this feature?
Thank you.

**Comment by hbitteur** [comment]
@larrabee 
I'm glad to read that MuseScore has finally decided to upgrade its PDF import! :-) :-)

First point: are you sure you want to use the Opus option? Does MuseScore support it?

Second point: Perhaps you did not clearly understand how Audiveris outputs are handled. I'll try to explain.

By default, all outputs of book "Foo" are written in a dedicated "Foo" folder, and the -output option simply defines the base folder for all output bookfolders.
This gives base/Foo/Foo.mxl (assuming that "base" is the defined output base)

Now, if you don't want to use a separate folder for each book, simply use `-option org.audiveris.omr.sheet.BookManager.useSeparateBookFolders=false` 
This will give base/Foo.mxl (still assuming that "base" is defined as your desired output base)

**Comment by larrabee** [comment]
Hello again;)
1. Yep, you are right. MS does not support opus format.
2. We have a problem with some files. Audiveris generate multiple files for one score. 
[example file](https://drive.google.com/file/d/1w8ywru5XQbUmcH8CrmmOZGZ98cMzFgtD/view?usp=sharing). This file contains 1 score on 26 pages. After convert it with command 
`Audiveris -batch -export -output /tmp -option org.audiveris.omr.sheet.BookManager.useSeparateBookFolders=false /tmp/score.pdf`
we got 11 mxl files:
```
ls /tmp/score*.mxl
/tmp/score.mvt10.mxl
/tmp/score.mvt11.mxl
/tmp/score.mvt1.mxl
/tmp/score.mvt2.mxl
/tmp/score.mvt3.mxl
/tmp/score.mvt4.mxl
/tmp/score.mvt5.mxl
/tmp/score.mvt6.mxl
/tmp/score.mvt7.mxl
/tmp/score.mvt8.mxl
/tmp/score.mvt9.mxl
```
 But we cannot convert multiple mxl files into one mscz.
Why does audiveris create 11 files instead of one? How can we fix this?

**Comment by maximumspatium** [comment]
> Why does audiveris create 11 files instead of one?

Audiveris somewhat recognizes that your score contains multiply movements. This is often the case when one or more systems are indented.

Did you try to process your example off-line in the UI mode? I suppose the result will be poor because your example contains a lot of stuff Audiveris currently doesn't recognize:
* Drum notation, see #33
* Guitar tablature
* Chord symbols, see #243

> How can we fix this?

Add a CLI argument to suppress exporting separate movements maybe? For the problematic scores as your example I don't see any short-term fix...

**Comment by larrabee** [comment]
> Add a CLI argument to suppress exporting separate movements maybe?
Yep, it will be cool ;)

**Comment by hbitteur** [comment]
Book indents are governed by the 'indentations' processing switch.
So it's up too the user to enable or disable this switch.

Closing this issue
