### ISSUE TITLE
Installing Audiveris on Nvidia Jetson TX2

### ISSUE THREAD

**Issue by kyle-redyeti** [Audiveris/audiveris#251]
I am having issues getting Audiveris to install on the Nvidia development board. It is a bit of an odd mix of hardware and software. It is Ubuntu 16.04 and it is arm64.  I have been able to install Tesseract 3.04.1 with leptonica-1.73 on the device but when I am trying to run the gradle script it wants to pull the jars from a repo and I see the following errors...

[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not find tesseract-linux-null.jar (org.bytedeco.javacpp-presets:tesseract:3.04.01-1.3).

[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not find leptonica-linux-null.jar (org.bytedeco.javacpp-presets:leptonica:1.73-1.3).

my computer shows...
tesseract --version
tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.2
 
Is there a way to modify the gradle script to point to these local versions? 

Thanks!

Kyle

**Comment by hbitteur** [comment]
Gradle is trying to load archives with names ending by "-linux-null.jar"
And the "null" comes from targetOS variable which is used as a classifier token for the archives (binary code).

See these lines in build.gradle file, starting line 15:
`ext.targetOSName   = System.getProperty('os.name').toLowerCase()\
                     .startsWith('mac os x') ? 'macosx' :\
                     System.getProperty('os.name').split(' ')[0].toLowerCase()`

`ext.targetOSArch   = ["i386":"x86", "i486":"x86", "i586":"x86", "i686":"x86", "x86":"x86",
                      "amd64":"x86_64", "x86-64":"x86_64", "x86_64":"x86_64"]\
                     [System.getProperty('os.arch').toLowerCase()]`

`ext.targetOS       = "${project.ext.targetOSName}-${project.ext.targetOSArch}"`

Could you check the values you get in your environment for system properties "os.name" and "os.arch"

**Comment by hbitteur** [comment]
Mind the fact that, for tesseract and for leptonica which are native programs (not Java), we need both the java interface and the binary library (which depends on your OS name and architecture).
Hence the need for the precise classifier token to load the proper binary archive.

**Comment by kyle-redyeti** [comment]
Thanks! If I do have the jar files local for tesseract and leptonica can I point Gradle to those rater than out to https://jcenter.bintray.com/org/bytedeco/javacpp-presets/tesseract/3.04.01-1.3/

Also, thanks for the quick response!

Thanks Again!

Kyle

**Comment by maximumspatium** [comment]
> Gradle is trying to load archives with names ending by "-linux-null.jar"
And the "null" comes from targetOS variable which is used as a classifier token for the archives (binary code).

This is related to #199. You'll need to provide the appropriate mapping for the currently unsupported `arm64` arch.

Try to uncomment this line and place it before jcenter(): https://github.com/Audiveris/audiveris/blob/6780b1f91197292f49843d5d9ecc3856c7296b36/build.gradle#L70

I cannot say for sure if it will work though.

**Comment by maximumspatium** [comment]
@kyle-redyeti Any progress?

**Comment by magic-k** [comment]
I'm not the OP but i tried to build audiveris on an arm64 chromebook.
Unfortunately theres no arm64 version of tesseract 3.x java binding. arm64 is only supported since 4.x
For leptonica there's no linux-arm64 version at all, only android-arm64.
At least according to https://jcenter.bintray.com

**Comment by maximumspatium** [comment]
> Unfortunately theres no arm64 version of tesseract 3.x java binding. arm64 is only supported since 4.x

Yes, that's true.

> For leptonica there's no linux-arm64 version at all, only android-arm64.

That's also true but fixable. Only need to add the appropriate architecture and compile Javacpp-presets from source.
I cannot do that due to lack of the corresponding hardware...

Regarding Tesseract 4.x support, we have to stuck to the legacy OCR engine due to various issues with the state-of-the-art LSTM engine, see #273.
I'm going to try out to switch to the legacy engine from Tesseract 4.x using oem=0. If it works, we could proceed with Tesseract 4 integration (based on the legacy mode) and adding linux-arm64 support...

**Comment by magic-k** [comment]
FYI Leptonica linux-arm64 has been added and will be released soon.
See https://github.com/bytedeco/javacv/issues/1021#issuecomment-506559232

**Comment by maximumspatium** [comment]
> I'm going to try out to switch to the legacy engine from Tesseract 4.x using oem=0.

It works, see https://github.com/Audiveris/audiveris/issues/273#issuecomment-506765160
