### ISSUE TITLE
Opening a new image tab 

### ISSUE THREAD

**Issue by rdbergen** [Audiveris/audiveris#253]
My ultimate goal is to insert an image preprocessing step into the pipeline between the steps LOAD and BINARIZE.
So I am working my way to it step by step and I am trying to open a new tab, where the image would be shown.
I have tried creating this new tab in the following functions (without success):

- added a new step "IMAGE_CORRECTION" to the enum `step.Step`
- added sheet tab to `sheet.ui.SheetTab`
- added the class `step.ImageCorrectionStep`
- added a new function in `sheet.Sheet` similar to `createInitialView()`
- added a new function in `sheet.ui.BookActions` similar to `displayInitial()`

The new (empty) step "ImageCorrection" is visible in the drop down menu and also appears in the progress bar.
But I am not able to create a new tab.

Thanks for helping so quickly and thoroughly with all the previous questions and for this one in advance, 
Ruwen Bergen

**Comment by maximumspatium** [comment]
> The new (empty) step "ImageCorrection" is visible in the drop down menu and also appears in the progress bar. But I am not able to create a new tab.

Can you share your code? Without seeing what are you trying to do, it's difficult to go beyond guessing...

**Comment by rdbergen** [comment]
My current goal is only to open a new tab (next to the INITIAL,BINARY and DATA tabs) to display an image.

In `org.audiveris.omr.sheet.Sheet` : 
```
    /**
     * Create and display the image correction view.
     */
    public void createImgCorrView ()
    {
        locationService.subscribeStrongly(LocationEvent.class, picture);

        // Display sheet picture
        PictureView pictureView = new PictureView(this, SheetTab.IMG_CORR_TAB);
        stub.getAssembly().addViewTab(
                SheetTab.IMG_CORR_TAB,
                pictureView,
                new BoardsPane(new PixelBoard(this), new BinarizationBoard(this)));
    }
```
This is mostly copied from `createInitialView ()`.

The previous method is called by:
`org.audiveris.omr.sheet.ui.BookActions`
```
    /**
     * Action that allows to display the view on corrected image
     *
     * @param e the event that triggered this action
     */
    @Action(enabledProperty = STUB_AVAILABLE)
    public void displayImgCorr (ActionEvent e)
    {
        final SheetStub stub = StubsController.getCurrentStub();

        if (stub.isDone(Step.IMAGE_CORRECTION)) {
            final SheetAssembly assembly = stub.getAssembly();
            final SheetTab tab = SheetTab.IMG_CORR_TAB;

            if (assembly.getPane(tab.label) == null) {
                stub.getSheet().createImgCorrView();
            } else {
                assembly.selectViewTab(tab);
            }
        } else {
            logger.info("No corrected image available yet.");
        }
    }
```

This is mostly copied from `displayBinary(ActionEvent e)`.

Also, the tab name and description exists in `org.audiveris.omr.sheet.ui.SheetTab`:
`IMG_CORR_TAB("ImageCorrection")`

and the step in `org.audiveris.omr.step.Step`:
`IMAGE_CORRECTION("Correct the sheet picture", new ImageCorrectionStep())`.

The new class `ImageCorrectionStep` is added in `org.audiveris.omr.step`.
It has the necessary methods `doit()`, `getSheetTab()` and a constructor.

At first I left the `doit()` method empty. The step showed up in the list of steps when I ran audiveris. The image correction step also showed up on the progress bar.
Then I tried to see if it could actually do something and inverted the initial image. That also worked.
But I can not open or create a new tab to show a different image than the initial image.

**Comment by hbitteur** [comment]
Sorry for such a late answer, I'm too busy on other tasks right now.

I suppose your ImageCorrectionStep class derives from AbstractStep class, which defines displayUI() as void by default. So, if you want your tab to be automatically displayed at end of the new IMAGE_CORRECTION step, you have to define your own version of displayUI() in ImageCorrectionStep class (and explicitly call for view creation and tab display there).

Now, if you want to manually display your tab at some point in time, you can manually call your action displayImgCorr that you added to BookActions class. If I were you, I would use the debugger on this displayImgCorr  method and follow it step by step, to understand what is happening.

**Comment by rdbergen** [comment]
Thank you very much for the answer, I will try it out and see where I can go from there.

**Comment by hbitteur** [comment]
Closing this issue, for lack of activity
