### ISSUE TITLE
Audiveris stalls processing sheet

### ISSUE THREAD

**Issue by lellid** [Audiveris/audiveris#257]
Using Audiveris 5.1.0, with a certain sheet (see attachment), Audiveris reproducible stalls  with full CPU utilization. Trying different preprocessing steps for the image (with /w.o binarization, cropped / not cropped) did not help.

Attached you find the sheet that leads to stalling, and a screenshot of the stalled program.
![img002](https://user-images.githubusercontent.com/12336631/53694462-bf537680-3daf-11e9-8311-4ed8e38460cc.png)

![screenshotstalling](https://user-images.githubusercontent.com/12336631/53694465-cd08fc00-3daf-11e9-86d4-db3dc718ebbd.png)

**Comment by Bacchushlg** [comment]
The reason for your problem is the is the 19/16 time mark in the last system.
If you delete it in your source image, the recognition works fine.
The problem must be handled - of course, but so you can continue...

**Comment by hbitteur** [comment]
Problem no longer occurs with recent Audiveris (5.2.3)

Closing
