### ISSUE TITLE
MXL output is invalid

### ISSUE THREAD

**Issue by ddsteve** [Audiveris/audiveris#258]
Running Audiveris 5.1.0:6780b1f91 on MacOS 10.14.3 all goes well and the recognition result looks good. However, on exporting to MXL the file cannot be opened in Finale, Musescore or Sibelius because it is reported as invalid.

Finale gives the following information:

error in file ..... at line 35: cvc-complex-type.2.4.b:The content of element 'part-list' is not complete. One of '{part-group, score-part}' is expected.

then:

XML error in file /Users/stevehunt/Desktop/loa/loa.xml at line 36:
cvc-complex-type.2.4.b: The content of element 'score-partwise' is not complete. One of '{part}' is expected.

then:

Invalid MusicXML file: score-parts and parts do not match

The zipped  XML is attached.

[loa.mxl.zip](https://github.com/Audiveris/audiveris/files/2927559/loa.mxl.zip)

**Comment by Bacchushlg** [comment]
Your file does not contain any "real" score information.
Please save the omr file and upload it here, so I can investigate whats going wrong.

**Comment by ddsteve** [comment]
Many thanks for your response. Unfortunately I can no longer load a pdf into Audiveris, because it appears to have lost freetype - which I understand to be built-in to MacOS. I have even tried a completely new installation, but with the same result. I am now at a loss to know how to proceed!

**Comment by Bacchushlg** [comment]
just export the file as image (I don't know which tools are available for this on a Mac...). Under Windows most PDF-viewers allow to export a file e.g. as jpg or tif. Both can be used as source for Audiveris.

**Comment by ddsteve** [comment]
Further to my last, I have now managed to persuade Audiveris to correctly read a pdf, and to produce a visually satisfactory transcription from it - apparently the pdf I had chosen before was not in an acceptable format. I have deliberately chosen a simple single page, single staff file. However, when I examine the output folder (which is in the standard location) there is no .omr file, just the .xml - and the .xml is always 1kb in size and obviously is not valid. I am aware that there is a problem with Tesseract, which does not appear to be able to locate its language files - but I am not concerned about reading the text content, and the music looks to be very accurately read. I attach a log file from my latest attempt in the hope that this may help.
[20190306T073220.log](https://github.com/Audiveris/audiveris/files/2935016/20190306T073220.log)

**Comment by ddsteve** [comment]
I think this is now fixed - I have revisited the Tesseract installation and at least a little of the text is now being interpreted, and I receive a meaningful .mxl file - my apologies for failing to appreciate that correct operation of Tesseract was essential to receiving a good result for the music!

Thanks for your interest, and for an excellent program!
