### ISSUE TITLE
Problems recognizing brace if staves are too far away

### ISSUE THREAD

**Issue by lellid** [Audiveris/audiveris#259]
The recognition fails reproducible if the staves (piano) are too far away from each other, causing the brace to be longer than usual. This can be seen in the following example: the first two pairs (57 and 59) are farther separated as the other three, and for them the recognition fails.

![image06cropped](https://user-images.githubusercontent.com/12336631/53841394-f76bdc80-3f9c-11e9-9903-ac73b70b323a.jpg)

![screenshot](https://user-images.githubusercontent.com/12336631/53841409-fc309080-3f9c-11e9-88df-71417b868fdb.png)

**Comment by Bacchushlg** [comment]
[Ain't Missbehavin'.zip](https://github.com/Audiveris/audiveris/files/3047966/Ain.t.Missbehavin.zip)

Similar for this score. When exporting it, the score gets 8 note lines!

**Comment by hbitteur** [comment]
Fixed in commit ef9f627d6e208f84267a11433ffe067401099c10 on development branch

Closing.
