### ISSUE TITLE
No part for AugmentationDotInter

### ISSUE THREAD

**Issue by cbenvenuti** [Audiveris/audiveris#26]
Dear all,

I have encountered an issue when transcribing certain sheets. The error goes as follows:

Error in RHYTHMS java.util.concurrent.ExecutionException: java.lang.illegalException: No part for AugmentationDotInter{#12202(0.760/0.760)}
Cause java.lang.IllegalStateException: No part for AugmentationDotInter{#12202(0.760/0.760)}
StepException detected in [RHYTHMS]
Cannot paint system#1

The error happens with specific pages of a score which are not different in symbolic vocabulary from the others, as far as I can tell. I'm running Audiveris (vanilla language pack) on a Mac with OSX High Sierra and JDK 8 (JKD 9 didn't seem to work). 

I would greatly appreciate any help on the issue. I am even willing to bypass transcription of rhythm, as I need only the notes to be encoded (by the way, is there a way to bypass a transcription step?).

Kind regards,
Christian

**Comment by maximumspatium** [comment]
Hello Christian,

sorry for the delayed response! We are very busy for the moment being.

In order to clarify the reason for this exception, I'll need to debug your concrete case. Can you grant me an access to the PDF in question somehow (via googledrive, wetransfer whatsoever)?
My email address is maximumspatium at googlemail.com

**Comment by hbitteur** [comment]
Maxim, did you get any concrete  case?
If not, I'd suggest to close the issue.

**Comment by maximumspatium** [comment]
I didn't get any concrete info. Let's close it for now.

**Comment by pods** [comment]
I had the same error text with different numbers. I was missing Tesseract OCR.
