### ISSUE TITLE
Rhythm check has problems with beams over measures

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#260]
[After Midnight.zip](https://github.com/Audiveris/audiveris/files/2949407/After.Midnight.zip)

This score has a curious notation: it uses beams over measures. I replaced them with flags, but unfortunately this does not help (or only partly: one of the measures keeps un-interpreted).
Finally I found a solution: delete and re-insert the bar lines - after this all measures are fine.

As this is a very unusual way of notation, it just a nice-to-have to have this solved.

**Comment by hbitteur** [comment]
NO!
A beam shoud stay in its measure.

You can manually split the beam, if you wish.

**Comment by hbitteur** [comment]
Implemented via commit fc4e8c7ad07c81da0ef489feb5966bce870bae68
