### ISSUE TITLE
support detection of cross note heads

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#262]
There are a couple of scores that use cross note heads. In vocal scores it is typically used for "ts" of "dm" sounds, and it is also used for rhythm sound tracks.
Would be a nice feature if Audiveris could support them.

One example:

![Hit the Road Jack 1](https://user-images.githubusercontent.com/33522630/54342717-8338d500-463d-11e9-8f61-4fb3e6cda01e.jpg)

**Comment by Bacchushlg** [comment]
![I don't know-07](https://user-images.githubusercontent.com/33522630/66639609-73a35e00-ec17-11e9-831e-1e3b00bb3e53.jpg)

I'd like to remind this query. Actually I have another example of a score with cross note heads. As long as these crosses are not detected, it is almost impossible to transcribe a score like this - and the only reason is the missing detection of the cross note heads.

**Comment by hbitteur** [comment]
@Bacchushlg 
Yes, I have not forgotten this request at all :-)

In current Audiveris, this would mean to extend template matching technique to recognize this new type of "note head".
But we have so many problems with template matching that I don't want to invest more on it. It would be like beating a dead horse.

The right decision is I think to discard template matching totally and replace it with the coming patch classifier.
The patch classifier itself needs to be improved in its training part. Something that Maxim is actively working on, together with our folks from ZHAW university.

As soon as the patch classifier gets up and running, I'll rush to the removal of template matching. And the support of cross note heads all together.

**Comment by Bacchushlg** [comment]
if not supported by the transcription... is it possible to provide the cross head as item that can be added manually? Now with the handy new feature to add items manually, it would be helpful if at least this would be possible.
Of course this correction can be done in the further step (e.g. MuseScore), but there is a good reason to provide it already in Audiveris: the rhythm analysis fails and also the output of the note's positions inside the measures is not correct, if the cross head notes are not part of the output

**Comment by hbitteur** [comment]
@Bacchushlg 
Yes, some manual support seems doable without recognition by the OMR engine.
Let me investigate the impact on current data model.
Then adding the ability to enter them manually should be rather easy.

**Comment by hbitteur** [comment]
First version is available as commit 3287aaad63ca735b44a89b1582c86095b1ce3676 in the branch named "cross-heads".

**Comment by hbitteur** [comment]
Here is the result, after some manual actions, for your score 'Hit The Road':

![image](https://user-images.githubusercontent.com/22053634/70519785-caa4b100-1b3c-11ea-969f-7b1df45962ad.png)

**Comment by Bacchushlg** [comment]
It's perfect. It makes a lot less re-editing work in MuseScore now.
Can be closed
