### ISSUE TITLE
call function that is running after adding a slur

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#263]
[Without You.zip](https://github.com/Audiveris/audiveris/files/2978966/Without.You.zip)

sometimes many measures of a score keep in rose although the initial errors were solved. Also "reprocess rhythm" doesn't help.
But: after adding or correcting a slur, the measure get white (ok).
It seems that after adding a slur, a certain function goes over the score page and recalculates better than "reprocess rhythm". Would be fine to have this function called on "reprocess rhythm".
In this case, the complete 1st page stays in rose...

**Comment by hbitteur** [comment]
@Bacchushlg 
I need more information: which sheet, which measure, which slur being modified.
Otherwise I can't see where the problem is in this 4-sheet input file.

**Comment by Bacchushlg** [comment]
It seems that the problem is no more present in the current version.
So lets close the issue
