### ISSUE TITLE
perform initial systems analysis for multi-page scores

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#264]
In case of multi page scores it can be interesting to perform an initial systems analysis before doing the complete transcription.
If the system analysis fails for one or two pages, it is interesting either to correct manually (which is not possible in the moment) or to edit the source image (e.g. by adding system lines that may be not correctly recognized or even by adding braces - which I do sometimes in case of bad scans).
The function should be available similar to the complete transcription from the menu bar - maybe something like "score analysis"

**Comment by hbitteur** [comment]
I'm linking this to the "Staff edition" feature, to provide user means to fix / complete / modify poor staff lines

**Comment by hbitteur** [comment]
Staff edition is now available, thanks to commit 04e6b39d1caa93f5e5e723add4a67bdd7e9f5b83 pushed to development branch
