### ISSUE TITLE
miss-interpreting flag + accidentials as whole notes

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#266]
[Blue Petals.zip](https://github.com/Audiveris/audiveris/files/3025284/Blue.Petals.zip)

This scan of rather good quality is full of errors in transcription, mainly for 2 reasons: problem to detect flags (due to the very wide opening form) and detection of whole notes instead of flag + accidentials.

**Comment by hbitteur** [comment]
I made an experiment with your book  example:
1. I manually assigned the unrecognized symbols (mainly the flags)
2. Exported the book samples
3. Pushed these samples to the global sample repository
4. Made incremental training of the classifier

Also, for a more strict recognition of whole notes, I lowered the constant "wholeBoost" from 0.38 to 0.25 (this constant is meant to boost recognition of whole heads).

And the raw output (reset to binary, transcribe, no manual correction at all) is available here:
[Blue.Petals-new.zip](https://github.com/Audiveris/audiveris/files/3537416/Blue.Petals-new.zip)

You can see by yourself that most errors are gone. There are a few remaining errors, not related to flags or whole heads, they can easily be fixed manually.

**Comment by Bacchushlg** [comment]
did you include these samples to the common library?
I tried to re-transcribe the score and get the same problem with the actual version...

**Comment by hbitteur** [comment]
No, I did not push this yet, because it was just a local experiment.
I will push the newly trained classifier

**Comment by hbitteur** [comment]
Done today with commit f2b650694657ec79ec6fd2512b87111511ee3f15
Closing this issue

**Comment by Bacchushlg** [comment]
Did you achieve to get the last system of page 2 transcribed?
I get errors due to the void note heads in the upper note line. They are not recognised as being on the same tick as the void head on the bottom system - leading to a wrong rhythmic interpretation.
