### ISSUE TITLE
Audiveris not opening

### ISSUE THREAD

**Issue by leonhudak** [Audiveris/audiveris#270]
Trying to open Audiveris, cmd pops up for a second and dissapears after this error message:
![vlc_2019-04-04_22-44-28](https://user-images.githubusercontent.com/33522493/55587257-35d6f180-572b-11e9-9c14-3dc43b232652.png)

I have the correct Java jdk and jre versions, have set the path etc etc. What could be causing this?

**Comment by hbitteur** [comment]
@leonhudak 
I can't read which java version you are really using. 
Please use command: java -version
Or, from within Audiveris, use menu "Help | About" to get Java vendor and Java version.
I suspect you are using a java version > 8 (which would explain that JAXB stuff is not included by default).
Current Audiveris requires 7 or 8.

**Comment by leonhudak** [comment]
heres my java -version output: 
java version "12" 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)

**Comment by hbitteur** [comment]
Yes, you should.
We plan to switch to 12 ASAP but for the time being you must use 8 (or 7)

**Comment by maximumspatium** [comment]
> We plan to switch to 12 ASAP but for the time being you must use 8 (or 7)

Side note: Java 7 won't work. 8 is the only choice.

**Comment by hbitteur** [comment]
Please tell us if you can now open Audiveris, so that we can close this issue

**Comment by leonhudak** [comment]
I'm sorry, I haven't had time to test it. I will do it tomorrow or today.

**Comment by hbitteur** [comment]
OK thanks, there is no need to hurry

**Comment by maximumspatium** [comment]
Closed after three weeks of inactivity.
