### ISSUE TITLE
Single line staves not recognized

### ISSUE THREAD

**Issue by et3ch8** [Audiveris/audiveris#274]
I'd like to convert a percussion score written in single line staves. Audiveris returns this message: "This sheet does not seem to contain staff lines". Shouldn't Audiveris be able to recognize this particular type of scores?

**Comment by maximumspatium** [comment]
> Shouldn't Audiveris be able to recognize this particular type of scores?

Audiveris currently doesn't support percussion notation. It has been requested long time ago (see #33) but we don't have sufficient development resources for that. Sorry!

**Comment by et3ch8** [comment]
I understand your means are limited, but I'm not talking about drumset notations with crosses and other bizarre noteheads - just basic notes, on a single line instead of a five-line staff. This kind of notation happens to feature in many symphonic conductor scores... Hope you'll have time to have a look on it some day.

**Comment by hbitteur** [comment]
As of Audiveris 5.2.3, 1-line percussion staves are supported via a specific processign switch.
Closing....
