### ISSUE TITLE
New interactive chords features

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/audiveris#286]
Beside submenus like "Inters" and "Glyphs" already available in contextual popup menu, perhaps we could add a "Chords" submenu, to provide the following features (according to the selected chords within a measure):

- **Split**. Enabled if only one chord is selected, this would cut the selected chord:
![image](https://user-images.githubusercontent.com/22053634/58369275-6b60b580-7ef8-11e9-9add-22ffe4122031.png)
 Resulting into 2 separate "half" chords, one above the other, like:
![image](https://user-images.githubusercontent.com/22053634/58369309-d3170080-7ef8-11e9-875d-a63bd653ddd9.png)

- **Merge**. Enabled only if more than 1 chord is selected, this would create a single chord, composed from the selected chords.
In the case of two stemmed chords, this would be the opposite action of Split.
In the case of several whole heads (for which there is no way for the engine to detect a commond chord) this would create a single chord.
![image](https://user-images.githubusercontent.com/22053634/58369291-96e3a000-7ef8-11e9-8d80-cee4bb1dfb7c.png)

- **Join in Voice**. Force the selected chords to belong to the same voice (and have different time offset values)

- **Join in Time**. Force the selected chords to share the same time offset value (and belong to separate voices).

As usual, these user interactive actions should be "cancellable" and "redoable" at will.

**Comment by Bacchushlg** [comment]
oh, what a nice featere idea! Yes, this will be helpful in a couple of messy situations. Up to now, I often delete and replace note heads (a bit more left, a bit more rigth) in order to convince Audiveris that chords belong to the same time stamp...

**Comment by hbitteur** [comment]
This feature is now available with commit beef43fdc8ded358433965295b2d9f0a8ddc489a  in development branch.
See the quick description published on issue #279

Don't hesitate to ask if something is not clear. Documentation is still to be written...
