### ISSUE TITLE
running "headless" for API?

### ISSUE THREAD

**Issue by mutablestudio** [Audiveris/audiveris#288]
Hello - I have no experience with Audiveris so would like to ask if anyone has ever used it cmd line or via an API interface? I saw some mention of the Java API in the setup docs or wiki but I wanted to ask here.

If this is documented could someone provide the link? 

TIA.

**Comment by hbitteur** [comment]
To run headless, simply use the "-batch" option on the command line.
See [handbook cli section](https://bacchushlg.gitbooks.io/audiveris-5-1/content/advanced/cli.html).

**Comment by maximumspatium** [comment]
Assuming the issue could be solved...
