### ISSUE TITLE
Call audiveris from python script

### ISSUE THREAD

**Issue by misterpilou** [Audiveris/audiveris#289]
I made a very basic script with python with 

`subprocess.run(["Audiveris", "-batch", "-export", f"./scores_data/{directory}/{sub}/{f}"])`

because my pdf was on differents folders, but resulting in a Failed loading language 'langcode'.

I would like to know how to get it through, PREFIX_TESSDATA is set and i got all traineddata within. One option would be to disable TEXT step.

Errors are:

Failed loading language 'deu'
Failed loading language 'eng'
Failed loading language 'fra'
Tesseract couldn't load any languages!

**Comment by maximumspatium** [comment]
> I would like to know how to get it through, PREFIX_TESSDATA is set and i got all traineddata within.

Add the following code to your script and run it:

`print ('Tesseract data is set to %s' % os.environ['PREFIX_TESSDATA'])`

What do you see?

It would be helpful to know what OS you're running on and which version of Tesseract is installed by default. To obtain the latter, run the following command in your terminal:

`tesseract --version`

> One option would be to disable TEXT step.

This is really undesirable because Audiveris will try to map every text letter to a musical symbol resulting in a complete mess...

**Comment by misterpilou** [comment]
Thanks for your repley and sorry for not telling all the infos:
Tesseract version: 4.0.0
Audiveris version: 5.1.1 (both are up to date)
I set in my python code the:
`os.environ["TESSDATA_PREFIX"] = "/usr/share/tesseract-ocr/4.00/tessadata/"`

**Comment by maximumspatium** [comment]
Tesseract 4.0 isn't supported yet, [this comment](https://github.com/Audiveris/audiveris/issues/273#issuecomment-495913308) explains why.

Audiveris requires tesseract 3.x and the appropriate language files. Your TESSDATA_PREFIX points to 4.x language files which are incompatible with Tesseract 3.x.

Please downgrade Tesseract to 3.x including its language files and everything should work as expected.

Please be careful while setting TESSDATA_PREFIX - it should be set to the **parent directory** of your "tessdata" directory.

**Comment by misterpilou** [comment]
Thank @maximumspatium for the help, to anyone with the same issue:
In ubuntu 18.04 i followed this to install [tesseract](https://www.lucacerone.net/2017/installing-tesseract-3-0-5-on-ubuntu-16-04/) 3.05, i move the tessdata from the link to /usr/share/tesseract-ocr/3.05/tessdata and pointed it in my TESSDATA_PREFIX. As the link said either the parent or tessdata directory work, for me it was the tessdata. I close it, thanks again =)
