### ISSUE TITLE
offset in lower staffs of multi-staff scores

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#29]
I use Audiveris through the import function of MuseScore.
Several times I had now the same problem: from a certain point in the score the lower measures (all but the first one) are no more synchronuous - the first note(s) of the following measure are appended to the actual one, and this repeats for the following measures.
In the appended file this happens in measure 7.

[Dona dona.pdf](https://github.com/Audiveris/audiveris/files/1458210/Dona.dona.pdf)

[Dona_dona (1).zip](https://github.com/Audiveris/audiveris/files/1458213/Dona_dona.1.zip)

**Comment by maximumspatium** [comment]
Sorry for the delayed answer!

Yes, the aforementioned problem occurs when the processed score contains rhythmical errors. For example, the 2nd note in the 2nd voice in the 7th measure has been wrongly recognized as a quarter note, hence the unwanted shift.

We're currently working on improving Audiveris, especially its MusicXML export, so the situation will be significantly improved.

BTW, I was able to obtain an almost error-free music recognition for your PDF by solely adjusting the binarization parameters. Try to set the following parameters in _Book/Score Parameters..._ menu as follows:
```
binarization type: ADAPTIVE
mean: 0.9
standard deviation: 0.6
```
Then reload the score from PDF. Let me know how it goes...

**Comment by Bacchushlg** [comment]
I use Audiveris through the import function of MuseScore. I don't see any possibility to provide any settings during this import function. 
I already tried to "install" Audiveris on my computer - I don't get it. The "how-to" does not really help me.
But anyway I'm very happy that you are working on the remaining problem. In general Audiveris is a really great tool.

**Comment by maximumspatium** [comment]
> I use Audiveris through the import function of MuseScore.

IIRC, Musescore import function still uses old [audiveris-eg](https://github.com/Audiveris/audiveris-eg) v4.3. I would strongly recommend to try out the latest audiveris because its recognition has been significantly improved since then.

Which of the installation instructions didn't work for you?

**Comment by Bacchushlg** [comment]
I meanwhile achived to get Audiveris build and run except for one step: the tesseract step outputs errors:

Failed loading language 'fra'
Failed loading language 'eng'
read_params_file: parameter not found:

After this Audiveris shuts down with no additional errors.

I have tried several combinations: put the language file to a certain directory and set TESSDATA_PREFIX to this directory or create a directory "C:\Program Files (x86)\tesseract-ocr\tessdata" and put the language files there. I get the error in both cases.
