### ISSUE TITLE
Audiverus does not run on laptop - Crashes before starts

### ISSUE THREAD

**Issue by minneiah** [Audiveris/audiveris#290]
Just installed Audiveris_Setup-5.1.0-windows-x86 on Acer laptop running Windows 8.1.  A window flashes for a split second, looks like a batch window, then closes, and that is it.  Tried starting it numerous times.  Looks like and error message, but not sure since it flashes by so fast.  Checked task manager and found nothing running so for some reason it seems to be crashing before it gets started.  Any help would be greatly appreciated.

**Comment by hbitteur** [comment]
Sounds like you have some problem that prevents the launching of Audiveris application. And you have no time to read any error message before the window closes.

Workaround: Explicitly open a terminal window, then launch Audiveris.bat from there.
Doing so, you'll be able to see these initial error messages

See #270 or #225

**Comment by maximumspatium** [comment]
Sounds like #225, that is you probably installed Java 32bit in a 64bit machine.

Please check first which CPU you're running on. Is it 64bit?

**Comment by minneiah** [comment]
Thanks for the help.  I did not have JAVA on my laptop.  It runs now, and I added a sheet of music to the program, but, I am not understanding how it creates a MIDI file of the score.  I can export to xml format, but I need midi files of the music.  Any help would be greatly appreciated!  I am not able to find a users manual of the program anywhere.  That would also greatly help.

**Comment by maximumspatium** [comment]
Closing the issue because the problem could be solved.
