### ISSUE TITLE
How to create a midi file

### ISSUE THREAD

**Issue by minneiah** [Audiveris/audiveris#292]
I need to be able to create a midi file of the music but there is not an export to midi option?  How to do this.  Thanks

**Comment by hbitteur** [comment]
There is no direct export from Audiveris OMR format to MIDI format.
But you can export from OMR to MusicXML, which  is a de facto standard for music exchange.

Then, you have plenty of music editors/sequencers that can create MIDI from MusicXML. MuseScore is one of them.

You can even directly connect such editors via Audiveris plugin mechanism. Please refer to handbook for more detailed explanation.
