### ISSUE TITLE
Getting Human readable mxl or xml

### ISSUE THREAD

**Issue by misterpilou** [Audiveris/audiveris#295]
Hi i wanted to know if i can have Human readable mxl or xml as the output i get from audiveris are (from what i see) binaries. I got some Stored /book.xml or sheet#1.xml output and don't know where to find those files

**Comment by Bacchushlg** [comment]
The files are normally stored in a subdirectory "Audiveris" of your documents folder (at least under Windows).
The files are not human readable, but they are intended to be imported into a notation program like MuseScore or others (every modern notation program can import such files)

**Comment by maximumspatium** [comment]
> Hi i wanted to know if i can have Human readable mxl or xml as the output i get from audiveris are (from what i see) binaries

Audiveris output can be one of the following:
* a book produced with "Save book as..." command stored in a file with ".omr" extension. Despite this extension, this is a plan ZIP archive. You can change ".omr" to ".zip", decompress it and browse its content easily. As you mentioned, book.xml and sheet#X.xml are standard XML files and can be read (and modified) by humans up to some limit.
* MusicXML files produced with "Export book/sheet" command (".mxl" extension). You can open them in a text editor, assuming you're familiar with the MusicXML format...

**Comment by misterpilou** [comment]
Super cool, thanks for the quick reply, i unzip my omr files, by applying -export=true on the cmd i wasn't able to see the mxl but anyway, it works for me. Closing it

**Comment by hbitteur** [comment]
@misterpilou 
FYI, a ".mxl" file is a **compressed** version of MusicXML, that almost any music edition software is able to import.
But if what you want is to indeed "see" its content, it's actually a ZIP file, so you can simply unzip it and read by yourself the contained .xml files it contains.

**Comment by misterpilou** [comment]
@hbitteur thanks so much, i didn't get that straight up. For further people, unzipping .omr give a list of sheets proceed by audiveris with a book.xml giving the underlying schemas and uncompressing the MusicXML (.mxl) file give you the whole book.

**Comment by misterpilou** [comment]
I think i need to introduce myself. I'm using audiveris for generated xml which i got mp3 attached to. My purpose is to do ML with it in order to generate score from mp3. I'm just started up. The project is for commercial purpose and i really hope having good results with the AI algorithm. One thing i want to add, i'm not open sourcing this project because i need some money but my ultimate goal is to make some geeky open source projects without worrying too much about money. So basically i'm creating a musescore-like app.
