### ISSUE TITLE
wrongly detected 3/4 instead of repeat bar stays in exported file

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#296]
[Gold Mine.zip](https://github.com/Audiveris/audiveris/files/3365372/Gold.Mine.zip)

in first line of page 2, a 3/4 was detected instead of a repeat bar. I deleted it an inserted a repeat manually, so everything appears to be fine. Same effect in page 6, 2nd system

tested with version: 5.1.0:ff26ab430

What makes the things even worse: when I import this file to MuseScore and delete the wrong 3/4, MuseScore breaks down (version 2.3 as well as 3.2) - ok, this is not a problem of Audiveris, but... what can I do?

**Comment by ebym** [comment]
@Bacchushlg, seems to be MuseScore problem. I have imported the mxl to lilypond and MuseScore 1.3, i don't see any 3/4 time signature, however the repeat marks on bar7 and 48 are missing on MuseScore 1.3. Once you cleanup the lilypond code, the repeat mark on bar 48 will be visible.

Audiveris:    5.1.1:2f64d06

lilypond direct pdf output and zip file contain Audiveris mxl export and MuseScore 1.3 file.
[goldmine.zip](https://github.com/Audiveris/audiveris/files/3373767/goldmine.zip)
[Gold Mine.pdf](https://github.com/Audiveris/audiveris/files/3373755/Gold.Mine.pdf)

can you share your mxl file to confirm ?.

**Comment by Bacchushlg** [comment]
I had finally solved the problem by deleting the TimeSig sections in the internal mscx file:

> <TimeSig>
>           <sigN>3</sigN>
>           <sigD>4</sigD>
>           <showCourtesySig>1</showCourtesySig>
> </TimeSig>
> 
But of course this only helps for this file - there must be a misbehaviour in the source code.

**Comment by ebym** [comment]
> I had finally solved the problem by deleting the TimeSig sections in the internal mscx file:
> 
> ```
> <TimeSig>
>           <sigN>3</sigN>
>           <sigD>4</sigD>
>           <showCourtesySig>1</showCourtesySig>
> </TimeSig>
> ```
> 
> But of course this only helps for this file - there must be a misbehaviour in the source code.

Is this MuseScore 2.x and 3.x file ?.

**Comment by Bacchushlg** [comment]
it was V2.3.

**Comment by ebym** [comment]
Were you able to find any error in the audiveris mxl or musescore file i have attached ?. 

If no time signature error on your audiveris mxl file, then we can confirm the issue is musescore import related.

**Comment by Bacchushlg** [comment]
I'm sure that there is a problem is inside Audiveris, because it had detected this 3/4 time signature. Also, as I told before, I have seen this section "TimeSig" in the exported file.
Of course the brake-down of MuseScore is another problem that should be fixed inside MuseScore - but this is another task

**Comment by hbitteur** [comment]
There were 2 bugs actually ...
- Deleted time signatures were still referred to by other parts of the data model, and ended up in the exported MusicXML data.
- A direct manual insertion of LEFT_REPEAT_SIGN or RIGHT_REPEAT_SIGN was not correctly handled later when looking for repeat signs and thus not exported into MusicXML.

This is now fixed in commit 625e8630e4b814605296c97f217f9d4c3a1a2664 to "development" branch.
Could you pull and check on your side?

**Comment by Bacchushlg** [comment]
The new version works fine concerning the problem.
Can be closed
