### ISSUE TITLE
Endless loop in Page

### ISSUE THREAD

**Issue by CCturner** [Audiveris/audiveris#300]
Hi,
The attached file get stuck in repeated error messages in PAGE process.

Regards
[Allemande.pdf](https://github.com/Audiveris/audiveris/files/3447592/Allemande.pdf)

**Comment by hbitteur** [comment]
There was a too strict dependency on specific sequences of barlines shapes (thin and thick) when looking for repeat signs during the PAGE step.
And in the provided "Allemande" image, there was not enough width difference between thin and thick barlines, therefore they were all considered as thin, which impeded a correct recognition of repeat signs.

I have just modified the recognition of barlines sequence to be less strict on barline thickness and rely mainly on the number of barlines.
This is available as commit 69f172a2c37ad9812629135cdfdb5379f1247f49 in the "development" branch.

If you don't want to pull and build from the development branch, and still want the "Allemande" image to be correctly processed, you can merely decrease the constant "minThinThickDelta" from its default value of 1.2 to 1.0. To do so, open the menu "Tools > Options" and enter minThinThickDelta in the search field.
In the "Allemande" score, the actual difference in width between thin and thick barlines is rather low and was considered a bit too low by Audiveris. By modifying minThinThickDelta you just lower the required minimum.
