### ISSUE TITLE
score provokes nullpointer exception

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#303]
The appended score provokes a nullpointer exception when starting transcription.

Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException

Version: 5.2.0-alpha:2f09f4f76

[Diamonds are the Girl's best Friends (1).zip](https://github.com/Audiveris/audiveris/files/3667550/Diamonds.are.the.Girl.s.best.Friends.1.zip)

**Comment by hbitteur** [comment]
Bug fix in commit 3d572694e33da1818a25627e3fe087636323286d on development branch
Was due to too lazy computation of bounds of a key inter ensemble.

**Comment by Bacchushlg** [comment]
works fine now
