### ISSUE TITLE
transcription ignores part of score key symbols

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#315]
![SCN_0003](https://user-images.githubusercontent.com/33522630/68083117-5bdd8500-fe25-11e9-9733-778a5e242965.jpg)

This score is written in b-key (two "b"s), but only one "b" is recognized.
It is a bit curious, that the 2nd b is not even once recognized as such.

**Comment by hbitteur** [comment]
@Bacchushlg 
This kind of manual modification is part of the first coming commit on geometric-ui branch. Available within 2 weeks...

**Comment by hbitteur** [comment]
Fixed in commit 6042a621f813159162a05dd1e5a329898c6c7819 available on development branch.
This was a matter of horizontal gap between key symbols.

Closing.
