### ISSUE TITLE
Audiveris 5.1.0

### ISSUE THREAD

**Issue by gunternulp** [Audiveris/audiveris#318]
Not able to start Audiveris on two computers, both Win10 1909

**Comment by gunternulp** [comment]
Not able to start Audiveris on two computers, both Win10 1909

**Comment by gunternulp** [comment]
Not able to start Audiveris on two computers, both Win10 1909C:\Program Files\Audiveris\bin>audiveris
INFO  []                      Main 334  | Environment:
- Audiveris:    5.1.0:4687c3527
- OS:           Windows 10 10.0
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 11.0.4+11, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 217  | CLI args: []
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:124)
        at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:112)
        at org.audiveris.omr.sheet.BookManager$LazySingleton.<clinit>(BookManager.java:467)
        at org.audiveris.omr.sheet.BookManager.getInstance(BookManager.java:458)
        at org.audiveris.omr.Main.main(Main.java:138)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

**Comment by Bacchushlg** [comment]
I'm afraid that your Java version might cause the problem.
I use version 8 (Build 1.8.0_191-b12).
Unfortunately java changes the API from time to time...

**Comment by gunternulp** [comment]
Thank you, I tried installing-->deinstalling-->installing Java, Audiveris. 
no change; same error like above
  
C:\WINDOWS\system32>java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode)

**Comment by Bacchushlg** [comment]
very curious. Are you sure that you do not have another java version on your computer? Java often keeps several versions on a computer. In detail it is possible to have different versions for Windows32 and 64-versions.
Have a look at "C:\program files\java" if you see more than one version there.

**Comment by gunternulp** [comment]
not very probably; I deinstalled Java, made a manual check in both program files folders (32 an 64 bit) and also used the JavaUninstallTool.
So the error source must be another.

**Comment by hbitteur** [comment]
@gunternulp 
In your very first message, I read this line:
`Java VM: OpenJDK 64-Bit Server VM (build 11.0.4+11, mixed mode)`
Audiveris 5.1.0 version does not support Java 11, but requires Java 8.

FYI, you can today use Java 11 with Audiveris _development_ version (5.2.0-alpha). To do so, you have to pull Audiveris 'development' branch and build it locally.

If you don't want to play with the development version, but stay with the latest stable release (5.1.0), you have to make sure that it uses a Java 8 version. Since you have reinstalled Java (version 8,  I suppose), could you double-check Audiveris messages. Better, could you post the latest log, so that we can check the actual Java version Audiveris is using in your environment?

**Comment by hbitteur** [comment]
Back to your very first message, we can notice that the program choked on "JAXBException" not being known.
This is typical of the modifications brought after Java 8, with a new modular Java architecture: JAXB stuff used to be part of Java core in version 8, but was put in a separate module starting with Java 9, IIRC.

So, please double-check your Java version.

**Comment by gunternulp** [comment]
Thank you, I've found a hidden JDK11 in the environment.

Aftre cleaning, reinstalling Java 8 Update 231, version check

C:\Program Files\Audiveris\bin>java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode)

and reinstalling audiveris 5.1.0?? I got a changed error message

C:\Program Files\Audiveris\bin>audiveris.bat
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnilept in 
java.library.path
 ?????????????? at java.lang.ClassLoader.loadLibrary(Unknown Source)
 ?????????????? at java.lang.Runtime.loadLibrary0(Unknown Source)
 ?????????????? at java.lang.System.loadLibrary(Unknown Source)
 ?????????????? at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
 ?????????????? at org.bytedeco.javacpp.Loader.load(Loader.java:613)
 ?????????????? at org.bytedeco.javacpp.Loader.load(Loader.java:530)
 ?????????????? at org.bytedeco.javacpp.lept.<clinit>(lept.java:10)
 ?????????????? at java.lang.Class.forName0(Native Method)
 ?????????????? at java.lang.Class.forName(Unknown Source)
 ?????????????? at org.bytedeco.javacpp.Loader.load(Loader.java:585)
 ?????????????? at org.bytedeco.javacpp.Loader.load(Loader.java:530)
 ?????????????? at 
org.bytedeco.javacpp.tesseract$TessBaseAPI.<clinit>(tesseract.java:3648)
 ?????????????? at 
org.audiveris.omr.text.tesseract.TesseractOCR.identify(TesseractOCR.java:152)
 ?????????????? at org.audiveris.omr.Main.showEnvironment(Main.java:348)
 ?????????????? at org.audiveris.omr.Main.main(Main.java:122)
 ?????????????? at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.UnsatisfiedLinkError: no liblept in java.library.path
 ?????????????? at java.lang.ClassLoader.loadLibrary(Unknown Source)
 ?????????????? at java.lang.Runtime.loadLibrary0(Unknown Source)
 ?????????????? at java.lang.System.loadLibrary(Unknown Source)
 ?????????????? at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
 ?????????????? at org.bytedeco.javacpp.Loader.load(Loader.java:604)
 ?????????????? ... 11 more

Am 20.11.2019 um 10:02 schrieb Herv?? Bitteur:

**Comment by gunternulp** [comment]
Now I fixed the problem ;-)
The Java update installer installed only the 32-bit version; after manually installing the 64-bit version Audiveris was running well.

Thank you for the hints
