### ISSUE TITLE
Several Recognition problems during recognizing complex scores

### ISSUE THREAD

**Issue by khjxiaogu** [Audiveris/audiveris#319]
First,it consider this 
![G_CLEF](https://user-images.githubusercontent.com/54445543/68959586-45620100-0809-11ea-8cb3-602d28f634ba.png)
as a treble clef but in fact there is __no__  treble clef here in source document.  
Second,The worst thing is that it can't recognize any note on ledger lines under first line,such as
![missed](https://user-images.githubusercontent.com/54445543/68959598-4b57e200-0809-11ea-94cb-89f5a0ebf177.png)
which makes optimizing the result is even __more troublesome than do the whole work manually__.  
This result is actually making me down.  
The orginal file and midi converted by hand is as below.  
[test1.pdf](https://github.com/Audiveris/audiveris/files/3852376/test1.pdf)
[test1.mid](https://www.khjxiaogu.com/test1.mid)
Hope to fix this ASAP.

**Comment by Bacchushlg** [comment]
Which version of Audiveris did you use for testing?
In my version (V5.2 testing) I get the following with no further editing - the remaining problems should be no problem to fix:
![image](https://user-images.githubusercontent.com/33522630/68994674-02923e80-0886-11ea-8624-b37bbe8bec8f.png)

**Comment by khjxiaogu** [comment]
However,I'm using V5.1.0 as the newest release.So where can I get V5.2.0 alpha?

**Comment by Bacchushlg** [comment]
what I use is a developer version. There should be a new official version in the near future.
