### ISSUE TITLE
at Audiveris.main(Audiveris.java:49)

### ISSUE THREAD

**Issue by geole** [Audiveris/audiveris#321]
hello
I'm just starting to use  Audiveris.
**First try**
I chose to install it with these commands:
git clone https://github.com/Audiveris/audiveris.git
cd audiveris

sudo add-apt-repository ppa:cwchien/gradle
sudo apt update
sudo apt install gradle

gradle wrapper --gradle-version=5.1.1 ### see https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2
./gradlew   build

**Second try**
I use this file
https://download.tuxfamily.org/librazik/decepas/pool/main/a/audiveris/audiveris_5.1.0-0librazik1_amd64.deb

**In both cases, the launch fails** 

 java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

export TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/
/usr/share/audiveris/bin/Audiveris
INFO  []                      Main 334  | Environment:
- Audiveris:    5.1.0:4f234fefb
- OS:           Linux 4.15.0-70-generic
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, **mixed mode, sharing**)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 217  | CLI args: []
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:124)
	at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:112)
	at org.audiveris.omr.sheet.BookManager$LazySingleton.<clinit>(BookManager.java:467)
	at org.audiveris.omr.sheet.BookManager.getInstance(BookManager.java:458)
	at org.audiveris.omr.Main.main(Main.java:138)
	at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more

Thank you for your advice

**Comment by hbitteur** [comment]
Audiveris 5.1 is not compatible with Java 11, it requires Java 8.

So, you have 2 possibilities:
- Install Java 8 (and make sure that it's Java 8  that is used when you launch Audiveris, and not the Java 11 installation)
- Or pull the "development" branch (you will get 5.2.0-alpha) which is compatible with Java 11. Since you run on Linux, this is likely to be your preferred option.

[A 3rd possibility is to wait for the 5.2 release (within a month or so)...] :-)

**Comment by hbitteur** [comment]
@geole Have you made any progress?
Can I close this issue?

**Comment by Krakitten** [comment]
I'm getting the same error on windows using the binary installer. 
![Error](https://user-images.githubusercontent.com/32579517/75654386-9caba600-5c2d-11ea-9c5c-0bfbcc72496d.PNG)

It appears to be defaulting to java 11. I have both java 8 and java 11 installed. Is there an easy way to switch the java version for audiveris back to 8. If not I could give the Dev branch idea above a try.

**Comment by Krakitten** [comment]
Created a JAVA_HOME sys var and now I think the program is running properly

**Comment by Krakitten** [comment]
Thank you for making this program. Everything ran without issue, and it did better than I imagined. Only 5 minor errors within 10 pages of piano music. Could probably fix everything and get the perfect transcription in less than 5 min.

I'm using this to transpose piano scores I find online into flute parts to play for fun. Thank you
