### ISSUE TITLE
Missing a clear back button in shape group selection view

### ISSUE THREAD

**Issue by hekkup** [Audiveris/audiveris#325]
In the sidebar shape view, you can select a shape group. Clicking a shape group shows the shapes in the group. However, once the group is shown, there's no back button visible. It's possible to go back to the shape group selection view by pressing Esc or by clicking group name. IMHO navigating back should be more obvious.

**Comment by hbitteur** [comment]
True. This hack was done to save on real estate.

What do you propose?
A visible "Back" button, separate from the title of the shape family?

**Comment by hekkup** [comment]
One option would be a small back button in front of group title. A tall button would provide more clickable area. The group title and the tool tip could still work like before. The button could be different color or looking different than the shape buttons so that it wouldn't be confused with the accidental, if that's a danger (maybe not a serious danger though).

![audiveris-shapes-navigation-01-191202](https://user-images.githubusercontent.com/1606010/69982033-32a33800-153c-11ea-8c8f-917880b7f1a9.png)

**Comment by hekkup** [comment]
Oh yes and the tooltip should include the shortcut key like in many other applications. This actually applies to all tooltips. Maybe I should add another issue / feature request for this.

**Comment by hekkup** [comment]
There's now a back button. I have tested it in Linux and it works. Is this issue ready to be closed?
