### ISSUE TITLE
problems with chords with note heads on both sides

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#326]
![Eternity (2)](https://user-images.githubusercontent.com/33522630/69911428-b285b100-141b-11ea-9d22-82217676f7a3.jpg)

In some - rather seldom - cases the rhythm check has problems with chords that have note heads on both sides of the stem.
In the score above this concerns the first two measures of the 2nd system: the rhythm check fails for the first chord of the piano voice. If I move the heads left of the stem to the right of the stem, everything is fine.
I could imagine that this might be solved by changing on of the parameters - but which one...?

**Comment by hbitteur** [comment]
Without moving the heads, you could simply select chord in first staff (the one with heads on both sides, plus dots) and the chord just below on second staff, then use Chords popup menu to set "Same Time Slot".

OK, this is just a manual fix.
I'll need to investigate why the vertical alignment failed in first place.

**Comment by hbitteur** [comment]
Fixed in commit 76eec48851a856d95e629571816857fd154f8faa
To be pulled from development branch

Closing this issue (but keeping the example image because of its last staff which exhibits a strong warping, to be addressed by future staff editor)
