### ISSUE TITLE
Add panning main view with mouse [feature request]

### ISSUE THREAD

**Issue by hekkup** [Audiveris/audiveris#330]
I suggest pan function in main view (sheet view) for mouse: take the middle mouse button (/wheel) into use so that you could pan the view with it. Inkscape is an example about what I mean. Click down: lock the position which to drag. Move mouse: move the locked position, panning the sheet with it. For clarification, I don't mean panning by rolling the mouse wheel.

**Comment by Bacchushlg** [comment]
Panning is supported in a different way already now: normal mouse wheel for up/down, and shift + wheel for left/right. For me it works very well this way.

**Comment by hbitteur** [comment]
Sorry, I'm not sure to understand the notion of "pan function", could you explain what "panning the sheet" means actually? English is not my mother language :-(

Here are a couple of other actions already available that may be of interest to you:
- The combination of CTRL key + mouse wheel rolling increases/decreases the zoom ratio, keeping the current selected point in the center of window.
- Pressing both mouse buttons (1 & 3, if wheel is2) and dragging the mouse drags the whole view.

**Comment by hekkup** [comment]
Ok, found the Shift+wheel panning.

@hbitteur panning is explained by @Bacchushlg in the above comment.

In geometric-ui branch the panning with mouse buttons 1&3 don't work. This happens in Linux. Traditionally, in X.org desktops mouse buttons 1+3 work like mouse button 2 (middle button or the wheel). This is an old workaround for the mice which didn't have the middle button, and it still works.

**Comment by hekkup** [comment]
Mouse buttons 1&3 for panning don't work in development branch either in Linux.

**Comment by hekkup** [comment]
Now the panning works with wheel / middle button dragging as well as with combination of buttons 1+3. Tested in Linux.
