### ISSUE TITLE
Can Audiveris run in  command line under Linux OS

### ISSUE THREAD

**Issue by guanboliang** [Audiveris/audiveris#335]
I wish the Audiveris could run in command line under Linux OS, for example:
1. Specify the score sheet image path as the input parameter
2. Then run Audiveris command, and the output is a musicxml file

**Comment by maximumspatium** [comment]
See https://github.com/Audiveris/audiveris/wiki/Launching#launching-audiveris and https://github.com/Audiveris/audiveris/wiki/CLI-Arguments

**Comment by hbitteur** [comment]
@guanboliang 
Was Maxim's advice OK for you? Can you run from Linux command line?

**Comment by hbitteur** [comment]
I suppose this was OK.
Closing.
