### ISSUE TITLE
gradle uses source compatibility 1.7 but SigPainter.java uses Java 11+ method (String::isBlank())

### ISSUE THREAD

**Issue by Philtard** [Audiveris/audiveris#337]
The Project is set to source compatibility 1.7 but SigPainter.java uses Java 11 String method isBlank(). In Java 1.7 isEmpty() can be used (differs to isBlank() in not ignoring leading trailing whitespaces - or - not "trim()"-ing before checking the length).

In src/main/org/audiveris/omr/sig/ui/SigPainter.java (Line 1008)

```

        if (word.getValue().isBlank()) {

```

[Open on Web](https://api.codestream.com/c/XfML1D_iBwy7KOSm/SmkYlblhQ4mjayvx8JxTWQ?marker=5df321e5b5a2630cf2c80839) · [Open in IDE](https://api.codestream.com/c/XfML1D_iBwy7KOSm/SmkYlblhQ4mjayvx8JxTWQ?marker=5df321e5b5a2630cf2c80839&ide=default) · [Open on GitHub](https://github.com/audiveris/audiveris/blob/2d271de367c050d5e51ff5dde9c4ffa6372ebf67/src/main/org/audiveris/omr/sig/ui/SigPainter.java#L1008)

**Comment by Philtard** [comment]
see PR #338 with a quick and dirty replacement of isBlank() with trim().isEmpty() without further analysis or testing to successfully build with the gradle wrapper again. The successful gradle build resolves this issue already as far as I was concerned opening it, so further code changes or starting a discussion about how to handle / or where to allow nullables generally in the code etc. not in this issues scope.

**Comment by hbitteur** [comment]
PR #338 merged.
Thanks
