### ISSUE TITLE
null pointer exception when adding a rest inter

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#339]
![White Christmas (1)](https://user-images.githubusercontent.com/33522630/70852180-d080f600-1e9e-11ea-8c7f-4c9a1b94b578.jpg)

In this score some rests are not recognized after transcription (5th system). When trying to add the rest manually, I get an error message:
Exception in addInter java.lang.NullPointerException

Version is: 5.2.1-alpha

**Comment by oleedd** [comment]
I have the same problem with the score from the previous issue.

**Comment by oleedd** [comment]
@Bacchushlg Does inserting rests work in other scores?

**Comment by oleedd** [comment]
Does inserting (drag&drop) rests work in other scores?

**Comment by hbitteur** [comment]
A bit strange. I discovered an error related to exclusion of bracket parts that led to a NullPointerException.
I fixed this in commit 7d1b007300158056e5adfe6dbb24e7c68c8167c2 and I can play with your score example, including adding rests, with no problem.
Could you pull again development branch and try again on your side?

Meanwhile, I'll forward you some interesting easy improvements about this score.

**Comment by oleedd** [comment]
Inserting rests started to work in my score too. But there is a similar problem with DOT_set.
![image](https://user-images.githubusercontent.com/36125949/71021876-e6452400-2107-11ea-801c-bf39d8ba1b17.png)
It gives the red error `No ghost instance for DOT_set`.

**Comment by Bacchushlg** [comment]
I tried the version: everything ok again.
Can be closed.
Dot set? I never used this...

**Comment by hbitteur** [comment]
@oleedd 
A DOT_set is a **physical** dot for which the logical symbol is not yet known. Remember a dot is a dot, but its meaning can be different between say an augmentation dot or a repeat dot or a staccato dot, etc which are **logical** symbols.
DOT_set is just the raw output of the glyph classifier which recognized a physical dot.

In the case of user edition, you insert logical symbols. So you should assign a logical dot, by selecting the augmentation dot, or the repeat dot, etc. But not from the classifier outputs. Remember the current classifier is just a glyph classifier, not able to take context into account.

This has nothing to do with the NullPointerException reported by Baruch in this issue. This is not the same problem, so you'd better open a separate issue about "DOT_set". Doing so, the right title about DOT_set would appear in the list of issues, letting the other users read about it. Please let's try to respect the rules.

**Comment by oleedd** [comment]
>Dot set? I never used this...

Dots are like non-recognizable symbols. I understand that they are very small and artifacts of bad quality can be recognized as dots. So maybe better nothing than too many wrong results. So need to insert them manually.

**Comment by oleedd** [comment]
>Dot set? I never used this...

But you have opened an issue about Dot set: https://github.com/Audiveris/audiveris/issues/84
