### ISSUE TITLE
I want this Audiveris to support Korean.

### ISSUE THREAD

**Issue by mailsjb** [Audiveris/audiveris#340]
HI, thanks to your program. really thanks.

However, this program can't use the korean song words.
only know English song words.

I want your program to update Korean song words.

thanks.

**Comment by hbitteur** [comment]
@mailsjb 
Audiveris delegates character recognition to Tesseract OCR software.
You just need to download Tesseract korean data. I suppose it's the kor.traineddata package available on [https://github.com/tesseract-ocr/tessdata/tree/3.04.00](https://github.com/tesseract-ocr/tessdata/tree/3.04.00).
Then install this package as explained in [https://bacchushlg.gitbooks.io/audiveris-5-1/content/install/sources.html](https://bacchushlg.gitbooks.io/audiveris-5-1/content/install/sources.html)
Please keep us informed about the result.

NOTA: Do no try to download Tesseract 4.x data, current Audiveris needs the older Tesseract 3.04 data as referenced above.

**Comment by hbitteur** [comment]
@mailsjb 
Any feedback yet?
Can we close this issue?

**Comment by mailsjb** [comment]
Thank you so much. We installed Tes-OcR and solved it. I'm just grateful that this is a matter of Tes-OCR, although I'm less aware of it. Thanks once again.
