### ISSUE TITLE
Tuning template matching for note heads

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/audiveris#341]
Current Audiveris version uses a shallow neural network for all fixed-shape symbols, except for note heads which are addressed by template matching.

Very roughly, template matching checks every pixel of a symbol candidate in input image against the corresponding pixel in the template being tried. Evaluation is simply the ratio of correct pixels over the total number of relevant pixels in the template.

Now, we can use different weights, depending on whether a template pixel is white or black. Right now, the weight is the same. But, while working on cross heads recognition (see cross-heads branch), I tried to play with color weights and improvement is significant, especially on cross heads.

I plan to retrofit this to the main version. Anybody can try this, with no need to recompile. Just play with the constants "**foreWeight**" or "**backWeight**". foreWeight is used by black template pixels and backWeight by white template pixels. They are by default both set to 1. 

The same input image of issue #339 is interesting. Quality is poor. Its notes are split between 2/3 black and 1/3 void (half or whole). I ran the same test (until REDUCTION step), with different values of foreWeight. Here are the results:

Input image content: black: 143, void: 72
- foreWeight 1: black missed: 23, void missed: 30 (this is the current version)
- foreWeight 3: black missed: 12, void missed: 11
- foreWeight 4: black missed: 9, void missed: 14
- foreWeight 5: black missed: 6, void missed: 14
- foreWeight 8: black missed: 6, void missed: 18

Obviously, we get significant improvements by increasing the weight for expected black pixels. On this example, value 5 seems to give the best results.

Template matching should be removed some day in favor of another technique (patch classifier). In the mean time, we have just added support for cross heads, and even for standard note heads, this improvement is immediately available.

**Comment by oleedd** [comment]
What is "cross heads recognition"?
>Template matching should be removed some day

Why not remove it now if it isn't good?

**Comment by hbitteur** [comment]
Cross head looks like an "X" (kind of ghost note, with no real pitch, but part of rhythm).

The problem with template matching is not to remove it, but to replace it with something which works

**Comment by oleedd** [comment]
>The problem with template matching is not to remove it, but to replace it with something which works.

I know. I mean a shallow neural network which works for other fixed-shape symbols.

6.x is too big - 1 GB. With several branches, it may be several times heavier. Released Audiveris - 40 MB, Github Audiveris 360 Mb. 1 GB * 360/4 = 9 GB.

**Comment by hbitteur** [comment]
As explained in the discussion on 6.0 prototype, the main drawback of the current classifier (which is a glyph classifier) is to be able to feed it with the right glyph, which in turns requires to be able to extract this right glyph, a problem known as "segmentation".

Before template matching, note heads were addressed by the glyph classifier, with results worse than template matching, because of this segmentation problem.

**Comment by hbitteur** [comment]
Modification introduced in development branch.
I'm closing the issue now
