### ISSUE TITLE
DOT_set

### ISSUE THREAD

**Issue by oleedd** [Audiveris/audiveris#342]
I propose to divide the button into 3 segments (types) to make it work.
As a variant:
![image](https://user-images.githubusercontent.com/36125949/71026869-bcddc580-2112-11ea-9800-e8d79f9ecb36.png)

**Comment by oleedd** [comment]
@hbitteur Good solution?

**Comment by oleedd** [comment]
@hbitteur Good solution?

**Comment by hbitteur** [comment]
I think not.

Like I told you already, these buttons are the raw outputs of the (physical) glyph classifier, which cannot make a difference between the various kinds of logical dots.

We are working on a new classifier (the patch classifier) which is meant to recognize logical symbols directly. Thus the outputs of this new classifier will be different for say a staccato dot and an augmentation dot.

**Comment by oleedd** [comment]
>these buttons are the raw outputs of the (physical) glyph classifier

But you can make an overlay over the button and use some rules to insert the needed symbol after user says which.

**Comment by hbitteur** [comment]
The physical classifier is available. It is complemented by algorithmic code to infer logical results.

The logical classifier is on its way. It will still be complemented by some algorithmic code, though certainly less than today.

Why should I waste time trying to "twist" the physical classifier outputs to somehow ressemble the coming logical classifier?
Time is a scarce resource, and there are plenty of tasks to carry out.

**Comment by oleedd** [comment]
>The logical classifier is on its way.

If the dot is the only goal then it isn't worse. Or there are many advantages?

**Comment by hbitteur** [comment]
Won't fix, for the reasons explained above.
Closing this issue.
