### ISSUE TITLE
support adding a slur at the end/beginning of a note line

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#346]
slurs are normally correctly recognized and handled, even from one line to the next one.
But if they are not automatically recognized, there is no way to add them manually.
Would be fine to add this possibility.

**Comment by hbitteur** [comment]
By "one line to the next one", I suppose you mean from one staff/part in a system to the corresponding staff/part in the next system.

If so, I'm afraid you are right :-( 
Connecting slurs between systems is usually well done by the engine but I forgot to include this in the manual features. Shame on me!

As soon as I complete current work on lyrics I'll jump on this issue.

**Comment by hbitteur** [comment]
Now implemented in commit 498ddc0a0d4b80b68bb9e8d6074cb5cd14b0e781 on development branch.
User gesture is simply to drag from one slur to the other, even though they are located in different systems.
