### ISSUE TITLE
A staff without a clef sign should assume the current clef

### ISSUE THREAD

**Issue by ddrinka** [Audiveris/audiveris#348]
I have a piece that does not include a clef sign at the beginning of each system:

![image](https://user-images.githubusercontent.com/1297262/73516363-720fc880-43b5-11ea-8229-c7e3813a50d2.png)

The LINKS step is unable to proceed with the following error:
```
[Badelt_POTC_Tuba4tet_SCORE#6] Error in performing [LINKS] java.util.concurrent.ExecutionException: java.lang.IllegalStateException: No clef found in {Staff id=5 left:150 right:2398} before java.awt.Point[x=920,y=1227]
```

I realize this is an odd formatting, and I'd be happy to add clef signs manually to work around the oddity, but I'm not sure how to manage that in Audiveris.

Any guidance?

**Comment by Bacchushlg** [comment]
You can select the proper clef from the right board (click on the g-clef, then select the proper clef and drag-n-drop it to the correct position (maybe a bit tricky, because in your score is very little space for inserting a clef).

**Comment by hbitteur** [comment]
We cannot blame the LINKS step on this :-)
I'd suggest to try to fix the case before LINKS step runs.

1. Typically run until HEADERS step since it's in this step that staff headers are processed. A staff header is the sequence: clef + key sig if any + time sig if any.

2. Then perform the manual corrections by drag n' drop from the shape board as @Bacchushlg  said.

3. Finally run until PAGE step.

And keep your fingers crossed...

**Comment by ddrinka** [comment]
Thanks for your responses.  I'm still having trouble.  Here's what I'm seeing:

### Process to HEADERS step
I receive the following message:
```
WARN  [Badelt_POTC_Tuba4tet_SCORE#6]               ClefBuilder 621  | Staff#5 no header clef.
WARN  [Badelt_POTC_Tuba4tet_SCORE#6]               ClefBuilder 621  | Staff#6 no header clef.
WARN  [Badelt_POTC_Tuba4tet_SCORE#6]               ClefBuilder 621  | Staff#8 no header clef.
WARN  [Badelt_POTC_Tuba4tet_SCORE#6]               ClefBuilder 621  | Staff#9 no header clef.
WARN  [Badelt_POTC_Tuba4tet_SCORE#6]               ClefBuilder 621  | Staff#10 no header clef.
WARN  [Badelt_POTC_Tuba4tet_SCORE#6]               ClefBuilder 621  | Staff#11 no header clef.
WARN  [Badelt_POTC_Tuba4tet_SCORE#6]               ClefBuilder 621  | Staff#12 no header clef.
INFO  [Badelt_POTC_Tuba4tet_SCORE#6]                  StepMenu 185  | End of sheet step HEADERS
```

And the sheet looks like this
![image](https://user-images.githubusercontent.com/1297262/73582771-ea28cd80-444b-11ea-966b-e4f1f9a41f78.png)

### Delete incorrectly-matched treble clef and add bass clefs
I can add the quarter notes later, if it's OK to have the clef on top of the first quarter notes.
![image](https://user-images.githubusercontent.com/1297262/73582866-628f8e80-444c-11ea-82c7-454189d3229a.png)

### Run PAGE step
I receive an exception:
```
WARN  [Badelt_POTC_Tuba4tet_SCORE#6]                 SheetStub 845  | Error in performing [STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1111)
        at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:832)
        at org.audiveris.omr.step.ui.StepMenu$StepAction$1.doInBackground(StepMenu.java:184)
        at org.audiveris.omr.step.ui.StepMenu$StepAction$1.doInBackground(StepMenu.java:159)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
        at org.audiveris.omr.sheet.PageCleaner.processGlyph(PageCleaner.java:448)
        at org.audiveris.omr.sheet.PageCleaner.visit(PageCleaner.java:215)
        at org.audiveris.omr.sig.inter.ClefInter.accept(ClefInter.java:141)
        at org.audiveris.omr.text.SheetScanner$TextsCleaner.eraseInters(SheetScanner.java:274)
        at org.audiveris.omr.text.SheetScanner.getCleanImage(SheetScanner.java:164)
        at org.audiveris.omr.text.SheetScanner.scanSheet(SheetScanner.java:129)
        at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:80)
        at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:42)
        at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:98)
        at org.audiveris.omr.step.Step.doit(Step.java:184)
        at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1101)
        at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1089)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        ... 3 common frames omitted
INFO  [Badelt_POTC_Tuba4tet_SCORE#6]                  StepMenu 185  | End of sheet step PAGE
```

And though the log says "End of sheet step PAGE", the Step menu only shows steps through CUE_BEAMS completed.  Running TEXTS continues to throw the same exception.

I tried reloading the input from scratch and processing just HEADERS, adding the clefs, and then running through, and TEXTS always throws the same exception.  I also tried squeezing little bass clefs into the front:
![image](https://user-images.githubusercontent.com/1297262/73583337-dd59a900-444e-11ea-89c5-ba1292d69a5a.png)

Same error.

**Comment by hbitteur** [comment]
@ddrinka 
We are trying to drive Audiveris off the road by all these work arounds. And it crashes because it is used to well paved roads! :-)

Could you post the original image, so that I can reproduce and debug what is happening? I can't promise the lack of original clef will work, but perhaps I can avoid the crashes. At least I can try.

**Comment by ddrinka** [comment]
[Badelt_POTC_Tuba4tet_SCORE.pdf](https://github.com/Audiveris/audiveris/files/4148867/Badelt_POTC_Tuba4tet_SCORE.pdf)

Apparently there is some music notation software out there that is defaulting to not including clefs on all but the first system.  Would it make sense to add an option to carry over clefs from previous systems if one isn't provided?

**Comment by hbitteur** [comment]
Well, it turns out to be much more difficult that I first expected.

Either you have the room to manually insert clefs or you have to somehow overwrite notes with clefs, and then re-insert these notes a little farther on the right. I tried that and it led to numerous problems, because a header is assumed to exist.

Or, we modify the engine so that, under an explicit user option, there is no header clef except in first system in sheet. But again, there are many portions of the code where we assume that the staff begins with a clef. 

All in all, I will leave this as an "enhancement request" for the time being.

**Comment by ddrinka** [comment]
Ok, thanks for trying @hbitteur

**Comment by MusicForStringsPercussionCeleste** [comment]
my opinion as a life long professional musician:  all music should have a clef at the beginning of every staff line as a given, whether for Audiveris or for any person reading the music.  Any music without clefs on a system is the problem of the composer/engraver, and they should not expect anyone to read the music without them.

________________________________

**Comment by ddrinka** [comment]
@MusicForStringsPercussionCeleste Totally agree.  If I were producing these PDFs I would do it differently.  My request here was based simply on the fact that some piece of software somewhere is "doing it wrong", and would it be worth allowing for that.

**Comment by hbitteur** [comment]
@MusicForStringsPercussionCeleste 
Indeed, we already have enough work making Audiveris behave correctly on "legally-formatted" scores to keep us busy for a while :-)

**Comment by MusicForStringsPercussionCeleste** [comment]
Indeed, we already have enough work making Audiveris behave correctly on "legally-formatted" scores to keep us busy for a while :-)

EXACTLY 🙂

________________________________
