### ISSUE TITLE
Could not build Audiveris on Windows

### ISSUE THREAD

**Issue by SF2311** [Audiveris/audiveris#35]
I'm trying to get Audiveris to run on a Windows System but the gradle build aborts with this error:
`FAILURE: Build failed with an exception.`
`What went wrong:
Executione failed for task ':startScripts'.`
`Could bot resolve all files for coniguratione ':runtimeClasspath'.
Could not find nd4j-native-windows-null.jar (org.nd4j:nd4j-native:0.8.0).
Searched in the following locations:
https://jcenter.bintray.com/org/nd4j/nd4j/-native/-0.8.0/nd4j-native-0.8.0-windows-null.jar`
And so on.

**Comment by maximumspatium** [comment]
Sorry for the delayed response. It looks like you're trying to run Audiveris on an unsupported architecture, hence `null` at the end of the nd4j bundle name.
What version of Windows you are running? On which CPU?

**Comment by SF2311** [comment]
My windows verssion is 8.1.
The Prozessor is a Intel i7 5500U @2.40GHz.

**Comment by maximumspatium** [comment]
Can you run `java -version` and `gradle -v` in your command prompt and post the result here? Thanks.

**Comment by SF2311** [comment]
>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

>gradle -v
------------------------------------------------------------
Gradle 4.3.1
------------------------------------------------------------

Build time:   2017-11-08 08:59:45 UTC
Revision:     e4f4804807ef7c2829da51877861ff06e07e006d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 8.1 6.3 x86

**Comment by maximumspatium** [comment]
Your gradle installation clearly refers to the older (and, probably, 32bit) JVM 1.8.0_121 although you have the newer JDK/JVM installed as well.
You need to repair your gradle installation (by removing 32bit JVM 1.8.0_121).
Please tell me how it goes so I can eventually close this issue.

**Comment by SF2311** [comment]
One test failed: 

    GhostscriptTest. pathTest

**Comment by maximumspatium** [comment]
I've removed that deprecated GhostscriptTest, see https://github.com/Audiveris/audiveris/commit/9fe7d81c5470bda735dc1598b99432f829b6721d

Would you kindly switch to the development branch (`git checkout development`), pull the latest commit (`git pull`) and retry your build (`gradle clean run`)? Thank you.

**Comment by SF2311** [comment]
`BUIL SUCCESSFUL`
Thanks a lot
