### ISSUE TITLE
option: detect cross note heads

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#353]
Actually I have a couple of scores that use cross heads a lot.
Would it be possible to support these head types optionally? As setting in sheet parameters.

**Comment by hbitteur** [comment]
It is already the case!
See the "book parameters", where you can set processing switches at sheet level, book level or default level.

**Comment by Bacchushlg** [comment]
oh, what a pity... Why didn't I notice it before.
And it works perfectly! All cross heads of my test score were detected!

**Comment by hbitteur** [comment]
To be clear.
Today we have in Book and Sheet pulldown menus:
- Book | set Book parameters
- Sheet | set Sheet parameters

In fact, **Book parameters** item allows to set parameters (most of them are processing switches) at different levels: Global, Book, Sheet. So this governs also sheet parameters.

And **Sheet parameters** item allows to inspect and potentially modify important sheet data that are often key for some steps (typical example is the value of beam thickness).

So, to avoid confusion, perhaps I should rename Sheet | **set Sheet parameters** to something like Sheet | **Edit Sheet data**.
What do you think?

**Comment by Bacchushlg** [comment]
For me the naming makes no big difference. 
But what would be helpful instead is keeping the values in the sheet parameter dialog after resetting the sheet to binary from the last transcription. So the user sees the last used parameters and can modify by inc-/decrementing the concerning parameter. 
In this case, **edit** indeed makes more sense...

**Comment by Bacchushlg** [comment]
![I'm all over It (2)](https://user-images.githubusercontent.com/33522630/74601531-9d760100-509f-11ea-9e48-3409ea65a4b0.jpg)

See this score: the "mf" and "f" above the first note line is far too high. (This is what I see, opening this in MuseScore)
What you can also observe is the wrong assignment of the "mf"s in the following note lines: click on note lines 5th measure, and you see that the mf below is assigned, instead of the one above (the top line has 2 mf-s at the same note). This concerns item #355 .

**Comment by hbitteur** [comment]
If I understand your request correctly, we should keep the values specifically entered by the user (the others don't matter) even when sheet is reset.
Doing so, the user would not have to re-enter the data he had entered before.

**Comment by Bacchushlg** [comment]
...and he sees what the program has used before. This is even more important.
