### ISSUE TITLE
re-connect of neighbour shape elements after adding stems or heads

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#358]
it happens from time to time that stems or heads are not recognized. No problem, they can be added manually rather quickly.
Unfortunately after adding them, some connections to neighbour elements are not refreshed as it is done in similar cases:
- beams: after adding a stem to an existing beam (normally this happens for a stems that is in the middle of a beam) the stem is not connected to this beam, it must be connected explicitly)
- lyrics: after adding a head, a lyrics element is not connected automatically

typical Example:
![image](https://user-images.githubusercontent.com/33522630/75014355-59f80a00-5486-11ea-92a5-8f5500983331.png)

**Comment by hbitteur** [comment]
Current policy is that links are searched at (manual) insertion time of symbol A **only if** A needs such link.
In the 2 cases mentioned here, the policy gives: 
- a stem does not need a beam.
- a head chord does not need a lyric item.

**Comment by Bacchushlg** [comment]
I understand the current policy. But it would help editing, if this feature could be added.
A stem that ends at (or near) a beam is very likely part of the beam. After adding the stem, actually the rhythm is not correct, because the added note does not get the correct timing.
This finally leads to an incorrect output - sometimes with corrupt timing of the measure(s).

**Comment by hbitteur** [comment]
This now works when inserting a compound note (head+stem): beam potential links are displayed when moving the compound and they are indeed created at drop time.
See commit a28c84b0f7c37c49d5e62c398a7cf1a2cad83725 in development branch.
