### ISSUE TITLE
memory leak in case of re-transcription

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#359]
I observe a memory leak in case I reset a sheet to binary and re-transcribe it.
In my test case, after each run the displayed memory usage (on top right) after pressing the "run garbage collection" augments by 45 MB (230, 275, 320 MB).

**Comment by hbitteur** [comment]
I'm away from home right now, and for 2 more weeks.
I'll investigate this when I return.

**Comment by Bacchushlg** [comment]
I notice this memory leak rather often in the last time, not only in case of re-transcription.
The more sheets I transcribe, the higher gets the used memory display getting red after about an hour...
In rather few cases I had to restart Audiveris because it become very slow...

**Comment by hbitteur** [comment]
@Bacchushlg 
I fixed the memory leaks (due to remaining Swing listeners) in commit ea6c52a7395e613b284660595fe55ba444aa7baa
