### ISSUE TITLE
step reduction removes "good" stems, beams and heads

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#362]
![if you leave me now 8](https://user-images.githubusercontent.com/33522630/75320074-35c57000-586e-11ea-83f6-937275e3cd57.jpg)

This score drives me crazy: the algorithm finds almost all stems, beams and heads - and then in step reduction, most of them are removed. No idea, why...

**Comment by hbitteur** [comment]
One more time: Inter candidates for head/beam/stem can be created provided their grade is at least 0.1 (minInterGrade). This does not imply they will survive!
The real test is made at REDUCTION step, using contextual grades that take into account Inter connections, such as head-stem connection. 
You can lower the constant minContextualGrade (0.5) if you wish. This may help you on specific scores.

**Comment by Bacchushlg** [comment]
Even with normal settings I get a much better recognition with the actual version (e20783e27).
So I close the issue.

**Comment by hbitteur** [comment]
You mean the "current" version, right? :-)

**Comment by Bacchushlg** [comment]
[years-of-solitude.pdf](https://github.com/Audiveris/audiveris/files/5145158/years-of-solitude.pdf)

Another score with the same problem. I have lowered minContextualGrade to 0.1, but still many formerly detected chords are removed during step reduction.

**Comment by Bacchushlg** [comment]
problem is solved with version 145bc93
