### ISSUE TITLE
wrong measure handling after merging of 2 systems

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#366]
[When I get older.zip](https://github.com/Audiveris/audiveris/files/4313552/When.I.get.older.zip)

When exporting this transcribed score, the score is split into 2 files.
In the first, the last system is no more correct - the upper note line is empty while the lower one contains the notes of the upper...
I assume the reason is that I had merged the system #5 manually (merge with system below). I also see that the measure counter has restarted for the last system (but with #4 ?)

**Comment by hbitteur** [comment]
These look like 2 sheets merged in a single image. Just as if you had opened a book, and scan the left sheet and the right sheet in one scan.
How should we read such image: left side from top to bottom, then right side from top to bottom?
Could you confirm?

If so, Audiveris has been designed to scan one sheet at a time, from top to bottom. 
In some cases, I don't have one immediately at hand, a system may be split horizontally. The left side is the ending system, the right side the starting system. These "half-systems" are horizontally aligned. And the next "full system" occupies the whole sheet width again.
Audiveris has never been thought to process 2 sheets in parallel in the same image.

Have you tried splitting this whole image into 2 sub-images, one image per side, and then launch Audiveris on one sub-image at a time?

**Comment by Bacchushlg** [comment]
About splitting: No, I did not, because it seemed to me that the transcription had analysed the page properly. At least the output view shows the proper system numeration.
I assume that the major problem is similar to #377: the missing bracket in system nr. 5.

But ok, I agree that normally the user should separate the pages and transcribe them one by one.

**Comment by hbitteur** [comment]
So, I'm closing this issue.
