### ISSUE TITLE
Video Tutorial of installing Audiveris

### ISSUE THREAD

**Issue by pianoplayer15** [Audiveris/audiveris#367]
Hi,

i have problems installing Audiveris on my Windows Notebook. I am sure it is because of me. Therefore it would be kind if someone could make a short Video tutorial of how to install Audiveris.
I would like to use Audiveris for my piano sheet music.

Thank You

**Comment by weidi** [comment]
Hi, what step are you failing on?
Have you been using the 5.1 installer or do you want to build a more recent development version on your own?
Here you will find the installer:
[](https://github.com/Audiveris/audiveris/releases)
Make sure you have Java installed and working, you can check this by running `java -version ` in cmd or powershell
Hope this helps.
@hbitteur If you want i can create a youtube video showing how to build development branch, what do you think?

**Comment by hbitteur** [comment]
@weidi 
I strongly support your idea to create small tutorial video(s), especially on topics that may look obvious for developers but much less easy for new-comers. We could think of:
- Binary installation on Windows. With special attention to Java version and bit architecture (32 vs 64)
- Clone and build on various OSes.
- Build a specific branch (such as development)
What else?

Thanks a lot for your help
/Hervé

**Comment by pianoplayer15** [comment]
My problem was setting up the Java Development Environment.
Installer for Audiveris and  Tesseract OCR worked well.
Different Version of Tesseract OCR confused me but everything works for me know.
Still, I think commercial versions are more developed than audiveris but thanks for your work.

**Comment by pianoplayer15** [comment]
My problem was setting up the Java Development Environment.
Installer for Audiveris and Tesseract OCR worked well.
Different Version of Tesseract OCR confused me but everything works for me now.
Still, I think commercial versions are more developed than audiveris but thanks for your work.
