### ISSUE TITLE
Weird Interline Bug leading to infinite loop

### ISSUE THREAD

**Issue by xwiz** [Audiveris/audiveris#369]
When I try to transcribe [this sheet](https://www.ugandacatholicmusic.com/wp-content/uploads/sheet/What%20Have%20we%20to%20Offer%20Him.pdf)

It ends up in an infinite loop with a repeating message like: 

    "Unknown style for StaffBarlineInter{#2470 FROZEN(0.792/0.792) s:3 null"

**Comment by hbitteur** [comment]
Latest development works nicely on your example.
You can wait for the coming 5.2 release in a few weeks.

Or, better, pull the "development" branch, and build it on your own, so you can immediately use it.
