### ISSUE TITLE
what is the differences during the ‘measure’,'part','systeminfo' in this repository?

### ISSUE THREAD

**Issue by gloddream** [Audiveris/audiveris#37]
what is the differences during the ‘measure’,'part','systeminfo' in this repository?  
thanks

**Comment by hbitteur** [comment]
Please refer to music on the Internet, WikiPedia for example

**Measure**: a unit of time in Western music representing a regular grouping of beats
**System**:  a group of staves that are played simultaneously, by one or several instruments
**Part**: a group of staves that are played by one instrument
