### ISSUE TITLE
duplicated lyric syllables in case of chords with more than 1 note head

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#370]
[Kriminaltango.zip](https://github.com/Audiveris/audiveris/files/4370851/Kriminaltango.zip)

In case of lyrics of chords with more than 1 note head, the lyrics are duplicated for each head.

Maybe this comes from the goal to assign lyrics to multiple voices in one note line - this makes sense. But in case a chords belongs to one voice, only one lyrics syllable should appear at this chord.

**Comment by hbitteur** [comment]
Bug fixed in development branch, commit 2da40b52681180d08751fdcdac352f9907889df0
Closing the issue
