### ISSUE TITLE
Is there any function wrapper available?

### ISSUE THREAD

**Issue by keishinz** [Audiveris/audiveris#372]
I'm trying to use the wonderful library in my own software. Really appreciate the contributors.
I wonder is there any function wrapper available for further usage?

I need a simple function that can convert PDF or image into MusicXML data.
Searched Google for information, but cannot get what I want.

Thanks!

**Comment by hbitteur** [comment]
@keishinz 
Have a look at the source code. You will notice that the main class (Audiveris class) is just an entry point that calls org.audiveris.omr.Main class, on its main() method with CLI arguments if any.

Nothing prevents you to call org.audiveris.omr.Main.main() method directly from inside your own code. Perhaps this method can be considered as the "simple function" you need.

Just try.

**Comment by keishinz** [comment]
@hbitteur 
Thank you. I'll give it a try.
