### ISSUE TITLE
wrong note pitches in some clefs

### ISSUE THREAD

**Issue by KannebTo** [Audiveris/audiveris#373]
I noticed wrong note pitches in MXL export from a piece in tenor clef. So i created this test image with some other clefs in MuseScore:
![original](https://user-images.githubusercontent.com/24896645/79116789-a88c9b00-7d89-11ea-9bbb-547818f86f75.png)
Audiveris:
![audiveris](https://user-images.githubusercontent.com/24896645/79116675-6e22fe00-7d89-11ea-86de-e475b44dede9.png)
Audiveris alfer manual cleanup:
![audiveris-edited](https://user-images.githubusercontent.com/24896645/79116718-86931880-7d89-11ea-8d1c-c76e289493c1.png)
MuseScore import:
![musescore-import](https://user-images.githubusercontent.com/24896645/79116763-9b6fac00-7d89-11ea-9f91-a2270b5f6227.png)

There are several problems:
1. I haven't been able to assign the key signature correctly.
2. Some clefs are in wrong position.
3. Some clefs are gone. (may caused by 2.)
4. wrong note pitches in some clefs
5. some rests are y-shifted

Audiveris version: current master (e51dc5f05)

**Comment by hbitteur** [comment]
@KannebTo 
The key signature insertion should work now (please use "development" branch rather than "master").

I think I remember, regarding the C-clef, that only tenor and alto variants are supported. Further investigation is needed.

For the F-clef change, template matching for whole notes has prevented recognition of these clefs by the engine. Replacement of template matching in high on our todo list. For now, manual correction should fix your case.

**Comment by KannebTo** [comment]
@hbitteur 
Thanks for your fast reply.

output with current `development` version (861999d7) in MuseScore:
![audiveris-edited-development](https://user-images.githubusercontent.com/24896645/79137236-9ffc8a80-7db2-11ea-9494-7067b31d96c8.png)

The key signature insertion is working!

Sadly the problem also persists with tenor-C-clef.

**Comment by KannebTo** [comment]
Yesterday i looked at the source code and i found it. Regarding that the other clefs are not supported, the result now represents the expected behavior:
![musescore-import-fix](https://user-images.githubusercontent.com/24896645/79683809-cf851a00-822c-11ea-89fe-c326f477c89c.png)

**Comment by hbitteur** [comment]
So I think this issue can be closed.

**Comment by hbitteur** [comment]
Sorry @KannebTo I had overlooked the fact that there was a PR behind your issue.
I just looked at your fix, and it seems OK.
I will include it later today (I'm in the middle of other modifications, a matter of a few hours).
