### ISSUE TITLE
bracket of triplet detected as ending_wrl

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#375]
in some cases brackets of triplets are recognized as ending_wrls. This can be rather nasty because they are not obviously visible in the output file - e.g. MuseScore simply stops playing, because by default the ending brackets are numbered "99".
Here an example with many wrongly detected endings:

![What a Difference a Day Made 4](https://user-images.githubusercontent.com/33522630/79637951-3d750700-8183-11ea-850a-58369cbac1ff.jpg)

**Comment by hbitteur** [comment]
They do look like ending_wrl (Ending with right leg), that's the problem.
Right now, the OMR engine can detect tuplets but not the related brackets.

So what can we do for this?
- A not too silly aproach would be to forbid ending processing for the sheet at hand.
- Another approach would be to check ending candidates more aggressively: can we impose the ending with right leg to start and/or end precisely on a barline? In your example, this would work correctly.

You are the musician. Please tell me.

**Comment by Bacchushlg** [comment]
[World On Our Shoulders.pdf](https://github.com/Audiveris/audiveris/files/4582239/World.On.Our.Shoulders.pdf)

The same problem applies to rectangles around system texts like "Intro" etc.
The algorithm detect such elements as ending_wrl, too (see this score).

My proposual concerning a good solution is to measure the length of the ending_wrl. Normally it is at least as long as the concerning measure. So, only accept it, if it is - let's say - 80% of the measure that it concerns.

**Comment by hbitteur** [comment]
OK, let's go for a measure-length-based check.

**Comment by hbitteur** [comment]
Done in development branch, commit 2dbe284c9117b57755152e1d55c4d321b13a7c2e
If you want to modify the ratio, you can always modify the constant org.audiveris.omr.sheet.curve.EndingsBuilder.minMeasureRatio which is by default set to 0.8

**Comment by Bacchushlg** [comment]
works perfect now.
