### ISSUE TITLE
Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS...]

### ISSUE THREAD

**Issue by gibsonjoshua55** [Audiveris/audiveris#381]
Trying to get started with audiveris on mac and am running into errors when transcribing a PDF.

![image](https://user-images.githubusercontent.com/10167681/80314878-43419c80-87c2-11ea-8feb-7cb619086f18.png)
I just build audiveris from source today.

I am on mac 10.14.16.

I installed tesseract today through `brew install tesseract` and am only using the included English language.

```
$ tesseract --version
tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.2.1 : libjpeg 9d : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 1.1.0 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
```

```
$ javac -version
javac 1.8.0_231
````

Thanks for any guidance!

**Comment by hbitteur** [comment]
I can't read from your messages which Audiveris version you are using, but the current official release requires Tesseract 3.04 (not Tesseract 4.x).

Have a look at issue #297 
And see also this recent comment: https://github.com/Audiveris/audiveris/issues/374#issuecomment-616152176
