### ISSUE TITLE
Cross notes initially detected are removed in step reduction

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#384]
![WiseGuys - Radio8](https://user-images.githubusercontent.com/33522630/81503926-b11fb500-92e6-11ea-8863-ad4e0cc15ec4.jpg)

In this score most of the cross note heads were properly detected, but then most of them are removes during step reduction. But why?

**Comment by hbitteur** [comment]
Before the REDUCTION step, any item (head, stem, beam, ...) which has been assigned a minimum recognition intrinsic grade (0.1 IIRC) is kept for further analysis, allowing other items to be later recognized and may be have either a support relationship  or an exclusion relationship with this item. A support relationship increases the contextual grade of the inter involved, depending on several parameters such as  the quality of the geometric connection, etc. An exclusion relationship is recorded for later reduction step.

At end of STEM step (the step right before REDUCTION), all contextual grades are computed and can be displayed in UI. For example click on a note head, the inter board will give you 2 values in the grade field: intrinsic / contextual. You can also select several inters with a lasso, and a right click will present all the items, ordered top down by decreasing contextual grade.

REDUCTION step simply uses these contextual grades, and a bunch of tests, to decide which inters survive in this struggle for life. The rules are simple: any inter with a low contextual grade (0.5, IIRC) is discarded, and in a mutual exclusion between two surviving inters, only the higher contextual grade survives.

Here, I flagged one cross-head as VIP (you can do so in the inter board), before launching the reduction step, and I got:
> [Issue-384] VIP deleted weak HeadInter{#1451(0.174/0.265) stf:5 NOTEHEAD_CROSS p:-1.00}

The intrinsic grade was low, but above the minimum required at creation (0.174 >= 0.1). The cross head was correctly connected to a stem, raising its contextual grade from 1.74 (if alone) to 0.265. That was not enough to reach the minimum required at reduction step (0.265 < 0.5).

**Comment by hbitteur** [comment]
Cross-heads generally get low intrinsic grades because current template matching algorithm performs badly on these shapes.

**Comment by Bacchushlg** [comment]
Maybe you can "push" the cross heads a bit to a better value when you find it connected to a stem - just because you know about the general bad recognition? Just an idea...

**Comment by hbitteur** [comment]
Yes, we can "cheat" a bit. This is sometimes called "positive discrimination", right?
I will implement this and, via an application constant, you'll be able to adjust the value. Let's try that.

**Comment by hbitteur** [comment]
Done in today's commit 238bb2cd5d8a6ca0e122ad678f21f6a4ab09a7d5

A cross head score is "boosted" according to the application constant org.audiveris.omr.sheet.note.NoteHeadsBuilder.crossBoost whose default value is 0.35, roughly meaning that the score raw value is raised by 35%.
With this default value, all the cross heads in your example are now recognized.

You can of course change this constant on your own, but beware of collateral damages if you set it too high: all head candidates will turn as cross heads!

**Comment by Bacchushlg** [comment]
Almost perfect. But I found out that boost factor 3.5 is much too high.
Trying some other scores, I found 0.1 as best factor, giving only few false hits but finding almost all real ones.
So, please use 0.1 as default factor.

**Comment by hbitteur** [comment]
Done
