### ISSUE TITLE
Export selected pages?

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#387]
Hi...

Is it possible to tell Audiveris to export only some selected pages of a book?  Suppose the book has 10 pages.  If I do Step -> Page, and then export Sheet, I can export one desired page, say page 1...  But suppose I want to export pages 1 and 2 and leave the other pages unexported and untranscribed...

Thanks,

Rodolfo

**Comment by Bacchushlg** [comment]
You can invalidate the sheets that you don't want to be exported. Then "export book" and you get want you want.

**Comment by rodolfo-medina** [comment]
thanks...  but that seems to be definitive and impossible to get back...?  I mean, suppose I want Audiveris to export now pages 2, 3 and 4 and, say, tomorrow pages 2, 3, 4 and 5...?  and the day after tomorrow all the 10 pages...?  would that be possible?  thanks

**Comment by Bacchushlg** [comment]
This is definitely not a task of Audiveris, but of a notation program (e.g. MuseScore).
But you could get an approach to your demand by saving the omr-File under a different name. So you keep e.g. the complete score under the original name and the extracts under different names (or you don't save the extract omr-s at all...)

**Comment by rodolfo-medina** [comment]
fine...  thanks

**Comment by gorgobacka** [comment]
There is a similar issue for selecting only specific pages during PDF import: #232. I also think this or the other feature would be a great addition for working with whole songbooks.

**Comment by hbitteur** [comment]
Could we try to formalize these features?

Supposing we have a 20-sheet PDF input:

1. **Import**: Which sheets should be loaded and transcribed? We already have the ability to "invalidate" some sheets. But perhaps, the other way around, we could explicitly tell which sheets to process. If so, should we record this information in the book itself, so that the next time the book is loaded, the same set of sheets are considered by default (I'd personally choose this approach).
2. **Export**: Which sheets should be exported? This may be the set of "considered" sheets as defined above, or a subset of these. Here again, should we record this information (which sheets to export) in the book itself? Perhaps not. Either way, the user should always have the ability to select some specific sheets for export at any time, and change the set at any time as well.

Please help me converge on some sort of specifications.

**Comment by hbitteur** [comment]
Regarding the plugins (calls of external programs running on Audiveris export), we could consider that we reuse the last selected set of sheets to export.
This adds a reason to record this set in the book itself.

**Comment by Bacchushlg** [comment]
I agree about **import**: In #129 I already asked for the possibility to add single page into an existing book. Also remove a page can be interesting (plus insert): Sometimes I have a multi-page score where one the the pages is of bad quality. So, remove, edit, re-insert can help in such cases.

About **exporting**: from my opinion there is no real need to spend much work in this: this can really be done in a notation program...

**Comment by rodolfo-medina** [comment]
I agree with 'export'.  In the attached document I must expurge the last two pages otherwise the output is corrupted.  To do so, I have to invalidate pages 9 and 10, export the book and remember not to save it; then close it and reopen it again to try to eliminate the problem.  If by mistake I save the book, the pages remain invalidate forever...

[verdi-caro_nome.zip](https://github.com/Audiveris/audiveris/files/4677791/verdi-caro_nome.zip)

**Comment by hbitteur** [comment]
@Bacchushlg 
What do you mean by "add single page into an existing book"?
Does the image of this page come from outside the book input file? (like growing a book?)

**Comment by Bacchushlg** [comment]
Yes, I did mean this.
Originally I started with transcription page by page. The disadvantage of this way is:

- the following pages have no information about the rhythm signature
- separate exports with changing rhythm signature loose their signature when added to an existing score in MuseScore
- the same problem concerns line and page breaks

So in the last time, I always create a TIF or PDF from my scanned images. But then I get sometimes the problem described above: one of the pages is of bad quality. Damn if I have already transcribed (with some manual editing) the first pages. So, a deletion of this page and re-import of an edited page (at the same position in the book) would be wonderful.

**Comment by hbitteur** [comment]
Partial processing (including export) is now possible by defining a selection of sheets. So #443 is now closed.

I'm keeping the #129 for the ability to "replace" a sheet by some external one (supposedly of better quality) in one action.
Or by removing and then inserting a sheet (in two separate actions).

Closing this one.
