### ISSUE TITLE
Area extraction

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#389]
Hi...

I select a certain area by dragging the mouse while keeping the
SHIFT key pressed ando so producing a rectangular "lasso".  Then

 right click -> Extraction

and it says: "Whole sheet" no area selected.  What am I missing?

thanks...

**Comment by Bacchushlg** [comment]
see handbook, **Extraction**:

Extracts a rectangular portion (or whole) of the underlying binary image and save it to disk. This is meant for sharing or further analysis.
Limitation: The rectangular area selection is effective only from the **Binary** tab, not from the Data tab.

**Comment by rodolfo-medina** [comment]
All right, thanks...  But what I mean is showing a portion of Data tab to other people for discussions, as done for example in #379 by hbitteur...

**Comment by Bacchushlg** [comment]
make a screenshot, paste into a image editor (e.g. irfan view, xnview, gimp,...) extract the part of the image that you need and copy-paste e.g. to the issue tracker.

**Comment by rodolfo-medina** [comment]
Maybe this could be another possible future enhancement: extraction also in the Data tab...

**Comment by hbitteur** [comment]
I personally use **Greenshot image editor**, a free utility, very useful to take snapshots, edit them and insert the result in HandBook document.

Let's keep focused on Music transcription.
I hate re-inventing the wheel.
Please!...
I'm closing this issue.
