### ISSUE TITLE
RYTHMS and PAGE failing

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#392]
Hi...

The attached two-measure extract won't complete its transcription process although each measure separately properly does...  Why...?  

![test](https://user-images.githubusercontent.com/64352612/83759109-9977ea00-a662-11ea-8264-9a6ff520ad58.png)

All my efforts to repair it didn't succeed...  The xml output is corrupted.  Please help...  Here's my last updated omr file:

[test.zip](https://github.com/Audiveris/audiveris/files/4730343/test.zip)

thanks

rodolfo

**Comment by rodolfo-medina** [comment]
...I tried very hard to repair it but didn't manage to...

rodolfo

**Comment by Bacchushlg** [comment]
please upload the complete page. 
This extract cannot be transcribed, because it lacks the system information on the left (key, clef)

**Comment by rodolfo-medina** [comment]
But this other even smaller extract also lacks of key and clef information but is regularly transcribed:

![test2](https://user-images.githubusercontent.com/64352612/83795780-82032600-a68f-11ea-99a1-08c9af94dea2.png)

This is the whole page:

[seidler-es6.pdf](https://github.com/Audiveris/audiveris/files/4732095/seidler-es6.pdf)

I know it's quite poor...

thanks...

**Comment by Bacchushlg** [comment]
well... This is really nothing that can be managed by Audiveris.
Especially the bottom part is unreadable.
Sorry, but I don't see a way how to transcribe such an image

**Comment by rodolfo-medina** [comment]
I'm new to Audiveris, only a few weeks old.  I see that in this case the PDF input is very very bad so Audiveris doesn't manage - neither could it ever do - to transcribe it.  But more in general, when the transcription process fails upon a certain PDF, is it possible - in some cases - after hard work - to have the transcription be completed...?  If so, in this particular difficult case, would it be possible in theory - although uconvenient in practice - after a long long work, starting patiently to add system lines at the bottom - to get Audiveris complete the transcription process...?  I'm asking this to better understand how Audiveris works...  thanks for creating and developing such a wonderful tool...

**Comment by Bacchushlg** [comment]
Yes it is. I have performed the transcription of a lot of "bad" scans using Audiveris.
But in cases like yours above I found out that it is easier to directly input the score into a notation program (I use MuseScore for this).
