### ISSUE TITLE
[New feature] Editing time slot fractions

### ISSUE THREAD

**Issue by oleedd** [Audiveris/audiveris#395]
![image](https://user-images.githubusercontent.com/36125949/84359092-ca12d300-abd0-11ea-8878-705dcc24d8ea.png)

**Comment by hbitteur** [comment]
???

**Comment by oleedd** [comment]
You see that there are incorrect/excess fractions on the image. How to edit/delete them? Seems that no such feature.

**Comment by hbitteur** [comment]
Not exactly.

This example shows two time slots (too) close to each other, hence their displayed offset values overlap.

The problem is not to edit the slots values, but to come up with correct slots.
You can do this by adding/removing entities and/or forcing same/separate time slots between chords.

**Comment by oleedd** [comment]
>forcing same/separate time slots between chords

How to do this?

**Comment by hbitteur** [comment]
You select one head of a chord and one head of another chord and open the popup menu via a right click.
There you should have a "Chords..." sub-menu, with the ability to split/merge slots and voices.

More information will be available in the new handbook I'm working on. A first version should be visible in one week or so.

**Comment by oleedd** [comment]
Oh, it can't help because many problems just with incorrect fractions. I thought it is about time signature time slots...
>adding/removing entities

Yes, but it is very long if there are many elements (especially voices) and measures. And need good luck to catch the correct result. No success in my case.
Editing is the most powerful way and it shouldn't be hard to implement.

**Comment by oleedd** [comment]
Also you can see that there are 1/1 + 4/8 fractions. It is not theoretically possible. After 1/1 should come 9/8 (but 1/1 isn't correct).

**Comment by hbitteur** [comment]
Yes the result is not correct, that's why the measure background is displayed in pink, to call user attention on it.

**Comment by oleedd** [comment]
By this I meant that the algorithm shouldn't give theoretically impossible (in order of digits) results. So this should be the biggest priority and will lead to the correct result.
The sense of "theoretically impossible results" is just decreasing time slot fractions.

**Comment by oleedd** [comment]
Do you agree?

**Comment by oleedd** [comment]
So can you please implement editing of fractions?

**Comment by hbitteur** [comment]
Current model is to arrange chords according to their own duration and to the relations with the other chords (are they located before, or at the same time offset, or after).
This results in a sequence of time slots, a time slot is basically a time offset since measure origin, and the set of chords that start at this time slot.

In other words, chords and their relations are the input and slots are the output.
The end user can modify chord duration and chord relations, this results in different time slots.
Not the other way around.

**Comment by oleedd** [comment]
In difficult cases, the algorithm gives totally incorrect time slot results.
In such cases, the only reliable way is to retype all wrong measures from zero. But such programs exist for the opposite reason (replace retype).
So editing of fractions is very important feature. Please add it.

**Comment by oleedd** [comment]
If it can't work together with auto analysis - you can just off auto analysis for the current measure.

**Comment by oleedd** [comment]
Why do you wontfix? After editing the rhythm analysis (which goes after inserting/deleting a note) may be disabled.
The thing is incorrect rhythm breaks export. All things should be editable. Now it remains to add only time slot fractions.

**Comment by oleedd** [comment]
Please explain why?

**Comment by oleedd** [comment]
The problem is in the following: The time slot issues are the most critical (because other things can be fixed manually). But you are not going to fix them quickly. Users can't wait several years for that. So there should be some instrument for time slots.

**Comment by hbitteur** [comment]
I already explained to you why Audiveris end user doesn't interact directly with the time slots but with the chords and the relations between them. Time slots are just the results of the sorting of chords within a measure.

You can think that Audiveris model should work the other way around, fine!
Feel free to investigate another approach and propose a suitable implementation.
Audiveris is an open-source project, the whole code is available, you are free to use it, to modify it, etc, according to the AGPL licence.

Just do it!

**Comment by oleedd** [comment]
I don't know Java to do it.
>Time slots are just the results of the sorting of chords within a measure.

If to change the result - the sorting should become correct. There should be a way to help the algorithm to make the correct sorting.
Also I propose an option to mark time signature slots. For example (4/4):
![image](https://user-images.githubusercontent.com/36125949/84779496-23be3780-afed-11ea-8ac8-1c3099d5ecd3.png)
And the algorithm will solve these 4 parts knowing the correct beginning fraction of each of them. I think it is the best way.
