### ISSUE TITLE
impossible to add triplet to the concerning note heads manually

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#397]
![Somewhere over the Rainbow - mit Klavier](https://user-images.githubusercontent.com/33522630/84595687-8e3e6e80-ae59-11ea-828e-3c512ca8de5e.jpg)

In measure 7 of this score there are triplets in all voices.
As often, the triplet for the bottom note line is only notated once. This is normally no problem, I just add a 2nd one to the lower voice using drag-n-drop.
Unfortunately this is not possible in this case, because drag-n-drop never finds the correct assignment for the note heads. It always "takes" the two middle note heads plus one from left or right.
The triplet algorithm should look for the voices when trying to connect. It should not mix the voices.

A similar problem applies to measure 12, bottom note lines. I find no solution how to properly place the triplet.

Maybe a "simple" solution could be drag-n-drop the "3" to the concerning chords, while "killing" the "oldest" one, until the triplet is connected correctly.

**Comment by hbitteur** [comment]
Yes, there is a bug in the automatic selection of chords involved by a tuplet: Two chords that share a note head should not be both involved. I'll fix this.

Meanwhile, you can manually correct the situation:
- 1/ Drag from the triplet to the missing chord
- 2/ Now there are 4 chords linked to the triplet, so use the Inters/Relations popup menu to remove the unwanted relation.

I just did this on your two measures. Granted, it's a bit awkward, but it works.

**Comment by hbitteur** [comment]
Bug now fixed via commit 39e8b5cfa29a517a63d400790381e6ac6f3bd8bc

In fact, beyond chords with share heads, we now filter out chords that overlap horizontally, to keep only the relevant ones for tuplet links.

Issue now closed.
