### ISSUE TITLE
Half(void) & 1/8 notes 

### ISSUE THREAD

**Issue by otradovec** [Audiveris/audiveris#398]
Hi,

I would appreciate advise on how to improve 1/2 and 1/8 note recognition. Audiveris does grat job for 1/4 notes but 1/2 and 1/8 make me sad. :-( The halves are usualy recognized/classified but eliminated in reduction.
![image](https://user-images.githubusercontent.com/59257907/84940017-84c63800-b0df-11ea-8541-dc8484fc4fc7.png)

**Comment by otradovec** [comment]
I still dont know what to do with the 1/2 notes, but 1/8 improved after sampling flags+retraining classifier. But what with the halves? They dont get sampled...

**Comment by hbitteur** [comment]
@otradovec 
Let me shed some light on this.
Audiveris engine uses different recognition techniques according to what it tries to detect.
- In HEADS step, it uses template matching recognition. This classifier uses descriptors for each shape to recognize, based on typical music font and staff interline. Results are generally OK, but rather poor on heads with holes (half heads, whole heads). You cannot train this classifier via samples.
- In SYMBOLS step (where flags are recognized, among many other shapes), a neural network is used. And it's true that you can train it on additional samples with good results.

In REDUCTION step (run after HEADS step), heads, stems and beams are "reduced" to resolve all conflicting interpretations and discard weakly recognized entities (typically any inter with contextual grade lower than 0.5 gets discarded!). Your weak halves may disappear there.

In LINKS step (run after SYMBOLS step), after all links (relations) between inters are established and conflicts resolved, weak inters (such as a weak flag) are discarded. So, your weak flags (needed for 1/8, 1/16, ... notes) may disappear there. But like I said, additional training is available and may help you here.

**Comment by otradovec** [comment]
Thanks for reply @hbitteur.
So is there any way to boost void heads grade, so they dont get reduced? Or some way to change template matching recognition?

**Comment by hbitteur** [comment]
We can cheat of course! :-) We can artificially slightly boost the score of void heads, but with the risk of increasing the number of false positives. It's doable but risky. Don't bet too much on this.

Regarding template matching itself, I think we have done all that was possible.
We are considering to replace template matching with totally different approaches, but we haven't got convincing results yet.

**Comment by otradovec** [comment]
So is there any setting parameter to "slightly boost the score of void heads"?

**Comment by hbitteur** [comment]
I think there is no direct parameter to do this. We would have to insert this into code.
