### ISSUE TITLE
Black note heads without stems

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#399]
Hi...

the attached score includes black pitches without stems, and they don't seem to be detected at all...  neither does it seem possible to insert them by hand...  no possibility at all...?

thanks

[arvo_part-fuer-alina.pdf](https://github.com/Audiveris/audiveris/files/4806566/arvo_part-fuer-alina.pdf)

**Comment by rodolfo-medina** [comment]
Hi, hbitteur...  no solution at all for this problem...?  thanks...

**Comment by hbitteur** [comment]
@rodolfo-medina 
Are you serious?
This is not "standard notation" for music:

1. Black heads have no stem at all (I mean: this is not a matter of image quality, there is absolutely no stem).
2. There is no time indication, and there is no way to infer any "implicit" time signature, since measure duration changes from each measure to the next (assuming black heads stand for quarters, and large void heads for wholes).

Audiveris has enough hard time to transcribe standard notation on some scores, and I'm in the process of improving its behavior on really poor-quality scores.

But I have no time to waste on this kind of "pseudo-notation".
Sorry.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.

**Comment by rodolfo-medina** [comment]
Sorry, I didn't imagine...  The score is a very famous one from a great contemporary composer...  I really didn't know the notation was so out of standard...  I'm not expert on that side...  Thanks.
