### ISSUE TITLE
"Drop point lies beyond sheet limits"

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#401]
The last system (last 5 measures) of the attached score is not properly exported.  Any attempt to repair left hand produces the error "Drop point lies beyond sheet limits".  Please help.  Thanks.

[jensen.zip](https://github.com/Audiveris/audiveris/files/4815430/jensen.zip)

**Comment by hbitteur** [comment]
Since commit a28c84b0f7c37c49d5e62c398a7cf1a2cad83725, manually inserted quarter notes are now directly linked to beams nearby.

Closing.
