### ISSUE TITLE
High quality PDFs converted to lossy binary before transcription

### ISSUE THREAD

**Issue by tjdickinson** [Audiveris/audiveris#403]
I've been using Audiveris to create .mxl files of a high quality PDF score (see example, attached). The score was probably exported from a professional sheet music software, which means everything is sharp and clear. But when I open the PDF in Audiveris, the binary image is very lossy and results in a poor transcription (and I have to do loads of correcting). Is there any way to prevent this loss of quality when opening a PDF?

[5 My Master Is Punctual.pdf](https://github.com/Audiveris/audiveris/files/4837406/5.My.Master.Is.Punctual.pdf)

**Comment by odelphi** [comment]
There is an option setting "DPI resolution for PDF images".  The default value is 300 which is pretty high.  However, you can increase it. Don't know if this will help.  Keep in mind the file size will explode and scanning will take longer.  Also you many come up against memory issues if you go higher than about 400.

**Comment by hbitteur** [comment]
Testing your input image with latest Audiveris version, I can't see significant problems, at least on page 1, the one I just tried.
There are about 10 slurs (wrongly) detected on staff lines, simply point on each and delete.
Also a sharp and a natural signs were not detected.
That's all.
