### ISSUE TITLE
The Audiveris.bat cannot find java.exe

### ISSUE THREAD

**Issue by NelDav** [Audiveris/audiveris#404]
The problem is that the batch script check if the executable `$JAVA_HOME$/bin/java.exe` exists.
Im am not sure, if that is the regular location of java.exe. In my case the directory of java.exe is `$JAVA_HOME$` itself.

So I had to remove `/bin` from the path.

**Comment by hbitteur** [comment]
@NelDav 
I confirm that java.exe is supposed to be in the bin subdirectory of java home.
See my config:
``` bash
$ which java.exe
/cygdrive/c/Program Files/Java/jdk-11.0.3/bin/java.exe

$ echo $JAVA_HOME
c:/Program Files/Java/jdk-11.0.3

$ cd "$JAVA_HOME"

$ pwd
/cygdrive/c/Program Files/Java/jdk-11.0.3

$ ls -l
total 133
drwxrwx---+ 1 SYSTEM SYSTEM    0 May 25  2019 bin
drwxrwx---+ 1 SYSTEM SYSTEM    0 May 25  2019 conf
-rwxr-x---+ 1 SYSTEM SYSTEM 3244 Apr  2  2019 COPYRIGHT
drwxrwx---+ 1 SYSTEM SYSTEM    0 May 25  2019 include
drwxrwx---+ 1 SYSTEM SYSTEM    0 May 25  2019 jmods
drwxrwx---+ 1 SYSTEM SYSTEM    0 May 25  2019 legal
drwxrwx---+ 1 SYSTEM SYSTEM    0 May 25  2019 lib
-rwxr-x---+ 1 SYSTEM SYSTEM  160 May 25  2019 README.html
-rwxr-x---+ 1 SYSTEM SYSTEM 1285 May 25  2019 release

```

Perhaps you should reinstall Java from scratch.

**Comment by NelDav** [comment]
I will have a look on a second PC soon.

**Comment by Mic31490** [comment]
I try to open AUDIVERIS on PC Win10 64bits and the résult (using powershell to keep messages)
is :

![Annotation 2020-07-20 164517](https://user-images.githubusercontent.com/68589551/88061982-849adb80-cb68-11ea-9b97-715d2fb80877.png)

Thank you in advance for your help

**Comment by hbitteur** [comment]
You have an architecture mismatch (32 vs 64 bits) between your Java environment and the binary you downloaded.

**Comment by NelDav** [comment]
> 
> 
> You have an architecture mismatch (32 vs 64 bits) between your Java environment and the binary you downloaded.

I checked your suggestion, and I am pretty sure that I do not have an architecture mismatch.

I used the `Audiveris_Setup-5.1.0-windows-x86_64.exe` executable to install Audiveris. Because of that I think, that I installed the 64-Bit version of  Audiveris.

I checked the architecture of my java environment as well. It is a 64-Bit architecture:

```powershell
PS> java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```
