### ISSUE TITLE
Error when executing program

### ISSUE THREAD

**Issue by odelphi** [Audiveris/audiveris#407]
I get two error messages when executing the Audiveris program

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnilept in java.library.path
After a few more lines I get:
Caused by: java.lang.UnsatisfiedLinkError: no liblept in java.library.path

The program ends and nothing happens.  I checked my java installation and I have the latest version.
I did a search in my Java installation for those two files and, sure enough, the program is right.  I do not have those files.

**Comment by odelphi** [comment]
UPDATE:  I looked at other posts and learned that Java is 32 bit but I downloaded the 64 bit version.  After installing the 32 bit version,  It works.  Now (cross my fingers) the scan works.

**Comment by hbitteur** [comment]
So, we can close the issue
