### ISSUE TITLE
Can't see errors in my score

### ISSUE THREAD

**Issue by odelphi** [Audiveris/audiveris#408]
I have three measures that are in Pink (have errors) and I cannot see any errors.  I have checked, and checked and triple dog-dare checked and nada.  Can't get the pink to go away on these three measures.  Problem is, when I import into Musescore those measures have all kinds of transcription errors and musescore will not import the measures AFTER these measures.  Is this an issue with the program that sometimes it thinks there are errors in a measure when there are none?  Included the measures as an attachment, dunno if this will help.     Thanks
![Music with errors](https://user-images.githubusercontent.com/52181093/87215559-56fa9a80-c2fd-11ea-9134-b3f3c0dda8ad.png)

**Comment by odelphi** [comment]
UPDATE:
I am wondering if the issue I mentioned in previous post has something to do with voices.  In this attachment I have the voices turned on.  As you can see,  the staff above the rose colored measures shows the two voices.  However, in the rose-colored measures some notes are still green (dont know what that means) and I don't think that is a coincidence.  Also, you can see the final staff, all the notes are green.  These are that measures that I cannot get to import into musescore.
Does this mean anything - notes that do not shows their voices?
![Music with errors 2](https://user-images.githubusercontent.com/52181093/87231383-6ec53380-c37c-11ea-8cfb-f4b76d29c767.png)

**Comment by odelphi** [comment]
I am noticing that when I do a "Reprocess rhythm" on the measure that has the cyan and dark green notes (1st and 3rd pink measures), I get these messages.  
INFO  []              SlotsBuilder 371  | S6 MeasureStack#18 Slot{#4 xOffset=115 timeOffset=1/4 incomings=[#11411] SUSPICIOUS}
INFO  []              SlotsBuilder 378  | Stack#18 endless loop detected
If I reprocess rhythm in a measure that only has cyan notes (middle pink measure),  I get these messages:
INFO  []              SlotsBuilder 371  | S6 MeasureStack#17 Slot{#8 xOffset=279 timeOffset=3/8 incomings=[#9099] SUSPICIOUS}
INFO  []              SlotsBuilder 371  | S6 MeasureStack#17 Slot{#11 xOffset=366 timeOffset=1/2 incomings=[#9100] SUSPICIOUS}
INFO  []              SlotsBuilder 371  | S6 MeasureStack#17 Slot{#14 xOffset=459 timeOffset=5/8 incomings=[#9101] SUSPICIOUS}

**Comment by hbitteur** [comment]
If you have set the "colored voices" option, then the various musical elements for which a voice is known will be displayed using the voice color.
Color is based on voice number, as recalled by the small panel at top center of Audiveris main window.
![image](https://user-images.githubusercontent.com/22053634/87292439-18353200-c501-11ea-9b07-7bec6aee67a0.png)
It gives the colors for voices in upper staff (1,2,3,4) and for the lower staff (5,6,7,8).

Within a measure, time slots and voices are determined in sync, starting from the beginning of the measure to its end.
If some error is detected, this computation stops here for the measure at hand. Hence, when voices color disappear, it's here that the problem occurred.

**Comment by hbitteur** [comment]
In your example, you can observed this phenomenum in: 
![image](https://user-images.githubusercontent.com/22053634/87295042-e7ef9280-c504-11ea-8525-690e1a33dd3f.png)
I cant' hardly see, but I suspect there should be a double beam for the notes on second staff, while it seems you have just one beam. The notes are then taken for 8th notes  while they should be 16th notes.

If so, the engine cannot vertically align these notes (that should be 16th notes but are mistaken for 8th notes) with the true 8th notes of the staff above. So it stops here.

Could you have a closer look at this?

**Comment by odelphi** [comment]
hbittuer, you are right.  I can see where the 16th note can be mistaken to be 8th notes.  However,  as you know I cannot decide what note value goes there.  The program automatically puts one beam rather than two, if it sees just one beam.  Oddly, beams is the only glyph, you cant place yourself.  You have to rely on the program to KNOW what to place.   An enhancement would be to allow the user to decide what goes there, not the program.
