### ISSUE TITLE
Build freeze on MouseWheelTest

### ISSUE THREAD

**Issue by jfvigneron** [Audiveris/audiveris#41]
Hi,

On MacOS 10.13.2 I try to build with Terminal and with XQuartz but the build process freeze on MouseWhellTest. It display nothing.. What it is suppose to display ? A box to tests the MooseWheel ?

org.audiveris.omr.ui.symbol.MusicFontTest > textPrintout FAILED
    java.io.FileNotFoundException at MusicFontTest.java:75
<==========---> 81% EXECUTING [15m 42s]
> :test > 4 tests completed, 1 failed
> :test > Executing test org.audiveris.omr.ui.MouseWheelTest

**Comment by maximumspatium** [comment]
Can you run `java -version` and `gradle -v` in your terminal and post the result here?

**Comment by scbrady** [comment]
I have the same problem as well.

`java -version`
```
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

`gradle -v`
```
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2017-12-20 15:45:23 UTC
Revision:     10ed9dc355dc39f6307cc98fbd8cea314bdd381c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          9.0.4 (Oracle Corporation 9.0.4+11)
OS:           Mac OS X 10.13.2 x86_64
```

**Comment by webfischi** [comment]
I'll get the same problem as well
`> Task :test`

```
org.audiveris.omr.ui.MouseWheelTest > play FAILED
    java.lang.NullPointerException at MouseWheelTest.java:102

186 tests completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
```

`java -version`
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

`gradle -v`
```
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2017-12-20 15:45:23 UTC
Revision:     10ed9dc355dc39f6307cc98fbd8cea314bdd381c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Windows 10 10.0 amd64
```

**Comment by maximumspatium** [comment]
Hello Scott,

I can only repeat what the section [Building and running](https://github.com/Audiveris/audiveris/blob/master/README.md#building-and-running) of our README.md says about the required JDK:

_version 8 is recommended; **version 9 is not yet supported**_

So JDK 9 isn't supported yet. You'll need to install JDK 8. We're currently busy with preparing the 5.1 release that will bring a much better UI. We plan to support JDK 9 in a future release. For the time being, it's not on our priority list. Sorry for that!

**Comment by maximumspatium** [comment]
@webfischi

Did you try `grade clean run` ? I'd recommend to try out the development branch because it contains the latest changes.

**Comment by webfischi** [comment]
It just happens that there was a Java Update available. With `build 1.8.0_161-b12` it finished without an error.

**Comment by scbrady** [comment]
@maximumspatium Thanks for the reply, I tried with version `1.8.0_102-b14` first, got that error, then updated all the way to version 9.

I had a really old version of java 8, so updating that along with installing Tesseract worked. That's what I get for not reading the docs carefully. Thanks!

**Comment by maximumspatium** [comment]
Closing because the original issue seems to have been resolved.
