### ISSUE TITLE
Retrieving the systems' coordinates

### ISSUE THREAD

**Issue by luisfvc** [Audiveris/audiveris#412]
Hi,
I would like to use Audiveris to extract only the systems' coordinates from a sheet image, e.g. [(x1, y1),..., (x4, y4)] for each system. I know I can get this from the resulting .xml file by reading the nodes "system layout" and "staff layout". However, is the a way to make it easier? When I try to run it via CLT and process until the step GRID, I get an error. I run the following command:
`Audiveris -batch -step GRID -export -output "folder/" -force -- "score.png"`
and get the following error:
![image](https://user-images.githubusercontent.com/47660358/87688782-b20e1080-c787-11ea-8e57-e1a7062b2911.png)
When I run without the `-step GRID` argument the transcription works fine, however the score is processed until the last step, which is time consuming and not necessary for my purposes.

Moreover, is there a way of handling it in a way I don't even need to create an xml file and read from it? For example accessing the system coordinates directly from one of the classes that are being instantiated?

Regards,
Luis

**Comment by hbitteur** [comment]
Export (to a MusicXML file) implies to run all steps.

If I were you, interested only in system and staff coordinates, I would go through the .omr file directly (it's just a zip archive).
And in the the sheet#N.xml file, which is a plain XML file, anybody can read the `<system>`, `<staff>` and `<line>` elements, giving the precise coordinates you are were looking for.

Documentation on internal .omr project file is available in [Audiveris Wiki section](https://github.com/Audiveris/audiveris/wiki/sheet%23N-xml).
Granted, this doc is not up-to-date but good enough for your simple needs.

Closing this issue...
