### ISSUE TITLE
Error when getting the GRID step - no system lines to build NO_STAFF buffer

### ISSUE THREAD

**Issue by luisfvc** [Audiveris/audiveris#413]
Dear community,
I am having troubles to reach the GRID step of some documents I have. Apparently Audiveris is failing to detect the staff lines. I attached as an example three score images: the 01 and 02 images are processed with no problems (staff and bar lines are correctly detected) but image 03 fails at this step. They have the same resolution and come from the same book. Any idea why processing until the GRID step works for the 01 and 02 but not for 03?
I understand that the resolution is quite poor, but unfortunately that's the data I have to work with.

Thanks and regards,
Luis

[scores.zip](https://github.com/Audiveris/audiveris/files/5040464/scores.zip)

**Comment by hbitteur** [comment]
@luisfvc 
Which Audiveris version are you using? Perhaps the 5.1 installed by the Windows installer.

I just tested your 3 sheets with latest version of "development" branch (5.2.1-alpha) and the GRID step worked correctly on all of them.
So I would suggest to clone and build from this development branch. At least until the coming 5.2 is officially released.

**Comment by luisfvc** [comment]
I was using version 5.1 on Ubuntu which I cloned and built from the "master" branch. Following your suggestion I switched to the "development" branch and it worked correctly indeed, thanks!

However, interestingly some scores which were almost flawlessly processed until GRID before (master) now fail by using the 5.2.1-alpha version, for instance the ones I have attached to this message. Maybe it could be interesting to investigate why they fail.

Thanks and regards,
Luis

[more_scores.zip](https://github.com/Audiveris/audiveris/files/5051811/more_scores.zip)

**Comment by hbitteur** [comment]
Different behaviors between current version and the "official" release were related to the additional support for 1-line, 4-line and 6-line staves, on top of the standard 5-line staves. Code of GRID step had been strongly modified for this.

I have just pushed this commit e73f23e9ee45536ed798a2a3eaa991a7cb40d907 to fix the code based on your cases. 
Please pull and rebuild.

All your examples (old & new) are now OK with grid step, if we except the beginning of staff 10 in 02.png (in more_scores archive).

On this staff part, there are simply not enough visible staff line portions to reliably extrapolate staff lines. 
![image](https://user-images.githubusercontent.com/22053634/89902757-22714b80-dbe7-11ea-89e9-253656189f81.png)

Staff 10 is the lower staff on the picture above which displays available "long" horizontal chunks, on which staff candidates are built.
In this precise example, we have two problems: many staff line pixels are simply missing (really bad image quality) or are hidden by crowded note heads.

**Comment by luisfvc** [comment]
Thank you for the fix in the code, I have rebuilt it and it works on the examples I attached.

In the last couple of days I've been testing both master and development branches on my scores and I indeed noticed some different behavior regarding the GRID step. Sometimes all systems are correctly detected with the 5.1 version, but not with the development one.

In case of interest in these cases, the attached scores exhibit this behavior: the first system of both of them are detected as if they were multiple systems with the development version, but correctly with the master one.

Thanks and regards,
Luis

[scores_grid_issue.zip](https://github.com/Audiveris/audiveris/files/5057770/scores_grid_issue.zip)

**Comment by luisfvc** [comment]
As an appendix of my previous message, for the following score page (good image quality this time) something weird happens while processing the 5th system with both dev ans master versions, I couldn't figure it out yet.

[07_rsz.zip](https://github.com/Audiveris/audiveris/files/5058200/07_rsz.zip)
