### ISSUE TITLE
could not determine java version

### ISSUE THREAD

**Issue by ca3games** [Audiveris/audiveris#414]
Hi, I'm using Lubuntu and when I make the following command: sudo ./gradlew clean build

It returns this.
```

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.7'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Already have SDK installed with gradle version 6 and java version 11 and the opendjk version 11.

**Comment by Sunny090628** [comment]
try java version 8.

**Comment by ca3games** [comment]
@Sunny090628  already have install openjdk-8, same error.

**Comment by EkanshdeepGupta** [comment]
> Hi, I'm using Lubuntu and when I make the following command: sudo ./gradlew clean build
> 
> It returns this.
> 
> ```
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine java version from '11.0.7'.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> ```
> 
> Already have SDK installed with gradle version 6 and java version 11 and the opendjk version 11.

I am having the same issue. I have the following:

    openjdk 11.0.8 2020-07-14  
    OpenJDK Runtime Environment 18.9 (build 11.0.8+10)  
    OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10, mixed mode, sharing)

**Comment by EkanshdeepGupta** [comment]
Actually, I managed to fix the issue by switching to Java 8. I use Fedora so I used to following link: https://tecadmin.net/install-java-on-fedora/

**Comment by hallvors** [comment]
I have the same issue:

* What went wrong:
Could not determine java version from '11.0.8'.

I think this is an issue with the Gradle build tool. I note that Audiveris seems to use a slightly outdated Gradle - latest non-beta is 6.6.1 while the jar file Audiveris ships:

Implementation-Title: Gradle
Implementation-Version: 4.6

I think updating Gradle will fix this.

**Comment by hallvors** [comment]
This does not seem like a trivial fix though. See https://docs.gradle.org/6.6/userguide/upgrading_version_5.html#changes_6.0  and 
[audiveris-dep-verification.pdf](https://github.com/Audiveris/audiveris/files/5251552/audiveris-dep-verification.pdf)

**Comment by hallvors** [comment]
I'm not a Java programmer so maybe I'm doing it wrong :) But having fixed build.gradle to say compileOnly instead of compile and runtimeOnly instead of runtime things start building - but with lots of compile errors :see_no_evil: 
So I'm afraid this is a task for the real pros like @hbitteur or @avm ..

**Comment by hbitteur** [comment]
Could you precise which Audiveris version you are trying to build?

- Either the "standard" 5.1 version, pretty old now, available on "master" branch, and which requires Java 8,

- Or the still unofficial 5.2-alpha version, available on "development" branch, and which requires Java 11.

**Comment by hallvors** [comment]
I have simply cloned the repository, so I'm trying to build the current 
master. Not sure which version this means :)

**Comment by hbitteur** [comment]
As of this writing, "master" branch means 5.1 release.

For more information about branches, you can have a look at this [Git Workflow article](https://github.com/Audiveris/audiveris/wiki/Git-Workflow) in Audiveris Wiki.

**Comment by hallvors** [comment]
Thank you, and apologies for having complained about something that's not supposed to work at this point :) I look forward to trying out Audiveris when I figure out how to run it with the right Java version :)
