### ISSUE TITLE
Converting error

### ISSUE THREAD

**Issue by TuanLa1972** [Audiveris/audiveris#415]
Hi there.
I am trying to convert attached file by batch mode as follows:
 ./Audiveris -batch -export -sheets 6 -output .  Blind*.pdf
and always get failure.
The logs:
```
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]            StepMonitoring 93   | MEASURES
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                      Page 251  | 4 raw measures: [4 in system#1]
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]            StepMonitoring 93   | CHORDS
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]            StepMonitoring 93   | CURVES
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]              SlursBuilder 156  | Slurs: 11
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]           SegmentsBuilder 110  | Segments: 3
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]            StepMonitoring 93   | SYMBOLS
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]            StepMonitoring 93   | LINKS
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]            StepMonitoring 93   | RHYTHMS
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]              SlotsBuilder 371  | S1 MeasureStack#1 Slot{#3 xOffset=267 timeOffset=1/4 incomings=[#1210] SUSPICIOUS}
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]              SlotsBuilder 371  | S1 MeasureStack#1 Slot{#5 xOffset=392 timeOffset=1/2 incomings=[#1211] SUSPICIOUS}
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                     Voice 234  | S1 Measure{#1P1} Voice #1 too long 1/4
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                     Voice 234  | S1 Measure{#1P2} Voice #1 too long 1/4
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                StackTuner 88   | S1 MeasureStack#1 no correct rhythm
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]              SlotsBuilder 371  | S1 MeasureStack#2 Slot{#3 xOffset=123 timeOffset=1/4 incomings=[#1202] SUSPICIOUS}
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]              SlotsBuilder 371  | S1 MeasureStack#2 Slot{#5 xOffset=249 timeOffset=1/2 incomings=[#1203] SUSPICIOUS}
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                     Voice 234  | S1 Measure{#2P1} Voice #1 too long 1/8
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                     Voice 234  | S1 Measure{#2P2} Voice #1 too long 1/8
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                StackTuner 88   | S1 MeasureStack#2 no correct rhythm
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]            StepMonitoring 93   | PAGE
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                     Voice 234  | S1 Measure{#1P1} Voice #1 too long 1/4
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                     Voice 234  | S1 Measure{#1P2} Voice #1 too long 1/4
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                     Voice 234  | S1 Measure{#2P1} Voice #1 too long 1/8
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                     Voice 234  | S1 Measure{#2P2} Voice #1 too long 1/8
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                 SheetStub 974  | Stub#7 storing
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                      Book 1660 | Stored /book.xml
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                   Picture 784  | Stored /sheet#7/BINARY.xml
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                     Sheet 1246 | Stored /sheet#7/sheet#7.xml
INFO  [Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7]                 SheetStub 979  | Sheet{Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com)#7} disposed
WARN  []                      Main 315  | Exception on Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com), java.lang.IndexOutOfBoundsException: Index: 5, Size: 2
java.lang.IndexOutOfBoundsException: Index: 5, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:638)
	at java.util.ArrayList.get(ArrayList.java:414)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1369)
	at org.audiveris.omr.score.Score.getPage(Score.java:630)
	at org.audiveris.omr.score.Score.getPages(Score.java:416)
	at org.audiveris.omr.score.ScoreReduction.reduce(ScoreReduction.java:75)
	at org.audiveris.omr.sheet.Book.reduceScores(Book.java:1443)
	at org.audiveris.omr.sheet.Book.transcribe(Book.java:1720)
	at org.audiveris.omr.sheet.Book.export(Book.java:591)
	at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:447)
	at org.audiveris.omr.CLI$CliTask.call(CLI.java:538)
	at org.audiveris.omr.Main.runBatchTasks(Main.java:312)
	at org.audiveris.omr.Main.main(Main.java:153)
	at Audiveris.main(Audiveris.java:49)
WARN  []                      Main 188  | Exit forced. Failure

```
Can you tell me what is wrong?
Thank you!
[Blinding Lights Sheet Music The Weeknd (SheetMusic-Free.com).pdf](https://github.com/Audiveris/audiveris/files/5046753/Blinding.Lights.Sheet.Music.The.Weeknd.SheetMusic-Free.com.pdf)

**Comment by Bacchushlg** [comment]
The batch conversion only works for perfect quality input files - and even there only in case that the score is not too complex.

Just use the GUI version of the program - it will show you the critical items in the score (there are a couple of them). Should not be a lot of effort to correct them.

**Comment by hbitteur** [comment]
@TuanLa1972 
Could you tell us which version of Audiveris you used?

I tried your command with the latest version available (5.2.1-alpha on development branch) and I got a slightly different behavior.  But still an error when exporting the whole score while only sheet 6 had been processed.
I think the error relates to the fact that early sheets had not been processed, while the "-export" option tries to export the whole score. I need to investigate this more seriously.

On your side, could you simply use
`./Audiveris -batch -export -output . Blind*.pdf`

That is: transcribe the whole score then export it.

**Comment by hbitteur** [comment]
Audiveris cannot load sheet number 2 from the .pdf file (although the other sheets can be loaded)
I also tried PDF Split and Merge utility, in an attempt to get a different PDF encoding. It cannot read this .pdf file either.

Do you have another version available?

**Comment by hbitteur** [comment]
I could successfully load sheet 6, then transcribe it, perform some manual corrections, then use "Sheet | **Export sheet as**" to export just the sheet at hand (sheet 6) to MusicXML format.

**Comment by hbitteur** [comment]
As a workaround, I used the trick explained in issue #280 (printing a PDF file to a PDF printer) in order to get a brand new PDF file.
Doing so, the original file (4732 KB) resulted in a new file (1664 KB).

I was able to load the (new) PDF file in Audiveris, but sheet number 2 still leads to problems.

Here is the batch loading of sheet 1:
``` 
2020-08-09 21:41:49,609 INFO [415-new]                 Book.java:496  | 7 sheets in D:\soft\cases\Issue-415\415-new.pdf
2020-08-09 21:41:49,812 INFO []                 Book.java:1764 | Stored /book.xml
2020-08-09 21:41:49,813 INFO []                 Book.java:1710 | Book stored as D:\soft\cases\Issue-415\415-new.omr
2020-08-09 21:41:49,820 INFO []                 Book.java:1405 | Book reaching SCALE on sheets:[#1]
2020-08-09 21:41:49,823 INFO [415-new]       StepMonitoring.java:93   | LOAD
2020-08-09 21:41:50,475 INFO [415-new]                 Book.java:1302 | Loaded image 1 2480x3507 from D:\soft\cases\Issue-415\415-new.pdf
```
The loading took about 0.6 seconds for sheet 1.

Now, here is the loading of sheet 2:
```
2020-08-09 21:42:06,047 INFO [415-new]                 Book.java:496  | 7 sheets in D:\soft\cases\Issue-415\415-new.pdf
2020-08-09 21:42:06,298 INFO []                 Book.java:1764 | Stored /book.xml
2020-08-09 21:42:06,299 INFO []                 Book.java:1710 | Book stored as D:\soft\cases\Issue-415\415-new.omr
2020-08-09 21:42:06,338 INFO []                 Book.java:1405 | Book reaching SCALE on sheets:[#2]
2020-08-09 21:42:06,342 INFO [415-new]       StepMonitoring.java:93   | LOAD
2020-08-09 21:44:29,357 INFO [415-new]                 Book.java:1302 | Loaded image 2 2480x3507 from D:\soft\cases\Issue-415\415-new.pdf
```
This time, the loading took **2 minutes and 23 seconds** for sheet 2.
And further processing took ages until the application completely hung.

Enough for this case. Please provide a more "civilized" input file :-)

**Comment by TuanLa1972** [comment]
Thank you very much for your input.
I know that Audiveris provides GUI for fix critical items without big effort,. However, I am not looking converting tool for myself but for blind people who needs click-and-convert type' app that doesn't require user's intervention after converting. Batch mode of Audiveris seems to fit their needs!
Back to our discuss:
I am testing with latest Audiveris, because I've downloaded from git and compiled it in my Ubuntu machine.
As I am testing with above attached file, Audiveris reports error on many pages of testing file. 
The problem is that only  pages with all things being recognized are generated in MusicXML. I'd expect that for partially recognized pages Audiveris should ignore the items that can't recognized and produces the output too. Of course, I know that OMR is different than OCR that OMR has to maintain rules of music, but I'd to ask whether can be it supported by this way?
The full result with log for my testing file is attached.
[sample.zip](https://github.com/Audiveris/audiveris/files/5048697/sample.zip)
[sample.pdf](https://github.com/Audiveris/audiveris/files/5048704/sample.pdf)
Thank you!

**Comment by hbitteur** [comment]
OMR in general is still a research area, and Audiveris in particular is still a work in progress.
Our resources are very limited and there is a continuous conflict between equally valuable requirements. Current examples are:
- Improve known weak areas of OMR engine (heads recognition, processing of poor-quality sheets),
- Develop OMR GUI tools to allow easy user corrections of engine outputs,
- Process each and every filed issue,
- Update documentation,
- Pack everything into a new release.

I perfectly understand that blind people cannot use the GUI tools and must rely on just the raw outputs of the OMR engine.
In that case, it is hopeless to try to automatically transcribe poor-quality scores as your provided example: there are too many remaining errors.

Another problem is that export to MusicXML is done partwise, meaning that, for each part, all sheets must be processed in sequence. So, what should we do with "missing" sheets (sheets for which transcription has failed)?

Perhaps we could switch from _partwise_ to _timewise_ MusicXML output. This might ease the export of scattered sheets. 
One additional topic to investigate! Sigh...

**Comment by hbitteur** [comment]
@TuanLa1972 
Pull again and build from development branch.
I have strengthened MusicXML export, see last commit b2de98813bec3a73a35ac638ae1623fca756b47c

You should now get, even in batch, a complete score .mxl file, even if sheet number 2 is still "untranscribable" and there are still many remaining errors here and there. Only OMR GUI could fix these errors.
But at least you get something.

**Comment by TuanLa1972** [comment]
@hbitteur : Great! Thank you very much!
