### ISSUE TITLE
Guide on how to use Audiveris API

### ISSUE THREAD

**Issue by moonlight-purple** [Audiveris/audiveris#42]
Good day! I am a beginner in programming and would like to integrate Audiveris into my project but I don't know where to start. I've read the source code but I don't have any idea on what are the code/classes that I'll need for the project. My project is a simple program that receives an image as input and output it as .xml in Music XML format. Is there a guide on how to use it? TIA

**Comment by thorncorona** [comment]
Just use the GUI version. It does everything you're describing.

**Comment by Foolius** [comment]
See here: [CLI](https://github.com/Audiveris/audiveris/wiki/CLI-Arguments) for a CLI interface. It's a bit clumsy but maybe you can execute bash commands from within you programming language.
This is an example call for what you describe:
`Audiveris/bin/Audiveris -export -batch ~/audiveris/data/examples/allegretto.png`

**Comment by moonlight-purple** [comment]
@thorncorona unfortunately I would like to integrate it in my mini project.
@Foolius I can go with that but the problem is I'll have to deal more effort on determining whether the mxl file has been created or not or when an error occurs.

I've already integrated it just yesterday without sleep for 48 hours because it was the deadline of my school project, and so I'm closing this. Thanks and great job for developing this awesome app!
