### ISSUE TITLE
Feature Request:  Ability to set custom time signature

### ISSUE THREAD

**Issue by Sunny090628** [Audiveris/audiveris#423]
I have some scores that have time signatures that are outside of what Audiveris provides.  eg. 6/4.  I wish I could define customer time signatures my own and the ORM would not mess it up.

**Comment by hbitteur** [comment]
This feature is on the todo list for coming 5.2 version

**Comment by hbitteur** [comment]
Done (see the 0/0 button in shape palette on time signature)
Closing.
