### ISSUE TITLE
Developer environment setup issues

### ISSUE THREAD

**Issue by j0ner0n** [Audiveris/audiveris#426]
I followed the tutorial in the [Wiki](https://github.com/Audiveris/audiveris/wiki/Environment) to set up my environment and familiarise myself with the application more to possibly help with development as I work on my final year project at University. Using Netbeans and following that guideline, my linting now mostly complains about javax packages missing (both when using default Java 14 as well as Java 1.8 as I understand you use?). Is there something I may have done wrong, this is my first time using Netbeans IDE.

**Apache Metadata:**
Product Version: Apache NetBeans IDE 12.1
Java: 14.0.1; OpenJDK 64-Bit Server VM 14.0.1+14
Runtime: OpenJDK Runtime Environment 14.0.1+14
System: Mac OS X version 10.15.7 running on x86_64; UTF-8; en_GB (nb)
User directory: /Users/jonasschafer/Library/Application Support/NetBeans/12.1
Cache directory: /Users/jonasschafer/Library/Caches/NetBeans/12.
(**Java Shell and Maven JDK is set up as Java 1.8.0_191**)

A small note while I'm at it that, for Apache NetBeans 12.1, there is no need to install the Gradle Plugin anymore (it actually doesn't exist anymore from what I see) unlike what the Environment setup mentions.

**Comment by hbitteur** [comment]
If you want to work on Audiveris development, I'd suggest you have a look at [this WiKi article](https://github.com/Audiveris/audiveris/wiki/Git-Workflow) which describes how we should use git branches.

- Latest official release is 5.1, based on Java 8.
- The coming one (5.2) is based on Java 11 (not 14). You can grab it today via the "development" branch (while the default "master" branch still points to 5.1 release).

Documentation will need an update too. Thanks for pointing out that Gradle plugin is no longer needed with latest NetBeans version.

**Comment by j0ner0n** [comment]
Thank you for the references. As I cloned and ran only the master branch, do you have any ideas what else could be an issue that I could do to get rid of my issue with javax? Googling the issue didn't really help me further and I do believe I have Java 8 properly set up from what I understand
