### ISSUE TITLE
Mid-bar clef symbol is understood as an error

### ISSUE THREAD

**Issue by git-along-little-dogies** [Audiveris/audiveris#428]
In one bar of my score on a treble clef, there is a bass clef mark ahead of a single note.  Its purpose is to indicate a much lower note without having to resort to many ledger lines.  However, this is a head-scratcher for audiveris and is considered an error.

**Comment by hbitteur** [comment]
I suppose the small bass clef was not correctly recognized by the OMR engine.
Simply drag n' drop proper clef manually from the shape palette to the desired location in your score.

**Comment by git-along-little-dogies** [comment]
![Dormi-original-clef-error](https://user-images.githubusercontent.com/73797561/98739941-179d9280-235f-11eb-826f-36fd8ac1c787.jpg)
![audiveris-clef-error](https://user-images.githubusercontent.com/73797561/98739955-1ec4a080-235f-11eb-9866-fe38d7db01bd.jpg)
Here are the original and Audiveris portions of that section.  Audiveris had accepted the drag-and-drop of the clef, but seems to object to its being there.

**Comment by git-along-little-dogies** [comment]
Never mind - it turned out there was a whole note hiding under the head of the clef.  Once that was removed the error was resolved.
