### ISSUE TITLE
Problem with double beams?

### ISSUE THREAD

**Issue by git-along-little-dogies** [Audiveris/audiveris#429]
I'm getting an error in this section, and the only thing I can think of is that the double beams in the treble of the accompaniment are being understood as a single beam, even though two distinct beams are shown.  Each beam is an independent object, which might be the problem.  On the other hand, such notation is sufficiently common that it must have been dealt with before.
![Audiveris-beams](https://user-images.githubusercontent.com/73797561/97816327-5b024d80-1c49-11eb-9678-c2f816ea4dc0.jpg)

**Comment by hbitteur** [comment]
Please provide the input image file, so that we can reproduce the problem and analyze what is happening.

**Comment by git-along-little-dogies** [comment]
![image](https://user-images.githubusercontent.com/73797561/98734857-6c3d0f80-2357-11eb-92ee-c12b6201cb1c.png)
Is this sufficient, or do you want the entire image input file?
Many thanks for your help.

**Comment by hbitteur** [comment]
Image resolution is much loo low (4 pixels as interline value!)
Audiveris needs something around 20 pixels

**Comment by hbitteur** [comment]
Have you tried with a better quality image?

**Comment by hbitteur** [comment]
Still no concrete input provided.
I'm closing the issue.
