### ISSUE TITLE
Mordants and inverted mordants are interchanged

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#432]
mordants and inverted mordants are correctly recognized, but appear interchanged in the export.

**Comment by hbitteur** [comment]
I just checked in MusicXML reference and you are right: the mordent with a vertical slash should be MORDENT while the one without a vertical slash should be MORDENT_INVERTED.
I'm afraid I need to retrain the glyph classifier just to fix this in a clean manner.

**Comment by hbitteur** [comment]
Please check these "definitions" found on site OnMusic Dictionary:
- [mordent definition](https://dictionary.onmusic.org/terms/2244-mordent), vertical line, uses the note below
- [inverted mordent definition](https://dictionary.onmusic.org/terms/1804-inverted_mordent), supposedly with no line but their example exhibits a vertical line, said to use the note below (?!). Plus the second paragraph telling us how confusing these definitions have been in the past.

Still pretty confusing to say the least! :-)

**Comment by hbitteur** [comment]
Bug fixed in commit 32674d2e72cd5b6ccf9e3b1375301689f8087a1d to development branch (source code fixed and neural network retrained from scratch).

**Comment by Bacchushlg** [comment]
So it seems that MuseScore interchanges the description, too.
But the symbol is forwarded correctly now.
