### ISSUE TITLE
problems with score analysis: seems to be less effective than before

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#440]
![Eine kleine Sehnsucht ](https://user-images.githubusercontent.com/33522630/99276795-51720b80-282d-11eb-89ab-5654ecf6e957.jpg)

Here is one of my reference scores... I transcribed with the lastest version (c8982c0) but I have the impression that the score analysis has got a draw back: many of the bar lines are not recognized and the 2nd system is split into 3.
Maybe a side effect of the latest changes?

**Comment by hbitteur** [comment]
@Bacchushlg 
I slightly modified and tuned the barline code in commit 16b4ca1bd3163ca230669590b35ffa880c629504
It works OK for your reference score above, and still works OK for the others you had submitted a few days ago regarding barline detection.

Code should be rather stable now. We are converging, that's the purpose of working on the "development" branch. :-)

**Comment by Bacchushlg** [comment]
Fine! The score analysis works perfect again. Uff.

But... again I don't get the transcription running through. I get

> [Eine kleine Sehnsucht] 18 raw measures: [3 in system#1, 6 in system#2, 5 in system#3, 4 in system#4]
> [Eine kleine Sehnsucht] Error in performing [TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException
> [Eine kleine Sehnsucht] Scores built: 1


And, when I save the book, I see that the gray png is removed:
> [Eine kleine Sehnsucht] Stored /book.xml
> [Eine kleine Sehnsucht] Removed /sheet#1/GRAY.png
> [Eine kleine Sehnsucht] Stored /sheet#1/HEAD_SPOTS.png
> [Eine kleine Sehnsucht] Stored /sheet#1/sheet#1.xml

**Comment by hbitteur** [comment]
Bug fix in commit 145bc9350f28c4a815f98da9ae7b33eec88b66cd
This allowed to discover and fix another bug in beam groups.
Also, I retrained the classifier with additional 1/16th rest and double flags.

**Comment by Bacchushlg** [comment]
This version is a great **breakthrough**! Don't touch it anymore ;-).
Really. when talking about "reference score", I used this one to explain, how to correct wrong detected items. No more possible with this version - because it's just too good!

The only thing that I dare to mention now: maybe you could have a look for a better detection of triplets. I have the impression that it had been better some time ago. If there is no solution now - just let it..
