### ISSUE TITLE
Voice colours

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#442]
In the image below you can see two measures with "Show score Voices" enabled: it seems to me that in the first measure there are too few colours (just one with 4 voices) and in the second measure there are too many colours: I can count up to 9 different coloures with only the same 4 voices.  If I select two pitches, right-click and choose "same voice" they still remain in different colours.

Please help understand why this.  Thanks.

![screenshot 2020-11-17 21:02:30](https://user-images.githubusercontent.com/64352612/99450966-6926be00-2919-11eb-98a5-574926e50420.png)

**Comment by Bacchushlg** [comment]
The 1sts measure has not been properly recognized. When you export it, the measure will be empty, because nothing has been properly detected (normally this should not happen - but sometimes after some editing I got the same problem).
For the 2nd measure:
The dot (violett, 1st chord top) is wrong. Therefore the rhythm check fails. In order to solve this, Audiveris tends to create additional voices.

**Comment by rodolfo-medina** [comment]
Thanks,,,  but why is the dot up there wrong?  It refers to two notes and increases their value by one half: the quarter below and the eighth above.  So it is, or should be, right.  In fact, that dot has both the coulours of those notes it refers to.

**Comment by Bacchushlg** [comment]
I dont think so. The dot only applies to the lower note.

-----Original Message-----

**Comment by rodolfo-medina** [comment]
In the following picture the two dots are separated but we have too many colours as well...

![screenshot 2020-11-19 19:13:27](https://user-images.githubusercontent.com/64352612/99712930-a450fa80-2a9b-11eb-84d8-dab7206f8767.png)

**Comment by rodolfo-medina** [comment]
See also issue #433...

**Comment by Bacchushlg** [comment]
![image](https://user-images.githubusercontent.com/33522630/99769451-a603d800-2b06-11eb-9ceb-93bec1121cef.png)

I took your score from #433 and added a missing 16th rest - and got the result above.

**Comment by rodolfo-medina** [comment]
Thanks...  Yes, the mistake is in the PDF source score...  Is it possible to correct it?  Because now, after adding that 16th rest, the colours are ok, but that's not what Schumann writes.  He wants an augmentation point on both the shared notes, below and above, so the 16th rest must be cancelled...  The problem comes from the fact that yellow notes in lower staff are not properly aligned with the above staff...  This error is in the original PDF score, that is wrong.  Any way to correct it within Audiveris?

**Comment by hbitteur** [comment]
@rodolfo-medina 
I appreciate your faith in Audiveris, thanks a lot! :-)
But it is not reasonable to expect that the OMR engine could fix mistakes in the source music score.

Frankly, the engine has already enough problems to cope with crowded and/or poor-quality images.
The end-user now has several manual means precisely to deal with the situations the engine cannot fix automatically. 
I think this is the right balance.

I still have a heavy work in progress regarding the poor-quality images. When I complete this task, the 5.2 release will be ready for general availability.

**Comment by rodolfo-medina** [comment]
all right, thank you...

**Comment by Bacchushlg** [comment]
I think we can close this issue
