### ISSUE TITLE
Partial export

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#443]
hbitteur, I think it would be important that Audiveris allowed to export only a part, only certain pages of a whole score.  Thanks.

**Comment by rodolfo-medina** [comment]
...although it is possible to cut the PDF with proper tools, i.e. "pdfjam", before opening it with Audiveris...

**Comment by rodolfo-medina** [comment]
...Although it is possibile to properly cut the PDF score with tools lime "pdfjam" before Audiveris loads it...

**Comment by hbitteur** [comment]
I think this request was discussed a long time ago but I don't remember if we came out with a clear specification.
It should not be very difficult to implement, once we know what is needed precisely.

Could you take the action point to search the issues history for this?

**Comment by rodolfo-medina** [comment]
Yes, that was discussed in #387...

**Comment by hbitteur** [comment]
Thanks for pointing to the right source.
Re-reading the issue, my understanding is that we still don't have a clear specification of what is needed.
Could we converge on this point?

**Comment by rodolfo-medina** [comment]
Suppose you have Schumann's Kreisleriana Op.16 and you want now study only song n.8.  You then need telling Audiveris to export only the pages of n.8.  Then, next month, you want add n.4 to your studying.  Then you reopen the file and tell Audiveris to add all the pages of n.4 to the total pages that are exported.  That's what I need.    At present you can't do that, unless you invalidate (permanently) those pages you don't want to export, which is uncomfortable if the document is large...  Then next month when you want to add n.4 you'll have to start from the score again, invalidate all pages except those of n.4 and save a second omr file on a different name...  Uncomfortable the more...

**Comment by hbitteur** [comment]
Let me correct you on one point: invalidation is not forever. You can simply point to the desired sheet and ask for reset of this sheet. This resets the "invalid" status of the sheet.
But this resets also every data in that sheet and you will have to reprocess it, I agree.

**Comment by hbitteur** [comment]
Using your example of several songs in a larger book.
Couldn't you use an external tool (like PDF-SAM) to just extract the sheets of song 8 and make a PDF file just for this song, and then launch Audiveris on it.
And do the same thing later for song 4.

**Comment by rodolfo-medina** [comment]
Yes, I did so and it worked although I had to do some more work on song 8 extracted than was needed on song 8 inside the whole album...  But it's all right, I'll do this way for the future.  As for sheet resetting, I only see a "Reset Book" button, not "Reset Sheet"...

**Comment by hbitteur** [comment]
Sorry, my mistake! There used to be a "Reset Sheet" command in the Sheet pull-down menu. I removed it long time ago, because I considered it duplicated the Step re-process feature. At the moment I made this decision, I had forgotten it also reset the "Invalid" flag. That was another mistake, to be fixed ASAP.

Could you elaborate on the "_more work on song 8 extracted than was needed on song 8 inside the whole album_"? If these songs are really independent movements, there should be no difference in their processing, whether inside a larger book or standing alone outside. I'm curious.

**Comment by rodolfo-medina** [comment]
Look at the difference in the two following pictures...  Both the PDF sources (the whole album and song n.8 extracted from it with "pdfjam") are attached in #430...

![screenshot 2020-11-21 09:06:23](https://user-images.githubusercontent.com/64352612/99872417-90abae00-2bd9-11eb-99e0-af4deffa61fd.png)

![screenshot 2020-11-21 09:06:27](https://user-images.githubusercontent.com/64352612/99872422-95706200-2bd9-11eb-81e9-86ff3c08a844.png)

P.S.: please help with my last message in #430...  thanks

**Comment by hbitteur** [comment]
You now have (via menu Book | Select sheets)  the ability to select sheets for processing within a larger book. This is something different of sheet validity.
You can of course modify your sheet(s) selection as you wish.

So, closing this issue.
