### ISSUE TITLE
editing impossible after some complex editing

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#445]
I had 2 cases where I could no more edit a transcription after storing (Ctrl-S).
I could export, and the export looks good.

After closing Audiveris and re-open the saved omr-file, everything was fine again.

Unfortunately I don't know, which of my actions led to the problem...

Additional comment: it not necessary to exit Audiveris: Close the document and re-open solves the problem, too

**Comment by hbitteur** [comment]
Yes, the same problem occurred to me, I guess it's related to the saving while removing the gray image.
Fix should arrive quickly.
Sorry for that.

**Comment by hbitteur** [comment]
Quick workaround:
In the Book Parameters, activate the first switch ("Keep loaded gray images") which is by default not activated.
Doing so, the gray images will be kept in the .omr project file and not removed. Obviously their removal led to the freeze.

A real fix will follow as soon as I find how.

**Comment by hbitteur** [comment]
Now fixed in commit 4540117e206dfca48fd188d54e2ee0b93ca6bbdf
Removal of the gray tab was not correctly handled.
