### ISSUE TITLE
NullPointerException in GridBilder

### ISSUE THREAD

**Issue by ossk** [Audiveris/audiveris#446]
I have an example of a relatively high-quality scan, that repeatedly fails in GridBuilder with NullPointerException using Audiveris 5.1.0:
[test] 1 sheet in /Pictures/scans/test.png
[test] Loaded image 1 4218x6325 from /Pictures/scans/test.png
[test] Book reaching PAGE on sheets:[#1]
[test] Beam minHeight:10 maxHeight:32 quorum:7245
[test] No beam key found, guessed value: 21
[test] Scale{line(5,6,9) interline(34,36,37) beam(21 extra) smallScale{ interline(27,28,30)}}
[test] Global slope: -0.00246
[test] Retrieved line clusters: 4 of size: 5 with interline: interline(34,36,37)
[test] Searching clusters with smallInterline: 28
[test] Retrieved line clusters: 14 of size: 5 with interline: interline(27,28,30)
[test] Error in GridBuilder: java.lang.NullPointerException
[test] No system lines to build NO_STAFF buffer
[test] No system lines to build NO_STAFF buffer
[test] Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException

The same effect I had earlier with bad-quality scans, but now I even tried three different scans of the same sheet and always got the same error.

**Comment by ossk** [comment]
Now attaching worked ...


![test](https://user-images.githubusercontent.com/3596270/100160095-406d6e00-2eaf-11eb-9e3c-d76450a53548.png)

**Comment by hbitteur** [comment]
@ossk 
Resolution of your image is much too high, processing it with Audiveris OMR will take ages for nothing or even worse results. BTW, there is a protection against such enormous images, you must have seen a warning about this.

Anyway, I scaled your image to 1/2 of its size (which means 1/4 of the initial pixel count), resulting in a more feasible work. A rule of thumb for a correct resolution is to reach an interline value (distance between 2 staff lines) around 20 pixels.

A few barlines on the left side of the image could not be detected, this resulted in many separate systems with few staves, while your score contains only 2 systems with many staves. So, I manually merged these small systems into larger ones (simply use a right-click on a system staff and in the "System..." submenu, select "Merge with system below".

I forgot the most important item: Do not use 5.1 anymore, but pull and build the "development" branch which provides 5.2-alpha version. Doing so, you will able to use a whole bunch of new UI tools.
5.2 should be published shortly, if I don't spend too much time on issue messages... :-)

**Comment by ossk** [comment]
From my experience so far, I always got better results at higher resolution even if it costs computing power, but this is clearly not the issue here. I will switch to 5.2 as soon as I found time to upgrade my system to Java 11.
However, I do not understand your solution: Because GRID fails, I have no system staff yet that is recognized as staff. So nothing to apply your suggestion to ...

**Comment by hbitteur** [comment]
With 5.2-alpha, I got all the staves recognized. Only their gathering into systems had to be manually modified.

**Comment by ossk** [comment]
Tested with latest alpha - solved
