### ISSUE TITLE
3/1 time

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#450]
Exercise 17 from Clementi's Gradus ad Parnassum shows a 3/1 time.  Audiveris detects it as 3/4 so all measures are red backgrounded.  Possible to add this strange time to Audiveris' list?  I'm attaching the PDF.  Exercise 17 is on p.87 of the file, p.86 of the book.  Thanks.

[clementi_Gradus-1.pdf](https://github.com/Audiveris/audiveris/files/5718327/clementi_Gradus-1.pdf)

**Comment by rodolfo-medina** [comment]
Putting 12/4 seems to fix it...

**Comment by hbitteur** [comment]
In terms of measure duration (not rhythm), 12/4 = 3/1 and the OMR engine checks are based upon measure duration do detect abnormal measures. Hence your results.

But you could explicitly try 3/1 as well: just manually insert a 3/1 time signature at the beginning of the movement and see what comes out of this. See [this handbook section](https://audiveris.github.io/audiveris/_pages/ui_tools/time/#custom-time-signature) on how to do this. And tell us about the results.

**Comment by rodolfo-medina** [comment]
Works fine...  thanks

**Comment by maximumspatium** [comment]
Closing this because the initial question has been clarified.
