### ISSUE TITLE
No ghost instance for OTTAVA_BASSA

### ISSUE THREAD

**Issue by ranzou06** [Audiveris/audiveris#454]
got an error when tryng to use the  8vb and 8va atributes "No ghost instance for OTTAVA_BASSA".

![image](https://user-images.githubusercontent.com/4295849/103161283-25e42880-47be-11eb-8331-054ef30d7de9.png)

**Comment by hbitteur** [comment]
8va and 8vb symbols may be recognized, but the underlying management for these octave-shift indications is not yet implemented. This is planned for coming 5.2 release.
See #448 (Octaviation)
