### ISSUE TITLE
faulty separation of common long stem into two stems

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#456]
![The Man I Love (1)](https://user-images.githubusercontent.com/33522630/103416155-a96a9480-4b85-11eb-9e94-1015b61b3e6c.jpg)

In some cases transcription splits long stems into 2 stems (example: 2nd system, 3rd measure). Even worse in measeure 2, 2nd system: the last chord of the bass line gets 2 stems - almost invisible.

**Comment by hbitteur** [comment]
Happy new year, Baruch!
These cases are among the typical ones I'm working on regarding poor-quality scores: If you look precisely at the black & white image, you'll notice that many pixels are missing, leading to the question: should the stem being built jump over these vertical gaps or not?
I'm adding this concrete example to my set of typical scores that 5.2 should address better.

**Comment by hbitteur** [comment]
Not all cases can be solved automatically, but results in 5.2.3 are acceptable.
Closing...
