### ISSUE TITLE
NumberFormatException while exporting omr file into mxl

### ISSUE THREAD

**Issue by aviaspe31** [Audiveris/audiveris#473]
I have a NumberFormatException error during the export of the book into mxl file. This mxl is created but nearly empty, containing only the name of the source file. The first steps seem to be OK on a quite simple score. I attach a zip file containing the image, the omr, the mxl and the log file.

Thank you for your help.
[au-clair-de-la-lune.zip](https://github.com/Audiveris/audiveris/files/6166880/au-clair-de-la-lune.zip)

**Comment by hbitteur** [comment]
According to your log file, this problem occurred with version 5.1 on Windows.
Retried with 5.2 alpha, this example works just fine.

5.2 is not officially released yet, it's a matter of a couple of weeks. These days, I have no time left to get back investigating a 5.1 bug, sorry for that.

You can today simply pull and build Audiveris "development" branch, which will give you a working 5.2 alpha (make sure to use Java 11, as opposed to Java 8 for 5.1).

**Comment by aviaspe31** [comment]
Thank you.
I am looking forward to 5.2 version.
