### ISSUE TITLE
Unable to build on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by BeFrankly** [Audiveris/audiveris#477]
Hello,
years ago I had tested Audiveris (on windows as far as I remember) and I could see that it will become a great piece of software. Now I'm here again and try to run it on Ubuntu 20.04, beccause I have changed from win to linux.
At the moment I get stuck in compiling. I followed the instruction that guesses one has JDK installed and I thing Oracle JDK is meant.
But as you might know, on newer Linux systems there is open java installed and I run into behaviour, that is also described here:
https://github.com/gradle/gradle/issues/8671
 The output in my case was:

#####################
./gradlew build
Downloading https://services.gradle.org/distributions/gradle-4.6-bin.zip
......................................................................
Unzipping /home/xyz/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo/gradle-4.6-bin.zip to /home/xyz/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo
Set executable permissions for: /home/xyz/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo/gradle-4.6/bin/gradle

FAILURE: Build failed with an exception.

\* What went wrong:
Could not determine java version from '11.0.10'.

\* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

\* Get more help at https://help.gradle.org
################

So I followed the hint there to upgrade to gradle 4.10. Ubuntu repository of 20.04 does not list this version, so I followed the idea here:
https://linuxize.com/post/how-to-install-gradle-on-ubuntu-20-04/
and installed gradle 4.10.3

After that I navigated to the audiveris source dir and called "gradle build"
[new.txt](https://github.com/Audiveris/audiveris/files/6192373/new.txt)
.
The build starts to run but ended with an error. So take a look into the attached file [new.txt](https://github.com/Audiveris/audiveris/files/6192382/new.txt).

It would be great if you could support building in Ubuntu 20.04.

Regards

**Comment by hbitteur** [comment]
Hello,
Could you tell us which branch you tried to build (master or development)?
And which Java version you used (8 or 11)?

**Comment by BeFrankly** [comment]
I did
git clone https://github.com/Audiveris/audiveris.git
and Java is

java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

**Comment by hbitteur** [comment]
You did not select any branch, hence you used the default one (master) which requires Java 8 (whereas you have Java 11).

So, either you use Java 8  and stick to master branch (old code of release 5.1)
Or, preferably, you use Java 11 and Audiveris development branch (soon to be released as 5.2)

For the latter, you have to explicitly switch to **development** branch by issuing the command:
>git checkout development

after the "git clone ..." command.

And then use gradlew as usual.

**Comment by BeFrankly** [comment]
Dear @hbitteur , thanks a lot. Yes, that did the trick. 

First I had to rename the gradle.sh that I have created along the way of following the solution at https://linuxize.com/post/how-to-install-gradle-on-ubuntu-20-04/
Now gradlew run starts audiveris 5.2.1-alpha. I only get warning, that no OCR is present. Here is the log:
#############################################

2021-03-24 07:36:06,200 WARN  []              TesseractOCR 315  | Tesseract data could not be found. Try setting the TESSDATA_PREFIX environment variable to the parent folder of "tessdata".
2021-03-24 07:36:06,202 INFO  []                      Main 401  | Environment:
\- Audiveris:    5.2.1-alpha:7646d251c
\- OS:           Linux 5.4.0-67-lowlatency
\- Architecture: amd64
\- Java VM:      OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
\- OCR Engine:   No OCR is available!
2021-03-24 07:36:06,236 INFO  []                       CLI 235  | CLI args: []
2021-03-24 07:36:06,387 INFO  []             AliasPatterns 131  | Alias patterns: [(IMSLP[0-9]*)-.*]
2021-03-24 07:36:06,757 INFO  []                   MainGui 415  | Audiveris version 5.2.1-alpha
2021-03-24 07:36:06,764 INFO  []                   MainGui 416  | 
LogUtil. Property logback.configurationFile not defined, skipped.
LogUtil. No /home/xyz/.config/AudiverisLtd/audiveris/logback.xml, skipped.
LogUtil. Configuration found file:///home/xyz/Compile/Audiveris/audiveris_5/res/logback.xml
LogUtil. Logging to /home/xyz/.cache/AudiverisLtd/audiveris/log/20210324T073606.log

2021-03-24 07:36:06,766 WARN  []                   MainGui 419  | No OCR is available! Check log file for more details.
###########################################

Thought I have done a normal Teseract install using Synaptic months ago. So if you have an idea how to get OCR working in this situation, great. I have to start working now and will further investigate perhaps this evening.

**Comment by hbitteur** [comment]
Ok, this sounds good.
The remaining problem with Tesseract is due to a misunderstanding (and we'll have to clarify this for the coming release).

Audiveris does not need any (strictly speaking) "installation" of Tesseract that you could have made on your own (as you did).
This is so, because Tesseract binaries are already linked as libraries by Audiveris project  (precise library names are tesseract:3.04.01-1.3 and leptonica:1.73-1.3) and dynamically called via javacpp.
So no need for any executable (like a .exe under Windows or a .so under Linux I think).

What is needed however, is access to **Tesseract language data files**, that govern the handling of one or several languages (typically English, Italian, German, French). These language files are accessed using TESSDATA_PREFIX environment variable.
And according to your log messages, either TESSDATA_PREFIX is not set or it does not point to some valid data folder.

As an example, here is my configuration (Cygwin under Windows):
>$ echo $TESSDATA_PREFIX
c:\Program Files (x86)\tesseract-ocr\

>$ ls "$TESSDATA_PREFIX"
tessdata

>$ ls "$TESSDATA_PREFIX/tessdata"
dan-frak.traineddata  eng.cube.size          fra.cube.size          ita.cube.size
deu.traineddata       eng.cube.word-freq     fra.cube.word-freq     ita.cube.word-freq
deu_frak.traineddata  eng.tesseract_cube.nn  fra.tesseract_cube.nn  ita.tesseract_cube.nn
deu-frak.traineddata  eng.traineddata        fra.traineddata        ita.traineddata
eng.cube.bigrams      fra.cube.bigrams       ita.cube.bigrams       ita_old.traineddata
eng.cube.fold         fra.cube.fold          ita.cube.fold          slk-frak.traineddata
eng.cube.lm           fra.cube.lm            ita.cube.lm
eng.cube.nn           fra.cube.nn            ita.cube.nn
eng.cube.params       fra.cube.params        ita.cube.params

**Comment by hallvors** [comment]
Maybe this explanation is useful regarding Tesseract data issue @BeFrankly : https://github.com/Audiveris/audiveris/issues/431#issuecomment-807482876

**Comment by BeFrankly** [comment]
Hello,
tanks for your advice. I found out where on Ubuntu 20.04 LTS the TESSDATA folder is, added the environment variable to my .bashrc and installed missing languages. So here how my environment looks like in bash:
>tesseract --list-langs
List of available languages (4):
deu
eng
fra
osd
env | grep tess
TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata
>
**But still tesseract doesn't seem to work.**
Here is log Output in the same shell when I started audiveris per ./gredlew run in the audiveris folder:

> INFO  [mhb1]          NoteHeadsBuilder 976  | S#1 3 heads purged
INFO  [mhb1]             HeadSeedTally 208  | Scale information: HeadSeeds{NOTEHEAD_BLACK[L:1.3]}
Failed loading language 'deu'
Failed loading language 'eng'
Failed loading language 'fra'
Tesseract couldn't load any languages!
WARN  [mhb1]            TesseractOrder 170  | Could not initialize Tesseract with lang deu+eng+fra
WARN  [mhb1]                 SheetStub 931  | Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1231)
        at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:915)
        at org.audiveris.omr.sheet.Book.reachBookStep(Book.java:1441)
        at org.audiveris.omr.sheet.Book.transcribe(Book.java:1790)
        at org.audiveris.omr.sheet.ui.BookActions$TranscribeBookTask.doInBackground(BookActions.java:2250)
        at org.audiveris.omr.sheet.ui.BookActions$TranscribeBookTask.doInBackground(BookActions.java:2230)
        at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
        at java.base/java.util.ArrayList.addAll(ArrayList.java:702)
        at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:107)
        at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:50)
        at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:101)
        at org.audiveris.omr.step.Step.doit(Step.java:184)
        at org.audiveris.omr.sheet.SheetStub.lambda$doOneStep$3(SheetStub.java:1216)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        ... 3 common frames omitted
INFO  [mhb1]                      Book 1499 | Scores built: 1
>

**Comment by hallvors** [comment]
Yes, this is due to incompatibility with Tesseract *4.x* data files, you most likely need to download *3.x* files as described in that comment.

**Comment by hbitteur** [comment]
Just 2 points:
- Audiveris needs data files from Tesseract 3.04 (not 4.x) as @hallvors said.
- TESSDATA_PREFIX must point to the **parent** folder of tessdata folder (not to tessdata folder itself)

And according to your log:
> TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata

Which is a good reason for not finding Tesseract data files...

**Comment by BeFrankly** [comment]
Ok, now it gets a bit complicating. In my world there exist different versions of a program that need config files, that work with that related version. My ubuntu version installed tesseract 4.1.1 and the tessdata files lie in the 4.00 folder. Ok so far.
Audiveris now needs 3.04 version of the data files. But where to put them and does tesseract 4.1.1 work with data files of version 3.04. Do I have to put them in the 4.00 folder which then contains a version mixture?

**Comment by BeFrankly** [comment]
Ok I can see in your documentation:

> You can download additional languages from Tesseract 3.04 tessdata repository. Pay attention to the fact that Audiveris is not yet compatible with version 4.0 which is the most recent version of Tesseract, it requires Tesseract version 3.04.
Note that besides downloading additional language(s), you will have to select them at runtime. This is detailed in Tesseract OCR article within the Building from sources section.

Alas. How to tell Ubuntu LTS to install an older version. I'm going to turn OCR off for now I think. Too much fiddling around.

**Comment by hbitteur** [comment]
No, there is one point you did not notice.

You can have Tesseract (4.x for example) **installed** on you machine, bet it Linux or Windows: you get the software executable and its related data files.
**At the same time**, you can create a folder somewhere and dowload there the data files of Tesseract 3.04 (I never told you to **install** Tesseract 3.04, but only to download the language data files). Now, in the command you use to launch Audiveris, set the TESSDATA_PREFIX variable so that it points to the parent folder of tessdata 3.04 folder.

All this is possible because Audiveris does not use a Tesseract exec (like the one you may have installed) but uses tesseract code via a binary library called from Audiveris Java code.

**Comment by BeFrankly** [comment]
Here a short conclusion on this:

1. I run into this problems because first of all, I have not read all of your good documentation about installing from source. That was my fault.
2. The documentation on Page [https://bacchushlg.gitbooks.io/audiveris-5-1/content/install/sources.html](https://bacchushlg.gitbooks.io/audiveris-5-1/content/install/sources.html) does not tell that the development branch works with Java 11 (what is good, that it works with)
3. The site also does not clearly tell, if Oracle JDK or Open JDK is needed. In this times we are in it would be great to make that clear.
4. And just a hint: the link to the Tesseract guide, that is included in your documentation, is a somehow "broken" link 
5. Last: Still you are doing a great job. I know how much work it is to maintain such a project.

Regards
Frank

**Comment by BeFrankly** [comment]
Oh, just saw your post. I will give it a try in a few minutes.

**Comment by hallvors** [comment]
Link to download old Tesseract files + some details here https://github.com/Audiveris/audiveris/issues/431#issuecomment-807482876

**Comment by BeFrankly** [comment]
Yeah, great. It works. Here is the location where I downloaded the data:
[https://tesseract-ocr.github.io/tessdoc/tess3/Data-Files.html](https://tesseract-ocr.github.io/tessdoc/tess3/Data-Files.html)
Where to leave the my testing results for that development brunch?
Thanks to all for your time and your hints. It was a long run to get to here, but at the end, it works.
