### ISSUE TITLE
Error in performing [CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by ImALiteralDude** [Audiveris/audiveris#480]
I tried to compile a PDF I got from MuseScore and this happened. See above error.

**Comment by hbitteur** [comment]
Please provide the input PDF file and the log of messages you got.
Without these pieces, there is nothing we can do to help you.

**Comment by ImALiteralDude** [comment]
[score.pdf](https://github.com/Audiveris/audiveris/files/6245807/score.pdf)
How do I get the log?

**Comment by hbitteur** [comment]
At the very beginning of the log window (bottom part of Audiveris window), there is a line like this one:
> LogUtil. Logging to C:\Users\herve\AppData\Roaming\AudiverisLtd\audiveris\log\20210402T083732.log

It gives you the precise log location on your local machine.

**Comment by ImALiteralDude** [comment]
[20210331T113215.log](https://github.com/Audiveris/audiveris/files/6258171/20210331T113215.log)
[20210331T123720.log](https://github.com/Audiveris/audiveris/files/6258172/20210331T123720.log)
Dunno which is which but they both gave same error (I think...)

**Comment by hbitteur** [comment]
Works correctly with latest version (5.2.3)
Closing ths issue
