### ISSUE TITLE
may want to give super-resolution a run on low res sources.

### ISSUE THREAD

**Issue by RamKromberg** [Audiveris/audiveris#486]
I messed around with some low res sheet images from google and managed to get them OCRed reasonable well after running them through a super-resolution pass.

![HENRMART.gif before](https://user-images.githubusercontent.com/14829269/115789689-31dba200-a3ce-11eb-901b-26cd2f0cd802.gif)

![HENRMART.jpg after](https://user-images.githubusercontent.com/14829269/115789692-32743880-a3ce-11eb-8c31-ea54de55ee2a.jpg)

![HENRY-MARTIN-English-Traditional-01.gif before](https://user-images.githubusercontent.com/14829269/115789695-33a56580-a3ce-11eb-8471-01f6b5582184.gif)

![HENRY-MARTIN-English-Traditional-01.jpg after](https://user-images.githubusercontent.com/14829269/115789698-343dfc00-a3ce-11eb-9958-1d09626b7db9.jpg)

Anyhow, I just tossed it on the [first online SR service I googled](https://bigjpg.com/) and it worked so I haven't bothered looking into it too much but I'm sure there should be non-proprietary FOSS solutions for line-art and such that will get similar or better results that you could use or reference or whatever...

Anyhow, thanks for a nice piece of software. :)

**Comment by RamKromberg** [comment]
p.s. found a foss project that got the job done online: https://github.com/lltcggie/waifu2x-caffe

I've run it through wine (winetricks vcrun2015 was necessary) via the the [snowshell gui](https://github.com/YukihoAA/waifu2x_snowshell/releases) forcing cpu only targeting 4x and got these:

![HENRY-MARTIN-English-Traditional-01_waifu2x_noise1_scale_x4_0](https://user-images.githubusercontent.com/14829269/115873910-2cbd3800-a44c-11eb-8717-ae7daf02061f.png)

![HENRMART_waifu2x_noise1_scale_x4_0](https://user-images.githubusercontent.com/14829269/115873900-29c24780-a44c-11eb-9434-09dc3c0d97fa.png)

They were OCRed by audiveris fine. The google-translated docs suggest there's different models to choose and such but I haven't messed around with any of it since it worked fine first pass.

Thanks again :)

**Comment by hbitteur** [comment]
@RamKromberg 
I didn't know that image improvement could work so well.

To evaluate the impact on Audiveris, I submitted your 6 images to the  OMR engine (2 scores, each with: low resolution, high resolution 1, high resolution 2). 
- Low resolution is so low that Audiveris proposes to discard the image. I tried to make it go on, but it quickly failed for lack of relevant data.
- High resolutions lead to really good results, perhaps 1 note or one barline missed, that's all. Easy to fix manually.
- The two services you tried (one online with limited use, one offline)  lead to comparable results.

This is a very interesting post.
I'm about to officially publish release 5.2 of Audiveris, as soon as the handbook on-going update is completed.
Could you take the action point of writing a section about the offline solution you have experienced (a step-by-step cookbook to make it work, which environments are needed, etc).
I would like to integrate your contribution in Audiveris handbook (preferably in markdown, but plain text would be fine too).

See what you can do.
Thanks in advance,
/Hervé

**Comment by RamKromberg** [comment]
>I didn't know that image improvement could work so well.
Yeah it took me by surprise too :D

>Could you take the action point of writing a section

Sure but I have a few details to iron out first. Basically, using wine to execute waifu2x-caffe was just a quick way to test if local foss options are viable following the surprising success I had with the online service. However, I feel it's otherwise too slow to be of practical use. So, before writing any docs, I'll need to try and build [waifu2x-ncnn-vulkan](https://github.com/nihui/waifu2x-ncnn-vulkan) and run it with the cunet model without wine first. My GPU is rather dated so I might still end up still running on the CPU but it should be better than using wine regardless. I also want to test different settings since I used 4x enlargement which is quite extreme and out of the design specs...

Btw, I'm not sure what the current status of Tesseract 4 for OMR, but looking up super-res foss implementations and models somehow landed me on this: https://guiem.medium.com/how-to-train-tesseract-4-ebe5881ff3b7
Pretty sure it won't help but I figured mentioning it wouldn't hurt either.

**Comment by RamKromberg** [comment]
Ok I did a little write-up but since forking the wiki didn't work I just cloned it, edited stuff with a text editor and used `git format-patch -n HEAD^` to prepare this:

[0001-wiki-waifu2x-low-res-img-enlargement-entry.patch.zip](https://github.com/Audiveris/audiveris/files/6372179/0001-wiki-waifu2x-low-res-img-enlargement-entry.patch.zip)

Since I didn't get to test it out on github properly I'm not sure the links and images are working correctly so you might want to proof and double check everything :D

**Comment by hbitteur** [comment]
Hi Ram,
Thanks for your quick contribution.
I applied your patch on Audiveris Wiki and had only to fix links to images.
I took the liberty to rephrase your very last paragraph (I think it's more understandable now, please check on [Audiveris wiki page](https://github.com/Audiveris/audiveris/wiki/Enlarging-Low-Resolution-Scans))

2 things left:
- I would like to give you credit for this document, could you give me an email address or something so that people can get in touch with you if they wish.
- I didn't have in mind to update Audiveris Wiki, because often people don't notice the Wiki on github projects. But on second thought this is indeed a good idea. And I will include your same text in Audiveris Handbook as well (the one I'm working on right now).

**Comment by RamKromberg** [comment]
>I would like to give you credit for this document, could you give me an email address or something so that people can get in touch with you if they wish.

No problem you can use the same email I used for the diff ( ramkromberg@mail.com ). 

Btw, since I produced the diff with _git format-patch_ from a local git commit, by using `git am` you can actually reapply it to the git ledger as a proper commit signed off by me using my email. So, if you'd like to "correct" the logs, you can:

```
git clone https://github.com/audiveris/audiveris.wiki.git
cd audiveris.wiki
git reset --hard HEAD~1
git clean -fd
git am ../0001-wiki-waifu2x-low-res-img-enlargement-entry.patch
```
Then review the commit using diff or whatever, make the changes you want as a new commit and force the changes through back to github as you usually do.

>I didn't have in mind to update Audiveris Wiki...

I actually mistook it for the handbook :)

Regardless you can go ahead and add, modify or drop it from any documentation as you see fit with or without credit. It's all good.

**Comment by hbitteur** [comment]
Done.
Thanks for the git lesson :-)

```bash
$ git log -3
commit 1d57f73241692099977989aa08da6ff8b029120d (HEAD -> master, origin/master, origin/HEAD)
Merge: b8c4682 ac56b4c
Author: Hervé Bitteur <herve.bitteur@audiveris.org>
Date:   Sun Apr 25 20:27:01 2021 +0200

    Fixed image links

commit b8c468262ae923652ab53e4c775e498f0d3d541a
Author: Ram Kromberg <ramkromberg@mail.com>
Date:   Sun Apr 25 17:29:37 2021 +0300

    wiki: waifu2x low res img enlargement entry

commit ac56b4cf0afa24aae2cea278c80f3f9eea35a06e
Author: Hervé Bitteur <herve.bitteur@audiveris.org>
Date:   Sun Apr 25 17:27:22 2021 +0200

    Enlarging-Low-Resolution-Scans by Ram Kromberg
```

**Comment by RamKromberg** [comment]
Happy to help :)
