### ISSUE TITLE
Some chord heads are ignored in reduction step

### ISSUE THREAD

**Issue by agorji** [Audiveris/audiveris#487]
Hello there,

Sometimes some heads are ignored in a set of heads with the same horizontal position in the measure. Here is an example (measure 39, staff 1):
<img width="964" alt="image" src="https://user-images.githubusercontent.com/18348090/118117525-0a379280-b3ec-11eb-9732-2d65f02b700a.png">

That's when in the head step all the heads are correctly recognized:
<img width="962" alt="Screen Shot 2021-05-13 at 12 49 29 PM" src="https://user-images.githubusercontent.com/18348090/118117684-3e12b800-b3ec-11eb-80c9-c80862efad99.png">

And it turns out that some are being ignored in reduction step:
<img width="966" alt="Screen Shot 2021-05-13 at 12 54 29 PM" src="https://user-images.githubusercontent.com/18348090/118117836-613d6780-b3ec-11eb-8173-63473cd4075f.png">

I couldn't figure out the underlying reason behind that. Since it is occuring often, I was wondering whether you have any comments on that.

You can access this example pdf that contain couple of these examples here:
[https://imslp.org/wiki/Ballo_di_Mantova_(Ferrini%2C_Giovanni_Battista)](https://imslp.org/wiki/Ballo_di_Mantova_(Ferrini%2C_Giovanni_Battista))

**Comment by hbitteur** [comment]
Could you check the contextual grade of these heads?
If less than 0.5 they won't survive the reduction.

**Comment by agorji** [comment]
> Could you check the contextual grade of these heads? If less than 0.5 they won't survive the reduction.

For those specific heads in my example that could not make it to the next step, the grades are higher than those that are selected (0.74 and 0.69 vs. 0.51). So I guess it shouldn't be the case.

**Comment by hbitteur** [comment]
OK, I've found where the problem is in the STEMS step.
And, you're right, this has nothing to do with heads grade.
I need some time to fix the STEMS algorithm (and I'm on the road right now), so be patient...

**Comment by agorji** [comment]
Perfect, thank you very much. I guess the issue must be clear to you but let me know if you needed more pdfs for investigation.
I will look forward to the updates.

Bon Voyage!

**Comment by hbitteur** [comment]
Your bugs are now fixed in commit 6091636d74e8c043394ad4138c5ec5099fe7a9ab.

But I discovered other wrong head linking, in "opposite stems" like:
![image](https://user-images.githubusercontent.com/22053634/118719261-8be25280-b828-11eb-97ea-fa7336b3a4e3.png)

So, I still need to work on STEMS step.
Thanks for this example which points out interesting cases.

**Comment by agorji** [comment]
> Your bugs are now fixed in commit [6091636](https://github.com/Audiveris/audiveris/commit/6091636d74e8c043394ad4138c5ec5099fe7a9ab) (development branch).
> 
I am testing on the latest development branch but it seems that the issue in measure 39 (third page of the book) still holds. Could you please verify if the new fix works for that specific measure, so I know that the problem is in my side?
> But I discovered other wrong head linking, in "opposite stems" like:
>
I was considering this mirrored head misinterpretation as a normal error that sometimes happen. 

I'm glad that the example could help bringing up some corner scenarios.

**Comment by Bacchushlg** [comment]
I saw in the comment of your commit "never linking heads top and bottom".
Be aware of score like this. The last measure contains a head with stems up and down.

![image](https://user-images.githubusercontent.com/33522630/119229629-386a5000-bb19-11eb-9401-0f321bf986d7.png)

**Comment by hbitteur** [comment]
@agorji 
Sorry for my late answer, I have been very busy this week, but away from my laptop...

Here is the binary view for measure 39:
![image](https://user-images.githubusercontent.com/22053634/119379450-caac5880-bcbf-11eb-9e01-1accdd4afbd7.png)

And here is the result after REDUCTION step:
![image](https://user-images.githubusercontent.com/22053634/119379576-f3345280-bcbf-11eb-8482-0de6865bb2a0.png)

So, for me, there is no error left.
Perhaps you should pull again from development branch, with commands like these:
```bash
git checkout development
git pull --all
```

**Comment by hbitteur** [comment]
@Bacchushlg 

Baruch,
The new STEMS algorithm should be able to deal automatically with the case you signaled (one head shared by two stems).
Could you check on your own (or send me the input file)?

Bye,
/Hervé

**Comment by hbitteur** [comment]
@Bacchushlg 
Oops, I hadn't noticed I could use our image directly!

Here are the results for the last measure:
![image](https://user-images.githubusercontent.com/22053634/119382687-a900a080-bcc2-11eb-918c-555e7cb8dd53.png)

Notice in lower staff that the shared head is correctly handled.
But in upper staff, there is a stem missing. I need to work this out.

**Comment by Bacchushlg** [comment]
I had observed this behaviour a couple of times already: transcription tends to connect one stem to 2 note heads, while ignoring the second stem that would like to connect to the other head instead. This happens a couple of times for this score.

**Comment by agorji** [comment]
@hbitteur 

Hi Hervé, glad to see you are back, and thanks for your answer. 

Knowing that it is working well on your side, I tried to make mine work. Interestingly I found that the problem was that I am loading the pdfs with 500 dpi and there the upper heads are ignored. But, as you verified, decreasing the dpi to default 300 will resolve it. Although I have observed that increasing the resolution usually improves the result, here it was the opposite. In general, it is still not clear to me that why the performance of Audiveris should be sensitive to the resolution to this extent i.e. on this specific sample increasing the dpi leads to better recognition in some measures and missing some details in other measures while decreasing it does the other way around.

**Comment by agorji** [comment]
> I had observed this behaviour a couple of times already: transcription tends to connect one stem to 2 note heads, while ignoring the second stem that would like to connect to the other head instead. This happens a couple of times for this score.

I have observed that as well. As a temporary solution I used to change *HeadStemRelation.yGapMax* and *HeadStemRelation.yGapMax_p1* to a very low number so force the model to not assign heads with vertical gaps to a stem. But even this one is not working for your example, and hopefully it seems that it is going to be further investigated for a better fix!

**Comment by hbitteur** [comment]
Bug now fixed with commit cf7a3d7b09b2f853d39fb854d9a0b4a663991a15, you can pull from development branch.

@agorji You should unset the modifications you made about HeadStemRelation.yGapMax and its derivatives, they would conflict with the new code.

All cases I checked are not OK, but please check on your own and signal any undesired result.

**Comment by agorji** [comment]
Works pretty well in my side as well. Thank you for the fix.

I believe this issue can be closed now.
