### ISSUE TITLE
tesseract version

### ISSUE THREAD

**Issue by RJVB** [Audiveris/audiveris#489]
Hi,

The build/install notes stipulate one should use version 3.04 of Tesseract, 3.04.00 if memory serves me well. I sprung for 3.04.01 which seems to work OK.
Are those instructions up to date, IOW, will audiveris really NOT work properly with newer Tesseract versions? The 3.04 version is quite old by now.

PS: Actually, there's only mention of the Tesseract language files - does that mean the Tesseract engine itself isn't requred or is that supposed to be pulled in as a dependency (as the MacPorts install command shown would)?

PS2: MacPorts port:tesseract is at 4.1.1 currently.

**Comment by hbitteur** [comment]
@RJVB 

I can confirm that Audiveris needs to use Tesseract language files related to old version 3.04.01. The newer 4.x versions don't work correctly with text found on music scores (problems with isolated lyric syllables, problems with text bounds).

And you are right: Tesseract engine is _not_ used. You are part of the very few people that noticed that!
To be precise, Tesseract code is used, but via a linked library (e.g. under Windows we don't use a .exe but a .jar file + javacpp). You can inspect the details in Gradle dependencies.

**Comment by RJVB** [comment]
Indeed, I see a reference to that extent, does it pull in a prebuilt libtesseract or does it use the one on the system?

**Comment by hbitteur** [comment]
According to Gradle, it uses tesseract:3.04.01-1.3 and leptonica:1.73-1.3

I suppose, but I don't know the details, that these libraries are in a cache where they have been loaded some time before.
For example, from my user account on Windows, I can see these files:
```
$ find . -name "*tesseract*"
./.gradle/caches/modules-2/files-2.1/org.bytedeco.javacpp-presets/tesseract
./.gradle/caches/modules-2/files-2.1/org.bytedeco.javacpp-presets/tesseract/3.04.01-1.3/80b57bf68fcf851fbbc44c28e10cb4ad3036fe7b/tesseract-3.04.01-1.3.jar
./.gradle/caches/modules-2/files-2.1/org.bytedeco.javacpp-presets/tesseract/3.04.01-1.3/ee4eeb8cb480a063ac74c87c0102c865db8f474f/tesseract-3.04.01-1.3-windows-x86_64.jar
./.gradle/caches/modules-2/metadata-2.71/descriptors/org.bytedeco.javacpp-presets/tesseract
./.javacpp/cache/tesseract-3.04.01-1.3-windows-x86_64.jar
./.javacpp/cache/tesseract-3.04.01-1.3-windows-x86_64.jar/org/bytedeco/javacpp/windows-x86_64/jnitesseract.dll
./.javacpp/cache/tesseract-3.04.01-1.3-windows-x86_64.jar/org/bytedeco/javacpp/windows-x86_64/libtesseract-3.dll
```

**Comment by stweil** [comment]
> The newer 4.x versions don't work correctly with text found on music scores (problems with isolated lyric syllables, problems with text bounds).

@hbitteur, what about the newer Tesseract 3.05.01, does it work? Is there an example which shows the problems with newer versions? Even the latest version Tesseract 5.0.1 should still be compatible to Tesseract 3, so I wonder what goes wrong there.

**Comment by stweil** [comment]
I continue my discussion at the related issue #273.
