### ISSUE TITLE
keep selection after "de-assign"

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#49]
It would be a helpful improvement to keep the selection of a glyph after pressing "de-assign".
Actually it is always necessary to select an object again.
Just a little improvement to make corrections easier to handle.

I used the actual dev. branch for the test (ver 5.1, 29.01.2018)

**Comment by hbitteur** [comment]
Strictly speaking, you de-assign an inter, not a glyph. :-)
But I agree that the program could keep the underlying glyph selection, to ease the immediate creation of a new inter.

Note that you don't always have to de-assign the inter first. You can directly assign a new inter (from the selected glyph), which will automatically remove any other inter based on the same glyph.

**Comment by hbitteur** [comment]
OK; Done as https://github.com/Audiveris/audiveris/commit/f9453c059745711f55af8e77ee24abe2f107c876
