### ISSUE TITLE
NumberFormatException for converting jpg-files to mxml

### ISSUE THREAD

**Issue by S0urC10ud** [Audiveris/audiveris#495]
On using a slightly modified version of https://hub.docker.com/r/toprock/audiveris which basically sets up the latest version of Audiveris (branch: master) as described in the docs I get a NumberFormatException:
```
audiveris-converter | musiScan.jpg
audiveris-converter | INFO  []                      Main 401  | Environment:
audiveris-converter | - Audiveris:    5.2.1:bcfc55ebf
audiveris-converter | - OS:           Linux 5.11.10-surface
audiveris-converter | - Architecture: amd64
audiveris-converter | - Java VM:      OpenJDK 64-Bit Server VM (build 11.0.9+11-alpine-r1, mixed mode)
audiveris-converter | - OCR Engine:   Tesseract OCR, version 3.04.01
audiveris-converter | INFO  []                       CLI 237  | CLI args: [-batch, -export, -output, /output/jpg, /input/musiScan.jpg]
audiveris-converter | INFO  []             AliasPatterns 131  | Alias patterns: [(IMSLP[0-9]*)-.*]
audiveris-converter | INFO  []                      Main 158  | Running in batch mode
audiveris-converter | INFO  []                  Versions 370  | Versions. Poll frequency: Weekly, next poll on: 08-Jan-2000
Exception in thread "main" java.lang.NumberFormatException: For input string: "v5"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.valueOf(Integer.java:957)
        at java.base/java.lang.Integer.decode(Integer.java:1436)
        at org.audiveris.omr.util.Version.<init>(Version.java:77)
        at org.audiveris.omr.sheet.Versions.poll(Versions.java:292)
        at org.audiveris.omr.sheet.Versions.considerPolling(Versions.java:275)
        at org.audiveris.omr.Main.main(Main.java:161)
        at Audiveris.main(Audiveris.java:49)
```
## Steps to reproduce
Here is my version of the Docker-File (but I also get the exception with the original version from the link above):
```dockerfile
FROM alpine as builder
RUN apk update && apk add openjdk11 \
        git \
        tesseract-ocr  \
		ttf-dejavu \
		tar
RUN git clone --branch master https://github.com/Audiveris/audiveris.git && \
        cd audiveris && \
        ./gradlew build && \
		mkdir /Audiveris && \
        tar -xvf /audiveris/build/distributions/Audiveris.tar -C /Audiveris 

FROM alpine 
COPY --from=builder /Audiveris/ /
RUN apk update && apk add openjdk11-jre \
        tesseract-ocr \
        tesseract-ocr-data-deu \
        tesseract-ocr-data-fra \
		font-bh-ttf \
		libuuid && \
		ln -s /usr/lib/libfontconfig.so.1 /usr/lib/libfontconfig.so && \
		ln -s /lib/libuuid.so.1 /usr/lib/libuuid.so.1 && \
		ln -s /lib/libc.musl-x86_64.so.1 /usr/lib/libc.musl-x86_64.so.1
ENV LD_LIBRARY_PATH /usr/lib
CMD ["sh", "-c", "/Audiveris/bin/Audiveris -batch -export -output /output/jpg /input/*.jpg"]
```
I am running this with the following - very simple - docker-compose file:
```yaml
version: "3.7"

services:
    audiveris:
        build: .
        image: s0urc10ud/audiveris-docker-images
        container_name: audiveris-converter
        volumes:
            -  "$PWD/input:/input/"
            -  "$PWD/output:/output/"
```
Before you ask: yes, the output and input directories already exist and the jpg file from the mounted `input` directory is visible inside the container (tested it with ls in the cmd-section).

**Comment by S0urC10ud** [comment]
This issue is probably caused by the fact that the latest release starts with a "v": v5.2.1 - is returned by latestRelease.getTagName() inside Versions.java:292 -- causing the exception above as this is not expected to be parsed

**Comment by hbitteur** [comment]
Sorry for such a late answer, I have been away for a while.

Your diagnostic is correct: latest Audiveris was named v5.2.1 and this caused the error.
Problem is that I didn't have this integer decoding in mind when I chose the release number on GitHub site (which by the was suggests to start the release tag with a 'v'...).

I plan to publish a new release very shortly (within one week), and name it 5.2.2

A defensive approach would be to "remove" any potential leading [vV] character in tag name before decoding its value.
What do you think?

**Comment by hbitteur** [comment]
Answering my own question, I noticed that I could edit the tag value for an existing release on github.
So, the tag for 5.2.1 is no longer v5.2.1 but 5.2.1 
https://github.com/Audiveris/audiveris/releases/tag/5.2.1

I will double-check if it works OK when someone tries to read the tag of the latest release.
