### ISSUE TITLE
problem with release version

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#498]
I'm afraid that the release version did not get all improvements of the last developments.
I just transcribed a version using the release - was a bit disappointed and used the former dev. version.
Here my results:
release:
![image](https://user-images.githubusercontent.com/33522630/123521708-98c05480-d6b8-11eb-953b-4251034cffed.png)

dev. version:
![image](https://user-images.githubusercontent.com/33522630/123521721-b4c3f600-d6b8-11eb-8a6e-cd6acd31407c.png)

**Comment by hbitteur** [comment]
Could you provide the input file, so that I can investigate what is happening?
I'm about to release a 5.2.2 (with additional UI features related to chords), but I would like to check your case.

**Comment by Bacchushlg** [comment]
Voila

![SCN_0006](https://user-images.githubusercontent.com/33522630/123523058-9c0c0e00-d6c1-11eb-8427-1256d3681159.jpg)

**Comment by hbitteur** [comment]
Danke!

**Comment by hbitteur** [comment]
Problem fixed in latest commit 68603e7808b72442b0b5e9e159d20703e2c9205f
(Development branch as usual)
