### ISSUE TITLE
Audiveris

### ISSUE THREAD

**Issue by Acapella-1** [Audiveris/audiveris#500]
Greetings --  
  I have recently installed the new version of Aud. and plan to be experimenting with it soon, after reading and trying to understand the Handbook.  BTW, IMOH  it is woefully Un-user-friendly (for us 'non-developers'), and seems to be written only for expert programmers!
  Anyway, I'm sure I will have questions about some of the functions of the program. I _did_ see a tutorial video showing an editing session, which was very helpful. 
  Just wanted to get confirmation that I'm in the right place to get help if I need it.   Please respond --  Thanks much.

**Comment by hbitteur** [comment]
@Acapella-1 
Could you elaborate on the "_woefully Un-user-friendly (for us 'non-developers')_" aspects of Audiveris?
If you have a concrete list of requests for enhancement, I'm personally interested to read them. We need something to start with.

I suppose the tutorial video is the one that Baruch made a couple of years ago. IMHO, it's a very good introduction for the end-user, although the software has evolved, so a new tutorial would make sense.

The handbook is still a work in progress, for at least a month or so. And meanwhile, some updates are needed on top of 5.2.1, a 5.2.2 release is planned for the coming week.

**Comment by Acapella-1** [comment]
Not sure where to start - there's so much that bears discussion --  **Some** examples are as follows:
1. Two tabs are mentioned, Binary & Data - doesn't seem to explain why there are 2 views, or the purpose of either
2. Steps - Doesn't explain when or how to use (and Not mentioned in the tutorial video)
3. Best example is probably found at Advanced Features > Options > Dialog.   An 'end user' would understand this?
The best way to answer your question, I guess, is to refer you to the email you sent me on 12/26 (attached) where you 
   answered a few questions for me, but most of them are not addressed here in the handbook .    

It really would help to have these procedures shown in a tutorial video.

[HBsDECemail.txt](https://github.com/Audiveris/audiveris/files/6787681/HBsDECemail.txt)
Respectfully,  Gary

**Comment by hbitteur** [comment]
> _Two tabs are mentioned, Binary & Data - doesn't seem to explain why there are 2 views, or the purpose of either_

Binary tab is for just binary input image, while data tab is for all objects detected by Audiveris so far.
See [handbook main_window section](https://audiveris.github.io/audiveris/_pages/main/main_window/)

> _Steps - Doesn't explain when or how to use (and Not mentioned in the tutorial video)_

Audiveris OMR engine works as a pipeline of 20 steps, each step focusing on a specific aspect (such as "heads recognition").
See [handbook pipeline secton](https://audiveris.github.io/audiveris/_pages/main/pipeline/)

> _Best example is probably found at Advanced Features > Options > Dialog. An 'end user' would understand this?_

This dialog is not meant for the beginner. It is listed under the "Advanced Features" specifically for that reason.

The only tutorial video that I know of is Baruch's small video which focuses on some UI features.
I agree that more tutorials would ease Audiveris learning curve. But so far, we don't have them.

Meanwhile, I'd recommend you to carefully read the handbook, even if it's still being worked upon, and start practicing Audiveris software. Many people have survived this exercise :-)
