### ISSUE TITLE
Partial beam

### ISSUE THREAD

**Issue by Acapella-1** [Audiveris/audiveris#505]
I had a good copy of  a short song, so Audi. did a decent job of transcribing, but I'm having a problem:

In the pic, I managed to fix the first 'flawed' beam in the (pink) measure, but it won't let me fix the next one. -  and why is it
only showing a segment?

![PartialBeam](https://user-images.githubusercontent.com/74429689/126886164-644900e4-631e-4a10-b14f-c071f0457b82.png)

**Comment by hbitteur** [comment]
@Acapella-1 
For any problem with beam recognition, I always begin by checking whether the SCALE step has been able to retrieve correct beam height.
Nota: you can always check scale results afterwards, for example by using `Sheet | Display Scale Plots` menu item which displays plots with scale legend saying something like:
- "Scale{line(2,2,3) interline(19,19,19) beam(10)}" *<= here beam is reliable*
- "Scale{line(2,2,3) interline(19,19,19) beam(10 **extra**)}" *<= here beam height is extrapolated and NOT reliable*
If beam height has been extrapolated, you can manually modify its value via `Sheet | Set Scaling Data`.

Now, even with correct typical beam height value, you may get some beams non recognized. I don't have the image input of your example, so I cannot investigate what really happened.

You said:
>  it won't let me fix the next one.

Sure you can fix it. You can assign, insert or edit a beam manually, just like any other Inter instance.

You said also:
> why is it only showing a segment?

Here, I don't know what is this "segment" you are referring to.

**Comment by Acapella-1** [comment]
Well, I just loaded it again, and it came up looking different.  Not sure if I corrected it -- it's not pink, but still shows a 'segment' -
meaning a 'portion' of the whole  (showing in Red)
  If you can't answer that last question, I'll be okay till the next problem occurs.
Thanks

**Comment by hbitteur** [comment]
Perhaps this "whole rest" was (wrongly) detected because the underlying glyph, which had not been recognized as a beam, was thus available for the symbols step. Just a guess of course.
Anyway, you can simply delete it, and proceed to the manual fix of the few unrecognized beams.

**Comment by Acapella-1** [comment]
Didn't consider the Red part being a rest (could be??)
It appeared to me to be a segment of the whole Beam. (Is there a reason that would happen?)
In Glyph Classifier section, it does show "HW_REST_set" as the first entry.
