### ISSUE TITLE
When to support jdk9?

### ISSUE THREAD

**Issue by wanghoppe** [Audiveris/audiveris#51]

**Comment by hbitteur** [comment]
I don't know.
What would be the benefits in a short term?

**Comment by webfischi** [comment]
The most important may be unicode support and automatic scaling on high DPI devices

**Comment by hbitteur** [comment]
Interesting. Could you elaborate on unicode support for musical symbols? How does this compare with the SMuFL initiative?

**Comment by webfischi** [comment]
All I found was [this](https://www.smufl.org/about/) looking at the "How SMuFL is organized" section. It seems to be an extension already. I thought maybe it could help with the rest and tempo OCR part. Unicode support could also make possible to write an own OCR for all languages, but like you already mentioned there is no time for it atm and my programming skills are way behind what's needed for sth like that. I'm happy, that I could create my own batch file to run Audiveris.

**Comment by JalonSolov** [comment]
[Unicode Musical Symbols](https://unicode.org/charts/PDF/U1D100.pdf)

**Comment by hbitteur** [comment]
@JalonSolov: What is the purpose of sending these [Unicode Musical Symbols](https://unicode.org/charts/PDF/U1D100.pdf)?
FYI, we have used this document as the reference for each and every name in Audiveris Shape class (NOTEHEAD_BLACK etc).
But, to my knowledge, this does not help us in OCR, symbol recognition or symbol rendering. Unless there is something I don't know about.
Could you elaborate?

**Comment by maximumspatium** [comment]
We recently decided to postpone any Java platform upgrades until the next LTS release (JDK 11). There is already the [java9](https://github.com/Audiveris/audiveris/tree/java9) branch containing a very early porting attempt. We plan to continue JDK upgrade as soon as JDK 11 become available.
