### ISSUE TITLE
'Korean' Menu and OMR... please

### ISSUE THREAD

**Issue by mailsjb** [Audiveris/audiveris#515]
I appreciate your program development. This version has significantly improved recognition rates.

However, there is one thing that is regrettable. That's what doesn't support '.

When you run the program, "Korean" comes out like this "ㅁㅁㅁ". Also, I don't recognize Korean lyrics, so I would appreciate it if you could improve this part.

Thank you again, and please apply for 'Korean'.

**Comment by hbitteur** [comment]
Have you tried to install and select Korean language in Audiveris?

If you don't know how to do this, have a look at this [HandBook section for general information](https://audiveris.github.io/audiveris/_pages/install/binaries/#additional-ocr-languages) and also [this one for Russian language](https://github.com/tesseract-ocr/tesseract).

I suppose that Korean data files are available at [https://github.com/tesseract-ocr/langdata/tree/main/kor](https://github.com/tesseract-ocr/langdata/tree/main/kor)

**Comment by hbitteur** [comment]
Any news?
Have you been able to include Korean with success?
If so, should we close this issue?
