### ISSUE TITLE
Repeats at beginning of line are interpreted as time-marker - impossible to reassign manually

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#52]
![blues and trouble](https://user-images.githubusercontent.com/33522630/35667401-d2098bc0-072d-11e8-85cb-4fbb0e70bc0b.jpg)

in the appended score the repeat at the beginning of line 2 is interpreted as 3/4-time marker. I can de-assign it but not assign as repeat (No ghost instance for LEFT_REPEAT_SIGN).

**Comment by hbitteur** [comment]
I confirm that manual re-assignment of barlines is not yet implemented.
It's only a matter of development priority, see [Perspective](https://github.com/Audiveris/audiveris/wiki/Perspective) section.
It's on the todo list...

**Comment by hbitteur** [comment]
Merged with issue #91

**Comment by Bacchushlg** [comment]
[Kalamatianos (jig) on The Session.zip](https://github.com/Audiveris/audiveris/files/1920335/Kalamatianos.jig.on.The.Session.zip)

I tried the last commit with a couple of scores. Most of them work fine "out-of-the-box" now, some need editing (remove "wrong" bar lines) which works fine. I'm happy!

This one does not!
I can remove the wrong detected "3/4" and replace with a repeat bar.
But in the export I still get the wrong "3/4" ?!?
And all repeat bars that appear in the beginning of a line are not exported (at least I don't get them in MuseScore).

**Comment by Bacchushlg** [comment]
intermediate state report (version 5.1.0:2e45a2935): the manually added repeat bar (last score) is now exported, but the manually removed 3/4 time is still in the export... (applies to both example scores)

**Comment by Bacchushlg** [comment]
the problem has been solved with one of the last versions
