### ISSUE TITLE
Bar lines overlooked (issues with score of Kospoth's Sym. C, 2nd Mvmt)

### ISSUE THREAD

**Issue by hmmueller** [Audiveris/audiveris#527]
Quite a number of bar lines are not recognized. However, when exporting as MXL and opening in MuseScore, most of them are repaired (wherever on the way), probably because a bar line in one system forces bar lines on all others (which is somewhat questionable for some music, but so be it). However, on sheet 4, bar lines are missed on all staves and hence not seen (in addition, missed triplet 3s mess up the rhythm - but that's [a different problem](https://github.com/Audiveris/audiveris/issues/526)).

I looked for some parameter like "minBarlineWidth" that I could reduce so that more lines are seen in this score; to no avail. Is there any "nudge parameter" that might help here?

Again, here are the zipped files (pdf, omr, log, mxl): [Scannen0017.zip](https://github.com/Audiveris/audiveris/files/7612063/Scannen0017.zip)

H.M.

**Comment by maximumspatium** [comment]
Hi Harald,

I had no big issues with the above score. Bar line recognition works out of the box for me.
I spent about an hour recognizing and fixing the score. Pretty good for a complete symphonic movement!
Here the files:
[Kospoth 2nd movement.zip](https://github.com/Audiveris/audiveris/files/8514145/Kospoth.2nd.movement.zip)

**Comment by hmmueller** [comment]
Thanks! - I'll have to retry it somewhen (I arranged - for piano - and performed only the 1st and 3rd movement, so this was not a big deal).

Harald M.
