### ISSUE TITLE
Acciaccaturas, appoggiaturas - and rests (issues with score of Kospoth's Sym. C, 1st Mvmt)

### ISSUE THREAD

**Issue by hmmueller** [Audiveris/audiveris#529]
"Small notes before a note" are hard to see and distinguish. In my Kospoth, there are only appoggiaturas ("langer Vorschlag", in German), which are the ones without a dash. All of them are written as eighths, which is probably wrong (the two in m.5 in the oboes should be quarters or halves, IMHO), but so it goes. 

Audiveris does not at all recognize the upper one in m.5, and thinks the lower one - in the 2nd oboe - is a quarter rest, which then somewhat garbles up the MXL. Could anything be done about this?

Pdf, omr, log, and mxl files, as usual, in a zip - only the initial 5 pages of this 25 page score: [Scannen0005_1-5.zip](https://github.com/Audiveris/audiveris/files/7612320/Scannen0005_1-5.zip)

H.M.

**Comment by maximumspatium** [comment]
Appoggiaturas aren't supported in Audiveris. You'd have to add them manually in MuseScore.

> Audiveris does not at all recognize the upper one in m.5, and thinks the lower one - in the 2nd oboe - is a quarter rest, which then somewhat garbles up the MXL. Could anything be done about this?

You would need to fix them manually using the Audiveris GUI before exporting as MusicXML...

**Comment by hmmueller** [comment]
Ok (although, they are frequent enough that, at some time, it would be nice if they - at least clearer ones - are recognized).

Harald M.
