### ISSUE TITLE
impossible to define triplets over quarter-notes manually

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#53]
![blues and trouble2](https://user-images.githubusercontent.com/33522630/35667555-65909e74-072e-11e8-89f9-b861b2a8e791.jpg)

The appended score contains a couple of triplets over quarter notes. It is not possible to define these triplets manually:
(TupletInter{#0 MANUAL(1.000) TUPLET_THREE} null sequence in TUPLET_THREE: 0
TupletInter{#7527 MANUAL(1.000) s:7 TUPLET_THREE} null sequence in TUPLET_THREE: 0)

**Comment by Bacchushlg** [comment]
no comment about this problem? Or is there a general problem to solve this?

**Comment by hbitteur** [comment]
I haven't studied this case yet, sorry.

**Comment by hbitteur** [comment]
Manual triplets assignment are now fixed by commit 8819bc01e08d31c83c38301a903d6457b752a7b5
All measures are OK, except measure 8 where time slots seem not correctly computed.
I need further investigation.

**Comment by Bacchushlg** [comment]
The reason for the latter problem is that the notes of the middle note line of measure 8 are not arranged correctly to the voices. Therefore the triplets cannot be correctly created, because a triplet is always concerning 1 specific voice
