### ISSUE TITLE
Dotted notes are hard to see for Audiveris (issues with score of Kospoth's Sym. C, 1st Mvmt)

### ISSUE THREAD

**Issue by hmmueller** [Audiveris/audiveris#530]
A fair number of dots is missed in this score (1st and 2nd violin in m.5, 2nd horn in m.7, 2nd violin in m.8 on the first page). Dots are small, true - but also here: Could anything be done about this? - as the wrong note lengths shift later notes in the resulting score quite a bit, and various music editors dont like this (Musescore is not that bad, because it assumes that all measures in all systems are of equal length; others dont do this ...)

Pdf, omr, log, and mxl files, as usual, in a zip - only the initial 5 pages of this 25 page score: [Scannen0005_1-5.zip](https://github.com/Audiveris/audiveris/files/7612326/Scannen0005_1-5.zip)

H.M.

**Comment by maximumspatium** [comment]
> Dots are small, true - but also here: Could anything be done about this?

I usually export a score as MusicXML, import it in MuseScore and play it back. Metrical problems as well as wrong/missing accidentals will be immediately audible. I then go back to Audiveris and fix them there. You can also inspect the recognized score visually using a larger magnification. I prefer to listen to the music instead.

**Comment by hmmueller** [comment]
Yes, of course. "Immediately audible" - well, since Gershwin's music fell out of copyright, we start to get quite interesting harmonies where errors are no longer that immediately recognizable, I'd venture ;-) - but of course, re-reading and re-listening to the score is necessary to find all problems. Still, dots are ... well ... anyone that is correctly recognized is one troublespot less :-)
