### ISSUE TITLE
Docker Image of Audiveris

### ISSUE THREAD

**Issue by ultraGentle** [Audiveris/audiveris#535]
In the spirit of #534, a related idea would be to make a Docker image to ease usage cross-platform.  

I'm just getting started with Docker, but if this is of interest, I'll report back if I make any headway.  

If others are more experienced with Docker, of course I'd welcome anyone to run with it!

**Comment by weidi** [comment]
You may have a look here, https://github.com/weidi/audiveris-docker and there https://hub.docker.com/r/toprock/audiveris
Right now i struggle to build it because of a dependeny problem mentioned in #540
