### ISSUE TITLE
Detection of Time_six instead of flag

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#539]
![Clipboard 1](https://user-images.githubusercontent.com/33522630/147380701-7c612f3b-6c2f-4303-9fb0-1834d5ecd2ef.jpg)

The score that I actually transcribe has problems with many "normal" flags. Instead, always "time_six" is detected on top position after selection of the glyph - which appear not logical at all to me. Maybe there is a wrong sample for time_six in the data base?

**Comment by hbitteur** [comment]
I supposed this was due to some wrong training sample(s).
Is it worth retrying with a recent Audiveris version? (5.3 was just released)

If not, we can simply close the issue.
