### ISSUE TITLE
detection of lyrics text above the note lines

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#55]
Audiveris does not expect lyrics above the note lines. In chorus notation this is rather common, esp. in the case that 2 voices share the same note line.
Maybe a feature like 
- select a part of text (by rectangle selection - shift + mouse)
- define this text as lyrics, with possibility to set the according voice number
- re-run the steps starting from "symbols" (because actually some lyrics text is "recognized" as symbols)
This would probably mean that the state before step "symbols" must be kept "in mind" - should be no problem I assume.

**Comment by webfischi** [comment]
This is already discussed in issue #44 the recognition is sometimes a little inaccurate because tesseract has problems with syllables. If you switch into development branch, you can select the affected word, deassign it and reassign it as text.

**Comment by hbitteur** [comment]
When you say line, I should understand staff, right?
The code in OMR engine that assigns text role uses a set of heuristics. And sometimes, result is not what you would expect in your special case. Typically, lyric lines are expected BELOW the staff not above.
Accordingly, your  lyrics line will not be recognized as such automatically.

Check if you can:
1. Deassign this line,
2. Force it to lyrics text (from the shape palette),
3. If your staff is first in system, chances are the lyric items will be linked with your staff below, since there is no staff above. (To be checked, I can't look at the code immediately)
4. If not, you can resort to link them manually.

**Comment by Bacchushlg** [comment]
![que sera sera 2](https://user-images.githubusercontent.com/33522630/35739347-979b1b16-0831-11e8-93fd-5416e34a26ee.jpg)

I tried to perform the hints above with this score (1st staff). The way how it should work is fine for me, but I don't get it functioning:

1. Deassign:  no problem. But I have to perform this multiple times, it seems that only one item is deassigned if I select a text line with multiple syllables.
2. Force to lyrics: not possible. 
I select the text and get the text selected. I see that now nothing is assigned (in the "Inter" section on the right). But when I press "lyrics" in the Shape section, nothing happens. Also I see a red cross while clicking on the "lyrics" button, that seems to tell me that this action is not allowed.

Another problem with the lyrics line above the bass staff of the first system: The lyrics line is attached as 2nd verse to the top staff. I don't expect that this is recognized automatically - but I did not find out, how to change this manually. Or have I do it syllable-by-syllable?

**Comment by hbitteur** [comment]
To force to lyrics, you have to select the desired glyphs, then DOUBLE-CLICK on the lyrics icon in shape palette.
These icons are meant for drag n' drop, and double-click. Some shape icons are not draggable (hence the red cross when you try to drag them), and you can just use the double-click. This is the case for all non-fixed-size shapes, and lyrics is one of them

**Comment by hbitteur** [comment]
IIRC, lyrics are linked by OMR engine to chords ot the staff just above.

You can manually change the link, syllable by syllable, by dragging relation from syllable to targeted chord. Don't forget to remove the previous links, they are not automatically removed (I could implement this removal)

**Comment by hbitteur** [comment]
Just for my understanding,  what would be the correct lyrics assignment for each of the 4 lyric lines of the top system ? 
Perhaps:
Line 1 and line 2 to top staff
Line 3 and line 4 to bottom staff

**Comment by Bacchushlg** [comment]
Correct, plus:
- line 1: voice 1, top staff
- line 2: voice 2, top staff
- line 3: voice 1, bottom staff
...

**Comment by Bacchushlg** [comment]
Maybe it would be a good idea to have a new entry in book-parameters list: 
"detect lyrics above staff"
Because, normally lyrics are below the staff, but unfortunately in chorus scores the combined staffs for 2 voices are rather common.

**Comment by Bacchushlg** [comment]
![wrong voices assignements for lyrics](https://user-images.githubusercontent.com/33522630/35905326-f0dd9e0c-0be6-11e8-8cb0-78a35f2a20c4.jpg)

The lyrics coloring to display the relation to the voices is a great improvement!
Now you can directly see the above described problem in the logical mode view. As you can see, almost all syllables are correctly detected! The only "missing link" is the possibility to correct the assignment.

What about the following idea: 
- select a lyrics line with a selection rectangle
- provide a new context menu item: "link to" with the list of detected staffs and the voice list for each staff.

**Comment by hbitteur** [comment]
Today, the user can modify the syllable/chord link manually. But this has to be done for each syllable in the lyrics line.
Your proposal is to make this possible at the whole line level, and I think it's a very good idea. To be effective, I first need to improve what I call "voice continuity" in measure sequence (to avoid jumps in voice IDs from one measure to the following one, something that definitely needs improvement).

**Comment by Bacchushlg** [comment]
That sounds very good. And by this way you would "zwei Fliegen mit einer Klappe schlagen" (faire d'une pierre deux coups).

**Comment by Bacchushlg** [comment]
What I have forgotten in the list above:

- select a lyrics line with a selection rectangle
- provide a new context menu item: "link to" with the list of detected staffs and the voice list for each staff.
- provide a 2nd menu item that allows to change the verse # (can be set to 1 by default).

**Comment by Bacchushlg** [comment]
problem has been solved with the last versions
