### ISSUE TITLE
First page not transferred to XML

### ISSUE THREAD

**Issue by jonarnoldmusic** [Audiveris/audiveris#552]
I'm working on a choral piece in which the first page looks fine in Audiveris, but only one measure out of five transfers to MusicXML. I've attached my OMR file as a ZIP.
[br600dpi.zip](https://github.com/Audiveris/audiveris/files/8050458/br600dpi.zip)
.

**Comment by hbitteur** [comment]
What is your version of Audiveris?

**Comment by hbitteur** [comment]
5.2.5 on Windows according to your .omr file
OK, I will check

**Comment by jonarnoldmusic** [comment]
Thanks! I should have also mentioned there is a measure inserted incorrectly- the measure that does transfer to XML is measure 4 in the paper score but measure 5 in the XML.

**Comment by hbitteur** [comment]
Fixed in development branch, see commit dc70df28db18645af4158883903765d68274b795.

There was a bug in GRID step when handling braces vertically aligned with grouping brackets on first sheet.
