### ISSUE TITLE
Is there any plan to support transcribing music sheets as a library instead of an application?

### ISSUE THREAD

**Issue by JamesChenX** [Audiveris/audiveris#553]
Thank you very much for this really wonderful repo.
I have viewed the code of `audiveris` and it doesn't decouple the logic of OMR from UI, so it's hard to integrate `audiveris` in other applications and I want to confirm that is there any plan to support transcribing music sheets as a library instead of an application? Maybe something like:
```java
String musicXml = Audiveris.transcribe(mySheetImage, someOptions);
```
Thanks.

**Comment by JamesChenX** [comment]
Thank you for your quick reply.
### Scenarios
* It's okay for us to not use the UI of `Audiveris` because we want to provide a Web that has a feature for users to upload their sheet images, and the backend server will respond to the HTTP request with the data of MusicXML from `Audiveris` and the users can correct the sheets in MusicXML via the simple sheet editor on Web or download it to correct it in a more powerful editor like `MuseScore`.
* If the input image file contains several movements, the server can respond with a zip file containing separate MusicXML files. The code above for `Audiveris` is just an example and it can also be:
```java
List<String>results1 = Audiveris.transcribeToStrings(mySheetImageInputStream, someOptions);
// or
List<byte[]>results2 = Audiveris.transcribeToByteArrays(mySheetImageInputStream, someOptions);
```
so that we can handle it to deliver the byte data to users via HTTP.
### What we have done
In fact, we have implemented a similar simple feature like `byte[] data = Audiveris.transcribe(mySheetImageInputStream);` without consuming and creating any files on the local filesystem for better performance by modifying a lot of the code of `Audiveris` in a little hacky way, but it's buggy and not a robust way to maintain.

### Solution
So we would be very appreciative if Audiveris can do some improvements to work as a library without UI to support consuming an InpuStream and output the MusicXML data like the code above without creating temporary files in a clear way. And I mention this because I found there are a lot of classes using `File` and cannot just consume `InputStream` currently (e.g. `org.audiveris.omr.sheet.Book` and `org.audiveris.omr.image.ImageLoading`) and it's better to decouple the logic of OMR from UI for better maintainability when working as a library.
Though we have modified the code of `Audiveris` to support such a feature it's buggy and not robust.

But it's fine if `Audiveris` does have a plan for it today and we will try to figure it out.
Thanks for your advice and the wonderful repo anyway :)

**Comment by hbitteur** [comment]
> It's better to decouple the logic of OMR from UI for better maintainability especially when working as a library.

Let's put it that way:
1. There is indeed an underlying data model. It's basically the SIG (Symbol Interpretation Graph), a graph of potential interpretations linked by relations. There is one SIG instance allocated for each system in the score.
2. OMR engine and OMR UI are separate actors, they both operate on this data model. They are or course coupled with the data model but rather decoupled from one another.
3. You can well run the OMR engine without any UI. It's the -batch option of Audiveris application. This would typically be the library approach.
4. When used, the OMR UI can trigger the OMR engine via key entry points. For example to update the measure rhythm data when the duration of a note has just been manually modified. If you are curious at code level, each defined engine Step has a public *impact()* method, specially meant for this.

**Comment by JamesChenX** [comment]
Thanks for your kind explanation of the difference between SIG and OMR UI.
I will adapt `Audiveris` so that we can integrate `Audiveris` into our server application without openning a process of `Audiveris`.
