### ISSUE TITLE
File .mxl is not a valid MusicXML file

### ISSUE THREAD

**Issue by Tobertet** [Audiveris/audiveris#556]
Hello everyone, I'm trying to convert some PDFs to musicXML but it looks like the conversion results in invalid musicXML files.

Here is one of the examples: 
[Chant.pdf](https://github.com/Audiveris/audiveris/files/8108736/Chant.pdf)

The .mxl file is created, but when I try to open it using MuseScore it complains about the file not being valid. The command musicxml2ly also complains about the same.

I am using Linux and executing the docker image https://github.com/weidi/audiveris-docker. I already posted an issue there but I was redirected here since the error does not seem to be caused due to the image.

Unfortunately, I don't own a Windows. Can someone try it in Windows and let me know if it works? I don't know how to proceed.

**Comment by Tobertet** [comment]
Digging a little bit more in the error, MuseScore is complaining specifically about:
`Fatal error: line 72 column 44 Namespace prefix 'xsi' not declared`

Meanwhile, musicxml2ly complains about the following:
`xml.parsers.expat.ExpatError: unbound prefix: line 76, column 10`

**Comment by hbitteur** [comment]
@Tobertet 
I can't reproduce this problem with Audiveris latest version (5.3-alpha) under Windows.
Your examples (Chant.pdf and test.pdf) are correctly transcribed and exported to MuseScore.

See the resulting Chant.mxl in Chant.zip below
[Chant.zip](https://github.com/Audiveris/audiveris/files/8123546/Chant.zip)

Could you specify your environment (using Help | About) and especially Audiveris version number?

**Comment by Tobertet** [comment]
Hi @hbitteur, thanks for your response.

I am using Audiveris from a docker image specified [here](https://github.com/weidi/audiveris-docker/blob/master/Dockerfile), from there I can see that the environment is:

Debian using Oracle JDK 17 with tesseract-ocr installed.
I don't know the Audiveris version number, but they are using the development branch. Maybe they should be using the master branch or a commit that specifies a new version.

Could you confirm that the .mxl is correct if you use the development branch version?

**Comment by Tobertet** [comment]
I just builded the Audiveris binaries and executed them on my machine. I'm using 5.3-alpha under Linux Mint. This is the output of the help command:

```
- Audiveris:    5.3-alpha:63747c78e
- OS:           Linux 5.4.0-100-generic
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
- OCR Engine:   No OCR is available!
```

When I import this file 
[SchbAvMaSample.pdf](https://github.com/Audiveris/audiveris/files/8126628/SchbAvMaSample.pdf)
and export the .mxl I get an error in the console:
```
WARN  [SchbAvMaSample]           PartwiseBuilder 1782 | Error visiting Measure{#1P2} in {Page#1.1}
java.lang.IllegalArgumentException: no such vertex in graph: RestChordInter{#9782 REMOVED(0.373/0.373) stf:2}
```

And the .mxl produced is corrupted. MuseScore says this:
```
Measure 1, staff 1 incomplete. Expected: 77/64; Found: 7/4
Measure 8, staff 2 incomplete. Expected: 17/16; Found: 0/1
Measure 8, staff 3 incomplete. Expected: 17/16; Found: 0/1
```

I also installed tesseract-ocr

**Comment by hbitteur** [comment]
I just checked, you are using the latest version of Audiveris in development branch.
With the same version (but running on Windows), I can process the same input as yours (SchbAvMaSample) with  no big difficulty.
- I selected the option "Support for implicit tuplets" in book parameters because most of the tuplets are implicit
- Then I had to make a few manual corrections (a 16th rest not recognized, and some triplets no recognized resulting in pink measures), and that's about it.

And no problem when exporting to MuseScore.

So, what happened in your case? 
I suppose you had to make a few corrections as I did, so that no measure was left in pink background. What else?

Could you post the .omr file so that I can have a look at its content, and compare with mine.

**Comment by Tobertet** [comment]
Here is the .omr
[SchbAvMaSample.zip](https://github.com/Audiveris/audiveris/files/8133244/SchbAvMaSample.zip)
 
I also selected the "Support for implicit tuplets". However, it seems like my problem is derived from the text not being recognized. It understands some characters as rests and other glyphs.

Also, I see that I am receiving an error "No OCR is available!". I have installed tesseract with both English and German extensions. However, I didn't set up the variable TESSDATA_PREFIX since the documentation only specifies to do it on Windows. Could that be the problem?

**Comment by hbitteur** [comment]
@Tobertet 
Any new on this?

Indeed, if you can't use OCR, then text symbols will try to be considered as music symbols.
Could you confirm?

**Comment by Tobertet** [comment]
@hbitteur that's right, the OCR was interpreting the text symbols as music symbols. Simply adding the TESSDATA_PREFIX made it work.

I would suggest that the documentation mentioned this environment variable for every OS and not only Windows.

Thank you, I'm closing this issue
