### ISSUE TITLE
Version 5.2.5 did not start

### ISSUE THREAD

**Issue by gunternulp** [Audiveris/audiveris#560]
After Update from 5.1.? to 5.2.5 programm start aborted with this known error message:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Audiveris has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 ...
I considered issues #225, #511, #544 with environment adjustments, java 11 installation etc. wit no success.

Microsoft Windows [Version 10.0.19044.1566]
Java pathes
C:\Program Files\Java\jdk-11.0.14
C:\Program Files\Java\jre1.8.0_321

Thanks in advance

The Gnulp

**Comment by gunternulp** [comment]
Problem solved!
After some reboots it works unexpectedly

**Comment by hbitteur** [comment]
The culprit must be the jre 8 (not consistent with your jdk 11)
Audiveris 5.2 requires Java (jre) 11

**Comment by Mike-the-french** [comment]
Hi,
I have the same problem. I've just installed jre-1.8 and audiveris. The program aborts when launching.
regards
Mike-the-french

**Comment by Mike-the-french** [comment]
Seems that Audiveris 5.2.4 works installing JDK-21 in place of JRE-1.8 ... Amazing !
Mike-the-french

**Comment by hbitteur** [comment]
Latest release (5.3) requires Java 17
It may work with higher Java versions
