### ISSUE TITLE
NPE when scanning two pdfs

### ISSUE THREAD

**Issue by aschoerk** [Audiveris/audiveris#561]
Hello referencing measures by staff sometimes return null. 
The consequence is, that the scanning completely fails and the result is not usable.

I worked around it, by avoiding the subsequent processing, if interested, I can create a pull-request for that, but I am not capable of solving the main problem.

[Noten6.pdf](https://github.com/Audiveris/audiveris/files/8259997/Noten6.pdf)
[Noten13.pdf](https://github.com/Audiveris/audiveris/files/8259998/Noten13.pdf)
.

**Comment by hbitteur** [comment]
@aschoerk 
I just ran latest Audiveris development version on these two PDF files, it worked OK.

What is your version of Audiveris? Use Help | About pulldown menu.
I'd advise you to pull and build from development branch, to make sure you get the latest version.

**Comment by aschoerk** [comment]
Did you only load these files or did you also try to transcribe. The only change I was able to pull was a document change from February 10.

**Comment by aschoerk** [comment]
AHhhhhh,
sorry. I will use that, thank you very much. Probably should have read some documentation, before checking out.
