### ISSUE TITLE
Audiveris 5.2 not converting further PDFs to XML after error with previous PDF

### ISSUE THREAD

**Issue by BenjaminHerrera** [Audiveris/audiveris#562]
I'm trying to convert a folder of 234 PDFs to MusicXML and the only quickest way is to run instances of Audiveris in parallel. My python script for running these instances works, but upon a couple PDFs have been exported to MusicXML, one PDF repeats the following error

```
2022-03-27 22:52:46,456 WARN [1135a]      PartwiseBuilder.java:2630 | Error visiting System#4 in {Page#6.1}
java.lang.NullPointerException: null
	at org.audiveris.omr.sheet.Part.createDummyPart(Part.java:342)
	at org.audiveris.omr.score.PartwiseBuilder.processSystem(PartwiseBuilder.java:2614)
	at org.audiveris.omr.score.PartwiseBuilder.processLogicalPart(PartwiseBuilder.java:1497)
	at org.audiveris.omr.score.PartwiseBuilder.processStub(PartwiseBuilder.java:2564)
	at org.audiveris.omr.score.PartwiseBuilder.processPartList(PartwiseBuilder.java:2175)
	at org.audiveris.omr.score.PartwiseBuilder.processScore(PartwiseBuilder.java:2359)
	at org.audiveris.omr.score.PartwiseBuilder.build(PartwiseBuilder.java:2876)
	at org.audiveris.omr.score.ScoreExporter.export(ScoreExporter.java:117)
	at org.audiveris.omr.score.ScoreExporter.export(ScoreExporter.java:91)
	at org.audiveris.omr.sheet.Book.export(Book.java:559)
	at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:549)
	at org.audiveris.omr.CLI$CliTask.call(CLI.java:643)
	at org.audiveris.omr.Main.runBatchTasks(Main.java:379)
	at org.audiveris.omr.Main.main(Main.java:167)
	at Audiveris.main(Audiveris.java:49)
```

Afterwards, newly created instances are formed with different PDFs, but then become stuck. What they usually output is this:

```
2022-03-27 22:52:50,204 INFO  []                      Main 401  | Environment:
- Audiveris:    5.2.5:09bbb8236
- OS:           Windows 10 10.0
- Architecture: amd64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 11.0.13+10-LTS-370, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
2022-03-27 22:52:50,221 INFO  []                       CLI 269  | CLI args: [-batch, -export, -output, .\mxml_unsorted, .\pdf\1238a.pdf]
2022-03-27 22:52:50,319 INFO  []             AliasPatterns 131  | Alias patterns: [(IMSLP[0-9]*)-.*]
2022-03-27 22:52:50,321 INFO  []                      Main 158  | Running in batch mode
2022-03-27 22:52:50,329 INFO  []                  Versions 392  | Versions. Poll frequency: Weekly, next poll on: 04-Mar-2022
```

Nothing else outputs for hours on time. I'm currently running the latest version of Audiveris with Java 11. Any help is appreciated. Thanks.

**P.S.**
The following is my python script for running converting PDFs to MusicXML:

```py
# Imports
from pathlib import Path
import subprocess
import time
import json
import os

# Get list of files in the /pdf/ directory
files = next(os.walk("./pdf/"), (None, None, []))[2]

# Instance and variable initialization
processes = set()
MAX_PROCESSES = 3
PROGRAM = "C:\\Program Files\\Audiveris\\bin\\Audiveris.bat"

# Check if tracker.json exists
# If not, make one
if not(Path("tracker.json").is_file()):
    # Create the file
    with open("tracker.json", "w") as out:
        # Write empty list to it
        json.dump({"track": []}, out)
    
# Open tracker.json
tracker_file = open('tracker.json', 'r')

# Get contents of tracker file
tracker = json.load(tracker_file)

# Get difference
files = [item for item in files if item not in tracker["track"]]

# Iterate for every file in /pdf/
for count, item in enumerate(files, 1):
    # Print status message
    print(f"OMR started for {item} | {count}/{len(files)}")
    
    # Append item to tracker list
    tracker["track"].append(item)
    
    # Write to file
    with open("tracker.json", "w") as out:
        # Write empty list to it
        json.dump({"track": sorted(tracker["track"])}, out)
    
    # Execute Audiveris in its own thread
    processes.add(subprocess.Popen([f"{PROGRAM}", "-force", "-batch", "-export", "-output", ".\\mxml_unsorted", f".\\pdf\\{item}"]))
    
    # Enter while loop if the number of processes is greater than or equal to max number of processes
    while len(processes) >= MAX_PROCESSES:
        # Sleep for a bit
        time.sleep(2)
        
        # Update processes when a process is finished
        processes.difference_update([p for p in processes if p.poll() is not None])
```

**Comment by hbitteur** [comment]
@BenjaminHerrera 
I can't really help you on your Python script, so I don't understand why all the following Audiveris processes seem to get stuck.
Let's first find out why your first example raised an NPE. Please post the input file so that I can debug it.

**Comment by BenjaminHerrera** [comment]
@hbitteur 

Surprisingly, as you sent that message, I debugged the issue down to when Audiveris checks for new versions.

The way the python script works is that it will initiate a new instance of Audiveris. When each instance of Audiveris is created, it always poll for a new version update. This occurs in `org.audiveris.omr.sheet.Versions.getLatestRelease()`. By the looks of it, Audiveris connects to GitHub anonymously to check for updates. This is an issue as after each successful operation, a new instance of Audiveris will form by the python script, which will connect GitHub again. Repeated connections to GitHub will cause a "Too many packets sent" error, which will make all other newly created instances hang. 

A solution that I found would be to set  `org.audiveris.omr.sheet.Versions.releaseCheckFrequency` to Never. That way, `org.audiveris.omr.sheet.Versions.getLatestRelease()` is never called which will stop the anonymous connections to GitHub.

**Comment by hbitteur** [comment]
Bravo for your debugging!

Setting `releaseCheckFrequency `constant to `Never` is indeed a workaround, but this may be an overkill.

- If you set this constant interactively, the new value is persisted on disk and no release check will ever be made again automatically (although you can still manually check for update).
- If the constant is set via the CLI parameter `-option` while running in `-batch` mode, the constant modification is done only for the duration of the batch and is not persisted on disk.

FYI, when a releaseCheck is made, the Date when this check is made is recorded, precisely to avoid repetitive checks. Hence the notion of releaseCheckFrequency. So far, so good.
However, this date is recorded as the `org.audiveris.omr.sheet.Versions.lastReleaseCheckDate` constant which, like any other constant, is persisted on disk:
- ALWAYS at the end of an interactive session
- NEVER at the end of a batch session, unless the constant `org.audiveris.omr.Main.persistBatchCliConstants` is set to true (and its default value is ... false)

So, in your case of repetitive batch jobs, the modified lastReleaseCheckDate constant never got written to disk, and each batch job considered only the old (unmodified) value and thus made the check to GitHub.

**Comment by hbitteur** [comment]
Perhaps, Audiveris update check policy could be modified as follows:
- ON by default for interactive sessions
- OFF by default for batch sessions

There are pros and cons...
Any ideas?

**Comment by hbitteur** [comment]
Meanwhile, we still have to investigate your initial NPE error. We just need the input file.

**Comment by BenjaminHerrera** [comment]
Oh yeah, I forgot to add that to my previous comment. 
[1135a.pdf](https://github.com/Audiveris/audiveris/files/8382424/1135a.pdf)
