### ISSUE TITLE
Audiveris not opening

### ISSUE THREAD

**Issue by RayReddingtonx** [Audiveris/audiveris#587]
Why is my audiveris not opening? Audiveris_Setup-5.2.5-windows-x86_64 
Windows 10, 64bit. 
jre-8u341-windows-x64 is my java

do I need Java 17 or 19 versions (from here https://www.oracle.com/java/technologies/downloads/#jdk19-windows ) which is very different and I dont know what it is, coz the audiveris download site directed me to the latest regular Java page. 

PS: I installed audiveris in another drive to save space in C://

**Comment by hbitteur** [comment]
You need **Java 17**.
(Java 19 may be OK as well, but has not yet been tested with Audiveris

**Comment by RayReddingtonx** [comment]
help: Plugins not loading. I made the plugins.xml using notepad+ but it's showing error in loading that file. The content of the plugin file is from here https://audiveris.github.io/audiveris/_pages/advanced/plugins/ 

> Error loading C:\Users\CORSAIR\AppData\Roaming\AudiverisLtd\audiveris\config\plugins.xml
> Classifier loaded XML norms.
> Classifier data loaded from default uri jar:file:/F:/Prog%20Files/lib/audiveris.jar!/res/basic-classifier.zip
> Versions. Poll frequency: Weekly, next poll on: 30-Sep-2022

**Comment by RayReddingtonx** [comment]
It's hardly able to view it, it's not worth trying, i cant manually edit each thing. It's better I can manually transcribe on musescore. 

![200 Short Two-Part Canons, Op 14 (Kunz, Konrad Max)#4-ext](https://user-images.githubusercontent.com/87129806/191989525-bfd29bd8-479b-4413-9b8b-93ba7b493b19.png)

**Comment by hbitteur** [comment]
> help: Plugins not loading. I made the plugins.xml using notepad+ but it's showing error in loading that file. The content of the plugin file is from here https://audiveris.github.io/audiveris/_pages/advanced/plugins/
> 
> > Error loading C:\Users\CORSAIR\AppData\Roaming\AudiverisLtd\audiveris\config\plugins.xml

The plugins.xml file presented in documentation is just an example.
Could you post your own version so that we can help you.

**Comment by hbitteur** [comment]
> It's hardly able to view it, it's not worth trying, i cant manually edit each thing. It's better I can manually transcribe on musescore.

I suspect a poor quality input. Try to feed Audiveris with a better image of the score.

**Comment by RayReddingtonx** [comment]
Its my plugin file, earlier I put it in a wrong folder so it was showing NO file found in the plugins/xml. 

>  <?xml version="1.0" encoding="UTF-8"?>

<plugins>

    
    <plugin id="MuseScore" tip="Invoke MuseScore on score XML">
        <arg>C:\Program Files\MuseScore 3\bin\MuseScore3.exe</arg>
        <arg>{}</arg>
    </plugin>

    
    <plugin id="Finale" tip="Export to Finale">
        <arg>C:\Program Files (x86)\Finale 2014\Finale.exe</arg>
        <arg>{}</arg>
    </plugin>

    
    <plugin id="Finale Notepad" tip="Export to notepad of Finale">
        <arg>C:\Program Files (x86)\Finale NotePad 2012\Finale NotePad.exe</arg>
        <arg>{}</arg>
    </plugin>

    
    <plugin id="PriMus" tip="Use of PriMus">
        <arg>C:\Program Files (x86)\PriMus Demo\PriMus.exe</arg>
        <arg>{}</arg>
    </plugin>

    
    <plugin id="EasyABC" tip="Export to EasyABC">
        <arg>C:\Program Files (x86)\EasyABC\easy_abc.exe</arg>
        <arg>{}</arg>
    </plugin>

    
    <plugin id="Forte" tip="Forte 9 Free">
        <arg>C:\Program Files (x86)\FORTE\FORTE 9 Free\FORTE.exe</arg>
        <arg>{}</arg>
    </plugin>

</plugins>

**Comment by hbitteur** [comment]
No news on this issue.
Should we close it?
