### ISSUE TITLE
Request: support for multiple-rest

### ISSUE THREAD

**Issue by RensBloom** [Audiveris/audiveris#593]
In pieces with more than one musician, it's common to have rests that take multiple measures. I see that Audiveris recognizes long, breve and whole rests, or I can assign it manually 
![image](https://user-images.githubusercontent.com/5883286/201633982-4177f9eb-6951-438f-a0ce-a44f6f585b44.png)
Nevertheless when I export the musicXML, it is found with a `<rest>` element instead of a `<multiple-rest>` [element](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/multiple-rest/), hence my music editor imports the XML incorrectly and the measure numbers at the start of each staff are incorrectly.
```<note default-x="89">
        <rest measure="yes">
          <display-step>B</display-step>
          <display-octave>4</display-octave>
        </rest>
        <duration>48</duration>
        <voice>3</voice>
      </note>
```

Besides that, I don't see an option in Audiveris to assign rests that consume multiple measures, as indicated with a number, such as this one. Would it be possible to add it as well?
![image](https://user-images.githubusercontent.com/5883286/201636810-fa1d7181-29c7-4e5e-8ab5-6dbb8fb936fc.png)
 
I am aware that it might be complex to implement, since all measure numbers should be recalculated as well based on user input (I guess it would be really hard to recognize the correct number with such a multi-measure rest).

**Comment by hbitteur** [comment]
Regarding the multi-measure rests (long horizontal line with a measure count), there is a _partial support_ in development version. See commits 93a12390b255e6852c19de477c26f893e18e8aa0 and bbf43f5cc6cb8806499e08aedd34a5192fc8e1f6 pushed on May 19.
Here "partial support" means the data model is OK and some detection might work. But there is yet no UI code to deal with this new feature.

I have been interrupted to work on full support for drums notations, a development not completed yet.
Please be patient...

**Comment by hbitteur** [comment]
These multi-measure rests are  now supported.

Audiveris 5.3 is released.
Please pull and build or use Windows installer.

Closing the issue.
