### ISSUE TITLE
Improve recognition of void heads

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/audiveris#60]
Recognition of note heads is done via "template matching" technique. I have no precise numbers about which head shapes are best recognized, but I often noticed that void heads are not on par with black heads.

The void shapes are the ones with a "white hole" in them, examples are NOTEHEAD_VOID, WHOLE_NOTE and BREVE (not yet implemented), as opposed to NOTEHEAD_BLACK.

The void heads are often not recognized or mistaken for black heads.

**Comment by Bacchushlg** [comment]
I noticed this problem several times, too.
I think there are 2 different cases:
- void heads on a staff line: in this case they are sometimes recognized as black heads (esp. half notes).
- between staff lines (esp. full notes): they are not recognized at all, because the upper and lower circle part are not recognized as part of the head. After step "heads" there are a couple of small note heads...

For the first case, it might be helpful to calculate a probability value that this head is full or void. A rhythm check in a later step (reduction ?) could then decide: void or full.

For the second case, maybe it makes sense to have a pattern of 2 half circles (the left and right part of a full void head) as reference pattern.

**Comment by hbitteur** [comment]
When you say "_full_" head, I think I should understand "_whole_" head, correct me if I'm wrong.

I have identified a few tracks for improvement of both void heads and whole heads, still using the template matching technique. Probably the use of patch classifier in future 6.x release (which is planned for end of this year) will totally overpass this technique, so I'm not keen on switching to the use of half circles for a very temporary usage.
Could you forward me several representative examples of void and especially whole heads, so that I can fine tune the parameters?

The OMR engine already plays with probabilities. For some time, I tried to rely on the RHYTHMS step to solve everything in a kind of "Big Reduction" but, after many long months of fighting, I had to give up and fall back to the more incremental approach we have today.

**Comment by hbitteur** [comment]
A significant improvement has been brought by commit 51fb896754fa0952d87fe80fdad5238b8e10178b which consisted in a more precise definition of templates descriptors and anchors locations.
I also simplified the matching algorithm, it is now more basic but provides better results in the end!

Here are the current results:
- Image with many triplets:
  22 halves, 22 recognized
- Amazing Grace:
  62 halves, 59 recognized, 1 mistaken for a small head, 1 mistaken for a black, 1 missing
- Ding-a-Dong3:
  25 halves, 18 recognized, 2 mistaken for black, 5 missing
  10 wholes, 10 recognized
- Dust in the wind: 
   23 halves, 5 recognized, 17 mistaken for black, 1 missing   
   23 wholes, 18 recognized, 5 missing

Can we go a little further?
A frequent "reason" for mistaking a void head for a black head might be the presence of staff line chunks right in the middle. Yet, during the matching evaluation, pixels from staff lines, ledgers and stems are "neutralized" but this may not be sufficient, especially with poor-quality sheets for which pixels are not clearly assigned to a staff line but are considered as part of some crossing object. Perhaps we could work around this problem by boosting good grade when "some pieces of white" are indeed found where a hole was expected? 

Is it worth it? I don't know.

**Comment by hbitteur** [comment]
@Bacchushlg 
You said: "After step "heads" there are a couple of small note heads..."
Of course, purpose of HEADS step is to retrieve good head _candidates_. Some will get support (and increase their contextual grade) via the next step (STEMS).
The REDUCTION step will finally discard the too weak entities and resolve any conflicts.

That's the way it works: the engine cannot immediately decide on the relevance of an item, because it may depend on other items nearby, which have not yet been detected.

**Comment by Bacchushlg** [comment]
great improvement! Merveilleux!
About the still not detected half notes: the main reason seems to be the bad quality of the stems. I have added some stems manually in the image, and then almost all of them are recognized!

About the proposual about these "some pieces of white": I think, that is a good approach. Maybe you can calculate some sort of mean value for the normal quality of black heads (of the actual image), and from this value calculate a percentage value for the expected white within a void head?

**Comment by hbitteur** [comment]
I prototyped a kind of "white pixel" boost but the results were much worse than the current version. Too bad. 

Could you elaborate on your proposal? I don't really understand the role of percentage value here.

**Comment by Bacchushlg** [comment]
I don't know how detection of the note head is performed. Is it pattern matching, or do you detect the oval shape of the note head and start evaluation from this?
- In case of pattern matching, my proposual makes no sense. In that case it seems to be the best to have some more "bad" pattern for void note heads.
- In case of shape detection I would expect that you calculate the percentage of black pixels inside the oval shape and from a certain percentage decide for a black head. This was, what I head in mind when writing the proposual above.

**Comment by hbitteur** [comment]
For note heads, it's template matching only.

In crowded poor quality sheets, don't even dream of finding ovals! Reality is that you just get big blobs on no precise shape.

**Comment by hbitteur** [comment]
Results are not perfect and never will be especially on poor scores, but are acceptable now.
Closing this issue,
