### ISSUE TITLE
Rest symbol showing up in Audiveris Music Scanner program does not export to musicXML

### ISSUE THREAD

**Issue by 8Itsuki8** [Audiveris/audiveris#603]

**Comment by hbitteur** [comment]
Could you further describe the problem you encountered?
- Environment
- Audiveris version
- Input image
- The rest symbol which was not exported to MusicXML

This would help!

**Comment by hbitteur** [comment]
Already 3 weeks passed, still no description, no concrete example provided.
Closing this issue.
