### ISSUE TITLE
re-arrange notation lines in complex scores

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#608]
[Say Ladeo.pdf](https://github.com/Audiveris/audiveris/files/10365834/Say.Ladeo.pdf)

In some cases - especially in choir scores - the arrangement of the voices is not static but varies from line to line (see the appended score).
Of course it is impossible for the transcription to the detect the correct arrangement.
Therefore I propose a possibility to re-assign the notation lines: 
After transcription of a complete score the user should see the detected assignment of the lines to the voices (or instruments) as detected in the first system of page 1 (which mostly shows all voices / instruments - but unfortunately not always).
In display mode _mix_ and _output_ the detected voices should be displayed together with the display of the system number (S1, S2,...). A click (or right click) on this voice item opens a dialog, displaying the available voices and let the user select the correct one.

The ideal solution would give an editing possibility inside this dialog, allowing to correct the voice texts (and maybe even to define the short item texts for the voices/instruments that used for all but the first lines for the output score)

**Comment by hbitteur** [comment]
OK, it took me a few minutes to understand. But looking at the provided score, things got much clearer.

"Translated" into Audiveris data model, this gives:
Provide the user with an interactive means to manage the definition of the various logical parts (full part name and abbreviation if any) and their dispatching as physical parts in each of the score systems.

Christmas time is over, but this feature sounds doable. :-)

**Comment by hbitteur** [comment]
Just playing with your example, I noticed that text is rather badly recognized by OCR.
This may be related to the font used in this score (it looks like a Jazz font).
On Internet, there seems to be ways to train Tesseract on specific fonts, something I never attempted so far.
I'm putting this question apart for the time being but will keep it in a corner of my mind.

**Comment by hbitteur** [comment]
@Bacchushlg 
I need some advice.
Here is a mockup of  logical part definition:
![image](https://user-images.githubusercontent.com/22053634/212537464-3e3da486-7c6c-4904-aeca-a00927d00676.png)

Let's imagine that we can easily update its fields (which I did) but also add new lines as desired, to come up with a complete and correct definition of the list of logical parts for the score at hand [and not just for the system at hand, as wrongly indicated by the dialog title, sorry it's just a quick & dirty exercise]

Now the question is: what would be the best gesture for the end user to map a physical part in a given system to its proper logical part?

We can imagine to add an item in the current popup menu, activated by a right click on some physical part. Then the user could navigate to 1/ the action to map the underlying physical to 2/ a logical part properly selected in a combo list. This can work, is easy to implement, but is not a very convenient gesture for the end user.

Wouldn't it be more convenient to operate the other way around? That is using a drag from the logical table (see image above) followed by a drop in the target physical part.
The problem with this approach is purely technical on the developer side: How to manage dnd from one window to another. I will investigate that.

Or, do you have any other gesture you would prefer?
Just tell me.

**Comment by Bacchushlg** [comment]
The dialog for defining the notation lines is perfect this way. 
I assume, it will not be necessary to add lines - normally Audiveris tends more to "invent" additional lines because of unclear correlation to the "real" voices.
About the "how to use" from the side of editing, my idea was to display the detected voice/instrument in the mixed/output display mode (where actually only the system id is displayed (S1, S2,...).
So the user has a quick overview about the detected voice. A click (of right click) on this voice/instrument text then opens the proposed dialog in order to select the proper voice.
A problem maybe space for displaying the voice (often the imported images have very little space on the left side). Maybe it's a good idea to add "free" space to the left of the image, or simply let the voice text overlay the first measure...

**Comment by hbitteur** [comment]
You mean a display like this? (this is very rough display, I should use a smaller font):
| mix | output|
| --- | --- |
|![image](https://user-images.githubusercontent.com/22053634/212541901-1ebf0850-6691-48e8-ae81-94df4f254bae.png)|![image](https://user-images.githubusercontent.com/22053634/212541781-61c32905-c951-4c07-bb7a-2aae561a98e8.png)|

**Comment by Bacchushlg** [comment]
Yes, perfect. But I would prefer a "normal" font ;-)

**Comment by hbitteur** [comment]
When you say a "normal" font, you  refer to its size or to its family? 
Because on this display, I used the same font family as the one used by the score itself in its textual items (which is Finale Jazz Text).

**Comment by Bacchushlg** [comment]
My comment was not meant so serious - more in the way: whatever font is used, let us take a "simple" unique font for display of the voice.
Also I never keep the "original" font in my transcriptions but always switch to MuseScore defaults.

**Comment by hbitteur** [comment]
@Bacchushlg 
Things are a bit more complex than I thought, but progressing.
Could you point me to a (rather simple) score for which the OMR engine "finds" too many logical parts, requiring the end-use to remove some of them. Such a concrete use case would help.
Thanks in advance.

**Comment by hbitteur** [comment]
I just pushed commit 6fa10395990bb9a4354ce84cbc13a02559568060 into "development" branch to provide end-user management of logical parts.
I still need to write the related documentation, but at least you can try these new features right now.

You will notice two new sub-menus in the popup menu (activated by a right click).

![image](https://user-images.githubusercontent.com/22053634/216137315-80b5c03e-04c7-4e91-a36d-15fcfec7e81a.png)
The Score menu provides two items:
- Collate parts, which attempts to collect and combine all parts into logical parts
- Edit logical parts, which launches the editor on the collated logical parts.

![image](https://user-images.githubusercontent.com/22053634/216138457-65637ea3-aef8-4f03-a60b-c1825b19f063.png)
The Part menu provides the current list of logical parts to pick from for the part at hand.

The editor for logical parts looks like below:
![image](https://user-images.githubusercontent.com/22053634/216139076-7558c00c-954e-4a80-9ef1-9c307802d90c.png)
In the example at hand, only the 4 first logicals (S,A,T,B) are relevant, so the end-user can simply remove the 4 following ones.

More on this later.

**Comment by Bacchushlg** [comment]
I just tried the new functionality with "American Tune".
The manual editing works fine and does what I expected.
What is unclear to me is the nice feature "collate parts". I only seems to delete the formal assignment but does not find new ones.

Also I noticed that properly found assignments are deleted during the last step of transcription (page) when I re-transcribe a single page.

**Comment by hbitteur** [comment]
Fix in commit d3fb05d90218bc8225f0dc48a8905303a16c66dc, the "Save" action now automatically locks the table of logicals.
The user can still manually unlock the table if so needed.
Pull "development" branch.
