### ISSUE TITLE
improvement for shape board

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#62]
While correcting a score using the elements from the shape palette (drag-n-drop or double click), I often need the same elements but from different sections.
Is it possible to provide the last used elements in a separate line, e.g. at the top, for direct access without going through the sections structure?

**Comment by hbitteur** [comment]
Very good idea. And easy to implement. 
Thanks

**Comment by hbitteur** [comment]
This separate palette for last used elements is now available via commit 37fbdaad5dda0dfbbf0fb4e49b6c02b21fe41be8

I also tried to make a visual difference between the palette of shape-sets (now displayed in light gray background, and which allows only to select a sub-palette) and a sub-palette of shapes (which are meant for double-click or drag n' drop). Too long description, just have a look by yourselves :-)

Closing the issue.
