### ISSUE TITLE
unable to add a "key" to a note line

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#620]
normally adding a key is simple by drap-n-drop a key symbol to a notation line. 
With the last version the selected key always switches to a single b or sharp, regardless of what I have selected (3 b -> 1 b, 4 sharp -> 1 sharp)

What is interesting: although I see the wrong key in the editor, the correct key is output during export. It seems that internally the correct key is added - only the representation in the editor is wrong

**Comment by hbitteur** [comment]
Fix by commit 1e6cefe6e1652f4dd013b5dca464db19a58d1089
As you suggested, this was only a matter of key display
