### ISSUE TITLE
5.3 beta failing OCR

### ISSUE THREAD

**Issue by franckmusescore** [Audiveris/audiveris#622]
Hello Everybody,
just build dev 5.3 to test some of the new features

Build is sucessfull, but it seems to fail OCR
-No languages is available
-At start-up OCR engine is mentionned as 4.1.1, which is strange as I thought it was 3.04

`INFO  []                      Main 401  | Environment:
- Audiveris:    5.3-beta:7403cacdc
- OS:           Windows 11 10.0
- Architecture: amd64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)
- OCR Engine:   Tesseract OCR, version 4.1.1`

FYI, I have 5.2.5 version running all well, including OCR

Anybody can help ?

**Comment by Bacchushlg** [comment]
have a look at the installation description:
https://github.com/Audiveris/audiveris/wiki/Installation

In chapter "Run" you see that you must have Tesseract installed and 4 languages, too

**Comment by franckmusescore** [comment]
Thanks for answering. I know about Tessearact, I have version 5.2.5 running with all 4 languages OK.
But does not work with 5.3-beta. It seems the languages files are not found

**Comment by hbitteur** [comment]
I'm away from home with no computer available, but I think I remember a
strange difference between Tesseract versions 3 and 4: the folder pointed
by TESSDATA_PREFIX environment variable.
In version 3, it is assumed to point to the parent folder of tessdata,
while in version 4, it is assumed to point to tessdata itself.
I'm writing this by memory, so could you check this:
- value of TESSDATA_PREFIX
- content of the pointed folder

Le lun. 20 févr. 2023 à 20:12, franckmusescore ***@***.***> a
écrit :

**Comment by Bacchushlg** [comment]
I've had a look at where the set variable points to at my computer.
It is "C:\Program Files (x86)\tesseract-ocr\tessdata", and it's just the directory where the tesseract files reside.

**Comment by hbitteur** [comment]
@franckmusescore 
Could you make the same checks on your environnent?

**Comment by franckmusescore** [comment]
Hello,
the 5.2.5 version is pointing to : 
"C:\Program Files (x86)\tesseract-ocr\tessdata"

the 5.3 
"C:\Program Files (x86)\tesseract-ocr\"
which explained it could not find the language files

I made a copy of of the content of \tessdata  (3.04 version) in the parent folder, and now I have both versions working.
I wonder if I need to get the version 4 languages files as the OCR engine for 5.3 is  Tess 4.1.1 

Thanks for your help

(I did notice some difference in music glyph recognition, with 5.3 beeing less efficient than 5.2.5 (bar lines not detected), I'll make another post about that later this week.)

**Comment by hbitteur** [comment]
@franckmusescore 
Regardless of Audiveris version, could you simply post the value of your TESSDATA_PREFIX environment variable?
Using either
> // Windows cmd
> echo %TESSDATA_PREFIX%

or

> // Windows cygwin
> echo $TESSDATA_PREFIX

FYI, mine gives:
> C:\Program Files (x86)\Tesseract-OCR\tessdata

**Comment by franckmusescore** [comment]
windows cmd
echo %TESSDATA_PREFIX%

Answer is:
%TESSDATA_PREFIX%

I don't understand...

**Comment by hbitteur** [comment]
It all depends on the terminal in which you type the command.
Assuming you are using cmd.exe, then you have to use the command: echo %TESSDATA_PREFIX%

If the command interpreter does not understand this command, then propably you are not using cmd.exe but some other interpreter.

**Comment by franckmusescore** [comment]
![image](https://user-images.githubusercontent.com/80044738/220889674-3df5e0ed-c487-4482-9059-e07f2829be4a.png)

still the same

**Comment by hbitteur** [comment]
So you have **no** environment variable named TESSDATA_PREFIX
In this case, under 64-bit Windows, Audiveris 5.3 version will look at "C:\Program Files (x86)\tesseract-ocr" default location,
because it now uses Tesseract 4 (as opposed to Tesseract 3 which had a different convention).

FYI, for availability reason, Audiveris 5.3 has switched to Tesseract 4, but used in the OcrEngineMode named OEM_TESSERACT_ONLY. This means using Tesseract 4 library in a kind of legacy mode, based on the old Tesseract 3 language data files.

Hoping everything is now clear enough.

**Comment by franckmusescore** [comment]
Thanks Hervé for the explanation.
I now understand why copy/paste the language files up the parent directory solved the problem :)
