### ISSUE TITLE
5.3beta poor recognition of bar lines in IMSLP part

### ISSUE THREAD

**Issue by franckmusescore** [Audiveris/audiveris#624]
Here is an example of comparison between 5.2.5 and 5.3beta on a imslp file IMSLP247361 (Massenet Don Quichotte opera)
5.3 is missing the last bar line on the page 91 (99)

[IMSLP247361_p99.pdf](https://github.com/Audiveris/audiveris/files/10826511/IMSLP247361_p99.pdf)

screenshot of 5.3 result (bottom of attached pdf file)
![image](https://user-images.githubusercontent.com/80044738/221237585-2cfdfe85-084f-487c-b72c-4b566a1e4ca2.png)

screenshot of 5.2.5 result 
![image](https://user-images.githubusercontent.com/80044738/221237956-8936f43d-3095-4fe1-bf26-241143e12513.png)

**Comment by hbitteur** [comment]
Fixed in commit cc2704269c625d0255f4cac14d2c5fdc38593a18 on development branch.
Left and right limits for a staff are now computed based on median rather than extreme values.

**Comment by franckmusescore** [comment]
Thanks Hervé.
Build 5.3-beta:cc2704269 working fine with barlines
