### ISSUE TITLE
Overall weird recognition

### ISSUE THREAD

**Issue by Objectful** [Audiveris/audiveris#625]
The input is a pdf file so it shouldn't be bad quality for the OCR. However, it gets things wrong sometimes pretty badly.
For example, the tempo marking is recognised as J=72, instead of normally.
![image](https://user-images.githubusercontent.com/73402079/221351488-8b97d9d1-edd8-4baf-9813-44a06b438231.png)
It ignores clef changes in some places. It detects them as curves, but that can be manually fixed.
![image](https://user-images.githubusercontent.com/73402079/221351524-d46ef0be-2182-4ff6-b4ee-e5e1042c541a.png)
It also gets quite messed up when things overlap
![image](https://user-images.githubusercontent.com/73402079/221351660-62195365-04a9-4b85-b78c-e2c0ed7ef145.png)

**Comment by hbitteur** [comment]
The reason is that current OCR (Tesseract) is not able to recognize the quarter symbol, it deals only with characters.

This has already been noted, perhaps a Tesseract could be trained on this, but how? I don't know.

**Comment by hbitteur** [comment]
> It also gets quite messed up when things overlap

I would be curious to see the input image. Could you post it (or a portion of it?

**Comment by hbitteur** [comment]
Even a human being would have serious difficulties in understanding these overlapping beams and stems.

We can keep this image for its funny aspects.
I'm closing the issue.
