### ISSUE TITLE
GUI enhancements

### ISSUE THREAD

**Issue by topchyan** [Audiveris/audiveris#626]
The interface currently has zoom by height and by width buttons, but it would be more convenient to provide a more traditional zoom capabilities (Ctrl Shift + and Ctrl Shift - for example?). This could help navigating easier.

**Comment by franckmusescore** [comment]
Ctrl+mouse scroll wheel does just that!

**Comment by topchyan** [comment]
Some of us use notebooks with trackpads, which makes things much less
convenient.

**Comment by hbitteur** [comment]
On the numeric keypad:
- CTRL + zooms in
- CTRL - zooms out
- CTRL 0 resets the zoom

But perhaps you don't have a separate numpad.
Here below is Audiveris source code where zoom-related keys are bound (within method bindKeys() in RubberPanel class):

```
       // Zoom modifications
        inputMap.put(KeyStroke.getKeyStroke("ctrl ADD"), "ZoomInAction");
        inputMap.put(KeyStroke.getKeyStroke("ctrl PLUS"), "ZoomInAction");
        actionMap.put("ZoomInAction", new ZoomAction(1));

        inputMap.put(KeyStroke.getKeyStroke("ctrl SUBTRACT"), "ZoomOutAction");
        inputMap.put(KeyStroke.getKeyStroke("ctrl MINUS"), "ZoomOutAction");
        actionMap.put("ZoomOutAction", new ZoomAction(-1));

        inputMap.put(KeyStroke.getKeyStroke("ctrl NUMPAD0"), "ZoomResetAction");
        inputMap.put(KeyStroke.getKeyStroke("ctrl 0"), "ZoomResetAction");
        actionMap.put("ZoomResetAction", new ZoomAction(0));
```

As you can see, ADD, SUBTRACT and NUMPAD0 are for numpad keys.
While PLUS, MINUS and 0 are meant for main keypad.

On my laptop, MINUS and 0 work as expected, while PLUS has no effect. I have a AZERTY keyboard, I switched to QWERTY just for a check, same result.

If you know how to make PLUS work, please tell me.

Also, notice I'm not using ctrl + shift, but simply ctrl. I tried ctrl + shift specifications with no result.

Could someone help us?

**Comment by topchyan** [comment]
Would this help in any way?
https://stackoverflow.com/questions/67044917/how-to-programmatically-determine-the-correct-keystroke-for-ctrl-plus-and-c

**Comment by hbitteur** [comment]
@topchyan 
Yes, it helped indirectly. Because I understood that, instead of targeting a '+' (PLUS), I should target an '=' (EQUALS). Even though these signs are on the same key.

So, here is the new binding sequence:
```
        // Zoom modifications
        inputMap.put(KeyStroke.getKeyStroke("ctrl ADD"), "ZoomInAction");
        inputMap.put(KeyStroke.getKeyStroke("ctrl EQUALS"), "ZoomInAction");
        inputMap.put(KeyStroke.getKeyStroke("ctrl shift EQUALS"), "ZoomInAction");
        actionMap.put("ZoomInAction", new ZoomAction(1));

        inputMap.put(KeyStroke.getKeyStroke("ctrl SUBTRACT"), "ZoomOutAction");
        inputMap.put(KeyStroke.getKeyStroke("ctrl MINUS"), "ZoomOutAction");
        inputMap.put(KeyStroke.getKeyStroke("ctrl shift MINUS"), "ZoomOutAction");
        actionMap.put("ZoomOutAction", new ZoomAction(-1));

        inputMap.put(KeyStroke.getKeyStroke("ctrl NUMPAD0"), "ZoomResetAction");
        inputMap.put(KeyStroke.getKeyStroke("ctrl 0"), "ZoomResetAction");
        inputMap.put(KeyStroke.getKeyStroke("ctrl shift 0"), "ZoomResetAction");
        actionMap.put("ZoomResetAction", new ZoomAction(0));
```
Note that I provide bindings both with and without the SHIFT modifier for all zoom in, out and reset actions

They all work on my French/AZERTY laptop, whether I use the numpad or not.
I have just pushed commit 3ab254b76c73b7b7411db99ca1c502df5c653cb8 for this.
Please pull and build the "development" branch and test on your own environment.

**Comment by hbitteur** [comment]
For further clarification, we don't bind **signs** but **keys**.
For example, if I programmatically switch my keyboard from French(France) /AZERTY to English(United States)/QWERTY:
- Zoom in is still available on the right most key (with signs "=" and "+")
- Zoom out is now available on the key located immediately on the left (with signs "-" and "_" on a US physical keyboard) and with signs ")" and "°" on my physical French keyboard.

**Comment by topchyan** [comment]
Tested it and it now works! Thank you!
