### ISSUE TITLE
tesseract init error

### ISSUE THREAD

**Issue by topchyan** [Audiveris/audiveris#628]
Got this error in the latest development branch. I switched lang options to just hye since tesseract always recognized using default parameters and there was no way to force Armenian (hye) option.

```
[Es Ko Khimeti Chim Gidi] Could not initialize Tesseract with lang hye
[Es Ko Khimeti Chim Gidi] Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.util.List.sort(java.util.Comparator)" because "list" is null
```

**Comment by hbitteur** [comment]
@topchyan 
Have you downloaded the "hye" language data file into Tesseract folder?

**Comment by hbitteur** [comment]
Could you confirm that this folder (.../GitHub/tessdata) where hye.traineddata is located, is the same folder where the other language files (such as eng.traineddata, ita.traineddata, etc) are also located?
In other words, you have one and only one folder for all the language files.

**Comment by hbitteur** [comment]
Do you have environment variable TESSDATA_PREFIX set? And if so, what is its value?

**Comment by topchyan** [comment]
![image](https://user-images.githubusercontent.com/16518288/222922244-c58a60b4-abe5-4922-8d5c-02e2f7946222.png)

export TESSDATA_PREFIX=/home/avetik/Documents/GitHub/tessdata
I run that first before I launch the program using ./gradlew run

Question: should I try the following
export TESSDATA_PREFIX...
./gradlew clean
./gradlew build
./gradlew run

... each time there's an update? or is that too much...

**Comment by topchyan** [comment]
to clarify -- GitHub folder (where I have tessdata subfolder) on my system is symlinked from SdCard -- not sure if that makes a difference

**Comment by hbitteur** [comment]
I suppose you tried to set language option from the command line.
Could you make the test from Audiveris GUI:
Use menu Book | Set book parameters, and there try to select OCR languages.
Click the checkbox on the left
The combo box should list all the languages available in the reference folder.
There you should see "hye".

**Comment by topchyan** [comment]
[Scan 1] 2 sheets in /home/avetik/Dropbox/Notes/Armenian/Scan 1.pdf
[Scan 1#1] Loaded image 1 2481x3506 from /home/avetik/Dropbox/Notes/Armenian/Scan 1.pdf
**Error in BookParameters java.lang.NullPointerException: Cannot invoke "String.trim()" because "spec" is null**

**Comment by hbitteur** [comment]
Update:
I just checked the file ISO639-3.xml, located in the "res" folder of Audiveris.
It does not contain a line for hye. Perhaps you should add one.
something like:
```xml
    <entry key="hye">Armenian</entry>
```

**Comment by hbitteur** [comment]
I confirm that file res/ ISO639-3.xml is used to filter language specification.
The exception on String.trim() must have occurred in class Language, line 322 (see your log file)

**Comment by topchyan** [comment]
I have added the entry for hye to res/ISO639-3.xml
clean, build and run (with export prefix) and still got errors

![image](https://user-images.githubusercontent.com/16518288/222923598-336999a8-ce07-4698-b26c-6e6632e1113e.png)

**Comment by hbitteur** [comment]
We can now suspect a problem with the file itself (hye.traineddata).
Where did you get it?
Audiveris requires old (Tesseract 3) files , not the new ones. It uses Tesseract 4 library, but in legacy mode.

**Comment by topchyan** [comment]
By now I can't recall where I got it from, unfortunately. Can you point me to where I can reliably get the right set of files?

**Comment by topchyan** [comment]
Reading from the enclosed readme points me to 

https://github.com/tesseract-ocr/tessdata/tree/3.04.00

**Comment by hbitteur** [comment]
See this page about [Languages supported in different versions of Tesseract](https://tesseract-ocr.github.io/tessdoc/Data-Files-in-different-versions.html)
The bad news is that Armenian (hye) seems to exist only in new versions (4.x and later)

**Comment by hbitteur** [comment]
> Reading from the enclosed readme points me to
> 
> https://github.com/tesseract-ocr/tessdata/tree/3.04.00

hye/Armenian does not appear on your page

**Comment by topchyan** [comment]
Okay, thank you for researching. Audiveris is a fantastic piece of software. At this point I shall give up and will type the text by hand, until (and if ever) Tess 4.0 gets full support. Kudos and thanks for your hard work!

**Comment by hbitteur** [comment]
You are welcome.

The problem with Tesseract 4 is that it does not play nicely with music-related text. For example lyrics can have their syllables separated, impeding their recognition. Also, Tesseract 4 provides no information about font and precise character bounds (as we get with Tesseract 3).
