### ISSUE TITLE
error "No offset defined for anchor TOP_RIGHT_STEM in template WHOLE_NOTE"

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#63]
when I try to insert a whole note from the shape board, at a place where it was not recognized in the score, I get the error message "No offset defined for anchor TOP_RIGHT_STEM in template WHOLE_NOTE".
It looks to me as if the algorithm would expect a stem where it can connect to note to - which makes no sense for e whole note.

**Comment by hbitteur** [comment]
Bug fixed in commit 8819bc01e08d31c83c38301a903d6457b752a7b5
