### ISSUE TITLE
Unable to modify Document parameters

### ISSUE THREAD

**Issue by Bergdolt** [Audiveris/audiveris#630]
Hello,
first I'd like to thanks audiveris team for providing this wonderfull software that saves me our in re transcribing score.

I use audiveris 5.2.5:e59df4b6a on linux (downloaded, then gradle build, gradle run). I can process images, generate music xml file.
But one thing thing that I cannot do is to modify Document parameter, I can launch the modify window, but then everything is grayed and it is not possible to change anything. Did I miss something?
Any help or tips will be appreciated.
Thanks,
Regard

![Capture d’écran du 2023-03-11 13-59-50](https://user-images.githubusercontent.com/116658186/224486024-6de88e88-7374-4efe-91cf-bdc9cd014aa2.png)

**Comment by hbitteur** [comment]
> Did I miss something?
Yes, you did! :-)

Please have a look at Audiveris handbook, precisely in section on [Book Parameters](https://audiveris.github.io/audiveris/_pages/main/book_parameters/).
 
You have to tick the checkbox at the beginning of a line to enter a specific value (here for sheet #4)
