### ISSUE TITLE
Wrong java version?

### ISSUE THREAD

**Issue by NaughtDZ** [Audiveris/audiveris#631]
### Error is here :
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Audiveris has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

###But whey I run "java -version"
java version "17.0.6" 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

Ps:I used install Java 11 and it not working,so I install Java 17.

**Comment by hbitteur** [comment]
@NaughtDZ 
Strange, I don't understand this behavior.
How did you launch Audiveris precisely?

**Comment by NaughtDZ** [comment]
> @NaughtDZ Strange, I don't understand this behavior. How did you launch Audiveris precisely?

Just in cmd,use ".\Audiveris.bat" or ".\Audivers",both have same error

**Comment by hbitteur** [comment]
Since you launch it from a cmd terminal window, could you post the whole list of messages you get?
We may find additional infoo there.

**Comment by NaughtDZ** [comment]
> Audiveris

Sorry, I didn't dwell further on this error, so I can't provide the full cmd log.
Later, I just completely and utterly uninstalled Java, restarted the computer, reinstalled java, and restarted the computer. The program works fine now.
