### ISSUE TITLE
adding manually an ending_wrl at beginning of staff

### ISSUE THREAD

**Issue by phdm** [Audiveris/audiveris#637]
Hello

I try to add manually an `ENDING_WRL` of 2 measures beginning at the beginning of a staff and terminated by a repeat.  Dragging it and editing it works, but no relation is created with the measure bars, nor with the `EndingNumber`.  The second `ENDING_WRL`, on measures 3 and 4 of the staff works perfectly.  I can see the dot lines showing the relations with the bars and the EndingNumber.
![Endings](https://user-images.githubusercontent.com/2923420/226283707-848fcadc-f9f1-4f60-922d-e75d523e37b6.PNG)

**Comment by phdm** [comment]
Sorry for the noise.  I retried the same manual edition, but this time I moved the `ENDING_WRL` near to the staff before placing it at its place in the original score.  This move near the staff created the relations.

**Comment by hbitteur** [comment]
@phdm 
As a general remark in Audiveris interactive editor, you generally need to "select" the target staff in some way before dropping any item. For example, this is automatically done when  hovering on a staff, since the "last staff" is taken as the target staff.
