### ISSUE TITLE
dont run on my system (Windows)

### ISSUE THREAD

**Issue by Le-Bennou** [Audiveris/audiveris#639]
Not sure it's a bug of your app or my PC.
When I run the app on windows 10, it close immediatly.
I try with the installer, not trying with the source code.

**Comment by BuddyZhu** [comment]
Same here, even with the right version of JAVA installed. (Java 11)

**Comment by hbitteur** [comment]
Could you check with issue #602 which basically allows you to read error messages before the terminal window get closed.

I'm away from home and any computer for a week or so. Sorry.

**Comment by hbitteur** [comment]
@Le-Bennou 
Have you tried to launch Audiveris from a terminal window?
And if so, please tell us what messages you got.

**Comment by hbitteur** [comment]
No news on this issue.
Closing it.
