### ISSUE TITLE
Bug: Cannot read field "x" because "prevBounds" is null

### ISSUE THREAD

**Issue by phdm** [Audiveris/audiveris#640]
Hello,

when using current development branch on the attached image, I get on page 3 the following error :

 Error in performing [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException: Cannot read field "x" because "prevBounds" is null

[01 - Ensemble.pdf](https://github.com/Audiveris/audiveris/files/11073032/01.-.Ensemble.pdf)

**Comment by hbitteur** [comment]
Bug due to void lines wrongly OCR'ed from chord diagrams.
Now fixed in commit 77a80f80362b9c9d39d0b57d555485ab634e5a9b
Please pull again.
