### ISSUE TITLE
PDF import score using tenor clef error

### ISSUE THREAD

**Issue by SnoopeeTheSnoop** [Audiveris/audiveris#650]
The PDF converter does a poor job in converting music using the tenor clef. Notes in the scope of the tenor clef are transposed upwards a by five notes. The conversion works okay with treble, bass and alto clefs.
The error occurs irrespective of the file size or number of instruments involved or the complexity of the score. The error is consistent over a number of otherwise successful conversions.  Notes in the scope of the tenor clef are transposed upwards a perfect fifth. 
A simple pdf import file using all four clefs is attached together with the results of converting to Musecore format and then exporting back to PDF format (since I Musescore format files not accepted here) . NB error free accept with notes in scope of tenor clef. 
[Test PDF importer input.pdf](https://github.com/Audiveris/audiveris/files/11425241/Test.PDF.importer.input.pdf)
[Test PDF importer output.pdf](https://github.com/Audiveris/audiveris/files/11425257/Test.PDF.importer.output.pdf)

**Comment by hbitteur** [comment]
@SnoopeeTheSnoop 
You didn't mention which Audiveris version is used.

Trying your input with latest development version (5.3-beta), **I observed no error**, including for the 3rd staff which begins with a tenor clef.

Here below are snapshots from MuseScore and from Finale fed with Audiveris MusicXML output:

![image](https://user-images.githubusercontent.com/22053634/237038101-7ce27778-d763-4a1c-b6d2-23d7952a2c93.png)

![image](https://user-images.githubusercontent.com/22053634/237038247-020dad03-60ac-4027-af20-0f2a5c8ba03b.png)

**Comment by SnoopeeTheSnoop** [comment]
Thanks for your rapid response. I use the Audiveris  version which is launched by Musescore. I've not noticed Musescore mentioning which version of Audiveris it has launched. How might i discover which version it launches?When i reported the problem to Musescore they said there was nothing they could do.How did you and, more importantly,  how could i use this latest development version (5.3 Beta)? Finally how could Musescore update the Audiveris version it launches?Richard Clarke, sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Hervé Bitteur ***@***.***> Date: 09/05/2023  10:45 am  (GMT+00:00) To: Audiveris/audiveris ***@***.***> Cc: SnoopeeTheSnoop ***@***.***>, Mention ***@***.***> Subject: Re: [Audiveris/audiveris] PDF import score using tenor clef error (Issue #650) 
@SnoopeeTheSnoop
You didn't mention which Audiveris version is used.
Trying your input with latest development version (5.3-beta), I observed no error, including for the 3rd staff which begins with a tenor clef.
Here below are snapshots from MuseScore and from Finale fed with Audiveris MusicXML output:

**Comment by SnoopeeTheSnoop** [comment]
I use windows 10. How can I use Audiveris (v 5.3) directly ?

**Comment by SnoopeeTheSnoop** [comment]
I use Windows 10.Richard Clarke, sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Hervé Bitteur ***@***.***> Date: 09/05/2023  1:45 pm  (GMT+00:00) To: Audiveris/audiveris ***@***.***> Cc: SnoopeeTheSnoop ***@***.***>, Mention ***@***.***> Subject: Re: [Audiveris/audiveris] PDF import score using tenor clef error (Issue #650) 
I can't help you with Musescore, sorry.
But I'd suggest you use Audiveris directly and then pass the resulting MusicXML data to Musescore (or call MuseScore from Audiveris via its plugin).
This way, you could use latest Audiveris version, which is 5.3-beta available on "development" branch.
What is your OS environment? (Windows, Linux or MacOS)

**Comment by SnoopeeTheSnoop** [comment]
How can I use Audiveris (v 5.3) directly ?

**Comment by hbitteur** [comment]
The latest installable release is 5.2, so I assume you installed this one.
In that case, you need Java 11
Please read instructions on [Audiveris project page](https://github.com/Audiveris/audiveris)

5.3 is not released yet, I'm working on it.
You can download and build it on your own (using Java 17). Here again, read project instructions.

In any case, here is what you could do to get information about what happened:
1/ Open a terminal window
2/ Launch Audiveris.bat **from this window**
3/ Read the error messages (since the window remains open)

**Comment by SnoopeeTheSnoop** [comment]
Im not sure which version, 5,2 or 5,3 i installed from your site
In commnad prompt screen IO get:
![image](https://github.com/Audiveris/audiveris/assets/132952468/ded3db30-4853-47f0-b979-5828dd9d7d30)
ie "Could not find or load main class Audiveris"

I'll try getting the Java 11

**Comment by SnoopeeTheSnoop** [comment]
I have succesfully installed Audiveris together with Java.
![image](https://github.com/Audiveris/audiveris/assets/132952468/38a38ea5-9085-49ea-bf1c-5dd4837d6464)
With this installed I can successfully input a PDF file with tenor, mezzo soprano, soprano and  Baritone clefs, and export into an MXL file which I can then load with MuseScore 3  of MuseScore 4 and save it as a MuseScore MSCZ file without the errors described above

Conclusion MuseScore is not but should be using the latest version of Audiveris, 5.2.5 or later.
