### ISSUE TITLE
inverted arrows in extraction/fusion popup menu

### ISSUE THREAD

**Issue by phdm** [Audiveris/audiveris#657]
Hello,

in the extraction/fusion menu (development branch) the arrows or the labels for the 'Vers le haurt' and 'Vers le bas' buttons are counter-intuitive :)
![hautbas](https://github.com/Audiveris/audiveris/assets/2923420/24e6279d-9574-4dc1-ab10-2538b99a2611)

**Comment by hbitteur** [comment]
C'est le moins qu'on puisse dire !

**Comment by hbitteur** [comment]
Fixed in commit e3b95a59163d203ee46492bfce421d529019c921
Closing.
