### ISSUE TITLE
miss-interpretation of stems in a piano score as barline

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#66]
![ich brech die herzen 1](https://user-images.githubusercontent.com/33522630/36072158-00565126-0f1b-11e8-8109-2fa851ce8aee.jpg)

In this almost perfect quality scan the notes on tick 3 of measure 16 are interpreted as barline.

I assume that this is more a problem of fine-tuning some parameters - but which one's?

**Comment by Bacchushlg** [comment]
I tried to remove the wrong barline and define the stems and heads manually.
![image](https://user-images.githubusercontent.com/33522630/36322079-50db9856-134c-11e8-8656-485afe3c7a41.png)
The added notes are in a certain way "not accepted": the stay black in the output view, the measure seems still logically split in 2 measures.

**Comment by hbitteur** [comment]
Nop, as of this writing you CANNOT manually add or remove a barline. It is still to be implemented...
I need some time.

**Comment by hbitteur** [comment]
Merged with issue #91
