### ISSUE TITLE
Unable to add Plugins

### ISSUE THREAD

**Issue by DEHWall** [Audiveris/audiveris#664]
Plugin launched on MusicXML output is null
Unable to add Musescore

**Comment by hbitteur** [comment]
Sorry for this late answer, I was away the last few weeks.

I don't understand your issue, could you be more explicit?
What did you try, and how?

I guess you tried to use or define a plugin to MuseScore. Could you confirm?
And if so, what went wrong?
Could you post the content of your `plugins.xml` file?

**Comment by DEHWall** [comment]
Hi

 

Thanks for the reply.

 

All sorted now – there was no plugins.xml file – I didn’t delete it though?

 

Added the default xml file from web and all is now working ok.

 

Regards

Dave
