### ISSUE TITLE
error when setting augmentation dots manually

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#67]
![frauen sind keine engel 2](https://user-images.githubusercontent.com/33522630/36297751-c5d1a9aa-12f4-11e8-87fb-fbb4a3ae4686.jpg)

The augmentation dots in measure 41ff are not detected. When I try to set them manually, I get the following error messages:

S3 MeasureStack#15 Voice #1 too long 1/8
S3 MeasureStack#15 Voice #1 too long 1/8
S3 MeasureStack#15 no correct rhythm
Invalid entity id: 8388

**Comment by hbitteur** [comment]
Not an answer yet, but:
The example image is much too big, use a lower resolution.
Some braces are truncated and cannot be correctly recognized, please leave some white margin on every side of the score.

**Comment by hbitteur** [comment]
I can now manually assign all augmentation dots. 
I still have rhythm problem with measure 49 though.

**Comment by Bacchushlg** [comment]
I have re-scanned the score. Unfortunately the score book is a little more than A4, and it's really tricky to get it centered properly. I have added some white around afterwords - it's ok this way?

**Comment by hbitteur** [comment]
Yes, it's OK this time

**Comment by Bacchushlg** [comment]
I have added the note heads manually and "connected" to the stem, which works fine. But for some reason it puts the notes into 3 different voices...

**Comment by Bacchushlg** [comment]
![andante 2](https://user-images.githubusercontent.com/33522630/36340533-4f3d6914-13df-11e8-884b-d56981a05526.jpg)

same problem with this score. Here I get the error message: 
"Exception in addInter java.lang.ClassCastException: org.audiveris.omr.sig.inter.RestInter cannot be cast to org.audiveris.omr.sig.inter.HeadInter"
 when trying to add the aug. dot in measure 1 and 2.
In measure 3 I am unable to add the dot by double-click on the Shape for aug.dot. But I can set it via drag-n-drop and also set it by context menu - curious...

**Comment by hbitteur** [comment]
Regarding the issue "_I have added the note heads manually and "connected" to the stem, which works fine. But for some reason it puts the notes into 3 different voices..._", it is now fixed by commit bf5d23fe3a1309422b25d1ae2ee108680bc5c5ac

**Comment by hbitteur** [comment]
Regarding the ClassCastException, bug is now fixed in commit 62e30b051384cbf8194ef962a81821e4e2891d0a 

As a side effect, the augmentation dots now get correctly assigned by the OMR engine.

**Comment by hbitteur** [comment]
Please keep issues separate!!!
For each of them I allocate a separate folder on my machine, with the example and the related artifacts.
Plus, it's easier to handle with github issue management.
Thanks in advance
