### ISSUE TITLE
Can I support exporting mid files？

### ISSUE THREAD

**Issue by Youth99** [Audiveris/audiveris#670]
Can I support exporting mid files？img or pdf to mid？

**Comment by hbitteur** [comment]
I think the answer is "yes", but indirectly:
1. use Audiveris to go from img or pdf to musicxml;
2. then use a sequencer like MuseScore to go from musicxml to sound (and probably MIDI file).

**Comment by hbitteur** [comment]
@Youth99 
Does this answer your question?

**Comment by jasonculligan** [comment]
Sorry to add to a closed ticket @Youth99  @hbitteur , but perhaps the Audiveris PDF (page 4) then needs to be corrected as it is misleading, it suggests that Audiveris handles the export to MIDI, which from what has been said here, it does not and instead relies on a 3rd party program.  Here is the excerpt from the PDF:

> Audiveris is an open source Optical Music Recognition (OMR) software. _**It is used to scan sheet music and convert it into a machine-readable format, such as MusicXML or MIDI.**_ This allows the music to be edited, played back, and shared digitally.

**Comment by hbitteur** [comment]
@jasonculligan 
You are perfectly right!
However, re-read the page carefully: this sentence was copied verbatim from ChatGPT answer, as mentioned in the handbook.
So +1 for ChatGPT mistakes. :-)

To be more serious, this has been corrected in the coming version of the handbook.
