### ISSUE TITLE
Error: Could not create the Java Virtual Machine.

### ISSUE THREAD

**Issue by JohnMama12** [Audiveris/audiveris#684]
I am having trouble running AudiVeris. I'm running java version jre-1.8. On windows 11
I'm simply running Audiveris.bat and the following error is thrown:

Unrecognized option: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Thanks

**Comment by hbitteur** [comment]
As stated on Audiveris web page, you need Java 17. Java 8 is way too old.
