### ISSUE TITLE
Audiveris doesn't open

### ISSUE THREAD

**Issue by toughcypradoodle** [Audiveris/audiveris#690]
**I have:**
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) Client VM (build 25.391-b13, mixed mode, sharing)
My problem is, after downloading all the necessary language packs, and setting JAVA_HOME  Audiveris only starts for a very short amount of time. I have looked at the other issues about this, but I still cannot seem to get the hang of it, since I am not that aware of the IT world; but I would love to use the product. Can someone please help? Thank you

**Comment by toughcypradoodle** [comment]
Oh and by the way, I have windows 11 and used the Audiveris_Setup 5.3.1

**Comment by hbitteur** [comment]
Java 17 is needed, not 8 or 11.

This is stated on [Audiveris web page](https://github.com/Audiveris/audiveris).

We have a chicken & egg problem here: The (Java) application cannot "complain" about its Java platform underneath without using it!

**Comment by toughcypradoodle** [comment]
But I did download java 17 from oracle, and then I added it as the environment for the java app I already downloaded.

**Comment by hbitteur** [comment]
We have to make sure that you are really using the Java 17 (not the other ones you also have)

What is your OS? I suppose Windows.
I suppose you have used the Windows installer?

I'd suggest you open a terminal window (cmd.exe) and from this terminal:
- Print out the value of JAVA_HOME environment variable:
   > echo %JAVA_HOME% 
- Check Java version:
   > java -version
- Or, perhaps better:
   > "%JAVA_HOME%\bin\java.exe" -version
- Launch the Audiveris.bat file (certainly located at C:\Program Files\Audiveris\bin\Audiveris.bat)

**Comment by toughcypradoodle** [comment]
<img width="308" alt="image" src="https://github.com/Audiveris/audiveris/assets/73947295/c767e5b1-3edb-48fd-89de-a1f6a9248b8b">
As you can see here java 17 is installed. 
But when I check Java version it still says:
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) Client VM (build 25.391-b13, mixed mode, sharing).

Regarding Audiveris.bat, that file immediately crashes when I try to open it.
Thank you for your guidance so far, and please let me know if there is anything else I can do to fix the problem.

**Comment by hbitteur** [comment]
> As you can see here java 17 is installed

So what? This does not mean it is actually used when you run the `Audiveris.bat` command file.

**Comment by toughcypradoodle** [comment]
Don't worry I solved it. This was my fault and I am very sorry for the trouble, I set JAVA_HOME to the wrong version. Upon setting it to the correct directory Audiveris works great! Have a nice rest of your day!
