### ISSUE TITLE
notes wrongly moved to new voices after manual adding a note head

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#71]
![coharm - ein freund-stimmen-02](https://user-images.githubusercontent.com/33522630/36195744-ce47f2a6-116e-11e8-8f46-d9030e573109.jpg)

In the score above the note head in measure 34 of the 3rd note of the top triplet is not detected.
I added the beam, the stem and note head manually. After this action, the voices of the other notes are re-arranged in a curious manner:
![manual note head adding before](https://user-images.githubusercontent.com/33522630/36195884-35606a9a-116f-11e8-8249-b3b4ae5d679b.jpg)
![manual note head adding after](https://user-images.githubusercontent.com/33522630/36195893-390066b4-116f-11e8-94b7-0556524894d8.jpg)

**Comment by Bacchushlg** [comment]
This problem is part of the general problem to move note to the correct voice.
I mark it as enhancement here.

**Comment by hbitteur** [comment]
In this special case, I was able to **drag a stem** to the proper target location, then I added black head and rebuilt the beam. Voices were OK in the end.

Not perfect, but it worked.

**Comment by Bacchushlg** [comment]
the problem does not exist any more
