### ISSUE TITLE
installing on win 10

### ISSUE THREAD

**Issue by tartarine** [Audiveris/audiveris#728]
Hi I downloaded the file and installed it on my computer. Win 10, 64 bits
when I try to open the programm I only have a shot of about 1 second an then the program shuts again. I downloaded git up but don know what to do with it.
I thought it would install the missing file from itself bu it doesn't 
what's next ?
thank you

**Comment by hbitteur** [comment]
This is usually related to a mismatch with Java version.
The installed version requires Java 17.
Please check your Java environment (using e.g. the command: java -version)

**Comment by tartarine** [comment]
thank you for your help
 I manage to install java 17
at least now I can open Audiveris
there seem to be some other issues but I must work on them first
thank you and have a nice day
--
M. Dubosson
Gerbergasse 53
4001 Basel
----Message d'origine----
De : ***@***.***
Date : 10/04/2024 - 19:35 (E)
À : ***@***.***
Cc : ***@***.***, ***@***.***
Objet : Re: [Audiveris/audiveris] installing on win 10 (Issue #728)
This is usually related to a mismatch with Java version.
 The installed version requires Java 17.
 Please check your Java environment (using e.g. the command: java -version)
