### ISSUE TITLE
Unable to detect staff lines

### ISSUE THREAD

**Issue by thuyduongcoding** [Audiveris/audiveris#731]
Hi everyone, 
I am using the Audiveris to transcribe the following file but the staff lines of the system#3 cannot be detected (shown red after the GRID step as below):
<img width="628" alt="Screenshot 2024-04-29 144806" src="https://github.com/Audiveris/audiveris/assets/88173269/c2ba026c-e059-46cf-b4c8-60f3fe8b757e">

Here is the file:
https://drive.google.com/file/d/1fQcJ9wUSUNYqOgu-vhzUu9nXAZ0vJNo5/view?usp=sharing

I've reviewed the document, and while there are methods provided for modifying the detected staff lines, there's no guidance on adding missing staff lines. Are there any techniques you recommend for addressing this issue?

Thank you so much!

**Comment by thuyduongcoding** [comment]
Oh I see, thank you so much!

By the way I want to ask to prevent this situation for future music sheets, should I set it to 0.05 permanently instead of 0? Are there any concerns with that?

**Comment by hbitteur** [comment]
This  will fix staves with lines non very regularly spaced.
At the risk of picking up a false staff some day.
It's up to you.

You can always get back to the previous settings if ever you encounter such false staff detection. Not a big deal.

**Comment by thuyduongcoding** [comment]
Thank you very much for your support! I will close this issue.
