### ISSUE TITLE
Can't apply Firmata

### ISSUE THREAD

**Issue by NohWayJose** [Audiveris/audiveris#732]
When I try to drag a Fermata from the glyph panel it issues multiple null pointer exceptions as the mouse cursor (in drag mode) gets to the left boundary of the glyph panel

`mouseDragged error: java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.glyph.Glyph.getBounds()" because "glyph" is null`

PLEASE make your Audiveris 'About' panel copyable, so I don't have to type in the following
ver: 5.4-alpha:d6217545a
Tesseract v 5.3.1
Java 21..0.3
Java RT: OpenJDK RE 21.0.3+9-suse-1.1-x8664
JVM: OpenJDK 64bit server VM (build 21.0.3+9-suse-1.1-x8664
Linux 6.8.9-1-default
AMD64 

Same for Fermata_below

**Comment by hbitteur** [comment]
The Fermata bug was fixed today in commit 8b76b2362fc820f7d170f80c87de6ca1bf894829 on development branch.

Regarding the About panel, I don't know yet how to make it copyable. Do you have a hint?

**Comment by NohWayJose** [comment]
Regarding the About panel...
I'm afraid not, I am a UXer, not a coder. I can do a bit of C++ on an Arduino or Python on a Raspberry Pi. Sorry.

Very happy to help you with UI design and improving the user experience though. Just DM me if you are

**Comment by hbitteur** [comment]
No problem.
This should be done shortly.

**Comment by hbitteur** [comment]
Just pushed commit e16a1ca238a5a8c77c8672d7a3a20f23bb0e2589 on the "development" branch.

By pressing the "Copy" button in the "About" dialog, you copy the content of the box to the clipboard.
No more need to painfully enter it by hand. :-)

Here is the result:
```
Audiveris
Role: Optical Music Recognition
Version: 5.4-alpha:e16a1ca23
Container: file:/D:/soft/audiveris-github/fermata/app/build/classes/java/main/
Home page: http://www.audiveris.org
Dev. project: https://github.com/Audiveris/audiveris
Software license: GNU Affero GPL v3
OCR engine: Tesseract OCR, version 5.3.1
OCR folder: C:\Users\herve\AppData\Roaming\AudiverisLtd\audiveris\config\tessdata
Java vendor: Oracle Corporation
Java version: 21.0.2
Java runtime: Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
Java VM: Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)
Operating System: Windows 10 10.0
Architecture: amd64
```
