### ISSUE TITLE
"org.audiveris.omr.sheet.Staff.isTablature()" because "staff" is null

### ISSUE THREAD

**Issue by lvpchen** [Audiveris/audiveris#737]
There is an error when i test in development branch:
Error in performing [CURVES] java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.sheet.Staff.isTablature()" because "staff" is null.
this is my test image
![20240618114546](https://github.com/Audiveris/audiveris/assets/30174621/100621b4-f1d0-456f-a702-cff36c9e80ff)

**Comment by hbitteur** [comment]
Here is the result at the end of GRID step:

![image](https://github.com/Audiveris/audiveris/assets/22053634/8b8848e7-4794-43e9-bde1-27a3b081d51a)

Obviously some staves are too "wavy" to be correctly recognized:
- The first system has its upper staff truncated
- The last system is not recognized as such, but as 3 different staff chunks.

Before pushing the transcription further, you should manually correct the geometry of the incorrect staves.
If you don't know to do it, see [this handbook section](https://audiveris.github.io/audiveris/_pages/ui_tools/staff_editor/) about staff editing.

**Comment by hbitteur** [comment]
After a few attempts, I gave up.
The staff chunks are too far from target, I cannot rebuild their structure via the staff editor.
Sorry.

**Comment by lvpchen** [comment]
Thank you for your reply.

**Comment by hbitteur** [comment]
I will **try** to improve staff lines detection (as well as staff editing) such that your example can lead to better results.
But this will need some time. And I'm away from Audiveris this week.
