### ISSUE TITLE
exceptionally long gradle build

### ISSUE THREAD

**Issue by hguan-dev** [Audiveris/audiveris#743]
hi, i'm currently using linux to build audiveris with gradle, and the process has been running for an exceptionally long time (see below)

<img width="562" alt="Screenshot 2024-07-09 at 12 03 55 PM" src="https://github.com/Audiveris/audiveris/assets/42282141/8424c17f-0c38-40c2-917b-0c9c2ff37a23">

i've built from source on mac in the past but i don't recall it being anywhere near this long, any tips for troubleshooting?

**Comment by hbitteur** [comment]
44 minutes, still configuring and not yet building...???
Building everything from scratch should take a couple of minutes.
And I have no idea what's going on here.

**Comment by hbitteur** [comment]
Any information?
Have you been able to fix this problem?

**Comment by hguan-dev** [comment]
Not too sure what the problem was actually but it ended up working a while ago. Thanks for checking in!
