### ISSUE TITLE
java 21 required now?

### ISSUE THREAD

**Issue by hguan-dev** [Audiveris/audiveris#747]
was running audiveris with java 17 on my local project but after porting it to aws ec2, error message writes that java 21 is required for audiveris. strange because i haven't updated my build of audiveris at all

**Comment by hguan-dev** [comment]
![Screenshot 2024-08-05 at 10 39 13 PM](https://github.com/user-attachments/assets/1355deb9-e43b-4fe4-bbac-b442465d01f5)

rebuilding audiveris from source gets stuck on this step too, i have the right dependencies right now

**Comment by hguan-dev** [comment]
fixed issue with another run after resetting terminal

**Comment by hbitteur** [comment]
Current Java requirements for Audiveris:
- On master branch: Java 17
- On development branch: Java 21
