### ISSUE TITLE
Error: Could not find or load main class Audiveris Caused by: java.lang.ClassNotFoundException: Audiveris

### ISSUE THREAD

**Issue by hguan-dev** [Audiveris/audiveris#748]
the build was successful and i'm fairly certain my path to the audiveris executable is correct: build/scripts/Audiveris

i believe i have the master branch too so having java 17 shouldnt be a problem here...

**Comment by hguan-dev** [comment]
i switched to dev branch with jdk 21 and the same error occurs. i'm also certain that the path to the executable is correct as well.

**Comment by hbitteur** [comment]
Did you perform a "git pull --all" before?
I'm asking this because I recently modified the project to be more modular (we now have a top project almost void and several sub-projects).

Or better, could  you clone Audiveris from github into a fresh folder and build from scratch there?

**Comment by hguan-dev** [comment]
yes, i did run that, and i cloned audiveris to a fresh folder too and built from the development branch. is it possible that i simply have the wrong path to executable?

**Comment by hguan-dev** [comment]
potentially could also be due to the headless configuration as i'm attempting to run the process in ubuntu on aws ec2... though i recall it was working for me in the past

**Comment by hguan-dev** [comment]
was able to fix this issue through using the .tar archive as described in the handbook, but another issue came up which i'll open another issue for.
