### ISSUE TITLE
normal text is sometimes assigned to chords similar to lyrics

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#76]
Text lines below the last measure of a page are sometimes recognized as lyrics.
If I remove the inters and re-assign as TXT each word is again "connected" to the chords above.

The ideal would be to be able to handle a certain text block as one object. Actually this happens automatically for text entries above the score (title, composer, etc.).

**Comment by hbitteur** [comment]
Fixed in commit 3f5af7dbf685e85881c8f6466ee586ba198a378f
Now, there is a slight semantic difference for these 2 buttons (lyrics and text):
- `lyrics` imposes lyrics role (as before)
- `text` imposes NON-lyrics role (that is, any role can be chosen except lyrics)
