### ISSUE TITLE
Auris fails on startup

### ISSUE THREAD

**Issue by blockx** [Audiveris/audiveris#760]
Hi,
I installed jdk-23_windows-x64_bin.msi and then Audiveris 5.3.1.  I put the following files into C:\Program Files (x86)\tesseract-ocr\tessdata :

deu.traineddata
eng.traineddata
fra.traineddata
ita.traineddata
in addition to what had already been installed as part of the Auris install:

dan-frak.traineddata
deu-frak.traineddata
slk-frak.traineddata

When I start Audiveris from the icon and batch file starts and immediately stops, when I run the batch file as follows I get the output after it:

C:\Program Files\Audiveris\bin>Audiveris.bat
Unrecognized option: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Anyone know what's up ?

**Comment by MiRa1970** [comment]
Try an actual jdk/jre. Older than 11 do not know --add-exports

**Comment by blockx** [comment]
Sorry, what do you mean by "actual jdk" ?   jdk-23_windows-x64_bin.msi is the latest version 23 of the JDK ?

**Comment by hbitteur** [comment]
I have not tested with Java 23 yet.

Perhaps this Java 23 no longer recognizes the "--add-exports" option which is a kind of workaround for the imposed modularity constraints.

Could you try Java 21 instead and post the results? I'm curious to see the difference.

**Comment by blockx** [comment]
No difference that I could see:

C:\Program Files (x86)\tesseract-ocr\tessdata>java -version
java version "21.0.5" 2024-10-15 LTS
Java(TM) SE Runtime Environment (build 21.0.5+9-LTS-239)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.5+9-LTS-239, mixed mode, sharing)

C:\Program Files (x86)\tesseract-ocr\tessdata>"C:\Program Files\Audiveris\bin\Audiveris.bat"
Unrecognized option: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by hbitteur** [comment]
I'm lost.
Perhaps you have several Java installed, and  Audiveris.bat is not picking the correct one.

Try this command:
> echo %JAVA_HOME%

And this one:
> java.exe -version

**Comment by blockx** [comment]
That was it: I just set JAVA_HOME to "C:\Program Files\Java\jdk-21" and Audiveris starts now.

Many thanks,
