### ISSUE TITLE
menu : help opens 404 page

### ISSUE THREAD

**Issue by aum7** [Audiveris/audiveris#765]
in main menu at top
clicking **help > handbook** will open 404 page
link is
`https://audiveris.github.io/audiveris/_pages/index-5.2/`

have fun

EDIT: link should probably be 1st handbook page : `https://audiveris.github.io/audiveris/_pages/handbook/`
EDIT: changed **help** into **help > handbook**

**Comment by hbitteur** [comment]
Yes it should.
Actually, in the current version it is: "https://audiveris.github.io/audiveris/" which points to a page with 3 links: one for the handbook, one for the .omr format and one for the wiki.
What is your Audiveris version?

**Comment by aum7** [comment]
exellence au pair !
