### ISSUE TITLE
2-note triplets (quarter+eights) are correctly handled but displayed in red

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#77]
![coharm - ein freund-stimmen-04](https://user-images.githubusercontent.com/33522630/36343167-084a7900-1409-11e8-8845-1831af1fe9af.jpg)

In measure 61 there are triplets consisting of a quarter and en eights note. I can define the triplet and it is correctly exported, but the physical mode shows the "3" in red which normally displays an error in the definition.

**Comment by hbitteur** [comment]
Yes, the tuplet processing is correctly done. But the checking of abnormal status is too simplistic (I have been a bit lazy here).
I'm going to fix that.

**Comment by hbitteur** [comment]
Now fixed in commit 57dd3df13c090d73e5ea4e015e222c5dd0a5f6da
It was easier than I thought...
Closing the issue
