### ISSUE TITLE
error messages (NullPointer...) during transcription - continue possible with good result

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#78]
![nur nicht aus liebe weinen 1](https://user-images.githubusercontent.com/33522630/36349849-69557cd4-148d-11e8-9607-64f7cb5143bd.jpg)

The transcription of this scan stops with a couple of error messages:

- [Nur nicht aus Liebe weinen 1] Error in SlursBuilder: java.lang.NullPointerException
- ....
- [Nur nicht aus Liebe weinen 1] S2 java.lang.NullPointerException
- ....
- [Nur nicht aus Liebe weinen 1] Error in LINKS java.util.concurrent.ExecutionException: 
- [Nur nicht aus Liebe weinen 1] Error in SlursBuilder: java.lang.NullPointerException
- ....
- [Nur nicht aus Liebe weinen 1] S2 java.lang.NullPointerException
- ....
- [Nur nicht aus Liebe weinen 1] Error in LINKS java.util.concurrent.ExecutionException: java.lang.NullPointerException

But it is possible to continue transcription afterwards, and the result is not too bad (for a rather complex score like this).

**Comment by hbitteur** [comment]
Fixed by commit 6bd394460aa677e40f4e9c1b05b69317a88b1048 with other minor bugs
Then closed.
