### ISSUE TITLE
faulty detected aug.points very near to note head

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#79]
![beatles - if i fell in love 1](https://user-images.githubusercontent.com/33522630/36384083-657b5fbe-158e-11e8-900b-8d3bb09fbdd4.jpg)

In this score there are 2 faulty aug.points. Took me a while to understand, why the measures 2 an 7 were marked as faulty...

I assume that there is a minimum distance of the aug.point relative to the note head. Maybe it is defined in pixels and as my scan is of rather high resolution, this value is too little?

**Comment by hbitteur** [comment]
No, there is no minimum distance between augmentation dot and the item to be augmented, but this will soon be investigated. Rather easy for a note head, less easy for a rest.

Distances are never stated in pixels but in interline fractions (or line fraction in some specific cases), precisely to be rather independent of the image scaling.

**Comment by hbitteur** [comment]
These false dots were made possible because the ledger detection did not take the whole ledger height in these cases. 

Set constant `maxThicknessHigh2` to 0.4 instead of 0.3 (in LedgersBuilder) to cope with the rather thick ledgers you have in your case, and they all get catched correctly.

**Comment by Bacchushlg** [comment]
Perfect! No errors left!
Should we use this value as new default?

**Comment by hbitteur** [comment]
OK, let's try this commit 2fc11f2ee2eaf70bdf795728dd07516d0ab665b2
0.4 interline is pretty thick for a ledger (it was 0.3 so far).
We'll see how other scores behave.
I'm closing this issue now
