### ISSUE TITLE
Cannot run the audiveris.jar file

### ISSUE THREAD

**Issue by spulimootil** [Audiveris/audiveris#8]
Build was successful and could run the program with gradle run
But when I tried to run the jar file, I got the error: `no main manifest attribute, in audiveris.jar`

**Comment by maximumspatium** [comment]
Some more information would be helpful. Which JDK/OS, the precise command caused the failure, more terminal output etc.

**Comment by spulimootil** [comment]
I am using Ubuntu 16.04 OS with java version "1.8.0_121"
I can run the program using gradle run.

Here is my gradle build output

```
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
targetOS=linux-x86_64
:clean
:git_build
:generateProgramId
:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:processResources
:classes
:jar
:startScripts
:distTar
:distZip
:assemble
:compileTestJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: /home/sp/NetBeansProjects/audiveris/src/test/org/audiveris/omr/ui/symbol/MusicFontTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:processTestResources UP-TO-DATE
:testClasses
:test
:check
:build

BUILD SUCCESSFUL
```
But when I try `java -jar build/jar/audiveris.jar` from the jar folder, I get the following output
`no main manifest attribute, in build/jar/audiveris.jar`

**Comment by maximumspatium** [comment]
To my knowledge, the JAR in `build/jar/audiveris.jar` isn't intended to be executed directly. You need to change into `build/distributions` directory where you'll find a ZIP and TAR distribution archives.

For the moment being, these distributions are missing some resources. Audiveris application started from there won't likely work correctly. I will fix it soon.

Is there any need for you to use the JAR instead of `grade run` ?

**Comment by spulimootil** [comment]
Thanks you Maxim for the info. I was trying to use this version in batch processing mode.

**Comment by maximumspatium** [comment]
I see. I've just opened another issue for the missing resources in the distributions: https://github.com/Audiveris/audiveris/issues/9

Can we close this issue?
