### ISSUE TITLE
Text defined as "normal" text by user is implicitly redefined as lyrics

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#80]
In the score of #79 the voice description in system 2 is detected as lyrics.
When I remove the inters and redefine as "normal" text, it immediately redefines as lyrics.
Same for last line ("Legato...")

**Comment by hbitteur** [comment]
As of today, you can manually force lyrics recognition or basic text recognition. In the first case, role will be "lyrics" by definition, whereas in the second case, the usual role heuristic is applied, which here led to lyrics (bad luck!)
I need to work on this...

**Comment by hbitteur** [comment]
Fixed by commit 3f5af7dbf685e85881c8f6466ee586ba198a378f
`text` action now imposes NON-lyrics
