### ISSUE TITLE
button "dot set" from basic classifier does not work

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#84]
often aug.dots are detected from the basic classifier (as "DOT_set") when I select the glyph. But when I press the button nothing happens - the dot is not defined a aug.dot as I would expect. 
The way over "heads and dots" / "aug.dot" works but is a step less convenient.

**Comment by hbitteur** [comment]
DOT_set is just a physical shape, whereas Augmentation dot, Staccato dot, Repeat dot are logical shapes with more specific meaning.
The OMR engine today uses a glyph classifier which works only on the glyph appearance (hence the DOT_set shape) and then needs additional algorithmic tests to guess the correct role of this dot (and this would be just a guess)
But when the shape is manually assigned, it's more efficient to use some guiding from the user who can explicitly select augmentation dot, staccato dot or repeat dot.

**Comment by Bacchushlg** [comment]
if I could express a wish, I would rather prefer a button for augmentation point inter instead of the actual function. It's (for me) the most common usage: add a missing aug.point.
But I agree: it's a "nice-to-have"

**Comment by hbitteur** [comment]
But your wish has already been granted! :-)
There is an "augmentation dot button", ready to be double-clicked in the HeadsAndDot sub-palette. Isn't it marvelous?
