### ISSUE TITLE
A manually removed clef re-appears in the exported output file

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#85]
Regarding image of #83 :
If I remove the wrong clefs and half notes and export, then import to MuseScore, the clefs appear in the score.

**Comment by hbitteur** [comment]
I just tried to reproduce the problem with image of #83 
When I remove the wrong clefs, they no longer appear, and there is no wrong clef exported in MusicXML.

**Comment by Bacchushlg** [comment]
I just reproduced the error: there are 2 G-clefs detected in measure 1 and 5 in the bass line. I export them (see the wrong clefs) then remove the clefs and export again: the clefs are again exported.

**Comment by hbitteur** [comment]
Yes, you are right I just could reproduce the case.
A stupid bug, now fixed in commit 9468ac592e9b0b02b451f9707ef8cdd6947443d0
