### ISSUE TITLE
additional score timings (7/8, 9/8, ...)

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#88]
There are a couple of scores that use timings different from the "normal" ones.
Although it is possible to define the timings manually by setting numerator and denominator separately, it might be better to provide more timings for better automatic recognition.
I propose to add the following:
7/8, 9/8, 12/8

**Comment by Bacchushlg** [comment]
I don't know what is the effort to provide these additional timings. It seems to need "only" to add some inters to the list.
If this is correct, maybe it's worth to do it in the near future...

**Comment by hbitteur** [comment]
Adding a new shape has limited impact on the code, but it makes the classifiers data obsolete: they immediately stop working! They have to be re-trained from scratch. And we need concrete samples of these new shapes to populate the training set.

This is why I generally avoid to modify the list of shapes. But, from times to times, this has to be done.

We could combine this with pending request #68 to augment the range of fingering shapes from 0-4 to 0-5, and here again we need concrete samples for the training set.

**Comment by Bacchushlg** [comment]
problem has been solved some versions ago
