### ISSUE TITLE
export of score with changing amount of note lines give wrong result

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#89]
[She's Always a Woman (4).zip](https://github.com/Audiveris/audiveris/files/1748043/She.s.Always.a.Woman.4.zip)

The appended score starts with 4 staves (2 systems) and ends with a system with 3 staves.

The output, imported to Musescore, gives a global system with 6 staves, where in the beginning the first system includes the top part of the second system.
I cannot decide, if the problem is the import of MuseScore - but I assume it is more probable that it is the export (or something else).

Also I cannot understand, why measure 3 is marked as faulty - it appears to be correct.

**Comment by maximumspatium** [comment]
Yes, this is a long-standing issue with MusicXML export with its roots in old Audiveris code. An attempt to fix the PartwiseBuilder class was made last year. We need to investigate this case again.
I'll mark this issue as bug because your example triggers several NullPointerExceptions. To be fixed ASAP.

**Comment by maximumspatium** [comment]
> Also I cannot understand, why measure 3 is marked as faulty - it appears to be correct.

I noticed that strange behavior for other scores as well. That's probably just another minor bug nobody bothered to fix it yet.

**Comment by Bacchushlg** [comment]
I was able to solve the problem by splitting the image in 2, last system into an extra image.
By this way everything worked fine. 
Could be added to the handbook for intermediate solution.

**Comment by Bacchushlg** [comment]
as there is a way to bypass the problem (not elegant, but working), and as this problem does only appear seldom... -> enhancement

**Comment by Bacchushlg** [comment]
problem does not exist any more with present version 5.1.0:2e45a2935
