### ISSUE TITLE
wrong detected bar lines lead to extra (empty) measure

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#91]
[BarP - Sweet Georgia Brown 2.zip](https://github.com/Audiveris/audiveris/files/1751393/BarP.-.Sweet.Georgia.Brown.2.zip)

The time signature (C) in the end of measure 12 is recognized as bar line, leading to an extra (empty) measure.
Unfortunately this completely disturbs MuseScore (which I do not understand...) and makes it impossible to import.
Manual delete of the bar line does not change anything.

**Comment by maximumspatium** [comment]
> The time signature (C) in the end of measure 12 is recognized as bar line, leading to an extra (empty) measure.

Not exactly. The vertical line in the middle of the cut time symbol has been labeled as _thin barline_. This is wrong but you can easily correct this by clicking on this line and then press the deassign button in the board to the right. Then select the cut time symbol manually by clicking on its parts while pressing CTRL (or OPTION on Mac) and assign it the "cut time" interpretation.

After that, you should be able to export the piece as MusicXML and import it in Musescore. That extra bar is still there but it could be easily deleted in Musescore.

Here the corrected and exported MusicXML [of your piece.](https://github.com/Audiveris/audiveris/files/1752810/BarP.-.Sweet.Georgia.Brown.2.mxl.zip)

**Comment by maximumspatium** [comment]
Your example reveals even more issues with MusicXML export, see #92.

**Comment by hbitteur** [comment]
I'm right now sketching the user ability to add/remove barline(s) and would appreciate your advices from the end-user point of view.
Strictly speaking, adding or removing a single barline inter is rather easy. But this generally has an impact on the surrounding mesures, and what is difficult is to determine **when** to actually proceed to measures adjustment.

**Removal**:
The example presented above (Sweet Georgia Brown) has 2-staff systems, and near the end of system 3, "cut" keys have their middle stick mistaken for a barline, leading to a false additional measure. Today, we can remove these false barlines, but the measure remains, leading to problem with MuseScore at least. So what should we propose regarding the impacted measures?
The user could manually delete each of these 2 false barlines, but obviously the application should wait until the second barline has been removed to actually launch the recomputation of measures. But at this time, the application would have lost reference of the first barline. This would be even worse for bigger systems.
So, for such barline removal (which in fact means measure removal or merge), perhaps we could simply add in the popup menu, sub-menu Measures, an item like "_Merge with measure on right_". Doing so, all the barlines to be removed would be implicitly designated by being the right border of the current false measure. And this would work the same, whatever the number of staves in the system.
I feel comfortable with this approach.

**Addition**:
The user could add barlines, one after the other (either by drag n' drop, or by glyph assignment). As long as these barlines still don't make up a full column, they would be displayed in red (meaning: abnormal status), to call user attention on the need to complete the work.
Only when the column is detected as complete, measure recomputation is launched (and barlines displayed normally).
The difficulty here is to make sure that the "column completeness" is correctly detected by the application. Especially if there is in fact a group of several barlines per staff? (double barlines, repeat signs)
Perhaps we would need some user explicit command to actually launch the measure recomputation?
Here, I'm not at all comfortable, could you help me?

**Comment by Bacchushlg** [comment]
What about forcing the user to select the bar line of the complete system for such actions (shift-select)?
This would work for both cases: add and remove.
If a user tries to add/remove only a part, Audiveris would output an error message, e.g. "select bars of the complete system".
Appears rather strait forward for me.

**Comment by hbitteur** [comment]
Let's consider the case of a really large system (say half the page high), it may be difficult to make a correct manual selection.

For removal, just inters are concerned, so that's rather easy.

For addition, the user needs to select all the proper glyphs candidates, and only those one, which is more difficult. A lasso would pick up a bunch of glyphs, from which the user should perhaps discard some, while at the same time keep grouping some glyphs for a single barline, other glyphs for another barline.
In poor scores, a barline may be made of several smaller glyphs, and at the same time we have to limit barline height at staff height. All this in one user gesture!?

**Comment by hbitteur** [comment]
For a removal, it should even be enough for the user to select one barline inter. He could be prompted for applying the removal to the whole system column of barlines. This is so because the GRID step imposes to have a complete column of barlines to really create them.

But for additions, the topic is still open...

**Comment by Bacchushlg** [comment]
Oh yes, you are right - I did not think about the problem, that e.g. parts of lyrics or other text might be included by the lasso, too.
So, then it seems your proposal is really the best: add bars one by one (if it is not possible with the lasso), and then provide an explicite user function, e.g. "recalculate score" (new button on the top).
For me it's good to handle, and it should work for other cases, too.

**Comment by maximumspatium** [comment]
> For a removal, it should even be enough for the user to select one barline inter. He could be prompted for applying the removal to the whole system column of baronies.

+1 because it's simple and fast.

> But for additions, the topic is still open...

How about that: right-click on the stave and select "Add barline" from the popup menu, then select the bar line type and finally specify whether it should be propagated to all staves.

**Comment by hbitteur** [comment]
Perhaps "_right-click on the stave and select "Add barline" from the popup menu, then select the bar line type_" could be simply replaced by "setting a barline at proper location" (glyph or DnD).
And I agree about prompting the user for propagation to the whole system.

**Comment by hbitteur** [comment]
Back to feature definition, here are the use cases.

**Removal**:
1. User can right point to a measure and, via  popup menu, ask for merge with next measure on right.
2. User can also select a barline and ask for its removal, user will be prompted for merge with next measure on right.

**Addition**:
To select proper barline type and proper target location, there are 2 possibilities:
1. User can use shape palette and drag selected barline type until target location in a given staff.
2. User can select one or several glyphs in one or several staves and, via popup menu, ask for barline addition.

In both addition cases, the target abscissa will be defined by the center of the barline type.
\[In the case of a multi-staff system, user will be prompted for propagation to the whole system height\]
Then current measure will be split in two, based on new barline.

**Comment by hbitteur** [comment]
This feature is now implemented in commit 5ce80c284b6a559665dd42de18c64772b3920c29

Here is how it works basically:
- Before MEASURES step, the user can play with BarlineInter instances, adding or removing them individually at will.
- After MEASURES step, the user will in fact play only with StaffBarlineInter instances and addition/removal will apply for the whole system height. The user is always prompted for confirmation of this system-height action.

A **BarlineInter** is one physical barline, its height is the staff height.
A **StaffBarlineInter** is a sign, at staff level, made of one or several physical barlines, close to one another abscissa-wise. For example, a StaffBarlineInter of shape RIGHT_REPEAT_SIGN, is the sequence of repeat dots, then a thin barline, then a thick barline. 

When the user starts to drag a barline shape from the shape palette, he will actually drag a BarlineInter or a StaffBarlineInter, depending on whether MEASURES step has been performed or not.

OK, this may sound too complex to read, simply try to use it, like any other Inter.

**Comment by hbitteur** [comment]
**UPDATE**
The merge and push did not work as I expected.
Let's  hope my personal backup will allow me to actually push the modified files (2 weeks of work...)
Sorry for the additional delay.

**Comment by maximumspatium** [comment]
> Let's hope my personal backup will allow me to actually push the modified files (2 weeks of work...)

Let me know if you need a helping hand. Until know, I never encountered any real problem with merge/push in the Git world. It sounds like your stuff need to be rebased first...

**Comment by hbitteur** [comment]
Finally, barlines edition is available via commits 99c7cd43e07d697a075eedd94d0997a8398f1114 and d1326c5b9115d801de113dd162a7379b4360905f

Please let me know if something does not work as expected.
