### ISSUE TITLE
when adding a beam over multiple notes, the beam is only connected to the first and last stem

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#93]
when adding a missing bar over more than 2 notes the bar is actually not connected to all stems below but only to the first an last one. Must be added manually each time

**Comment by hbitteur** [comment]
What is the precise meaning of bar here? Generally a bar is a measure, and barlines separate measures.
Could you give an example?

Re-reading your issue, perhaps you are referring to a beam? If so, for a beam, only the side stems are mandatory. The other ones must be connected manually.

**Comment by Bacchushlg** [comment]
sorry, mistake: I meant "beam". English...is sometimes not so easy...

**Comment by Bacchushlg** [comment]
> for a beam, only the side stems are mandatory. The other ones must be connected manually.

When the beam is recognized during transcription, it is connected to all stems below (above). So I would expect the same behaviour for the manual adding of a beam.

**Comment by hbitteur** [comment]
Yes, this sounds doable.

**Comment by Bacchushlg** [comment]
although I had flagged this item as enhancement - it seems to me rather important, because it concerns the rhythm check.
While I know meanwhile that after adding a beam it is important to check if the relations to the stems must be checked, it might disturb a "normal" user because the missing connections are not obvious...

**Comment by hbitteur** [comment]
OK, I will do this ASAP

**Comment by hbitteur** [comment]
Done with commit e8c8e97590c4787c74199573319d613f71b65790

Please note there  is now a risk that too many stems get connected to a new beam. We'll see how it works actually.

**Comment by Bacchushlg** [comment]
Works perfectly. I tried a couple of "old" score images - all were recognized correctly.
Did you improve the transcription recognition, too? I have the impression, the automatic recognition is better than it was before...
