### ISSUE TITLE
ending number="0"

### ISSUE THREAD

**Issue by soundnotation** [Audiveris/audiveris#97]
[This file](https://github.com/Audiveris/audiveris/files/1759026/songs.4.pdf) generates [this output](https://github.com/Audiveris/audiveris/files/1759071/songs.4.mxl.zip) with the latest build from development.

It appears the output xml is not a valid xml. MuseScore says:

> Fatal error: line 580 column 54 Content of attribute number does not match its type definition: String content does not match pattern facet..

At that line there is this xml code:
`        <ending number="0" type="stop" default-y="38"></ending>`

so definitely `ending number="0"` is wrong generated code.

The command I ran was `/usr/local/Audiveris/bin/Audiveris -batch -export -output "..." -- "... /songs.2.pdf"`

**Comment by Bacchushlg** [comment]
I've converted the file in interactive mode. It is really of too bad quality. Look at the result for the first 2 systems:
![image](https://user-images.githubusercontent.com/33522630/36680354-db2aca4c-1b15-11e8-8906-5ccca19a18e4.png)

**Comment by maximumspatium** [comment]
> It is really of too bad quality.

There are actually two different issues with your score. It

- has a too low resolution (the embedded picture reveals the interline value of 10 pixels but min 20 are required)
- looks like to be handwritten

Audiveris doesn't guarantee anything for handwritten scores. With some luck, you're able to get a meaningful output for them.

**Comment by maximumspatium** [comment]
Back to the topic. Invalid XML is definitely unacceptable. I need to verify this case. Perhaps we need to add a check for invalid XML and reject them before export...

**Comment by hbitteur** [comment]
OK, such number attribute should not be 0.
What should the engine do?
- export the ending, but without this number attribute, or
- not export the ending at all
I'd vote for the first case

**Comment by maximumspatium** [comment]
Strictly speaking, an ending without any repeat indication doesn't make any sense - it must be reentered anyways. So the rejection of incomplete/incorrect endings sounds logical.
But I'm okay with the 1st option too because it would be much likely easier to fix...

**Comment by hbitteur** [comment]
Not a real fix in commit 84615e573e04ed19a837ecd29e761ee0f8345d0f, but when no number has been assigned to an ending, it is exported with a dummy number set to 99.
This allows the ending to be exported and then later fixed via any music editor.

**Comment by hbitteur** [comment]
I propose we keep this issue open, until the user has a way to force an ending number manually.

**Comment by hbitteur** [comment]
Commit 55c416a23c285c45dcfb1afb01801e184c86daef refines number format (as 1,2) without any other character such as period, in order to suit MuseScore validation.

**Comment by hbitteur** [comment]
Available in 5.3
Closing the issie
