### ISSUE TITLE
Accidentials are ignored if they are too far left from note head (multiple acc.s before chord)

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#99]
![ich brech die herzen 2](https://user-images.githubusercontent.com/33522630/36833659-7df961f4-1d30-11e8-86ef-0e2e38bd4b3a.jpg)

In case that there are multiple accidentals left from a chord (example: 3rd system), they are ignored if they are too far away from the note head. I assume there is a fix max. value for the check, but I assume there need to be a variable one, depending on what else is left of the chord.

**Comment by hbitteur** [comment]
I agree, we need a more flexible strategy than plain horizontal distance, something that takes the chord heads geometry into account.
Right now, I'm doing something similar with augmentation dots.

**Comment by Bacchushlg** [comment]
I'm not sure that the chord geometry is really relevant. It more the question, if there are other accidentals in between. If so, a larger distance to the chord should be accepted.

**Comment by hbitteur** [comment]
For alterations, I would say both:
1. whether the chord has heads on both sides of the stem
2. whether there are other alterations that would overlap with the candidate

Whereas for augmentation dots, only the 1st case is relevant.

**Comment by Bacchushlg** [comment]
problem is almost solved. There is one missing connection (after manual addition), but this is really very far away - from my point of view acceptable.
